/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieu;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuLocalService;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTCapPhepBienHieuPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTCapPhepBienHieuPhuongTienPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTCapPhepPhuHieuPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTCapPhepPhuHieuPhuongTienPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTCapPhepPhuHieuTuyenPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTPhuongTienVanTaiPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTXuLyBienHieuPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTXuLyBienHieuPhuongTienPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTXuLyPhuHieuPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTXuLyPhuHieuPhuongTienPersistence;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.service.persistence.QLVTXuLyPhuHieuPhuongTienTuyenPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the q l v t xu ly phu hieu local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.service.impl.QLVTXuLyPhuHieuLocalServiceImpl}.
 * </p>
 *
 * @author binhta
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.service.impl.QLVTXuLyPhuHieuLocalServiceImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuLocalServiceUtil
 * @generated
 */
public abstract class QLVTXuLyPhuHieuLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements QLVTXuLyPhuHieuLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuLocalServiceUtil} to access the q l v t xu ly phu hieu local service.
	 */

	/**
	 * Adds the q l v t xu ly phu hieu to the database. Also notifies the appropriate model listeners.
	 *
	 * @param qlvtXuLyPhuHieu the q l v t xu ly phu hieu
	 * @return the q l v t xu ly phu hieu that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public QLVTXuLyPhuHieu addQLVTXuLyPhuHieu(QLVTXuLyPhuHieu qlvtXuLyPhuHieu)
		throws SystemException {
		qlvtXuLyPhuHieu.setNew(true);

		return qlvtXuLyPhuHieuPersistence.update(qlvtXuLyPhuHieu);
	}

	/**
	 * Creates a new q l v t xu ly phu hieu with the primary key. Does not add the q l v t xu ly phu hieu to the database.
	 *
	 * @param id the primary key for the new q l v t xu ly phu hieu
	 * @return the new q l v t xu ly phu hieu
	 */
	@Override
	public QLVTXuLyPhuHieu createQLVTXuLyPhuHieu(int id) {
		return qlvtXuLyPhuHieuPersistence.create(id);
	}

	/**
	 * Deletes the q l v t xu ly phu hieu with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the q l v t xu ly phu hieu
	 * @return the q l v t xu ly phu hieu that was removed
	 * @throws PortalException if a q l v t xu ly phu hieu with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public QLVTXuLyPhuHieu deleteQLVTXuLyPhuHieu(int id)
		throws PortalException, SystemException {
		return qlvtXuLyPhuHieuPersistence.remove(id);
	}

	/**
	 * Deletes the q l v t xu ly phu hieu from the database. Also notifies the appropriate model listeners.
	 *
	 * @param qlvtXuLyPhuHieu the q l v t xu ly phu hieu
	 * @return the q l v t xu ly phu hieu that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public QLVTXuLyPhuHieu deleteQLVTXuLyPhuHieu(
		QLVTXuLyPhuHieu qlvtXuLyPhuHieu) throws SystemException {
		return qlvtXuLyPhuHieuPersistence.remove(qlvtXuLyPhuHieu);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(QLVTXuLyPhuHieu.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return qlvtXuLyPhuHieuPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyPhuHieuModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return qlvtXuLyPhuHieuPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyPhuHieuModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return qlvtXuLyPhuHieuPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return qlvtXuLyPhuHieuPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return qlvtXuLyPhuHieuPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public QLVTXuLyPhuHieu fetchQLVTXuLyPhuHieu(int id)
		throws SystemException {
		return qlvtXuLyPhuHieuPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the q l v t xu ly phu hieu with the primary key.
	 *
	 * @param id the primary key of the q l v t xu ly phu hieu
	 * @return the q l v t xu ly phu hieu
	 * @throws PortalException if a q l v t xu ly phu hieu with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public QLVTXuLyPhuHieu getQLVTXuLyPhuHieu(int id)
		throws PortalException, SystemException {
		return qlvtXuLyPhuHieuPersistence.findByPrimaryKey(id);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return qlvtXuLyPhuHieuPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the q l v t xu ly phu hieus.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyPhuHieuModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of q l v t xu ly phu hieus
	 * @param end the upper bound of the range of q l v t xu ly phu hieus (not inclusive)
	 * @return the range of q l v t xu ly phu hieus
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<QLVTXuLyPhuHieu> getQLVTXuLyPhuHieus(int start, int end)
		throws SystemException {
		return qlvtXuLyPhuHieuPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of q l v t xu ly phu hieus.
	 *
	 * @return the number of q l v t xu ly phu hieus
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getQLVTXuLyPhuHieusCount() throws SystemException {
		return qlvtXuLyPhuHieuPersistence.countAll();
	}

	/**
	 * Updates the q l v t xu ly phu hieu in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param qlvtXuLyPhuHieu the q l v t xu ly phu hieu
	 * @return the q l v t xu ly phu hieu that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public QLVTXuLyPhuHieu updateQLVTXuLyPhuHieu(
		QLVTXuLyPhuHieu qlvtXuLyPhuHieu) throws SystemException {
		return qlvtXuLyPhuHieuPersistence.update(qlvtXuLyPhuHieu);
	}

	/**
	 * Returns the q l v t cap phep bien hieu local service.
	 *
	 * @return the q l v t cap phep bien hieu local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepBienHieuLocalService getQLVTCapPhepBienHieuLocalService() {
		return qlvtCapPhepBienHieuLocalService;
	}

	/**
	 * Sets the q l v t cap phep bien hieu local service.
	 *
	 * @param qlvtCapPhepBienHieuLocalService the q l v t cap phep bien hieu local service
	 */
	public void setQLVTCapPhepBienHieuLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepBienHieuLocalService qlvtCapPhepBienHieuLocalService) {
		this.qlvtCapPhepBienHieuLocalService = qlvtCapPhepBienHieuLocalService;
	}

	/**
	 * Returns the q l v t cap phep bien hieu persistence.
	 *
	 * @return the q l v t cap phep bien hieu persistence
	 */
	public QLVTCapPhepBienHieuPersistence getQLVTCapPhepBienHieuPersistence() {
		return qlvtCapPhepBienHieuPersistence;
	}

	/**
	 * Sets the q l v t cap phep bien hieu persistence.
	 *
	 * @param qlvtCapPhepBienHieuPersistence the q l v t cap phep bien hieu persistence
	 */
	public void setQLVTCapPhepBienHieuPersistence(
		QLVTCapPhepBienHieuPersistence qlvtCapPhepBienHieuPersistence) {
		this.qlvtCapPhepBienHieuPersistence = qlvtCapPhepBienHieuPersistence;
	}

	/**
	 * Returns the q l v t cap phep bien hieu phuong tien local service.
	 *
	 * @return the q l v t cap phep bien hieu phuong tien local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepBienHieuPhuongTienLocalService getQLVTCapPhepBienHieuPhuongTienLocalService() {
		return qlvtCapPhepBienHieuPhuongTienLocalService;
	}

	/**
	 * Sets the q l v t cap phep bien hieu phuong tien local service.
	 *
	 * @param qlvtCapPhepBienHieuPhuongTienLocalService the q l v t cap phep bien hieu phuong tien local service
	 */
	public void setQLVTCapPhepBienHieuPhuongTienLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepBienHieuPhuongTienLocalService qlvtCapPhepBienHieuPhuongTienLocalService) {
		this.qlvtCapPhepBienHieuPhuongTienLocalService = qlvtCapPhepBienHieuPhuongTienLocalService;
	}

	/**
	 * Returns the q l v t cap phep bien hieu phuong tien persistence.
	 *
	 * @return the q l v t cap phep bien hieu phuong tien persistence
	 */
	public QLVTCapPhepBienHieuPhuongTienPersistence getQLVTCapPhepBienHieuPhuongTienPersistence() {
		return qlvtCapPhepBienHieuPhuongTienPersistence;
	}

	/**
	 * Sets the q l v t cap phep bien hieu phuong tien persistence.
	 *
	 * @param qlvtCapPhepBienHieuPhuongTienPersistence the q l v t cap phep bien hieu phuong tien persistence
	 */
	public void setQLVTCapPhepBienHieuPhuongTienPersistence(
		QLVTCapPhepBienHieuPhuongTienPersistence qlvtCapPhepBienHieuPhuongTienPersistence) {
		this.qlvtCapPhepBienHieuPhuongTienPersistence = qlvtCapPhepBienHieuPhuongTienPersistence;
	}

	/**
	 * Returns the q l v t cap phep phu hieu local service.
	 *
	 * @return the q l v t cap phep phu hieu local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuLocalService getQLVTCapPhepPhuHieuLocalService() {
		return qlvtCapPhepPhuHieuLocalService;
	}

	/**
	 * Sets the q l v t cap phep phu hieu local service.
	 *
	 * @param qlvtCapPhepPhuHieuLocalService the q l v t cap phep phu hieu local service
	 */
	public void setQLVTCapPhepPhuHieuLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuLocalService qlvtCapPhepPhuHieuLocalService) {
		this.qlvtCapPhepPhuHieuLocalService = qlvtCapPhepPhuHieuLocalService;
	}

	/**
	 * Returns the q l v t cap phep phu hieu persistence.
	 *
	 * @return the q l v t cap phep phu hieu persistence
	 */
	public QLVTCapPhepPhuHieuPersistence getQLVTCapPhepPhuHieuPersistence() {
		return qlvtCapPhepPhuHieuPersistence;
	}

	/**
	 * Sets the q l v t cap phep phu hieu persistence.
	 *
	 * @param qlvtCapPhepPhuHieuPersistence the q l v t cap phep phu hieu persistence
	 */
	public void setQLVTCapPhepPhuHieuPersistence(
		QLVTCapPhepPhuHieuPersistence qlvtCapPhepPhuHieuPersistence) {
		this.qlvtCapPhepPhuHieuPersistence = qlvtCapPhepPhuHieuPersistence;
	}

	/**
	 * Returns the q l v t cap phep phu hieu phuong tien local service.
	 *
	 * @return the q l v t cap phep phu hieu phuong tien local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuPhuongTienLocalService getQLVTCapPhepPhuHieuPhuongTienLocalService() {
		return qlvtCapPhepPhuHieuPhuongTienLocalService;
	}

	/**
	 * Sets the q l v t cap phep phu hieu phuong tien local service.
	 *
	 * @param qlvtCapPhepPhuHieuPhuongTienLocalService the q l v t cap phep phu hieu phuong tien local service
	 */
	public void setQLVTCapPhepPhuHieuPhuongTienLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuPhuongTienLocalService qlvtCapPhepPhuHieuPhuongTienLocalService) {
		this.qlvtCapPhepPhuHieuPhuongTienLocalService = qlvtCapPhepPhuHieuPhuongTienLocalService;
	}

	/**
	 * Returns the q l v t cap phep phu hieu phuong tien persistence.
	 *
	 * @return the q l v t cap phep phu hieu phuong tien persistence
	 */
	public QLVTCapPhepPhuHieuPhuongTienPersistence getQLVTCapPhepPhuHieuPhuongTienPersistence() {
		return qlvtCapPhepPhuHieuPhuongTienPersistence;
	}

	/**
	 * Sets the q l v t cap phep phu hieu phuong tien persistence.
	 *
	 * @param qlvtCapPhepPhuHieuPhuongTienPersistence the q l v t cap phep phu hieu phuong tien persistence
	 */
	public void setQLVTCapPhepPhuHieuPhuongTienPersistence(
		QLVTCapPhepPhuHieuPhuongTienPersistence qlvtCapPhepPhuHieuPhuongTienPersistence) {
		this.qlvtCapPhepPhuHieuPhuongTienPersistence = qlvtCapPhepPhuHieuPhuongTienPersistence;
	}

	/**
	 * Returns the q l v t cap phep phu hieu tuyen local service.
	 *
	 * @return the q l v t cap phep phu hieu tuyen local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuTuyenLocalService getQLVTCapPhepPhuHieuTuyenLocalService() {
		return qlvtCapPhepPhuHieuTuyenLocalService;
	}

	/**
	 * Sets the q l v t cap phep phu hieu tuyen local service.
	 *
	 * @param qlvtCapPhepPhuHieuTuyenLocalService the q l v t cap phep phu hieu tuyen local service
	 */
	public void setQLVTCapPhepPhuHieuTuyenLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuTuyenLocalService qlvtCapPhepPhuHieuTuyenLocalService) {
		this.qlvtCapPhepPhuHieuTuyenLocalService = qlvtCapPhepPhuHieuTuyenLocalService;
	}

	/**
	 * Returns the q l v t cap phep phu hieu tuyen persistence.
	 *
	 * @return the q l v t cap phep phu hieu tuyen persistence
	 */
	public QLVTCapPhepPhuHieuTuyenPersistence getQLVTCapPhepPhuHieuTuyenPersistence() {
		return qlvtCapPhepPhuHieuTuyenPersistence;
	}

	/**
	 * Sets the q l v t cap phep phu hieu tuyen persistence.
	 *
	 * @param qlvtCapPhepPhuHieuTuyenPersistence the q l v t cap phep phu hieu tuyen persistence
	 */
	public void setQLVTCapPhepPhuHieuTuyenPersistence(
		QLVTCapPhepPhuHieuTuyenPersistence qlvtCapPhepPhuHieuTuyenPersistence) {
		this.qlvtCapPhepPhuHieuTuyenPersistence = qlvtCapPhepPhuHieuTuyenPersistence;
	}

	/**
	 * Returns the q l v t phuong tien van tai local service.
	 *
	 * @return the q l v t phuong tien van tai local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTPhuongTienVanTaiLocalService getQLVTPhuongTienVanTaiLocalService() {
		return qlvtPhuongTienVanTaiLocalService;
	}

	/**
	 * Sets the q l v t phuong tien van tai local service.
	 *
	 * @param qlvtPhuongTienVanTaiLocalService the q l v t phuong tien van tai local service
	 */
	public void setQLVTPhuongTienVanTaiLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTPhuongTienVanTaiLocalService qlvtPhuongTienVanTaiLocalService) {
		this.qlvtPhuongTienVanTaiLocalService = qlvtPhuongTienVanTaiLocalService;
	}

	/**
	 * Returns the q l v t phuong tien van tai persistence.
	 *
	 * @return the q l v t phuong tien van tai persistence
	 */
	public QLVTPhuongTienVanTaiPersistence getQLVTPhuongTienVanTaiPersistence() {
		return qlvtPhuongTienVanTaiPersistence;
	}

	/**
	 * Sets the q l v t phuong tien van tai persistence.
	 *
	 * @param qlvtPhuongTienVanTaiPersistence the q l v t phuong tien van tai persistence
	 */
	public void setQLVTPhuongTienVanTaiPersistence(
		QLVTPhuongTienVanTaiPersistence qlvtPhuongTienVanTaiPersistence) {
		this.qlvtPhuongTienVanTaiPersistence = qlvtPhuongTienVanTaiPersistence;
	}

	/**
	 * Returns the q l v t xu ly bien hieu local service.
	 *
	 * @return the q l v t xu ly bien hieu local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyBienHieuLocalService getQLVTXuLyBienHieuLocalService() {
		return qlvtXuLyBienHieuLocalService;
	}

	/**
	 * Sets the q l v t xu ly bien hieu local service.
	 *
	 * @param qlvtXuLyBienHieuLocalService the q l v t xu ly bien hieu local service
	 */
	public void setQLVTXuLyBienHieuLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyBienHieuLocalService qlvtXuLyBienHieuLocalService) {
		this.qlvtXuLyBienHieuLocalService = qlvtXuLyBienHieuLocalService;
	}

	/**
	 * Returns the q l v t xu ly bien hieu persistence.
	 *
	 * @return the q l v t xu ly bien hieu persistence
	 */
	public QLVTXuLyBienHieuPersistence getQLVTXuLyBienHieuPersistence() {
		return qlvtXuLyBienHieuPersistence;
	}

	/**
	 * Sets the q l v t xu ly bien hieu persistence.
	 *
	 * @param qlvtXuLyBienHieuPersistence the q l v t xu ly bien hieu persistence
	 */
	public void setQLVTXuLyBienHieuPersistence(
		QLVTXuLyBienHieuPersistence qlvtXuLyBienHieuPersistence) {
		this.qlvtXuLyBienHieuPersistence = qlvtXuLyBienHieuPersistence;
	}

	/**
	 * Returns the q l v t xu ly bien hieu phuong tien local service.
	 *
	 * @return the q l v t xu ly bien hieu phuong tien local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyBienHieuPhuongTienLocalService getQLVTXuLyBienHieuPhuongTienLocalService() {
		return qlvtXuLyBienHieuPhuongTienLocalService;
	}

	/**
	 * Sets the q l v t xu ly bien hieu phuong tien local service.
	 *
	 * @param qlvtXuLyBienHieuPhuongTienLocalService the q l v t xu ly bien hieu phuong tien local service
	 */
	public void setQLVTXuLyBienHieuPhuongTienLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyBienHieuPhuongTienLocalService qlvtXuLyBienHieuPhuongTienLocalService) {
		this.qlvtXuLyBienHieuPhuongTienLocalService = qlvtXuLyBienHieuPhuongTienLocalService;
	}

	/**
	 * Returns the q l v t xu ly bien hieu phuong tien persistence.
	 *
	 * @return the q l v t xu ly bien hieu phuong tien persistence
	 */
	public QLVTXuLyBienHieuPhuongTienPersistence getQLVTXuLyBienHieuPhuongTienPersistence() {
		return qlvtXuLyBienHieuPhuongTienPersistence;
	}

	/**
	 * Sets the q l v t xu ly bien hieu phuong tien persistence.
	 *
	 * @param qlvtXuLyBienHieuPhuongTienPersistence the q l v t xu ly bien hieu phuong tien persistence
	 */
	public void setQLVTXuLyBienHieuPhuongTienPersistence(
		QLVTXuLyBienHieuPhuongTienPersistence qlvtXuLyBienHieuPhuongTienPersistence) {
		this.qlvtXuLyBienHieuPhuongTienPersistence = qlvtXuLyBienHieuPhuongTienPersistence;
	}

	/**
	 * Returns the q l v t xu ly phu hieu local service.
	 *
	 * @return the q l v t xu ly phu hieu local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuLocalService getQLVTXuLyPhuHieuLocalService() {
		return qlvtXuLyPhuHieuLocalService;
	}

	/**
	 * Sets the q l v t xu ly phu hieu local service.
	 *
	 * @param qlvtXuLyPhuHieuLocalService the q l v t xu ly phu hieu local service
	 */
	public void setQLVTXuLyPhuHieuLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuLocalService qlvtXuLyPhuHieuLocalService) {
		this.qlvtXuLyPhuHieuLocalService = qlvtXuLyPhuHieuLocalService;
	}

	/**
	 * Returns the q l v t xu ly phu hieu persistence.
	 *
	 * @return the q l v t xu ly phu hieu persistence
	 */
	public QLVTXuLyPhuHieuPersistence getQLVTXuLyPhuHieuPersistence() {
		return qlvtXuLyPhuHieuPersistence;
	}

	/**
	 * Sets the q l v t xu ly phu hieu persistence.
	 *
	 * @param qlvtXuLyPhuHieuPersistence the q l v t xu ly phu hieu persistence
	 */
	public void setQLVTXuLyPhuHieuPersistence(
		QLVTXuLyPhuHieuPersistence qlvtXuLyPhuHieuPersistence) {
		this.qlvtXuLyPhuHieuPersistence = qlvtXuLyPhuHieuPersistence;
	}

	/**
	 * Returns the q l v t xu ly phu hieu phuong tien local service.
	 *
	 * @return the q l v t xu ly phu hieu phuong tien local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuPhuongTienLocalService getQLVTXuLyPhuHieuPhuongTienLocalService() {
		return qlvtXuLyPhuHieuPhuongTienLocalService;
	}

	/**
	 * Sets the q l v t xu ly phu hieu phuong tien local service.
	 *
	 * @param qlvtXuLyPhuHieuPhuongTienLocalService the q l v t xu ly phu hieu phuong tien local service
	 */
	public void setQLVTXuLyPhuHieuPhuongTienLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuPhuongTienLocalService qlvtXuLyPhuHieuPhuongTienLocalService) {
		this.qlvtXuLyPhuHieuPhuongTienLocalService = qlvtXuLyPhuHieuPhuongTienLocalService;
	}

	/**
	 * Returns the q l v t xu ly phu hieu phuong tien persistence.
	 *
	 * @return the q l v t xu ly phu hieu phuong tien persistence
	 */
	public QLVTXuLyPhuHieuPhuongTienPersistence getQLVTXuLyPhuHieuPhuongTienPersistence() {
		return qlvtXuLyPhuHieuPhuongTienPersistence;
	}

	/**
	 * Sets the q l v t xu ly phu hieu phuong tien persistence.
	 *
	 * @param qlvtXuLyPhuHieuPhuongTienPersistence the q l v t xu ly phu hieu phuong tien persistence
	 */
	public void setQLVTXuLyPhuHieuPhuongTienPersistence(
		QLVTXuLyPhuHieuPhuongTienPersistence qlvtXuLyPhuHieuPhuongTienPersistence) {
		this.qlvtXuLyPhuHieuPhuongTienPersistence = qlvtXuLyPhuHieuPhuongTienPersistence;
	}

	/**
	 * Returns the q l v t xu ly phu hieu phuong tien tuyen local service.
	 *
	 * @return the q l v t xu ly phu hieu phuong tien tuyen local service
	 */
	public vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuPhuongTienTuyenLocalService getQLVTXuLyPhuHieuPhuongTienTuyenLocalService() {
		return qlvtXuLyPhuHieuPhuongTienTuyenLocalService;
	}

	/**
	 * Sets the q l v t xu ly phu hieu phuong tien tuyen local service.
	 *
	 * @param qlvtXuLyPhuHieuPhuongTienTuyenLocalService the q l v t xu ly phu hieu phuong tien tuyen local service
	 */
	public void setQLVTXuLyPhuHieuPhuongTienTuyenLocalService(
		vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuPhuongTienTuyenLocalService qlvtXuLyPhuHieuPhuongTienTuyenLocalService) {
		this.qlvtXuLyPhuHieuPhuongTienTuyenLocalService = qlvtXuLyPhuHieuPhuongTienTuyenLocalService;
	}

	/**
	 * Returns the q l v t xu ly phu hieu phuong tien tuyen persistence.
	 *
	 * @return the q l v t xu ly phu hieu phuong tien tuyen persistence
	 */
	public QLVTXuLyPhuHieuPhuongTienTuyenPersistence getQLVTXuLyPhuHieuPhuongTienTuyenPersistence() {
		return qlvtXuLyPhuHieuPhuongTienTuyenPersistence;
	}

	/**
	 * Sets the q l v t xu ly phu hieu phuong tien tuyen persistence.
	 *
	 * @param qlvtXuLyPhuHieuPhuongTienTuyenPersistence the q l v t xu ly phu hieu phuong tien tuyen persistence
	 */
	public void setQLVTXuLyPhuHieuPhuongTienTuyenPersistence(
		QLVTXuLyPhuHieuPhuongTienTuyenPersistence qlvtXuLyPhuHieuPhuongTienTuyenPersistence) {
		this.qlvtXuLyPhuHieuPhuongTienTuyenPersistence = qlvtXuLyPhuHieuPhuongTienTuyenPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieu",
			qlvtXuLyPhuHieuLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieu");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return QLVTXuLyPhuHieu.class;
	}

	protected String getModelClassName() {
		return QLVTXuLyPhuHieu.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = qlvtXuLyPhuHieuPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepBienHieuLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepBienHieuLocalService qlvtCapPhepBienHieuLocalService;
	@BeanReference(type = QLVTCapPhepBienHieuPersistence.class)
	protected QLVTCapPhepBienHieuPersistence qlvtCapPhepBienHieuPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepBienHieuPhuongTienLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepBienHieuPhuongTienLocalService qlvtCapPhepBienHieuPhuongTienLocalService;
	@BeanReference(type = QLVTCapPhepBienHieuPhuongTienPersistence.class)
	protected QLVTCapPhepBienHieuPhuongTienPersistence qlvtCapPhepBienHieuPhuongTienPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuLocalService qlvtCapPhepPhuHieuLocalService;
	@BeanReference(type = QLVTCapPhepPhuHieuPersistence.class)
	protected QLVTCapPhepPhuHieuPersistence qlvtCapPhepPhuHieuPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuPhuongTienLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuPhuongTienLocalService qlvtCapPhepPhuHieuPhuongTienLocalService;
	@BeanReference(type = QLVTCapPhepPhuHieuPhuongTienPersistence.class)
	protected QLVTCapPhepPhuHieuPhuongTienPersistence qlvtCapPhepPhuHieuPhuongTienPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuTuyenLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTCapPhepPhuHieuTuyenLocalService qlvtCapPhepPhuHieuTuyenLocalService;
	@BeanReference(type = QLVTCapPhepPhuHieuTuyenPersistence.class)
	protected QLVTCapPhepPhuHieuTuyenPersistence qlvtCapPhepPhuHieuTuyenPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTPhuongTienVanTaiLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTPhuongTienVanTaiLocalService qlvtPhuongTienVanTaiLocalService;
	@BeanReference(type = QLVTPhuongTienVanTaiPersistence.class)
	protected QLVTPhuongTienVanTaiPersistence qlvtPhuongTienVanTaiPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyBienHieuLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyBienHieuLocalService qlvtXuLyBienHieuLocalService;
	@BeanReference(type = QLVTXuLyBienHieuPersistence.class)
	protected QLVTXuLyBienHieuPersistence qlvtXuLyBienHieuPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyBienHieuPhuongTienLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyBienHieuPhuongTienLocalService qlvtXuLyBienHieuPhuongTienLocalService;
	@BeanReference(type = QLVTXuLyBienHieuPhuongTienPersistence.class)
	protected QLVTXuLyBienHieuPhuongTienPersistence qlvtXuLyBienHieuPhuongTienPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuLocalService qlvtXuLyPhuHieuLocalService;
	@BeanReference(type = QLVTXuLyPhuHieuPersistence.class)
	protected QLVTXuLyPhuHieuPersistence qlvtXuLyPhuHieuPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuPhuongTienLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuPhuongTienLocalService qlvtXuLyPhuHieuPhuongTienLocalService;
	@BeanReference(type = QLVTXuLyPhuHieuPhuongTienPersistence.class)
	protected QLVTXuLyPhuHieuPhuongTienPersistence qlvtXuLyPhuHieuPhuongTienPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuPhuongTienTuyenLocalService.class)
	protected vn.dtt.duongbo.dao.capbienhieuphuhieu.service.QLVTXuLyPhuHieuPhuongTienTuyenLocalService qlvtXuLyPhuHieuPhuongTienTuyenLocalService;
	@BeanReference(type = QLVTXuLyPhuHieuPhuongTienTuyenPersistence.class)
	protected QLVTXuLyPhuHieuPhuongTienTuyenPersistence qlvtXuLyPhuHieuPhuongTienTuyenPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private QLVTXuLyPhuHieuLocalServiceClpInvoker _clpInvoker = new QLVTXuLyPhuHieuLocalServiceClpInvoker();
}