/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbien.dao.vrcb.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.duongbien.dao.vrcb.model.DmMaritime;
import vn.dtt.duongbien.dao.vrcb.model.DmMaritimeModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DmMaritime service. Represents a row in the &quot;DM_MARITIME&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbien.dao.vrcb.model.DmMaritimeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DmMaritimeImpl}.
 * </p>
 *
 * @author longdm
 * @see DmMaritimeImpl
 * @see vn.dtt.duongbien.dao.vrcb.model.DmMaritime
 * @see vn.dtt.duongbien.dao.vrcb.model.DmMaritimeModel
 * @generated
 */
public class DmMaritimeModelImpl extends BaseModelImpl<DmMaritime>
	implements DmMaritimeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dm maritime model instance should use the {@link vn.dtt.duongbien.dao.vrcb.model.DmMaritime} interface instead.
	 */
	public static final String TABLE_NAME = "DM_MARITIME";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.INTEGER },
			{ "MaritimeCode", Types.VARCHAR },
			{ "MaritimeReference", Types.VARCHAR },
			{ "MaritimeOrder", Types.INTEGER },
			{ "MaritimeName", Types.VARCHAR },
			{ "MaritimeNameVN", Types.VARCHAR },
			{ "Address", Types.VARCHAR },
			{ "AddressVN", Types.VARCHAR },
			{ "StateCode", Types.VARCHAR },
			{ "CityCode", Types.VARCHAR },
			{ "IsDelete", Types.INTEGER },
			{ "MarkedAsDelete", Types.INTEGER },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "RequestedDate", Types.TIMESTAMP },
			{ "SyncVersion", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table DM_MARITIME (id INTEGER not null primary key,MaritimeCode VARCHAR(75) null,MaritimeReference VARCHAR(75) null,MaritimeOrder INTEGER,MaritimeName VARCHAR(75) null,MaritimeNameVN VARCHAR(75) null,Address VARCHAR(75) null,AddressVN VARCHAR(75) null,StateCode VARCHAR(75) null,CityCode VARCHAR(75) null,IsDelete INTEGER,MarkedAsDelete INTEGER,ModifiedDate DATE null,RequestedDate DATE null,SyncVersion VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DM_MARITIME";
	public static final String ORDER_BY_JPQL = " ORDER BY dmMaritime.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DM_MARITIME.id ASC";
	public static final String DATA_SOURCE = "vaoracangbienDataSource";
	public static final String SESSION_FACTORY = "ravaocangbienSessionFactory";
	public static final String TX_MANAGER = "ravaocangbienTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbien.dao.vrcb.model.DmMaritime"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbien.dao.vrcb.model.DmMaritime"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbien.dao.vrcb.model.DmMaritime"),
			true);
	public static long MARITIMECODE_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbien.dao.vrcb.model.DmMaritime"));

	public DmMaritimeModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DmMaritime.class;
	}

	@Override
	public String getModelClassName() {
		return DmMaritime.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maritimeCode", getMaritimeCode());
		attributes.put("maritimeReference", getMaritimeReference());
		attributes.put("maritimeOrder", getMaritimeOrder());
		attributes.put("maritimeName", getMaritimeName());
		attributes.put("maritimeNameVN", getMaritimeNameVN());
		attributes.put("address", getAddress());
		attributes.put("addressVN", getAddressVN());
		attributes.put("stateCode", getStateCode());
		attributes.put("citycode", getCitycode());
		attributes.put("isDelete", getIsDelete());
		attributes.put("markedAsDelete", getMarkedAsDelete());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("requestedDate", getRequestedDate());
		attributes.put("syncVersion", getSyncVersion());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maritimeCode = (String)attributes.get("maritimeCode");

		if (maritimeCode != null) {
			setMaritimeCode(maritimeCode);
		}

		String maritimeReference = (String)attributes.get("maritimeReference");

		if (maritimeReference != null) {
			setMaritimeReference(maritimeReference);
		}

		Integer maritimeOrder = (Integer)attributes.get("maritimeOrder");

		if (maritimeOrder != null) {
			setMaritimeOrder(maritimeOrder);
		}

		String maritimeName = (String)attributes.get("maritimeName");

		if (maritimeName != null) {
			setMaritimeName(maritimeName);
		}

		String maritimeNameVN = (String)attributes.get("maritimeNameVN");

		if (maritimeNameVN != null) {
			setMaritimeNameVN(maritimeNameVN);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String addressVN = (String)attributes.get("addressVN");

		if (addressVN != null) {
			setAddressVN(addressVN);
		}

		String stateCode = (String)attributes.get("stateCode");

		if (stateCode != null) {
			setStateCode(stateCode);
		}

		String citycode = (String)attributes.get("citycode");

		if (citycode != null) {
			setCitycode(citycode);
		}

		Integer isDelete = (Integer)attributes.get("isDelete");

		if (isDelete != null) {
			setIsDelete(isDelete);
		}

		Integer markedAsDelete = (Integer)attributes.get("markedAsDelete");

		if (markedAsDelete != null) {
			setMarkedAsDelete(markedAsDelete);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Date requestedDate = (Date)attributes.get("requestedDate");

		if (requestedDate != null) {
			setRequestedDate(requestedDate);
		}

		String syncVersion = (String)attributes.get("syncVersion");

		if (syncVersion != null) {
			setSyncVersion(syncVersion);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public String getMaritimeCode() {
		if (_maritimeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _maritimeCode;
		}
	}

	@Override
	public void setMaritimeCode(String maritimeCode) {
		_columnBitmask |= MARITIMECODE_COLUMN_BITMASK;

		if (_originalMaritimeCode == null) {
			_originalMaritimeCode = _maritimeCode;
		}

		_maritimeCode = maritimeCode;
	}

	public String getOriginalMaritimeCode() {
		return GetterUtil.getString(_originalMaritimeCode);
	}

	@Override
	public String getMaritimeReference() {
		if (_maritimeReference == null) {
			return StringPool.BLANK;
		}
		else {
			return _maritimeReference;
		}
	}

	@Override
	public void setMaritimeReference(String maritimeReference) {
		_maritimeReference = maritimeReference;
	}

	@Override
	public int getMaritimeOrder() {
		return _maritimeOrder;
	}

	@Override
	public void setMaritimeOrder(int maritimeOrder) {
		_maritimeOrder = maritimeOrder;
	}

	@Override
	public String getMaritimeName() {
		if (_maritimeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _maritimeName;
		}
	}

	@Override
	public void setMaritimeName(String maritimeName) {
		_maritimeName = maritimeName;
	}

	@Override
	public String getMaritimeNameVN() {
		if (_maritimeNameVN == null) {
			return StringPool.BLANK;
		}
		else {
			return _maritimeNameVN;
		}
	}

	@Override
	public void setMaritimeNameVN(String maritimeNameVN) {
		_maritimeNameVN = maritimeNameVN;
	}

	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@Override
	public String getAddressVN() {
		if (_addressVN == null) {
			return StringPool.BLANK;
		}
		else {
			return _addressVN;
		}
	}

	@Override
	public void setAddressVN(String addressVN) {
		_addressVN = addressVN;
	}

	@Override
	public String getStateCode() {
		if (_stateCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _stateCode;
		}
	}

	@Override
	public void setStateCode(String stateCode) {
		_stateCode = stateCode;
	}

	@Override
	public String getCitycode() {
		if (_citycode == null) {
			return StringPool.BLANK;
		}
		else {
			return _citycode;
		}
	}

	@Override
	public void setCitycode(String citycode) {
		_citycode = citycode;
	}

	@Override
	public int getIsDelete() {
		return _isDelete;
	}

	@Override
	public void setIsDelete(int isDelete) {
		_isDelete = isDelete;
	}

	@Override
	public int getMarkedAsDelete() {
		return _markedAsDelete;
	}

	@Override
	public void setMarkedAsDelete(int markedAsDelete) {
		_markedAsDelete = markedAsDelete;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public Date getRequestedDate() {
		return _requestedDate;
	}

	@Override
	public void setRequestedDate(Date requestedDate) {
		_requestedDate = requestedDate;
	}

	@Override
	public String getSyncVersion() {
		if (_syncVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _syncVersion;
		}
	}

	@Override
	public void setSyncVersion(String syncVersion) {
		_syncVersion = syncVersion;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DmMaritime toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DmMaritime)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DmMaritimeImpl dmMaritimeImpl = new DmMaritimeImpl();

		dmMaritimeImpl.setId(getId());
		dmMaritimeImpl.setMaritimeCode(getMaritimeCode());
		dmMaritimeImpl.setMaritimeReference(getMaritimeReference());
		dmMaritimeImpl.setMaritimeOrder(getMaritimeOrder());
		dmMaritimeImpl.setMaritimeName(getMaritimeName());
		dmMaritimeImpl.setMaritimeNameVN(getMaritimeNameVN());
		dmMaritimeImpl.setAddress(getAddress());
		dmMaritimeImpl.setAddressVN(getAddressVN());
		dmMaritimeImpl.setStateCode(getStateCode());
		dmMaritimeImpl.setCitycode(getCitycode());
		dmMaritimeImpl.setIsDelete(getIsDelete());
		dmMaritimeImpl.setMarkedAsDelete(getMarkedAsDelete());
		dmMaritimeImpl.setModifiedDate(getModifiedDate());
		dmMaritimeImpl.setRequestedDate(getRequestedDate());
		dmMaritimeImpl.setSyncVersion(getSyncVersion());

		dmMaritimeImpl.resetOriginalValues();

		return dmMaritimeImpl;
	}

	@Override
	public int compareTo(DmMaritime dmMaritime) {
		int value = 0;

		if (getId() < dmMaritime.getId()) {
			value = -1;
		}
		else if (getId() > dmMaritime.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DmMaritime)) {
			return false;
		}

		DmMaritime dmMaritime = (DmMaritime)obj;

		int primaryKey = dmMaritime.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DmMaritimeModelImpl dmMaritimeModelImpl = this;

		dmMaritimeModelImpl._originalMaritimeCode = dmMaritimeModelImpl._maritimeCode;

		dmMaritimeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DmMaritime> toCacheModel() {
		DmMaritimeCacheModel dmMaritimeCacheModel = new DmMaritimeCacheModel();

		dmMaritimeCacheModel.id = getId();

		dmMaritimeCacheModel.maritimeCode = getMaritimeCode();

		String maritimeCode = dmMaritimeCacheModel.maritimeCode;

		if ((maritimeCode != null) && (maritimeCode.length() == 0)) {
			dmMaritimeCacheModel.maritimeCode = null;
		}

		dmMaritimeCacheModel.maritimeReference = getMaritimeReference();

		String maritimeReference = dmMaritimeCacheModel.maritimeReference;

		if ((maritimeReference != null) && (maritimeReference.length() == 0)) {
			dmMaritimeCacheModel.maritimeReference = null;
		}

		dmMaritimeCacheModel.maritimeOrder = getMaritimeOrder();

		dmMaritimeCacheModel.maritimeName = getMaritimeName();

		String maritimeName = dmMaritimeCacheModel.maritimeName;

		if ((maritimeName != null) && (maritimeName.length() == 0)) {
			dmMaritimeCacheModel.maritimeName = null;
		}

		dmMaritimeCacheModel.maritimeNameVN = getMaritimeNameVN();

		String maritimeNameVN = dmMaritimeCacheModel.maritimeNameVN;

		if ((maritimeNameVN != null) && (maritimeNameVN.length() == 0)) {
			dmMaritimeCacheModel.maritimeNameVN = null;
		}

		dmMaritimeCacheModel.address = getAddress();

		String address = dmMaritimeCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			dmMaritimeCacheModel.address = null;
		}

		dmMaritimeCacheModel.addressVN = getAddressVN();

		String addressVN = dmMaritimeCacheModel.addressVN;

		if ((addressVN != null) && (addressVN.length() == 0)) {
			dmMaritimeCacheModel.addressVN = null;
		}

		dmMaritimeCacheModel.stateCode = getStateCode();

		String stateCode = dmMaritimeCacheModel.stateCode;

		if ((stateCode != null) && (stateCode.length() == 0)) {
			dmMaritimeCacheModel.stateCode = null;
		}

		dmMaritimeCacheModel.citycode = getCitycode();

		String citycode = dmMaritimeCacheModel.citycode;

		if ((citycode != null) && (citycode.length() == 0)) {
			dmMaritimeCacheModel.citycode = null;
		}

		dmMaritimeCacheModel.isDelete = getIsDelete();

		dmMaritimeCacheModel.markedAsDelete = getMarkedAsDelete();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dmMaritimeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dmMaritimeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date requestedDate = getRequestedDate();

		if (requestedDate != null) {
			dmMaritimeCacheModel.requestedDate = requestedDate.getTime();
		}
		else {
			dmMaritimeCacheModel.requestedDate = Long.MIN_VALUE;
		}

		dmMaritimeCacheModel.syncVersion = getSyncVersion();

		String syncVersion = dmMaritimeCacheModel.syncVersion;

		if ((syncVersion != null) && (syncVersion.length() == 0)) {
			dmMaritimeCacheModel.syncVersion = null;
		}

		return dmMaritimeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maritimeCode=");
		sb.append(getMaritimeCode());
		sb.append(", maritimeReference=");
		sb.append(getMaritimeReference());
		sb.append(", maritimeOrder=");
		sb.append(getMaritimeOrder());
		sb.append(", maritimeName=");
		sb.append(getMaritimeName());
		sb.append(", maritimeNameVN=");
		sb.append(getMaritimeNameVN());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", addressVN=");
		sb.append(getAddressVN());
		sb.append(", stateCode=");
		sb.append(getStateCode());
		sb.append(", citycode=");
		sb.append(getCitycode());
		sb.append(", isDelete=");
		sb.append(getIsDelete());
		sb.append(", markedAsDelete=");
		sb.append(getMarkedAsDelete());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", requestedDate=");
		sb.append(getRequestedDate());
		sb.append(", syncVersion=");
		sb.append(getSyncVersion());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbien.dao.vrcb.model.DmMaritime");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maritimeCode</column-name><column-value><![CDATA[");
		sb.append(getMaritimeCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maritimeReference</column-name><column-value><![CDATA[");
		sb.append(getMaritimeReference());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maritimeOrder</column-name><column-value><![CDATA[");
		sb.append(getMaritimeOrder());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maritimeName</column-name><column-value><![CDATA[");
		sb.append(getMaritimeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maritimeNameVN</column-name><column-value><![CDATA[");
		sb.append(getMaritimeNameVN());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>addressVN</column-name><column-value><![CDATA[");
		sb.append(getAddressVN());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stateCode</column-name><column-value><![CDATA[");
		sb.append(getStateCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>citycode</column-name><column-value><![CDATA[");
		sb.append(getCitycode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isDelete</column-name><column-value><![CDATA[");
		sb.append(getIsDelete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>markedAsDelete</column-name><column-value><![CDATA[");
		sb.append(getMarkedAsDelete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestedDate</column-name><column-value><![CDATA[");
		sb.append(getRequestedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>syncVersion</column-name><column-value><![CDATA[");
		sb.append(getSyncVersion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DmMaritime.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DmMaritime.class
		};
	private int _id;
	private String _maritimeCode;
	private String _originalMaritimeCode;
	private String _maritimeReference;
	private int _maritimeOrder;
	private String _maritimeName;
	private String _maritimeNameVN;
	private String _address;
	private String _addressVN;
	private String _stateCode;
	private String _citycode;
	private int _isDelete;
	private int _markedAsDelete;
	private Date _modifiedDate;
	private Date _requestedDate;
	private String _syncVersion;
	private long _columnBitmask;
	private DmMaritime _escapedModel;
}