/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbien.dao.vrcb.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbien.dao.vrcb.model.PassengerList;
import vn.dtt.duongbien.dao.vrcb.model.PassengerListModel;
import vn.dtt.duongbien.dao.vrcb.model.PassengerListSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PassengerList service. Represents a row in the &quot;passenger_list&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbien.dao.vrcb.model.PassengerListModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PassengerListImpl}.
 * </p>
 *
 * @author longdm
 * @see PassengerListImpl
 * @see vn.dtt.duongbien.dao.vrcb.model.PassengerList
 * @see vn.dtt.duongbien.dao.vrcb.model.PassengerListModel
 * @generated
 */
@JSON(strict = true)
public class PassengerListModelImpl extends BaseModelImpl<PassengerList>
	implements PassengerListModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a passenger list model instance should use the {@link vn.dtt.duongbien.dao.vrcb.model.PassengerList} interface instead.
	 */
	public static final String TABLE_NAME = "passenger_list";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "passengercode", Types.VARCHAR },
			{ "documentno", Types.VARCHAR },
			{ "fullname", Types.VARCHAR },
			{ "statecode", Types.VARCHAR },
			{ "birthday", Types.TIMESTAMP },
			{ "birthplace", Types.VARCHAR },
			{ "passporttypecode", Types.VARCHAR },
			{ "passportno", Types.VARCHAR },
			{ "portcheckincode", Types.VARCHAR },
			{ "portcheckoutcode", Types.VARCHAR },
			{ "istransit", Types.BOOLEAN },
			{ "createdate", Types.TIMESTAMP },
			{ "modifydate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table passenger_list (id LONG not null primary key,passengercode VARCHAR(75) null,documentno VARCHAR(75) null,fullname VARCHAR(75) null,statecode VARCHAR(75) null,birthday DATE null,birthplace VARCHAR(75) null,passporttypecode VARCHAR(75) null,passportno VARCHAR(75) null,portcheckincode VARCHAR(75) null,portcheckoutcode VARCHAR(75) null,istransit BOOLEAN,createdate DATE null,modifydate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table passenger_list";
	public static final String ORDER_BY_JPQL = " ORDER BY passengerList.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY passenger_list.createdate ASC";
	public static final String DATA_SOURCE = "vaoracangbienDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbien.dao.vrcb.model.PassengerList"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbien.dao.vrcb.model.PassengerList"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PassengerList toModel(PassengerListSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PassengerList model = new PassengerListImpl();

		model.setId(soapModel.getId());
		model.setPassengerCode(soapModel.getPassengerCode());
		model.setDocumentNo(soapModel.getDocumentNo());
		model.setFullName(soapModel.getFullName());
		model.setStateCode(soapModel.getStateCode());
		model.setBirthDay(soapModel.getBirthDay());
		model.setBirthPlace(soapModel.getBirthPlace());
		model.setPassportTypeCode(soapModel.getPassportTypeCode());
		model.setPassPortNo(soapModel.getPassPortNo());
		model.setPortCheckInCode(soapModel.getPortCheckInCode());
		model.setPortCheckOutCode(soapModel.getPortCheckOutCode());
		model.setIsTransit(soapModel.getIsTransit());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifyDate(soapModel.getModifyDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PassengerList> toModels(PassengerListSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PassengerList> models = new ArrayList<PassengerList>(soapModels.length);

		for (PassengerListSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbien.dao.vrcb.model.PassengerList"));

	public PassengerListModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PassengerList.class;
	}

	@Override
	public String getModelClassName() {
		return PassengerList.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("passengerCode", getPassengerCode());
		attributes.put("documentNo", getDocumentNo());
		attributes.put("fullName", getFullName());
		attributes.put("stateCode", getStateCode());
		attributes.put("birthDay", getBirthDay());
		attributes.put("birthPlace", getBirthPlace());
		attributes.put("passportTypeCode", getPassportTypeCode());
		attributes.put("passPortNo", getPassPortNo());
		attributes.put("portCheckInCode", getPortCheckInCode());
		attributes.put("portCheckOutCode", getPortCheckOutCode());
		attributes.put("isTransit", getIsTransit());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifyDate", getModifyDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String passengerCode = (String)attributes.get("passengerCode");

		if (passengerCode != null) {
			setPassengerCode(passengerCode);
		}

		String documentNo = (String)attributes.get("documentNo");

		if (documentNo != null) {
			setDocumentNo(documentNo);
		}

		String fullName = (String)attributes.get("fullName");

		if (fullName != null) {
			setFullName(fullName);
		}

		String stateCode = (String)attributes.get("stateCode");

		if (stateCode != null) {
			setStateCode(stateCode);
		}

		Date birthDay = (Date)attributes.get("birthDay");

		if (birthDay != null) {
			setBirthDay(birthDay);
		}

		String birthPlace = (String)attributes.get("birthPlace");

		if (birthPlace != null) {
			setBirthPlace(birthPlace);
		}

		String passportTypeCode = (String)attributes.get("passportTypeCode");

		if (passportTypeCode != null) {
			setPassportTypeCode(passportTypeCode);
		}

		String passPortNo = (String)attributes.get("passPortNo");

		if (passPortNo != null) {
			setPassPortNo(passPortNo);
		}

		String portCheckInCode = (String)attributes.get("portCheckInCode");

		if (portCheckInCode != null) {
			setPortCheckInCode(portCheckInCode);
		}

		String portCheckOutCode = (String)attributes.get("portCheckOutCode");

		if (portCheckOutCode != null) {
			setPortCheckOutCode(portCheckOutCode);
		}

		Boolean isTransit = (Boolean)attributes.get("isTransit");

		if (isTransit != null) {
			setIsTransit(isTransit);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifyDate = (Date)attributes.get("modifyDate");

		if (modifyDate != null) {
			setModifyDate(modifyDate);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getPassengerCode() {
		if (_passengerCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _passengerCode;
		}
	}

	@Override
	public void setPassengerCode(String passengerCode) {
		_passengerCode = passengerCode;
	}

	@JSON
	@Override
	public String getDocumentNo() {
		if (_documentNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _documentNo;
		}
	}

	@Override
	public void setDocumentNo(String documentNo) {
		_documentNo = documentNo;
	}

	@JSON
	@Override
	public String getFullName() {
		if (_fullName == null) {
			return StringPool.BLANK;
		}
		else {
			return _fullName;
		}
	}

	@Override
	public void setFullName(String fullName) {
		_fullName = fullName;
	}

	@JSON
	@Override
	public String getStateCode() {
		if (_stateCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _stateCode;
		}
	}

	@Override
	public void setStateCode(String stateCode) {
		_stateCode = stateCode;
	}

	@JSON
	@Override
	public Date getBirthDay() {
		return _birthDay;
	}

	@Override
	public void setBirthDay(Date birthDay) {
		_birthDay = birthDay;
	}

	@JSON
	@Override
	public String getBirthPlace() {
		if (_birthPlace == null) {
			return StringPool.BLANK;
		}
		else {
			return _birthPlace;
		}
	}

	@Override
	public void setBirthPlace(String birthPlace) {
		_birthPlace = birthPlace;
	}

	@JSON
	@Override
	public String getPassportTypeCode() {
		if (_passportTypeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _passportTypeCode;
		}
	}

	@Override
	public void setPassportTypeCode(String passportTypeCode) {
		_passportTypeCode = passportTypeCode;
	}

	@JSON
	@Override
	public String getPassPortNo() {
		if (_passPortNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _passPortNo;
		}
	}

	@Override
	public void setPassPortNo(String passPortNo) {
		_passPortNo = passPortNo;
	}

	@JSON
	@Override
	public String getPortCheckInCode() {
		if (_portCheckInCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portCheckInCode;
		}
	}

	@Override
	public void setPortCheckInCode(String portCheckInCode) {
		_portCheckInCode = portCheckInCode;
	}

	@JSON
	@Override
	public String getPortCheckOutCode() {
		if (_portCheckOutCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portCheckOutCode;
		}
	}

	@Override
	public void setPortCheckOutCode(String portCheckOutCode) {
		_portCheckOutCode = portCheckOutCode;
	}

	@JSON
	@Override
	public boolean getIsTransit() {
		return _isTransit;
	}

	@Override
	public boolean isIsTransit() {
		return _isTransit;
	}

	@Override
	public void setIsTransit(boolean isTransit) {
		_isTransit = isTransit;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifyDate() {
		return _modifyDate;
	}

	@Override
	public void setModifyDate(Date modifyDate) {
		_modifyDate = modifyDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PassengerList.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PassengerList toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PassengerList)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PassengerListImpl passengerListImpl = new PassengerListImpl();

		passengerListImpl.setId(getId());
		passengerListImpl.setPassengerCode(getPassengerCode());
		passengerListImpl.setDocumentNo(getDocumentNo());
		passengerListImpl.setFullName(getFullName());
		passengerListImpl.setStateCode(getStateCode());
		passengerListImpl.setBirthDay(getBirthDay());
		passengerListImpl.setBirthPlace(getBirthPlace());
		passengerListImpl.setPassportTypeCode(getPassportTypeCode());
		passengerListImpl.setPassPortNo(getPassPortNo());
		passengerListImpl.setPortCheckInCode(getPortCheckInCode());
		passengerListImpl.setPortCheckOutCode(getPortCheckOutCode());
		passengerListImpl.setIsTransit(getIsTransit());
		passengerListImpl.setCreateDate(getCreateDate());
		passengerListImpl.setModifyDate(getModifyDate());

		passengerListImpl.resetOriginalValues();

		return passengerListImpl;
	}

	@Override
	public int compareTo(PassengerList passengerList) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				passengerList.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PassengerList)) {
			return false;
		}

		PassengerList passengerList = (PassengerList)obj;

		long primaryKey = passengerList.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PassengerList> toCacheModel() {
		PassengerListCacheModel passengerListCacheModel = new PassengerListCacheModel();

		passengerListCacheModel.id = getId();

		passengerListCacheModel.passengerCode = getPassengerCode();

		String passengerCode = passengerListCacheModel.passengerCode;

		if ((passengerCode != null) && (passengerCode.length() == 0)) {
			passengerListCacheModel.passengerCode = null;
		}

		passengerListCacheModel.documentNo = getDocumentNo();

		String documentNo = passengerListCacheModel.documentNo;

		if ((documentNo != null) && (documentNo.length() == 0)) {
			passengerListCacheModel.documentNo = null;
		}

		passengerListCacheModel.fullName = getFullName();

		String fullName = passengerListCacheModel.fullName;

		if ((fullName != null) && (fullName.length() == 0)) {
			passengerListCacheModel.fullName = null;
		}

		passengerListCacheModel.stateCode = getStateCode();

		String stateCode = passengerListCacheModel.stateCode;

		if ((stateCode != null) && (stateCode.length() == 0)) {
			passengerListCacheModel.stateCode = null;
		}

		Date birthDay = getBirthDay();

		if (birthDay != null) {
			passengerListCacheModel.birthDay = birthDay.getTime();
		}
		else {
			passengerListCacheModel.birthDay = Long.MIN_VALUE;
		}

		passengerListCacheModel.birthPlace = getBirthPlace();

		String birthPlace = passengerListCacheModel.birthPlace;

		if ((birthPlace != null) && (birthPlace.length() == 0)) {
			passengerListCacheModel.birthPlace = null;
		}

		passengerListCacheModel.passportTypeCode = getPassportTypeCode();

		String passportTypeCode = passengerListCacheModel.passportTypeCode;

		if ((passportTypeCode != null) && (passportTypeCode.length() == 0)) {
			passengerListCacheModel.passportTypeCode = null;
		}

		passengerListCacheModel.passPortNo = getPassPortNo();

		String passPortNo = passengerListCacheModel.passPortNo;

		if ((passPortNo != null) && (passPortNo.length() == 0)) {
			passengerListCacheModel.passPortNo = null;
		}

		passengerListCacheModel.portCheckInCode = getPortCheckInCode();

		String portCheckInCode = passengerListCacheModel.portCheckInCode;

		if ((portCheckInCode != null) && (portCheckInCode.length() == 0)) {
			passengerListCacheModel.portCheckInCode = null;
		}

		passengerListCacheModel.portCheckOutCode = getPortCheckOutCode();

		String portCheckOutCode = passengerListCacheModel.portCheckOutCode;

		if ((portCheckOutCode != null) && (portCheckOutCode.length() == 0)) {
			passengerListCacheModel.portCheckOutCode = null;
		}

		passengerListCacheModel.isTransit = getIsTransit();

		Date createDate = getCreateDate();

		if (createDate != null) {
			passengerListCacheModel.createDate = createDate.getTime();
		}
		else {
			passengerListCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifyDate = getModifyDate();

		if (modifyDate != null) {
			passengerListCacheModel.modifyDate = modifyDate.getTime();
		}
		else {
			passengerListCacheModel.modifyDate = Long.MIN_VALUE;
		}

		return passengerListCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", passengerCode=");
		sb.append(getPassengerCode());
		sb.append(", documentNo=");
		sb.append(getDocumentNo());
		sb.append(", fullName=");
		sb.append(getFullName());
		sb.append(", stateCode=");
		sb.append(getStateCode());
		sb.append(", birthDay=");
		sb.append(getBirthDay());
		sb.append(", birthPlace=");
		sb.append(getBirthPlace());
		sb.append(", passportTypeCode=");
		sb.append(getPassportTypeCode());
		sb.append(", passPortNo=");
		sb.append(getPassPortNo());
		sb.append(", portCheckInCode=");
		sb.append(getPortCheckInCode());
		sb.append(", portCheckOutCode=");
		sb.append(getPortCheckOutCode());
		sb.append(", isTransit=");
		sb.append(getIsTransit());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifyDate=");
		sb.append(getModifyDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbien.dao.vrcb.model.PassengerList");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>passengerCode</column-name><column-value><![CDATA[");
		sb.append(getPassengerCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentNo</column-name><column-value><![CDATA[");
		sb.append(getDocumentNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fullName</column-name><column-value><![CDATA[");
		sb.append(getFullName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stateCode</column-name><column-value><![CDATA[");
		sb.append(getStateCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>birthDay</column-name><column-value><![CDATA[");
		sb.append(getBirthDay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>birthPlace</column-name><column-value><![CDATA[");
		sb.append(getBirthPlace());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>passportTypeCode</column-name><column-value><![CDATA[");
		sb.append(getPassportTypeCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>passPortNo</column-name><column-value><![CDATA[");
		sb.append(getPassPortNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portCheckInCode</column-name><column-value><![CDATA[");
		sb.append(getPortCheckInCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portCheckOutCode</column-name><column-value><![CDATA[");
		sb.append(getPortCheckOutCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isTransit</column-name><column-value><![CDATA[");
		sb.append(getIsTransit());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDate</column-name><column-value><![CDATA[");
		sb.append(getModifyDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PassengerList.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PassengerList.class
		};
	private long _id;
	private String _passengerCode;
	private String _documentNo;
	private String _fullName;
	private String _stateCode;
	private Date _birthDay;
	private String _birthPlace;
	private String _passportTypeCode;
	private String _passPortNo;
	private String _portCheckInCode;
	private String _portCheckOutCode;
	private boolean _isTransit;
	private Date _createDate;
	private Date _modifyDate;
	private PassengerList _escapedModel;
}