/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.thanhtoan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import vn.dtt.duongbo.dao.thanhtoan.service.persistence.ThanhToanKeyPayPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ThanhToanKeyPay service. Represents a row in the &quot;log_thanhtoankeypay&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.thanhtoan.model.impl.ThanhToanKeyPayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.thanhtoan.model.impl.ThanhToanKeyPayImpl}.
 * </p>
 *
 * @author win_64
 * @see ThanhToanKeyPay
 * @see vn.dtt.duongbo.dao.thanhtoan.model.impl.ThanhToanKeyPayImpl
 * @see vn.dtt.duongbo.dao.thanhtoan.model.impl.ThanhToanKeyPayModelImpl
 * @generated
 */
public interface ThanhToanKeyPayModel extends BaseModel<ThanhToanKeyPay> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a thanh toan key pay model instance should use the {@link ThanhToanKeyPay} interface instead.
	 */

	/**
	 * Returns the primary key of this thanh toan key pay.
	 *
	 * @return the primary key of this thanh toan key pay
	 */
	public ThanhToanKeyPayPK getPrimaryKey();

	/**
	 * Sets the primary key of this thanh toan key pay.
	 *
	 * @param primaryKey the primary key of this thanh toan key pay
	 */
	public void setPrimaryKey(ThanhToanKeyPayPK primaryKey);

	/**
	 * Returns the ID of this thanh toan key pay.
	 *
	 * @return the ID of this thanh toan key pay
	 */
	public long getId();

	/**
	 * Sets the ID of this thanh toan key pay.
	 *
	 * @param id the ID of this thanh toan key pay
	 */
	public void setId(long id);

	/**
	 * Returns the id doanh nghiep of this thanh toan key pay.
	 *
	 * @return the id doanh nghiep of this thanh toan key pay
	 */
	public long getIdDoanhNghiep();

	/**
	 * Sets the id doanh nghiep of this thanh toan key pay.
	 *
	 * @param idDoanhNghiep the id doanh nghiep of this thanh toan key pay
	 */
	public void setIdDoanhNghiep(long idDoanhNghiep);

	/**
	 * Returns the good code of this thanh toan key pay.
	 *
	 * @return the good code of this thanh toan key pay
	 */
	@AutoEscape
	public String getGoodCode();

	/**
	 * Sets the good code of this thanh toan key pay.
	 *
	 * @param goodCode the good code of this thanh toan key pay
	 */
	public void setGoodCode(String goodCode);

	/**
	 * Returns the amount of this thanh toan key pay.
	 *
	 * @return the amount of this thanh toan key pay
	 */
	public long getAmount();

	/**
	 * Sets the amount of this thanh toan key pay.
	 *
	 * @param amount the amount of this thanh toan key pay
	 */
	public void setAmount(long amount);

	/**
	 * Returns the merchant trans ID of this thanh toan key pay.
	 *
	 * @return the merchant trans ID of this thanh toan key pay
	 */
	@AutoEscape
	public String getMerchantTransId();

	/**
	 * Sets the merchant trans ID of this thanh toan key pay.
	 *
	 * @param merchantTransId the merchant trans ID of this thanh toan key pay
	 */
	public void setMerchantTransId(String merchantTransId);

	/**
	 * Returns the merchant code of this thanh toan key pay.
	 *
	 * @return the merchant code of this thanh toan key pay
	 */
	@AutoEscape
	public String getMerchantCode();

	/**
	 * Sets the merchant code of this thanh toan key pay.
	 *
	 * @param merchantCode the merchant code of this thanh toan key pay
	 */
	public void setMerchantCode(String merchantCode);

	/**
	 * Returns the response code of this thanh toan key pay.
	 *
	 * @return the response code of this thanh toan key pay
	 */
	@AutoEscape
	public String getResponseCode();

	/**
	 * Sets the response code of this thanh toan key pay.
	 *
	 * @param responseCode the response code of this thanh toan key pay
	 */
	public void setResponseCode(String responseCode);

	/**
	 * Returns the transid keypay of this thanh toan key pay.
	 *
	 * @return the transid keypay of this thanh toan key pay
	 */
	public long getTransidKeypay();

	/**
	 * Sets the transid keypay of this thanh toan key pay.
	 *
	 * @param transidKeypay the transid keypay of this thanh toan key pay
	 */
	public void setTransidKeypay(long transidKeypay);

	/**
	 * Returns the net cost of this thanh toan key pay.
	 *
	 * @return the net cost of this thanh toan key pay
	 */
	public long getNetCost();

	/**
	 * Sets the net cost of this thanh toan key pay.
	 *
	 * @param netCost the net cost of this thanh toan key pay
	 */
	public void setNetCost(long netCost);

	/**
	 * Returns the ship fee of this thanh toan key pay.
	 *
	 * @return the ship fee of this thanh toan key pay
	 */
	public long getShipFee();

	/**
	 * Sets the ship fee of this thanh toan key pay.
	 *
	 * @param shipFee the ship fee of this thanh toan key pay
	 */
	public void setShipFee(long shipFee);

	/**
	 * Returns the currency code of this thanh toan key pay.
	 *
	 * @return the currency code of this thanh toan key pay
	 */
	@AutoEscape
	public String getCurrencyCode();

	/**
	 * Sets the currency code of this thanh toan key pay.
	 *
	 * @param currencyCode the currency code of this thanh toan key pay
	 */
	public void setCurrencyCode(String currencyCode);

	/**
	 * Returns the bank code of this thanh toan key pay.
	 *
	 * @return the bank code of this thanh toan key pay
	 */
	@AutoEscape
	public String getBankCode();

	/**
	 * Sets the bank code of this thanh toan key pay.
	 *
	 * @param bankCode the bank code of this thanh toan key pay
	 */
	public void setBankCode(String bankCode);

	/**
	 * Returns the xml description of this thanh toan key pay.
	 *
	 * @return the xml description of this thanh toan key pay
	 */
	@AutoEscape
	public String getXmlDescription();

	/**
	 * Sets the xml description of this thanh toan key pay.
	 *
	 * @param xmlDescription the xml description of this thanh toan key pay
	 */
	public void setXmlDescription(String xmlDescription);

	/**
	 * Returns the ngay xu ly of this thanh toan key pay.
	 *
	 * @return the ngay xu ly of this thanh toan key pay
	 */
	public Date getNgayXuLy();

	/**
	 * Sets the ngay xu ly of this thanh toan key pay.
	 *
	 * @param ngayXuLy the ngay xu ly of this thanh toan key pay
	 */
	public void setNgayXuLy(Date ngayXuLy);

	/**
	 * Returns the thong tin ho so of this thanh toan key pay.
	 *
	 * @return the thong tin ho so of this thanh toan key pay
	 */
	@AutoEscape
	public String getThongTinHoSo();

	/**
	 * Sets the thong tin ho so of this thanh toan key pay.
	 *
	 * @param thongTinHoSo the thong tin ho so of this thanh toan key pay
	 */
	public void setThongTinHoSo(String thongTinHoSo);

	/**
	 * Returns the loai message of this thanh toan key pay.
	 *
	 * @return the loai message of this thanh toan key pay
	 */
	public long getLoaiMessage();

	/**
	 * Sets the loai message of this thanh toan key pay.
	 *
	 * @param loaiMessage the loai message of this thanh toan key pay
	 */
	public void setLoaiMessage(long loaiMessage);

	/**
	 * Returns the ipn of this thanh toan key pay.
	 *
	 * @return the ipn of this thanh toan key pay
	 */
	public long getIpn();

	/**
	 * Sets the ipn of this thanh toan key pay.
	 *
	 * @param ipn the ipn of this thanh toan key pay
	 */
	public void setIpn(long ipn);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ThanhToanKeyPay thanhToanKeyPay);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ThanhToanKeyPay> toCacheModel();

	@Override
	public ThanhToanKeyPay toEscapedModel();

	@Override
	public ThanhToanKeyPay toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}