/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.thanhtoan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TthcYeuCauThanhToan service. Represents a row in the &quot;tthc_yeucauthanhtoan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcYeuCauThanhToanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcYeuCauThanhToanImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcYeuCauThanhToan
 * @see vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcYeuCauThanhToanImpl
 * @see vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcYeuCauThanhToanModelImpl
 * @generated
 */
public interface TthcYeuCauThanhToanModel extends BaseModel<TthcYeuCauThanhToan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc yeu cau thanh toan model instance should use the {@link TthcYeuCauThanhToan} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc yeu cau thanh toan.
	 *
	 * @return the primary key of this tthc yeu cau thanh toan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc yeu cau thanh toan.
	 *
	 * @param primaryKey the primary key of this tthc yeu cau thanh toan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc yeu cau thanh toan.
	 *
	 * @return the ID of this tthc yeu cau thanh toan
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc yeu cau thanh toan.
	 *
	 * @param id the ID of this tthc yeu cau thanh toan
	 */
	public void setId(long id);

	/**
	 * Returns the ma so yeu cau of this tthc yeu cau thanh toan.
	 *
	 * @return the ma so yeu cau of this tthc yeu cau thanh toan
	 */
	@AutoEscape
	public String getMaSoYeuCau();

	/**
	 * Sets the ma so yeu cau of this tthc yeu cau thanh toan.
	 *
	 * @param maSoYeuCau the ma so yeu cau of this tthc yeu cau thanh toan
	 */
	public void setMaSoYeuCau(String maSoYeuCau);

	/**
	 * Returns the so tien of this tthc yeu cau thanh toan.
	 *
	 * @return the so tien of this tthc yeu cau thanh toan
	 */
	public long getSoTien();

	/**
	 * Sets the so tien of this tthc yeu cau thanh toan.
	 *
	 * @param soTien the so tien of this tthc yeu cau thanh toan
	 */
	public void setSoTien(long soTien);

	/**
	 * Returns the chi tiet yeu cau of this tthc yeu cau thanh toan.
	 *
	 * @return the chi tiet yeu cau of this tthc yeu cau thanh toan
	 */
	@AutoEscape
	public String getChiTietYeuCau();

	/**
	 * Sets the chi tiet yeu cau of this tthc yeu cau thanh toan.
	 *
	 * @param chiTietYeuCau the chi tiet yeu cau of this tthc yeu cau thanh toan
	 */
	public void setChiTietYeuCau(String chiTietYeuCau);

	/**
	 * Returns the ngay tao of this tthc yeu cau thanh toan.
	 *
	 * @return the ngay tao of this tthc yeu cau thanh toan
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this tthc yeu cau thanh toan.
	 *
	 * @param ngayTao the ngay tao of this tthc yeu cau thanh toan
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the nguoi tao of this tthc yeu cau thanh toan.
	 *
	 * @return the nguoi tao of this tthc yeu cau thanh toan
	 */
	public long getNguoiTao();

	/**
	 * Sets the nguoi tao of this tthc yeu cau thanh toan.
	 *
	 * @param nguoiTao the nguoi tao of this tthc yeu cau thanh toan
	 */
	public void setNguoiTao(long nguoiTao);

	/**
	 * Returns the to chuc quan ly of this tthc yeu cau thanh toan.
	 *
	 * @return the to chuc quan ly of this tthc yeu cau thanh toan
	 */
	public long getToChucQuanLy();

	/**
	 * Sets the to chuc quan ly of this tthc yeu cau thanh toan.
	 *
	 * @param toChucQuanLy the to chuc quan ly of this tthc yeu cau thanh toan
	 */
	public void setToChucQuanLy(long toChucQuanLy);

	/**
	 * Returns the ho so thu tuc ID of this tthc yeu cau thanh toan.
	 *
	 * @return the ho so thu tuc ID of this tthc yeu cau thanh toan
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this tthc yeu cau thanh toan.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this tthc yeu cau thanh toan
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the xac nhan thanh toan ID of this tthc yeu cau thanh toan.
	 *
	 * @return the xac nhan thanh toan ID of this tthc yeu cau thanh toan
	 */
	public long getXacNhanThanhToanId();

	/**
	 * Sets the xac nhan thanh toan ID of this tthc yeu cau thanh toan.
	 *
	 * @param xacNhanThanhToanId the xac nhan thanh toan ID of this tthc yeu cau thanh toan
	 */
	public void setXacNhanThanhToanId(long xacNhanThanhToanId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TthcYeuCauThanhToan tthcYeuCauThanhToan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TthcYeuCauThanhToan> toCacheModel();

	@Override
	public TthcYeuCauThanhToan toEscapedModel();

	@Override
	public TthcYeuCauThanhToan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}