/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.thanhtoan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TthcHinhThucNopPhi service. Represents a row in the &quot;tthc_hinhthucnopphi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcHinhThucNopPhiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcHinhThucNopPhiImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcHinhThucNopPhi
 * @see vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcHinhThucNopPhiImpl
 * @see vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcHinhThucNopPhiModelImpl
 * @generated
 */
public interface TthcHinhThucNopPhiModel extends BaseModel<TthcHinhThucNopPhi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc hinh thuc nop phi model instance should use the {@link TthcHinhThucNopPhi} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc hinh thuc nop phi.
	 *
	 * @return the primary key of this tthc hinh thuc nop phi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc hinh thuc nop phi.
	 *
	 * @param primaryKey the primary key of this tthc hinh thuc nop phi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc hinh thuc nop phi.
	 *
	 * @return the ID of this tthc hinh thuc nop phi
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc hinh thuc nop phi.
	 *
	 * @param id the ID of this tthc hinh thuc nop phi
	 */
	public void setId(long id);

	/**
	 * Returns the thu tuc hanh chinh ID of this tthc hinh thuc nop phi.
	 *
	 * @return the thu tuc hanh chinh ID of this tthc hinh thuc nop phi
	 */
	public long getThuTucHanhChinhId();

	/**
	 * Sets the thu tuc hanh chinh ID of this tthc hinh thuc nop phi.
	 *
	 * @param thuTucHanhChinhId the thu tuc hanh chinh ID of this tthc hinh thuc nop phi
	 */
	public void setThuTucHanhChinhId(long thuTucHanhChinhId);

	/**
	 * Returns the don vi thuc hien ID of this tthc hinh thuc nop phi.
	 *
	 * @return the don vi thuc hien ID of this tthc hinh thuc nop phi
	 */
	public long getDonViThucHienId();

	/**
	 * Sets the don vi thuc hien ID of this tthc hinh thuc nop phi.
	 *
	 * @param donViThucHienId the don vi thuc hien ID of this tthc hinh thuc nop phi
	 */
	public void setDonViThucHienId(long donViThucHienId);

	/**
	 * Returns the phi nop ban dau of this tthc hinh thuc nop phi.
	 *
	 * @return the phi nop ban dau of this tthc hinh thuc nop phi
	 */
	public long getPhiNopBanDau();

	/**
	 * Sets the phi nop ban dau of this tthc hinh thuc nop phi.
	 *
	 * @param phiNopBanDau the phi nop ban dau of this tthc hinh thuc nop phi
	 */
	public void setPhiNopBanDau(long phiNopBanDau);

	/**
	 * Returns the chuyen khoan of this tthc hinh thuc nop phi.
	 *
	 * @return the chuyen khoan of this tthc hinh thuc nop phi
	 */
	@AutoEscape
	public String getChuyenKhoan();

	/**
	 * Sets the chuyen khoan of this tthc hinh thuc nop phi.
	 *
	 * @param chuyenKhoan the chuyen khoan of this tthc hinh thuc nop phi
	 */
	public void setChuyenKhoan(String chuyenKhoan);

	/**
	 * Returns the key pay of this tthc hinh thuc nop phi.
	 *
	 * @return the key pay of this tthc hinh thuc nop phi
	 */
	@AutoEscape
	public String getKeyPay();

	/**
	 * Sets the key pay of this tthc hinh thuc nop phi.
	 *
	 * @param keyPay the key pay of this tthc hinh thuc nop phi
	 */
	public void setKeyPay(String keyPay);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TthcHinhThucNopPhi tthcHinhThucNopPhi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TthcHinhThucNopPhi> toCacheModel();

	@Override
	public TthcHinhThucNopPhi toEscapedModel();

	@Override
	public TthcHinhThucNopPhi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}