/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.thanhtoan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TthcXacNhanThanhToan service. Represents a row in the &quot;tthc_xacnhanthanhtoan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcXacNhanThanhToanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcXacNhanThanhToanImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcXacNhanThanhToan
 * @see vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcXacNhanThanhToanImpl
 * @see vn.dtt.duongbo.dao.thanhtoan.model.impl.TthcXacNhanThanhToanModelImpl
 * @generated
 */
public interface TthcXacNhanThanhToanModel extends BaseModel<TthcXacNhanThanhToan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc xac nhan thanh toan model instance should use the {@link TthcXacNhanThanhToan} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc xac nhan thanh toan.
	 *
	 * @return the primary key of this tthc xac nhan thanh toan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc xac nhan thanh toan.
	 *
	 * @param primaryKey the primary key of this tthc xac nhan thanh toan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc xac nhan thanh toan.
	 *
	 * @return the ID of this tthc xac nhan thanh toan
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc xac nhan thanh toan.
	 *
	 * @param id the ID of this tthc xac nhan thanh toan
	 */
	public void setId(long id);

	/**
	 * Returns the ma tu sinh of this tthc xac nhan thanh toan.
	 *
	 * @return the ma tu sinh of this tthc xac nhan thanh toan
	 */
	@AutoEscape
	public String getMaTuSinh();

	/**
	 * Sets the ma tu sinh of this tthc xac nhan thanh toan.
	 *
	 * @param maTuSinh the ma tu sinh of this tthc xac nhan thanh toan
	 */
	public void setMaTuSinh(String maTuSinh);

	/**
	 * Returns the so tien of this tthc xac nhan thanh toan.
	 *
	 * @return the so tien of this tthc xac nhan thanh toan
	 */
	public long getSoTien();

	/**
	 * Sets the so tien of this tthc xac nhan thanh toan.
	 *
	 * @param soTien the so tien of this tthc xac nhan thanh toan
	 */
	public void setSoTien(long soTien);

	/**
	 * Returns the hinh thuc thanh toan of this tthc xac nhan thanh toan.
	 *
	 * @return the hinh thuc thanh toan of this tthc xac nhan thanh toan
	 */
	public long getHinhThucThanhToan();

	/**
	 * Sets the hinh thuc thanh toan of this tthc xac nhan thanh toan.
	 *
	 * @param hinhThucThanhToan the hinh thuc thanh toan of this tthc xac nhan thanh toan
	 */
	public void setHinhThucThanhToan(long hinhThucThanhToan);

	/**
	 * Returns the thong tin xac nhan of this tthc xac nhan thanh toan.
	 *
	 * @return the thong tin xac nhan of this tthc xac nhan thanh toan
	 */
	@AutoEscape
	public String getThongTinXacNhan();

	/**
	 * Sets the thong tin xac nhan of this tthc xac nhan thanh toan.
	 *
	 * @param thongTinXacNhan the thong tin xac nhan of this tthc xac nhan thanh toan
	 */
	public void setThongTinXacNhan(String thongTinXacNhan);

	/**
	 * Returns the tai lieu dinh kem of this tthc xac nhan thanh toan.
	 *
	 * @return the tai lieu dinh kem of this tthc xac nhan thanh toan
	 */
	public long getTaiLieuDinhKem();

	/**
	 * Sets the tai lieu dinh kem of this tthc xac nhan thanh toan.
	 *
	 * @param taiLieuDinhKem the tai lieu dinh kem of this tthc xac nhan thanh toan
	 */
	public void setTaiLieuDinhKem(long taiLieuDinhKem);

	/**
	 * Returns the ngay tao of this tthc xac nhan thanh toan.
	 *
	 * @return the ngay tao of this tthc xac nhan thanh toan
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this tthc xac nhan thanh toan.
	 *
	 * @param ngayTao the ngay tao of this tthc xac nhan thanh toan
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the nguoi tao of this tthc xac nhan thanh toan.
	 *
	 * @return the nguoi tao of this tthc xac nhan thanh toan
	 */
	public long getNguoiTao();

	/**
	 * Sets the nguoi tao of this tthc xac nhan thanh toan.
	 *
	 * @param nguoiTao the nguoi tao of this tthc xac nhan thanh toan
	 */
	public void setNguoiTao(long nguoiTao);

	/**
	 * Returns the ngay xac nhan of this tthc xac nhan thanh toan.
	 *
	 * @return the ngay xac nhan of this tthc xac nhan thanh toan
	 */
	public Date getNgayXacNhan();

	/**
	 * Sets the ngay xac nhan of this tthc xac nhan thanh toan.
	 *
	 * @param ngayXacNhan the ngay xac nhan of this tthc xac nhan thanh toan
	 */
	public void setNgayXacNhan(Date ngayXacNhan);

	/**
	 * Returns the nguoi xac nhan of this tthc xac nhan thanh toan.
	 *
	 * @return the nguoi xac nhan of this tthc xac nhan thanh toan
	 */
	public long getNguoiXacNhan();

	/**
	 * Sets the nguoi xac nhan of this tthc xac nhan thanh toan.
	 *
	 * @param nguoiXacNhan the nguoi xac nhan of this tthc xac nhan thanh toan
	 */
	public void setNguoiXacNhan(long nguoiXacNhan);

	/**
	 * Returns the to chuc quan ly of this tthc xac nhan thanh toan.
	 *
	 * @return the to chuc quan ly of this tthc xac nhan thanh toan
	 */
	public long getToChucQuanLy();

	/**
	 * Sets the to chuc quan ly of this tthc xac nhan thanh toan.
	 *
	 * @param toChucQuanLy the to chuc quan ly of this tthc xac nhan thanh toan
	 */
	public void setToChucQuanLy(long toChucQuanLy);

	/**
	 * Returns the trang thai xac nhan of this tthc xac nhan thanh toan.
	 *
	 * @return the trang thai xac nhan of this tthc xac nhan thanh toan
	 */
	public int getTrangThaiXacNhan();

	/**
	 * Sets the trang thai xac nhan of this tthc xac nhan thanh toan.
	 *
	 * @param trangThaiXacNhan the trang thai xac nhan of this tthc xac nhan thanh toan
	 */
	public void setTrangThaiXacNhan(int trangThaiXacNhan);

	/**
	 * Returns the y kien xu ly of this tthc xac nhan thanh toan.
	 *
	 * @return the y kien xu ly of this tthc xac nhan thanh toan
	 */
	@AutoEscape
	public String getYKienXuLy();

	/**
	 * Sets the y kien xu ly of this tthc xac nhan thanh toan.
	 *
	 * @param yKienXuLy the y kien xu ly of this tthc xac nhan thanh toan
	 */
	public void setYKienXuLy(String yKienXuLy);

	/**
	 * Returns the loai phi of this tthc xac nhan thanh toan.
	 *
	 * @return the loai phi of this tthc xac nhan thanh toan
	 */
	@AutoEscape
	public String getLoaiPhi();

	/**
	 * Sets the loai phi of this tthc xac nhan thanh toan.
	 *
	 * @param loaiPhi the loai phi of this tthc xac nhan thanh toan
	 */
	public void setLoaiPhi(String loaiPhi);

	/**
	 * Returns the ten doanh nghiep of this tthc xac nhan thanh toan.
	 *
	 * @return the ten doanh nghiep of this tthc xac nhan thanh toan
	 */
	@AutoEscape
	public String getTenDoanhNghiep();

	/**
	 * Sets the ten doanh nghiep of this tthc xac nhan thanh toan.
	 *
	 * @param tenDoanhNghiep the ten doanh nghiep of this tthc xac nhan thanh toan
	 */
	public void setTenDoanhNghiep(String tenDoanhNghiep);

	/**
	 * Returns the ghi chu of this tthc xac nhan thanh toan.
	 *
	 * @return the ghi chu of this tthc xac nhan thanh toan
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this tthc xac nhan thanh toan.
	 *
	 * @param ghiChu the ghi chu of this tthc xac nhan thanh toan
	 */
	public void setGhiChu(String ghiChu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TthcXacNhanThanhToan tthcXacNhanThanhToan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TthcXacNhanThanhToan> toCacheModel();

	@Override
	public TthcXacNhanThanhToan toEscapedModel();

	@Override
	public TthcXacNhanThanhToan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}