/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MotCuaNhanTraHoSo service. Represents a row in the &quot;motcua_nhantrahoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.motcua.model.impl.MotCuaNhanTraHoSoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.motcua.model.impl.MotCuaNhanTraHoSoImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaNhanTraHoSo
 * @see vn.dtt.duongbo.dao.motcua.model.impl.MotCuaNhanTraHoSoImpl
 * @see vn.dtt.duongbo.dao.motcua.model.impl.MotCuaNhanTraHoSoModelImpl
 * @generated
 */
public interface MotCuaNhanTraHoSoModel extends BaseModel<MotCuaNhanTraHoSo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mot cua nhan tra ho so model instance should use the {@link MotCuaNhanTraHoSo} interface instead.
	 */

	/**
	 * Returns the primary key of this mot cua nhan tra ho so.
	 *
	 * @return the primary key of this mot cua nhan tra ho so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mot cua nhan tra ho so.
	 *
	 * @param primaryKey the primary key of this mot cua nhan tra ho so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mot cua nhan tra ho so.
	 *
	 * @return the ID of this mot cua nhan tra ho so
	 */
	public long getId();

	/**
	 * Sets the ID of this mot cua nhan tra ho so.
	 *
	 * @param id the ID of this mot cua nhan tra ho so
	 */
	public void setId(long id);

	/**
	 * Returns the ho so thu tuc ID of this mot cua nhan tra ho so.
	 *
	 * @return the ho so thu tuc ID of this mot cua nhan tra ho so
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this mot cua nhan tra ho so.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this mot cua nhan tra ho so
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the ten nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @return the ten nguoi nop of this mot cua nhan tra ho so
	 */
	@AutoEscape
	public String getTenNguoiNop();

	/**
	 * Sets the ten nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @param tenNguoiNop the ten nguoi nop of this mot cua nhan tra ho so
	 */
	public void setTenNguoiNop(String tenNguoiNop);

	/**
	 * Returns the cmnd nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @return the cmnd nguoi nop of this mot cua nhan tra ho so
	 */
	@AutoEscape
	public String getCmndNguoiNop();

	/**
	 * Sets the cmnd nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @param cmndNguoiNop the cmnd nguoi nop of this mot cua nhan tra ho so
	 */
	public void setCmndNguoiNop(String cmndNguoiNop);

	/**
	 * Returns the dia chi nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @return the dia chi nguoi nop of this mot cua nhan tra ho so
	 */
	@AutoEscape
	public String getDiaChiNguoiNop();

	/**
	 * Sets the dia chi nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @param diaChiNguoiNop the dia chi nguoi nop of this mot cua nhan tra ho so
	 */
	public void setDiaChiNguoiNop(String diaChiNguoiNop);

	/**
	 * Returns the so dien thoai nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @return the so dien thoai nguoi nop of this mot cua nhan tra ho so
	 */
	@AutoEscape
	public String getSoDienThoaiNguoiNop();

	/**
	 * Sets the so dien thoai nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @param soDienThoaiNguoiNop the so dien thoai nguoi nop of this mot cua nhan tra ho so
	 */
	public void setSoDienThoaiNguoiNop(String soDienThoaiNguoiNop);

	/**
	 * Returns the email nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @return the email nguoi nop of this mot cua nhan tra ho so
	 */
	@AutoEscape
	public String getEmailNguoiNop();

	/**
	 * Sets the email nguoi nop of this mot cua nhan tra ho so.
	 *
	 * @param emailNguoiNop the email nguoi nop of this mot cua nhan tra ho so
	 */
	public void setEmailNguoiNop(String emailNguoiNop);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MotCuaNhanTraHoSo motCuaNhanTraHoSo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MotCuaNhanTraHoSo> toCacheModel();

	@Override
	public MotCuaNhanTraHoSo toEscapedModel();

	@Override
	public MotCuaNhanTraHoSo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}