/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MotCuaPhieuXuLy service. Represents a row in the &quot;motcua_phieuxuly&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.motcua.model.impl.MotCuaPhieuXuLyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.motcua.model.impl.MotCuaPhieuXuLyImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaPhieuXuLy
 * @see vn.dtt.duongbo.dao.motcua.model.impl.MotCuaPhieuXuLyImpl
 * @see vn.dtt.duongbo.dao.motcua.model.impl.MotCuaPhieuXuLyModelImpl
 * @generated
 */
public interface MotCuaPhieuXuLyModel extends BaseModel<MotCuaPhieuXuLy> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mot cua phieu xu ly model instance should use the {@link MotCuaPhieuXuLy} interface instead.
	 */

	/**
	 * Returns the primary key of this mot cua phieu xu ly.
	 *
	 * @return the primary key of this mot cua phieu xu ly
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mot cua phieu xu ly.
	 *
	 * @param primaryKey the primary key of this mot cua phieu xu ly
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mot cua phieu xu ly.
	 *
	 * @return the ID of this mot cua phieu xu ly
	 */
	public long getId();

	/**
	 * Sets the ID of this mot cua phieu xu ly.
	 *
	 * @param id the ID of this mot cua phieu xu ly
	 */
	public void setId(long id);

	/**
	 * Returns the ho so thu tuc ID of this mot cua phieu xu ly.
	 *
	 * @return the ho so thu tuc ID of this mot cua phieu xu ly
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this mot cua phieu xu ly.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this mot cua phieu xu ly
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the quy trinh thu tuc ID of this mot cua phieu xu ly.
	 *
	 * @return the quy trinh thu tuc ID of this mot cua phieu xu ly
	 */
	public long getQuyTrinhThuTucId();

	/**
	 * Sets the quy trinh thu tuc ID of this mot cua phieu xu ly.
	 *
	 * @param quyTrinhThuTucId the quy trinh thu tuc ID of this mot cua phieu xu ly
	 */
	public void setQuyTrinhThuTucId(long quyTrinhThuTucId);

	/**
	 * Returns the so thu tu of this mot cua phieu xu ly.
	 *
	 * @return the so thu tu of this mot cua phieu xu ly
	 */
	public int getSoThuTu();

	/**
	 * Sets the so thu tu of this mot cua phieu xu ly.
	 *
	 * @param soThuTu the so thu tu of this mot cua phieu xu ly
	 */
	public void setSoThuTu(int soThuTu);

	/**
	 * Returns the trich yeu noi dung of this mot cua phieu xu ly.
	 *
	 * @return the trich yeu noi dung of this mot cua phieu xu ly
	 */
	@AutoEscape
	public String getTrichYeuNoiDung();

	/**
	 * Sets the trich yeu noi dung of this mot cua phieu xu ly.
	 *
	 * @param trichYeuNoiDung the trich yeu noi dung of this mot cua phieu xu ly
	 */
	public void setTrichYeuNoiDung(String trichYeuNoiDung);

	/**
	 * Returns the ghi chu of this mot cua phieu xu ly.
	 *
	 * @return the ghi chu of this mot cua phieu xu ly
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this mot cua phieu xu ly.
	 *
	 * @param ghiChu the ghi chu of this mot cua phieu xu ly
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the phieu xu ly cha of this mot cua phieu xu ly.
	 *
	 * @return the phieu xu ly cha of this mot cua phieu xu ly
	 */
	public long getPhieuXuLyCha();

	/**
	 * Sets the phieu xu ly cha of this mot cua phieu xu ly.
	 *
	 * @param phieuXuLyCha the phieu xu ly cha of this mot cua phieu xu ly
	 */
	public void setPhieuXuLyCha(long phieuXuLyCha);

	/**
	 * Returns the trang thai hien tai ID of this mot cua phieu xu ly.
	 *
	 * @return the trang thai hien tai ID of this mot cua phieu xu ly
	 */
	public long getTrangThaiHienTaiId();

	/**
	 * Sets the trang thai hien tai ID of this mot cua phieu xu ly.
	 *
	 * @param trangThaiHienTaiId the trang thai hien tai ID of this mot cua phieu xu ly
	 */
	public void setTrangThaiHienTaiId(long trangThaiHienTaiId);

	/**
	 * Returns the phan nhom ho so ID of this mot cua phieu xu ly.
	 *
	 * @return the phan nhom ho so ID of this mot cua phieu xu ly
	 */
	public long getPhanNhomHoSoId();

	/**
	 * Sets the phan nhom ho so ID of this mot cua phieu xu ly.
	 *
	 * @param phanNhomHoSoId the phan nhom ho so ID of this mot cua phieu xu ly
	 */
	public void setPhanNhomHoSoId(long phanNhomHoSoId);

	/**
	 * Returns the chiem quyen xu ly of this mot cua phieu xu ly.
	 *
	 * @return the chiem quyen xu ly of this mot cua phieu xu ly
	 */
	public long getChiemQuyenXuLy();

	/**
	 * Sets the chiem quyen xu ly of this mot cua phieu xu ly.
	 *
	 * @param chiemQuyenXuLy the chiem quyen xu ly of this mot cua phieu xu ly
	 */
	public void setChiemQuyenXuLy(long chiemQuyenXuLy);

	/**
	 * Returns the trang thai ket thuc of this mot cua phieu xu ly.
	 *
	 * @return the trang thai ket thuc of this mot cua phieu xu ly
	 */
	public long getTrangThaiKetThuc();

	/**
	 * Sets the trang thai ket thuc of this mot cua phieu xu ly.
	 *
	 * @param trangThaiKetThuc the trang thai ket thuc of this mot cua phieu xu ly
	 */
	public void setTrangThaiKetThuc(long trangThaiKetThuc);

	/**
	 * Returns the to chuc quan ly of this mot cua phieu xu ly.
	 *
	 * @return the to chuc quan ly of this mot cua phieu xu ly
	 */
	public long getToChucQuanLy();

	/**
	 * Sets the to chuc quan ly of this mot cua phieu xu ly.
	 *
	 * @param toChucQuanLy the to chuc quan ly of this mot cua phieu xu ly
	 */
	public void setToChucQuanLy(long toChucQuanLy);

	/**
	 * Returns the file tai lieu of this mot cua phieu xu ly.
	 *
	 * @return the file tai lieu of this mot cua phieu xu ly
	 */
	public long getFileTaiLieu();

	/**
	 * Sets the file tai lieu of this mot cua phieu xu ly.
	 *
	 * @param fileTaiLieu the file tai lieu of this mot cua phieu xu ly
	 */
	public void setFileTaiLieu(long fileTaiLieu);

	/**
	 * Returns the nguoi xu ly of this mot cua phieu xu ly.
	 *
	 * @return the nguoi xu ly of this mot cua phieu xu ly
	 */
	public long getNguoiXuLy();

	/**
	 * Sets the nguoi xu ly of this mot cua phieu xu ly.
	 *
	 * @param nguoiXuLy the nguoi xu ly of this mot cua phieu xu ly
	 */
	public void setNguoiXuLy(long nguoiXuLy);

	/**
	 * Returns the nguoi duoc uy quyen of this mot cua phieu xu ly.
	 *
	 * @return the nguoi duoc uy quyen of this mot cua phieu xu ly
	 */
	public long getNguoiDuocUyQuyen();

	/**
	 * Sets the nguoi duoc uy quyen of this mot cua phieu xu ly.
	 *
	 * @param nguoiDuocUyQuyen the nguoi duoc uy quyen of this mot cua phieu xu ly
	 */
	public void setNguoiDuocUyQuyen(long nguoiDuocUyQuyen);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MotCuaPhieuXuLy motCuaPhieuXuLy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MotCuaPhieuXuLy> toCacheModel();

	@Override
	public MotCuaPhieuXuLy toEscapedModel();

	@Override
	public MotCuaPhieuXuLy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}