/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MotCuaChuyenDichTrangThai service. Represents a row in the &quot;motcua_chuyendichtrangthai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.motcua.model.impl.MotCuaChuyenDichTrangThaiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.motcua.model.impl.MotCuaChuyenDichTrangThaiImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaChuyenDichTrangThai
 * @see vn.dtt.duongbo.dao.motcua.model.impl.MotCuaChuyenDichTrangThaiImpl
 * @see vn.dtt.duongbo.dao.motcua.model.impl.MotCuaChuyenDichTrangThaiModelImpl
 * @generated
 */
public interface MotCuaChuyenDichTrangThaiModel extends BaseModel<MotCuaChuyenDichTrangThai> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mot cua chuyen dich trang thai model instance should use the {@link MotCuaChuyenDichTrangThai} interface instead.
	 */

	/**
	 * Returns the primary key of this mot cua chuyen dich trang thai.
	 *
	 * @return the primary key of this mot cua chuyen dich trang thai
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mot cua chuyen dich trang thai.
	 *
	 * @param primaryKey the primary key of this mot cua chuyen dich trang thai
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mot cua chuyen dich trang thai.
	 *
	 * @return the ID of this mot cua chuyen dich trang thai
	 */
	public long getId();

	/**
	 * Sets the ID of this mot cua chuyen dich trang thai.
	 *
	 * @param id the ID of this mot cua chuyen dich trang thai
	 */
	public void setId(long id);

	/**
	 * Returns the trang thai nguon ID of this mot cua chuyen dich trang thai.
	 *
	 * @return the trang thai nguon ID of this mot cua chuyen dich trang thai
	 */
	public long getTrangThaiNguonId();

	/**
	 * Sets the trang thai nguon ID of this mot cua chuyen dich trang thai.
	 *
	 * @param trangThaiNguonId the trang thai nguon ID of this mot cua chuyen dich trang thai
	 */
	public void setTrangThaiNguonId(long trangThaiNguonId);

	/**
	 * Returns the trang thai dich ID of this mot cua chuyen dich trang thai.
	 *
	 * @return the trang thai dich ID of this mot cua chuyen dich trang thai
	 */
	public long getTrangThaiDichId();

	/**
	 * Sets the trang thai dich ID of this mot cua chuyen dich trang thai.
	 *
	 * @param trangThaiDichId the trang thai dich ID of this mot cua chuyen dich trang thai
	 */
	public void setTrangThaiDichId(long trangThaiDichId);

	/**
	 * Returns the dieu kien chuyen dich of this mot cua chuyen dich trang thai.
	 *
	 * @return the dieu kien chuyen dich of this mot cua chuyen dich trang thai
	 */
	@AutoEscape
	public String getDieuKienChuyenDich();

	/**
	 * Sets the dieu kien chuyen dich of this mot cua chuyen dich trang thai.
	 *
	 * @param dieuKienChuyenDich the dieu kien chuyen dich of this mot cua chuyen dich trang thai
	 */
	public void setDieuKienChuyenDich(String dieuKienChuyenDich);

	/**
	 * Returns the hanh dong xu ly of this mot cua chuyen dich trang thai.
	 *
	 * @return the hanh dong xu ly of this mot cua chuyen dich trang thai
	 */
	@AutoEscape
	public String getHanhDongXuLy();

	/**
	 * Sets the hanh dong xu ly of this mot cua chuyen dich trang thai.
	 *
	 * @param hanhDongXuLy the hanh dong xu ly of this mot cua chuyen dich trang thai
	 */
	public void setHanhDongXuLy(String hanhDongXuLy);

	/**
	 * Returns the so ngay xu ly of this mot cua chuyen dich trang thai.
	 *
	 * @return the so ngay xu ly of this mot cua chuyen dich trang thai
	 */
	public int getSoNgayXuLy();

	/**
	 * Sets the so ngay xu ly of this mot cua chuyen dich trang thai.
	 *
	 * @param soNgayXuLy the so ngay xu ly of this mot cua chuyen dich trang thai
	 */
	public void setSoNgayXuLy(int soNgayXuLy);

	/**
	 * Returns the phan nhom ho so ID of this mot cua chuyen dich trang thai.
	 *
	 * @return the phan nhom ho so ID of this mot cua chuyen dich trang thai
	 */
	public long getPhanNhomHoSoId();

	/**
	 * Sets the phan nhom ho so ID of this mot cua chuyen dich trang thai.
	 *
	 * @param phanNhomHoSoId the phan nhom ho so ID of this mot cua chuyen dich trang thai
	 */
	public void setPhanNhomHoSoId(long phanNhomHoSoId);

	/**
	 * Returns the quy trinh thu tuc ID of this mot cua chuyen dich trang thai.
	 *
	 * @return the quy trinh thu tuc ID of this mot cua chuyen dich trang thai
	 */
	public long getQuyTrinhThuTucId();

	/**
	 * Sets the quy trinh thu tuc ID of this mot cua chuyen dich trang thai.
	 *
	 * @param quyTrinhThuTucId the quy trinh thu tuc ID of this mot cua chuyen dich trang thai
	 */
	public void setQuyTrinhThuTucId(long quyTrinhThuTucId);

	/**
	 * Returns the tao phieu moi of this mot cua chuyen dich trang thai.
	 *
	 * @return the tao phieu moi of this mot cua chuyen dich trang thai
	 */
	public int getTaoPhieuMoi();

	/**
	 * Sets the tao phieu moi of this mot cua chuyen dich trang thai.
	 *
	 * @param taoPhieuMoi the tao phieu moi of this mot cua chuyen dich trang thai
	 */
	public void setTaoPhieuMoi(int taoPhieuMoi);

	/**
	 * Returns the thong bao xu ly of this mot cua chuyen dich trang thai.
	 *
	 * @return the thong bao xu ly of this mot cua chuyen dich trang thai
	 */
	@AutoEscape
	public String getThongBaoXuLy();

	/**
	 * Sets the thong bao xu ly of this mot cua chuyen dich trang thai.
	 *
	 * @param thongBaoXuLy the thong bao xu ly of this mot cua chuyen dich trang thai
	 */
	public void setThongBaoXuLy(String thongBaoXuLy);

	/**
	 * Returns the chuyen xu ly of this mot cua chuyen dich trang thai.
	 *
	 * @return the chuyen xu ly of this mot cua chuyen dich trang thai
	 */
	public int getChuyenXuLy();

	/**
	 * Sets the chuyen xu ly of this mot cua chuyen dich trang thai.
	 *
	 * @param chuyenXuLy the chuyen xu ly of this mot cua chuyen dich trang thai
	 */
	public void setChuyenXuLy(int chuyenXuLy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MotCuaChuyenDichTrangThai motCuaChuyenDichTrangThai);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MotCuaChuyenDichTrangThai> toCacheModel();

	@Override
	public MotCuaChuyenDichTrangThai toEscapedModel();

	@Override
	public MotCuaChuyenDichTrangThai toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}