/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MotCuaAnhXaTrangThai service. Represents a row in the &quot;motcua_anhxatrangthai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.motcua.model.impl.MotCuaAnhXaTrangThaiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.motcua.model.impl.MotCuaAnhXaTrangThaiImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaAnhXaTrangThai
 * @see vn.dtt.duongbo.dao.motcua.model.impl.MotCuaAnhXaTrangThaiImpl
 * @see vn.dtt.duongbo.dao.motcua.model.impl.MotCuaAnhXaTrangThaiModelImpl
 * @generated
 */
public interface MotCuaAnhXaTrangThaiModel extends BaseModel<MotCuaAnhXaTrangThai> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mot cua anh xa trang thai model instance should use the {@link MotCuaAnhXaTrangThai} interface instead.
	 */

	/**
	 * Returns the primary key of this mot cua anh xa trang thai.
	 *
	 * @return the primary key of this mot cua anh xa trang thai
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mot cua anh xa trang thai.
	 *
	 * @param primaryKey the primary key of this mot cua anh xa trang thai
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mot cua anh xa trang thai.
	 *
	 * @return the ID of this mot cua anh xa trang thai
	 */
	public long getId();

	/**
	 * Sets the ID of this mot cua anh xa trang thai.
	 *
	 * @param id the ID of this mot cua anh xa trang thai
	 */
	public void setId(long id);

	/**
	 * Returns the ma t t can bo of this mot cua anh xa trang thai.
	 *
	 * @return the ma t t can bo of this mot cua anh xa trang thai
	 */
	@AutoEscape
	public String getMaTTCanBo();

	/**
	 * Sets the ma t t can bo of this mot cua anh xa trang thai.
	 *
	 * @param maTTCanBo the ma t t can bo of this mot cua anh xa trang thai
	 */
	public void setMaTTCanBo(String maTTCanBo);

	/**
	 * Returns the ma t t doanh nghiep of this mot cua anh xa trang thai.
	 *
	 * @return the ma t t doanh nghiep of this mot cua anh xa trang thai
	 */
	@AutoEscape
	public String getMaTTDoanhNghiep();

	/**
	 * Sets the ma t t doanh nghiep of this mot cua anh xa trang thai.
	 *
	 * @param maTTDoanhNghiep the ma t t doanh nghiep of this mot cua anh xa trang thai
	 */
	public void setMaTTDoanhNghiep(String maTTDoanhNghiep);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MotCuaAnhXaTrangThai motCuaAnhXaTrangThai);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MotCuaAnhXaTrangThai> toCacheModel();

	@Override
	public MotCuaAnhXaTrangThai toEscapedModel();

	@Override
	public MotCuaAnhXaTrangThai toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}