/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OEPUserMgtWorkingUnit service. Represents a row in the &quot;oep_usermgt_workingunit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.motcua.model.impl.OEPUserMgtWorkingUnitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.motcua.model.impl.OEPUserMgtWorkingUnitImpl}.
 * </p>
 *
 * @author win_64
 * @see OEPUserMgtWorkingUnit
 * @see vn.dtt.duongbo.dao.motcua.model.impl.OEPUserMgtWorkingUnitImpl
 * @see vn.dtt.duongbo.dao.motcua.model.impl.OEPUserMgtWorkingUnitModelImpl
 * @generated
 */
public interface OEPUserMgtWorkingUnitModel extends BaseModel<OEPUserMgtWorkingUnit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a o e p user mgt working unit model instance should use the {@link OEPUserMgtWorkingUnit} interface instead.
	 */

	/**
	 * Returns the primary key of this o e p user mgt working unit.
	 *
	 * @return the primary key of this o e p user mgt working unit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this o e p user mgt working unit.
	 *
	 * @param primaryKey the primary key of this o e p user mgt working unit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the working unit ID of this o e p user mgt working unit.
	 *
	 * @return the working unit ID of this o e p user mgt working unit
	 */
	public long getWorkingUnitId();

	/**
	 * Sets the working unit ID of this o e p user mgt working unit.
	 *
	 * @param workingUnitId the working unit ID of this o e p user mgt working unit
	 */
	public void setWorkingUnitId(long workingUnitId);

	/**
	 * Returns the user ID of this o e p user mgt working unit.
	 *
	 * @return the user ID of this o e p user mgt working unit
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this o e p user mgt working unit.
	 *
	 * @param userId the user ID of this o e p user mgt working unit
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this o e p user mgt working unit.
	 *
	 * @return the user uuid of this o e p user mgt working unit
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this o e p user mgt working unit.
	 *
	 * @param userUuid the user uuid of this o e p user mgt working unit
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this o e p user mgt working unit.
	 *
	 * @return the group ID of this o e p user mgt working unit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this o e p user mgt working unit.
	 *
	 * @param groupId the group ID of this o e p user mgt working unit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this o e p user mgt working unit.
	 *
	 * @return the create date of this o e p user mgt working unit
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this o e p user mgt working unit.
	 *
	 * @param createDate the create date of this o e p user mgt working unit
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this o e p user mgt working unit.
	 *
	 * @return the modified date of this o e p user mgt working unit
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this o e p user mgt working unit.
	 *
	 * @param modifiedDate the modified date of this o e p user mgt working unit
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this o e p user mgt working unit.
	 *
	 * @return the organization ID of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getOrganizationId();

	/**
	 * Sets the organization ID of this o e p user mgt working unit.
	 *
	 * @param organizationId the organization ID of this o e p user mgt working unit
	 */
	public void setOrganizationId(String organizationId);

	/**
	 * Returns the gov agent ID of this o e p user mgt working unit.
	 *
	 * @return the gov agent ID of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getGovAgentId();

	/**
	 * Sets the gov agent ID of this o e p user mgt working unit.
	 *
	 * @param govAgentId the gov agent ID of this o e p user mgt working unit
	 */
	public void setGovAgentId(String govAgentId);

	/**
	 * Returns the name of this o e p user mgt working unit.
	 *
	 * @return the name of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this o e p user mgt working unit.
	 *
	 * @param name the name of this o e p user mgt working unit
	 */
	public void setName(String name);

	/**
	 * Returns the enname of this o e p user mgt working unit.
	 *
	 * @return the enname of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getEnname();

	/**
	 * Sets the enname of this o e p user mgt working unit.
	 *
	 * @param enname the enname of this o e p user mgt working unit
	 */
	public void setEnname(String enname);

	/**
	 * Returns the is root of this o e p user mgt working unit.
	 *
	 * @return the is root of this o e p user mgt working unit
	 */
	public int getIsRoot();

	/**
	 * Sets the is root of this o e p user mgt working unit.
	 *
	 * @param isRoot the is root of this o e p user mgt working unit
	 */
	public void setIsRoot(int isRoot);

	/**
	 * Returns the parent working unit ID of this o e p user mgt working unit.
	 *
	 * @return the parent working unit ID of this o e p user mgt working unit
	 */
	public long getParentWorkingUnitId();

	/**
	 * Sets the parent working unit ID of this o e p user mgt working unit.
	 *
	 * @param parentWorkingUnitId the parent working unit ID of this o e p user mgt working unit
	 */
	public void setParentWorkingUnitId(long parentWorkingUnitId);

	/**
	 * Returns the address of this o e p user mgt working unit.
	 *
	 * @return the address of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this o e p user mgt working unit.
	 *
	 * @param address the address of this o e p user mgt working unit
	 */
	public void setAddress(String address);

	/**
	 * Returns the city no of this o e p user mgt working unit.
	 *
	 * @return the city no of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getCityNo();

	/**
	 * Sets the city no of this o e p user mgt working unit.
	 *
	 * @param cityNo the city no of this o e p user mgt working unit
	 */
	public void setCityNo(String cityNo);

	/**
	 * Returns the city name of this o e p user mgt working unit.
	 *
	 * @return the city name of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this o e p user mgt working unit.
	 *
	 * @param cityName the city name of this o e p user mgt working unit
	 */
	public void setCityName(String cityName);

	/**
	 * Returns the district no of this o e p user mgt working unit.
	 *
	 * @return the district no of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getDistrictNo();

	/**
	 * Sets the district no of this o e p user mgt working unit.
	 *
	 * @param districtNo the district no of this o e p user mgt working unit
	 */
	public void setDistrictNo(String districtNo);

	/**
	 * Returns the district name of this o e p user mgt working unit.
	 *
	 * @return the district name of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getDistrictName();

	/**
	 * Sets the district name of this o e p user mgt working unit.
	 *
	 * @param districtName the district name of this o e p user mgt working unit
	 */
	public void setDistrictName(String districtName);

	/**
	 * Returns the ward no of this o e p user mgt working unit.
	 *
	 * @return the ward no of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getWardNo();

	/**
	 * Sets the ward no of this o e p user mgt working unit.
	 *
	 * @param wardNo the ward no of this o e p user mgt working unit
	 */
	public void setWardNo(String wardNo);

	/**
	 * Returns the ward name of this o e p user mgt working unit.
	 *
	 * @return the ward name of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getWardName();

	/**
	 * Sets the ward name of this o e p user mgt working unit.
	 *
	 * @param wardName the ward name of this o e p user mgt working unit
	 */
	public void setWardName(String wardName);

	/**
	 * Returns the gps position of this o e p user mgt working unit.
	 *
	 * @return the gps position of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getGpsPosition();

	/**
	 * Sets the gps position of this o e p user mgt working unit.
	 *
	 * @param gpsPosition the gps position of this o e p user mgt working unit
	 */
	public void setGpsPosition(String gpsPosition);

	/**
	 * Returns the tel no of this o e p user mgt working unit.
	 *
	 * @return the tel no of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getTelNo();

	/**
	 * Sets the tel no of this o e p user mgt working unit.
	 *
	 * @param telNo the tel no of this o e p user mgt working unit
	 */
	public void setTelNo(String telNo);

	/**
	 * Returns the fax of this o e p user mgt working unit.
	 *
	 * @return the fax of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this o e p user mgt working unit.
	 *
	 * @param fax the fax of this o e p user mgt working unit
	 */
	public void setFax(String fax);

	/**
	 * Returns the email of this o e p user mgt working unit.
	 *
	 * @return the email of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this o e p user mgt working unit.
	 *
	 * @param email the email of this o e p user mgt working unit
	 */
	public void setEmail(String email);

	/**
	 * Returns the website of this o e p user mgt working unit.
	 *
	 * @return the website of this o e p user mgt working unit
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this o e p user mgt working unit.
	 *
	 * @param website the website of this o e p user mgt working unit
	 */
	public void setWebsite(String website);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OEPUserMgtWorkingUnit oepUserMgtWorkingUnit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OEPUserMgtWorkingUnit> toCacheModel();

	@Override
	public OEPUserMgtWorkingUnit toEscapedModel();

	@Override
	public OEPUserMgtWorkingUnit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}