/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.quocte.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai;
import vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModel;
import vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai service. Represents a row in the &quot;qlvt_xuly_gpkdvt_quocte_loaihinhvantai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl}.
 * </p>
 *
 * @author NoiPham
 * @see QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl
 * @see vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai
 * @see vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModel
 * @generated
 */
@JSON(strict = true)
public class QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModelImpl extends BaseModelImpl<QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai>
	implements QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt xu ly gpkdvt quoc te loai hinh van tai model instance should use the {@link vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_xuly_gpkdvt_quocte_loaihinhvantai";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "THONGTINCAP_GPKD_VANTAIID", Types.INTEGER },
			{ "MALOAIHINHHOATDONG", Types.VARCHAR },
			{ "SOLUONGPHUONGTIEN", Types.INTEGER },
			{ "THIETBIGIAMSATHANHTRINH", Types.BIGINT },
			{ "PHAMVIHOATDONG", Types.VARCHAR },
			{ "SOCHUYEN", Types.INTEGER },
			{ "MAUSON", Types.VARCHAR },
			{ "KETQUAXULY", Types.VARCHAR },
			{ "LYDOKHONGDAT", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_xuly_gpkdvt_quocte_loaihinhvantai (ID LONG not null primary key,THONGTINCAP_GPKD_VANTAIID INTEGER,MALOAIHINHHOATDONG VARCHAR(75) null,SOLUONGPHUONGTIEN INTEGER,THIETBIGIAMSATHANHTRINH LONG,PHAMVIHOATDONG VARCHAR(75) null,SOCHUYEN INTEGER,MAUSON VARCHAR(75) null,KETQUAXULY VARCHAR(75) null,LYDOKHONGDAT VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_xuly_gpkdvt_quocte_loaihinhvantai";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_xuly_gpkdvt_quocte_loaihinhvantai.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai"),
			true);
	public static long THONGTINCAPGPKDVANTAIID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai toModel(
		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai model = new QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl();

		model.setId(soapModel.getId());
		model.setThongTinCapGpkdVanTaiId(soapModel.getThongTinCapGpkdVanTaiId());
		model.setMaLoaiHinhHoatDong(soapModel.getMaLoaiHinhHoatDong());
		model.setSoLuongPhuongTien(soapModel.getSoLuongPhuongTien());
		model.setThietBiGiamSatHanhTrinh(soapModel.getThietBiGiamSatHanhTrinh());
		model.setPhamViHoatDong(soapModel.getPhamViHoatDong());
		model.setSoChuyen(soapModel.getSoChuyen());
		model.setMauSon(soapModel.getMauSon());
		model.setKetQuaXuLy(soapModel.getKetQuaXuLy());
		model.setLyDoKhongDat(soapModel.getLyDoKhongDat());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai> toModels(
		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai> models = new ArrayList<QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai>(soapModels.length);

		for (QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai"));

	public QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thongTinCapGpkdVanTaiId", getThongTinCapGpkdVanTaiId());
		attributes.put("maLoaiHinhHoatDong", getMaLoaiHinhHoatDong());
		attributes.put("soLuongPhuongTien", getSoLuongPhuongTien());
		attributes.put("thietBiGiamSatHanhTrinh", getThietBiGiamSatHanhTrinh());
		attributes.put("phamViHoatDong", getPhamViHoatDong());
		attributes.put("soChuyen", getSoChuyen());
		attributes.put("mauSon", getMauSon());
		attributes.put("ketQuaXuLy", getKetQuaXuLy());
		attributes.put("lyDoKhongDat", getLyDoKhongDat());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer thongTinCapGpkdVanTaiId = (Integer)attributes.get(
				"thongTinCapGpkdVanTaiId");

		if (thongTinCapGpkdVanTaiId != null) {
			setThongTinCapGpkdVanTaiId(thongTinCapGpkdVanTaiId);
		}

		String maLoaiHinhHoatDong = (String)attributes.get("maLoaiHinhHoatDong");

		if (maLoaiHinhHoatDong != null) {
			setMaLoaiHinhHoatDong(maLoaiHinhHoatDong);
		}

		Integer soLuongPhuongTien = (Integer)attributes.get("soLuongPhuongTien");

		if (soLuongPhuongTien != null) {
			setSoLuongPhuongTien(soLuongPhuongTien);
		}

		Long thietBiGiamSatHanhTrinh = (Long)attributes.get(
				"thietBiGiamSatHanhTrinh");

		if (thietBiGiamSatHanhTrinh != null) {
			setThietBiGiamSatHanhTrinh(thietBiGiamSatHanhTrinh);
		}

		String phamViHoatDong = (String)attributes.get("phamViHoatDong");

		if (phamViHoatDong != null) {
			setPhamViHoatDong(phamViHoatDong);
		}

		Integer soChuyen = (Integer)attributes.get("soChuyen");

		if (soChuyen != null) {
			setSoChuyen(soChuyen);
		}

		String mauSon = (String)attributes.get("mauSon");

		if (mauSon != null) {
			setMauSon(mauSon);
		}

		String ketQuaXuLy = (String)attributes.get("ketQuaXuLy");

		if (ketQuaXuLy != null) {
			setKetQuaXuLy(ketQuaXuLy);
		}

		String lyDoKhongDat = (String)attributes.get("lyDoKhongDat");

		if (lyDoKhongDat != null) {
			setLyDoKhongDat(lyDoKhongDat);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public int getThongTinCapGpkdVanTaiId() {
		return _thongTinCapGpkdVanTaiId;
	}

	@Override
	public void setThongTinCapGpkdVanTaiId(int thongTinCapGpkdVanTaiId) {
		_columnBitmask |= THONGTINCAPGPKDVANTAIID_COLUMN_BITMASK;

		if (!_setOriginalThongTinCapGpkdVanTaiId) {
			_setOriginalThongTinCapGpkdVanTaiId = true;

			_originalThongTinCapGpkdVanTaiId = _thongTinCapGpkdVanTaiId;
		}

		_thongTinCapGpkdVanTaiId = thongTinCapGpkdVanTaiId;
	}

	public int getOriginalThongTinCapGpkdVanTaiId() {
		return _originalThongTinCapGpkdVanTaiId;
	}

	@JSON
	@Override
	public String getMaLoaiHinhHoatDong() {
		if (_maLoaiHinhHoatDong == null) {
			return StringPool.BLANK;
		}
		else {
			return _maLoaiHinhHoatDong;
		}
	}

	@Override
	public void setMaLoaiHinhHoatDong(String maLoaiHinhHoatDong) {
		_maLoaiHinhHoatDong = maLoaiHinhHoatDong;
	}

	@JSON
	@Override
	public int getSoLuongPhuongTien() {
		return _soLuongPhuongTien;
	}

	@Override
	public void setSoLuongPhuongTien(int soLuongPhuongTien) {
		_soLuongPhuongTien = soLuongPhuongTien;
	}

	@JSON
	@Override
	public long getThietBiGiamSatHanhTrinh() {
		return _thietBiGiamSatHanhTrinh;
	}

	@Override
	public void setThietBiGiamSatHanhTrinh(long thietBiGiamSatHanhTrinh) {
		_thietBiGiamSatHanhTrinh = thietBiGiamSatHanhTrinh;
	}

	@JSON
	@Override
	public String getPhamViHoatDong() {
		if (_phamViHoatDong == null) {
			return StringPool.BLANK;
		}
		else {
			return _phamViHoatDong;
		}
	}

	@Override
	public void setPhamViHoatDong(String phamViHoatDong) {
		_phamViHoatDong = phamViHoatDong;
	}

	@JSON
	@Override
	public int getSoChuyen() {
		return _soChuyen;
	}

	@Override
	public void setSoChuyen(int soChuyen) {
		_soChuyen = soChuyen;
	}

	@JSON
	@Override
	public String getMauSon() {
		if (_mauSon == null) {
			return StringPool.BLANK;
		}
		else {
			return _mauSon;
		}
	}

	@Override
	public void setMauSon(String mauSon) {
		_mauSon = mauSon;
	}

	@JSON
	@Override
	public String getKetQuaXuLy() {
		if (_ketQuaXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ketQuaXuLy;
		}
	}

	@Override
	public void setKetQuaXuLy(String ketQuaXuLy) {
		_ketQuaXuLy = ketQuaXuLy;
	}

	@JSON
	@Override
	public String getLyDoKhongDat() {
		if (_lyDoKhongDat == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongDat;
		}
	}

	@Override
	public void setLyDoKhongDat(String lyDoKhongDat) {
		_lyDoKhongDat = lyDoKhongDat;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl =
			new QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl();

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setId(getId());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setThongTinCapGpkdVanTaiId(getThongTinCapGpkdVanTaiId());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setMaLoaiHinhHoatDong(getMaLoaiHinhHoatDong());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setSoLuongPhuongTien(getSoLuongPhuongTien());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setThietBiGiamSatHanhTrinh(getThietBiGiamSatHanhTrinh());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setPhamViHoatDong(getPhamViHoatDong());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setSoChuyen(getSoChuyen());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setMauSon(getMauSon());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setKetQuaXuLy(getKetQuaXuLy());
		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.setLyDoKhongDat(getLyDoKhongDat());

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl.resetOriginalValues();

		return qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiImpl;
	}

	@Override
	public int compareTo(
		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai qlvtXuLyGpkdvtQuocTeLoaiHinhVanTai) {
		int value = 0;

		if (getId() < qlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.getId()) {
			value = -1;
		}
		else if (getId() > qlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai)) {
			return false;
		}

		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai qlvtXuLyGpkdvtQuocTeLoaiHinhVanTai = (QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai)obj;

		long primaryKey = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModelImpl qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModelImpl =
			this;

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModelImpl._originalThongTinCapGpkdVanTaiId = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModelImpl._thongTinCapGpkdVanTaiId;

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModelImpl._setOriginalThongTinCapGpkdVanTaiId = false;

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai> toCacheModel() {
		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel =
			new QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel();

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.id = getId();

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.thongTinCapGpkdVanTaiId = getThongTinCapGpkdVanTaiId();

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.maLoaiHinhHoatDong = getMaLoaiHinhHoatDong();

		String maLoaiHinhHoatDong = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.maLoaiHinhHoatDong;

		if ((maLoaiHinhHoatDong != null) && (maLoaiHinhHoatDong.length() == 0)) {
			qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.maLoaiHinhHoatDong = null;
		}

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.soLuongPhuongTien = getSoLuongPhuongTien();

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.thietBiGiamSatHanhTrinh = getThietBiGiamSatHanhTrinh();

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.phamViHoatDong = getPhamViHoatDong();

		String phamViHoatDong = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.phamViHoatDong;

		if ((phamViHoatDong != null) && (phamViHoatDong.length() == 0)) {
			qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.phamViHoatDong = null;
		}

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.soChuyen = getSoChuyen();

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.mauSon = getMauSon();

		String mauSon = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.mauSon;

		if ((mauSon != null) && (mauSon.length() == 0)) {
			qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.mauSon = null;
		}

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.ketQuaXuLy = getKetQuaXuLy();

		String ketQuaXuLy = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.ketQuaXuLy;

		if ((ketQuaXuLy != null) && (ketQuaXuLy.length() == 0)) {
			qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.ketQuaXuLy = null;
		}

		qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.lyDoKhongDat = getLyDoKhongDat();

		String lyDoKhongDat = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.lyDoKhongDat;

		if ((lyDoKhongDat != null) && (lyDoKhongDat.length() == 0)) {
			qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel.lyDoKhongDat = null;
		}

		return qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thongTinCapGpkdVanTaiId=");
		sb.append(getThongTinCapGpkdVanTaiId());
		sb.append(", maLoaiHinhHoatDong=");
		sb.append(getMaLoaiHinhHoatDong());
		sb.append(", soLuongPhuongTien=");
		sb.append(getSoLuongPhuongTien());
		sb.append(", thietBiGiamSatHanhTrinh=");
		sb.append(getThietBiGiamSatHanhTrinh());
		sb.append(", phamViHoatDong=");
		sb.append(getPhamViHoatDong());
		sb.append(", soChuyen=");
		sb.append(getSoChuyen());
		sb.append(", mauSon=");
		sb.append(getMauSon());
		sb.append(", ketQuaXuLy=");
		sb.append(getKetQuaXuLy());
		sb.append(", lyDoKhongDat=");
		sb.append(getLyDoKhongDat());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongTinCapGpkdVanTaiId</column-name><column-value><![CDATA[");
		sb.append(getThongTinCapGpkdVanTaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maLoaiHinhHoatDong</column-name><column-value><![CDATA[");
		sb.append(getMaLoaiHinhHoatDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soLuongPhuongTien</column-name><column-value><![CDATA[");
		sb.append(getSoLuongPhuongTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thietBiGiamSatHanhTrinh</column-name><column-value><![CDATA[");
		sb.append(getThietBiGiamSatHanhTrinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phamViHoatDong</column-name><column-value><![CDATA[");
		sb.append(getPhamViHoatDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soChuyen</column-name><column-value><![CDATA[");
		sb.append(getSoChuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mauSon</column-name><column-value><![CDATA[");
		sb.append(getMauSon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketQuaXuLy</column-name><column-value><![CDATA[");
		sb.append(getKetQuaXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongDat</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongDat());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.class
		};
	private long _id;
	private int _thongTinCapGpkdVanTaiId;
	private int _originalThongTinCapGpkdVanTaiId;
	private boolean _setOriginalThongTinCapGpkdVanTaiId;
	private String _maLoaiHinhHoatDong;
	private int _soLuongPhuongTien;
	private long _thietBiGiamSatHanhTrinh;
	private String _phamViHoatDong;
	private int _soChuyen;
	private String _mauSon;
	private String _ketQuaXuLy;
	private String _lyDoKhongDat;
	private long _columnBitmask;
	private QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai _escapedModel;
}