/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QlvtDiemDungDangKyVietCam service. Represents a row in the &quot;qlvt_diemdungdangky_vc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.common.model.impl.QlvtDiemDungDangKyVietCamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.common.model.impl.QlvtDiemDungDangKyVietCamImpl}.
 * </p>
 *
 * @author win_64
 * @see QlvtDiemDungDangKyVietCam
 * @see vn.dtt.duongbo.dao.common.model.impl.QlvtDiemDungDangKyVietCamImpl
 * @see vn.dtt.duongbo.dao.common.model.impl.QlvtDiemDungDangKyVietCamModelImpl
 * @generated
 */
public interface QlvtDiemDungDangKyVietCamModel extends BaseModel<QlvtDiemDungDangKyVietCam> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt diem dung dang ky viet cam model instance should use the {@link QlvtDiemDungDangKyVietCam} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt diem dung dang ky viet cam.
	 *
	 * @return the primary key of this qlvt diem dung dang ky viet cam
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt diem dung dang ky viet cam.
	 *
	 * @param primaryKey the primary key of this qlvt diem dung dang ky viet cam
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt diem dung dang ky viet cam.
	 *
	 * @return the ID of this qlvt diem dung dang ky viet cam
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt diem dung dang ky viet cam.
	 *
	 * @param id the ID of this qlvt diem dung dang ky viet cam
	 */
	public void setId(long id);

	/**
	 * Returns the phuong tien dang ky ID of this qlvt diem dung dang ky viet cam.
	 *
	 * @return the phuong tien dang ky ID of this qlvt diem dung dang ky viet cam
	 */
	@AutoEscape
	public String getPhuongTienDangKyId();

	/**
	 * Sets the phuong tien dang ky ID of this qlvt diem dung dang ky viet cam.
	 *
	 * @param PhuongTienDangKyId the phuong tien dang ky ID of this qlvt diem dung dang ky viet cam
	 */
	public void setPhuongTienDangKyId(String PhuongTienDangKyId);

	/**
	 * Returns the noi dung ho so ID of this qlvt diem dung dang ky viet cam.
	 *
	 * @return the noi dung ho so ID of this qlvt diem dung dang ky viet cam
	 */
	@AutoEscape
	public String getNoiDungHoSoId();

	/**
	 * Sets the noi dung ho so ID of this qlvt diem dung dang ky viet cam.
	 *
	 * @param NoiDungHoSoId the noi dung ho so ID of this qlvt diem dung dang ky viet cam
	 */
	public void setNoiDungHoSoId(String NoiDungHoSoId);

	/**
	 * Returns the ho so thu tuc ID of this qlvt diem dung dang ky viet cam.
	 *
	 * @return the ho so thu tuc ID of this qlvt diem dung dang ky viet cam
	 */
	@AutoEscape
	public String getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this qlvt diem dung dang ky viet cam.
	 *
	 * @param HoSoThuTucId the ho so thu tuc ID of this qlvt diem dung dang ky viet cam
	 */
	public void setHoSoThuTucId(String HoSoThuTucId);

	/**
	 * Returns the ma diem dung of this qlvt diem dung dang ky viet cam.
	 *
	 * @return the ma diem dung of this qlvt diem dung dang ky viet cam
	 */
	public long getMaDiemDung();

	/**
	 * Sets the ma diem dung of this qlvt diem dung dang ky viet cam.
	 *
	 * @param MaDiemDung the ma diem dung of this qlvt diem dung dang ky viet cam
	 */
	public void setMaDiemDung(long MaDiemDung);

	/**
	 * Returns the ten diem dung of this qlvt diem dung dang ky viet cam.
	 *
	 * @return the ten diem dung of this qlvt diem dung dang ky viet cam
	 */
	public long getTenDiemDung();

	/**
	 * Sets the ten diem dung of this qlvt diem dung dang ky viet cam.
	 *
	 * @param TenDiemDung the ten diem dung of this qlvt diem dung dang ky viet cam
	 */
	public void setTenDiemDung(long TenDiemDung);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtDiemDungDangKyVietCam qlvtDiemDungDangKyVietCam);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtDiemDungDangKyVietCam> toCacheModel();

	@Override
	public QlvtDiemDungDangKyVietCam toEscapedModel();

	@Override
	public QlvtDiemDungDangKyVietCam toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}