/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.common.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TthcThanhPhanHoSoBieuMau service. Represents a row in the &quot;tthc_thanhphanhoso_bieumau&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.common.model.impl.TthcThanhPhanHoSoBieuMauModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.common.model.impl.TthcThanhPhanHoSoBieuMauImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcThanhPhanHoSoBieuMau
 * @see vn.dtt.duongbo.dao.common.model.impl.TthcThanhPhanHoSoBieuMauImpl
 * @see vn.dtt.duongbo.dao.common.model.impl.TthcThanhPhanHoSoBieuMauModelImpl
 * @generated
 */
public interface TthcThanhPhanHoSoBieuMauModel extends BaseModel<TthcThanhPhanHoSoBieuMau> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc thanh phan ho so bieu mau model instance should use the {@link TthcThanhPhanHoSoBieuMau} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc thanh phan ho so bieu mau.
	 *
	 * @return the primary key of this tthc thanh phan ho so bieu mau
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc thanh phan ho so bieu mau.
	 *
	 * @param primaryKey the primary key of this tthc thanh phan ho so bieu mau
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc thanh phan ho so bieu mau.
	 *
	 * @return the ID of this tthc thanh phan ho so bieu mau
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc thanh phan ho so bieu mau.
	 *
	 * @param id the ID of this tthc thanh phan ho so bieu mau
	 */
	public void setId(long id);

	/**
	 * Returns the thanh phan ho so ID of this tthc thanh phan ho so bieu mau.
	 *
	 * @return the thanh phan ho so ID of this tthc thanh phan ho so bieu mau
	 */
	public long getThanhPhanHoSoId();

	/**
	 * Sets the thanh phan ho so ID of this tthc thanh phan ho so bieu mau.
	 *
	 * @param thanhPhanHoSoId the thanh phan ho so ID of this tthc thanh phan ho so bieu mau
	 */
	public void setThanhPhanHoSoId(long thanhPhanHoSoId);

	/**
	 * Returns the bieu mau ho so ID of this tthc thanh phan ho so bieu mau.
	 *
	 * @return the bieu mau ho so ID of this tthc thanh phan ho so bieu mau
	 */
	public long getBieuMauHoSoId();

	/**
	 * Sets the bieu mau ho so ID of this tthc thanh phan ho so bieu mau.
	 *
	 * @param bieuMauHoSoId the bieu mau ho so ID of this tthc thanh phan ho so bieu mau
	 */
	public void setBieuMauHoSoId(long bieuMauHoSoId);

	/**
	 * Returns the so thu tu of this tthc thanh phan ho so bieu mau.
	 *
	 * @return the so thu tu of this tthc thanh phan ho so bieu mau
	 */
	public int getSoThuTu();

	/**
	 * Sets the so thu tu of this tthc thanh phan ho so bieu mau.
	 *
	 * @param soThuTu the so thu tu of this tthc thanh phan ho so bieu mau
	 */
	public void setSoThuTu(int soThuTu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TthcThanhPhanHoSoBieuMau tthcThanhPhanHoSoBieuMau);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TthcThanhPhanHoSoBieuMau> toCacheModel();

	@Override
	public TthcThanhPhanHoSoBieuMau toEscapedModel();

	@Override
	public TthcThanhPhanHoSoBieuMau toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}