/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TthcThongBaoXuLy service. Represents a row in the &quot;tthc_thongbaoxuly&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.common.model.impl.TthcThongBaoXuLyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.common.model.impl.TthcThongBaoXuLyImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcThongBaoXuLy
 * @see vn.dtt.duongbo.dao.common.model.impl.TthcThongBaoXuLyImpl
 * @see vn.dtt.duongbo.dao.common.model.impl.TthcThongBaoXuLyModelImpl
 * @generated
 */
public interface TthcThongBaoXuLyModel extends BaseModel<TthcThongBaoXuLy> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc thong bao xu ly model instance should use the {@link TthcThongBaoXuLy} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc thong bao xu ly.
	 *
	 * @return the primary key of this tthc thong bao xu ly
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc thong bao xu ly.
	 *
	 * @param primaryKey the primary key of this tthc thong bao xu ly
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc thong bao xu ly.
	 *
	 * @return the ID of this tthc thong bao xu ly
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc thong bao xu ly.
	 *
	 * @param id the ID of this tthc thong bao xu ly
	 */
	public void setId(long id);

	/**
	 * Returns the ho so thu tuc ID of this tthc thong bao xu ly.
	 *
	 * @return the ho so thu tuc ID of this tthc thong bao xu ly
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this tthc thong bao xu ly.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this tthc thong bao xu ly
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the ma thong bao of this tthc thong bao xu ly.
	 *
	 * @return the ma thong bao of this tthc thong bao xu ly
	 */
	@AutoEscape
	public String getMaThongBao();

	/**
	 * Sets the ma thong bao of this tthc thong bao xu ly.
	 *
	 * @param maThongBao the ma thong bao of this tthc thong bao xu ly
	 */
	public void setMaThongBao(String maThongBao);

	/**
	 * Returns the noi dung thong bao of this tthc thong bao xu ly.
	 *
	 * @return the noi dung thong bao of this tthc thong bao xu ly
	 */
	@AutoEscape
	public String getNoiDungThongBao();

	/**
	 * Sets the noi dung thong bao of this tthc thong bao xu ly.
	 *
	 * @param noiDungThongBao the noi dung thong bao of this tthc thong bao xu ly
	 */
	public void setNoiDungThongBao(String noiDungThongBao);

	/**
	 * Returns the du lieu thong bao of this tthc thong bao xu ly.
	 *
	 * @return the du lieu thong bao of this tthc thong bao xu ly
	 */
	@AutoEscape
	public String getDuLieuThongBao();

	/**
	 * Sets the du lieu thong bao of this tthc thong bao xu ly.
	 *
	 * @param duLieuThongBao the du lieu thong bao of this tthc thong bao xu ly
	 */
	public void setDuLieuThongBao(String duLieuThongBao);

	/**
	 * Returns the ngay gio of this tthc thong bao xu ly.
	 *
	 * @return the ngay gio of this tthc thong bao xu ly
	 */
	public Date getNgayGio();

	/**
	 * Sets the ngay gio of this tthc thong bao xu ly.
	 *
	 * @param ngayGio the ngay gio of this tthc thong bao xu ly
	 */
	public void setNgayGio(Date ngayGio);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TthcThongBaoXuLy tthcThongBaoXuLy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TthcThongBaoXuLy> toCacheModel();

	@Override
	public TthcThongBaoXuLy toEscapedModel();

	@Override
	public TthcThongBaoXuLy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}