/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TthcThanhPhanHoSo service. Represents a row in the &quot;tthc_thanhphanhoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.common.model.impl.TthcThanhPhanHoSoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.common.model.impl.TthcThanhPhanHoSoImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcThanhPhanHoSo
 * @see vn.dtt.duongbo.dao.common.model.impl.TthcThanhPhanHoSoImpl
 * @see vn.dtt.duongbo.dao.common.model.impl.TthcThanhPhanHoSoModelImpl
 * @generated
 */
public interface TthcThanhPhanHoSoModel extends BaseModel<TthcThanhPhanHoSo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc thanh phan ho so model instance should use the {@link TthcThanhPhanHoSo} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc thanh phan ho so.
	 *
	 * @return the primary key of this tthc thanh phan ho so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc thanh phan ho so.
	 *
	 * @param primaryKey the primary key of this tthc thanh phan ho so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc thanh phan ho so.
	 *
	 * @return the ID of this tthc thanh phan ho so
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc thanh phan ho so.
	 *
	 * @param id the ID of this tthc thanh phan ho so
	 */
	public void setId(long id);

	/**
	 * Returns the thu tuc hanh chinh ID of this tthc thanh phan ho so.
	 *
	 * @return the thu tuc hanh chinh ID of this tthc thanh phan ho so
	 */
	public long getThuTucHanhChinhId();

	/**
	 * Sets the thu tuc hanh chinh ID of this tthc thanh phan ho so.
	 *
	 * @param thuTucHanhChinhId the thu tuc hanh chinh ID of this tthc thanh phan ho so
	 */
	public void setThuTucHanhChinhId(long thuTucHanhChinhId);

	/**
	 * Returns the ten thanh phan of this tthc thanh phan ho so.
	 *
	 * @return the ten thanh phan of this tthc thanh phan ho so
	 */
	@AutoEscape
	public String getTenThanhPhan();

	/**
	 * Sets the ten thanh phan of this tthc thanh phan ho so.
	 *
	 * @param tenThanhPhan the ten thanh phan of this tthc thanh phan ho so
	 */
	public void setTenThanhPhan(String tenThanhPhan);

	/**
	 * Returns the ghi chu of this tthc thanh phan ho so.
	 *
	 * @return the ghi chu of this tthc thanh phan ho so
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this tthc thanh phan ho so.
	 *
	 * @param ghiChu the ghi chu of this tthc thanh phan ho so
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the ma thanh phan of this tthc thanh phan ho so.
	 *
	 * @return the ma thanh phan of this tthc thanh phan ho so
	 */
	@AutoEscape
	public String getMaThanhPhan();

	/**
	 * Sets the ma thanh phan of this tthc thanh phan ho so.
	 *
	 * @param maThanhPhan the ma thanh phan of this tthc thanh phan ho so
	 */
	public void setMaThanhPhan(String maThanhPhan);

	/**
	 * Returns the thu tu hien thi of this tthc thanh phan ho so.
	 *
	 * @return the thu tu hien thi of this tthc thanh phan ho so
	 */
	public long getThuTuHienThi();

	/**
	 * Sets the thu tu hien thi of this tthc thanh phan ho so.
	 *
	 * @param thuTuHienThi the thu tu hien thi of this tthc thanh phan ho so
	 */
	public void setThuTuHienThi(long thuTuHienThi);

	/**
	 * Returns the loai thanh phan of this tthc thanh phan ho so.
	 *
	 * @return the loai thanh phan of this tthc thanh phan ho so
	 */
	public long getLoaiThanhPhan();

	/**
	 * Sets the loai thanh phan of this tthc thanh phan ho so.
	 *
	 * @param loaiThanhPhan the loai thanh phan of this tthc thanh phan ho so
	 */
	public void setLoaiThanhPhan(long loaiThanhPhan);

	/**
	 * Returns the so tai lieu dinh kem of this tthc thanh phan ho so.
	 *
	 * @return the so tai lieu dinh kem of this tthc thanh phan ho so
	 */
	public long getSoTaiLieuDinhKem();

	/**
	 * Sets the so tai lieu dinh kem of this tthc thanh phan ho so.
	 *
	 * @param soTaiLieuDinhKem the so tai lieu dinh kem of this tthc thanh phan ho so
	 */
	public void setSoTaiLieuDinhKem(long soTaiLieuDinhKem);

	/**
	 * Returns the mau truc tuyen of this tthc thanh phan ho so.
	 *
	 * @return the mau truc tuyen of this tthc thanh phan ho so
	 */
	@AutoEscape
	public String getMauTrucTuyen();

	/**
	 * Sets the mau truc tuyen of this tthc thanh phan ho so.
	 *
	 * @param mauTrucTuyen the mau truc tuyen of this tthc thanh phan ho so
	 */
	public void setMauTrucTuyen(String mauTrucTuyen);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TthcThanhPhanHoSo tthcThanhPhanHoSo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TthcThanhPhanHoSo> toCacheModel();

	@Override
	public TthcThanhPhanHoSo toEscapedModel();

	@Override
	public TthcThanhPhanHoSo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}