/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.doanhnghiep.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiep;
import vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiepModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DnDoanhNghiep service. Represents a row in the &quot;dn_nguoilamthutuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiepModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DnDoanhNghiepImpl}.
 * </p>
 *
 * @author win_64
 * @see DnDoanhNghiepImpl
 * @see vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiep
 * @see vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiepModel
 * @generated
 */
public class DnDoanhNghiepModelImpl extends BaseModelImpl<DnDoanhNghiep>
	implements DnDoanhNghiepModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dn doanh nghiep model instance should use the {@link vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiep} interface instead.
	 */
	public static final String TABLE_NAME = "dn_nguoilamthutuc";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "masodoanhnghiep", Types.VARCHAR },
			{ "tendoanhnghiep", Types.VARCHAR },
			{ "diachi", Types.VARCHAR },
			{ "matinhthanh", Types.VARCHAR },
			{ "maquanhuyen", Types.VARCHAR },
			{ "maphuongxa", Types.VARCHAR },
			{ "dienthoai", Types.VARCHAR },
			{ "WEBSITE", Types.VARCHAR },
			{ "fax", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "master", Types.BIGINT },
			{ "ngaydangki", Types.TIMESTAMP },
			{ "hangtaikhoan", Types.VARCHAR },
			{ "makichhoat", Types.VARCHAR },
			{ "ngaykichhoat", Types.TIMESTAMP },
			{ "SODANGKYKINHDOANH", Types.VARCHAR },
			{ "NGAYCAPDKKD", Types.TIMESTAMP },
			{ "NGAYHETHANDKKD", Types.TIMESTAMP },
			{ "COQUANCAPDKKD", Types.VARCHAR },
			{ "LOAIDOANHNGHIEP", Types.VARCHAR },
			{ "NGUOIDAIDIEN", Types.VARCHAR },
			{ "SODIENTHOAINGUOIDAIDIEN", Types.VARCHAR },
			{ "CHUCVUNGUOIDAIDIEN", Types.VARCHAR },
			{ "TENTIENGANH", Types.VARCHAR },
			{ "TENVIETTAT", Types.VARCHAR },
			{ "SOGPKDVANTAIBANGOTO", Types.VARCHAR },
			{ "NGAYCAPGPKDVANTAIBANGOTO", Types.TIMESTAMP },
			{ "COQUANCAPGPKDVANTAIBANGOTO", Types.VARCHAR },
			{ "MASOCONGDAN", Types.VARCHAR },
			{ "TENCONGDAN", Types.VARCHAR },
			{ "QUOCTICH", Types.VARCHAR },
			{ "GIOITINH", Types.VARCHAR },
			{ "NGAYCAPCMND", Types.TIMESTAMP },
			{ "NOICAPCMND", Types.VARCHAR },
			{ "LOAINGUOILAMTHUTUC", Types.VARCHAR },
			{ "NAMSINH", Types.VARCHAR },
			{ "NGAYSINH", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table dn_nguoilamthutuc (id LONG not null primary key,masodoanhnghiep VARCHAR(75) null,tendoanhnghiep VARCHAR(75) null,diachi VARCHAR(75) null,matinhthanh VARCHAR(75) null,maquanhuyen VARCHAR(75) null,maphuongxa VARCHAR(75) null,dienthoai VARCHAR(75) null,WEBSITE VARCHAR(75) null,fax VARCHAR(75) null,email VARCHAR(75) null,master LONG,ngaydangki DATE null,hangtaikhoan VARCHAR(75) null,makichhoat VARCHAR(75) null,ngaykichhoat DATE null,SODANGKYKINHDOANH VARCHAR(75) null,NGAYCAPDKKD DATE null,NGAYHETHANDKKD DATE null,COQUANCAPDKKD VARCHAR(75) null,LOAIDOANHNGHIEP VARCHAR(75) null,NGUOIDAIDIEN VARCHAR(75) null,SODIENTHOAINGUOIDAIDIEN VARCHAR(75) null,CHUCVUNGUOIDAIDIEN VARCHAR(75) null,TENTIENGANH VARCHAR(75) null,TENVIETTAT VARCHAR(75) null,SOGPKDVANTAIBANGOTO VARCHAR(75) null,NGAYCAPGPKDVANTAIBANGOTO DATE null,COQUANCAPGPKDVANTAIBANGOTO VARCHAR(75) null,MASOCONGDAN VARCHAR(75) null,TENCONGDAN VARCHAR(75) null,QUOCTICH VARCHAR(75) null,GIOITINH VARCHAR(75) null,NGAYCAPCMND DATE null,NOICAPCMND VARCHAR(75) null,LOAINGUOILAMTHUTUC VARCHAR(75) null,NAMSINH VARCHAR(75) null,NGAYSINH DATE null)";
	public static final String TABLE_SQL_DROP = "drop table dn_nguoilamthutuc";
	public static final String ORDER_BY_JPQL = " ORDER BY dnDoanhNghiep.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY dn_nguoilamthutuc.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiep"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiep"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiep"),
			true);
	public static long EMAIL_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static long LOAINGUOILAMTHUTUC_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiep"));

	public DnDoanhNghiepModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DnDoanhNghiep.class;
	}

	@Override
	public String getModelClassName() {
		return DnDoanhNghiep.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maSoDoanhNghiep", getMaSoDoanhNghiep());
		attributes.put("tenDoanhNghiep", getTenDoanhNghiep());
		attributes.put("diaChi", getDiaChi());
		attributes.put("maTinhThanh", getMaTinhThanh());
		attributes.put("maQuanHuyen", getMaQuanHuyen());
		attributes.put("maPhuongXa", getMaPhuongXa());
		attributes.put("dienThoai", getDienThoai());
		attributes.put("website", getWebsite());
		attributes.put("fax", getFax());
		attributes.put("email", getEmail());
		attributes.put("master", getMaster());
		attributes.put("ngayDangKi", getNgayDangKi());
		attributes.put("hangTaiKhoan", getHangTaiKhoan());
		attributes.put("maKichHoat", getMaKichHoat());
		attributes.put("ngayKichHoat", getNgayKichHoat());
		attributes.put("soDangKyKinhDoanh", getSoDangKyKinhDoanh());
		attributes.put("ngayCapDkKd", getNgayCapDkKd());
		attributes.put("ngayHetHanDKKD", getNgayHetHanDKKD());
		attributes.put("coQuanCapDkKd", getCoQuanCapDkKd());
		attributes.put("loaiDoanhNghiep", getLoaiDoanhNghiep());
		attributes.put("nguoiDaiDien", getNguoiDaiDien());
		attributes.put("soDienThoaiNguoiDaiDien", getSoDienThoaiNguoiDaiDien());
		attributes.put("chucVuNguoiDaiDien", getChucVuNguoiDaiDien());
		attributes.put("tenTiengAnh", getTenTiengAnh());
		attributes.put("tenVietTat", getTenVietTat());
		attributes.put("soGpkdVanTaiBangOto", getSoGpkdVanTaiBangOto());
		attributes.put("ngayCapGpkdVanTaiBangOto", getNgayCapGpkdVanTaiBangOto());
		attributes.put("coQuanCapGpkdVanTaiBangOto",
			getCoQuanCapGpkdVanTaiBangOto());
		attributes.put("maSoCongDan", getMaSoCongDan());
		attributes.put("tenCongDan", getTenCongDan());
		attributes.put("quocTich", getQuocTich());
		attributes.put("gioiTinh", getGioiTinh());
		attributes.put("ngayCapCMND", getNgayCapCMND());
		attributes.put("noiCapCMND", getNoiCapCMND());
		attributes.put("loaiNguoiLamThuTuc", getLoaiNguoiLamThuTuc());
		attributes.put("namSinh", getNamSinh());
		attributes.put("ngaySinh", getNgaySinh());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maSoDoanhNghiep = (String)attributes.get("maSoDoanhNghiep");

		if (maSoDoanhNghiep != null) {
			setMaSoDoanhNghiep(maSoDoanhNghiep);
		}

		String tenDoanhNghiep = (String)attributes.get("tenDoanhNghiep");

		if (tenDoanhNghiep != null) {
			setTenDoanhNghiep(tenDoanhNghiep);
		}

		String diaChi = (String)attributes.get("diaChi");

		if (diaChi != null) {
			setDiaChi(diaChi);
		}

		String maTinhThanh = (String)attributes.get("maTinhThanh");

		if (maTinhThanh != null) {
			setMaTinhThanh(maTinhThanh);
		}

		String maQuanHuyen = (String)attributes.get("maQuanHuyen");

		if (maQuanHuyen != null) {
			setMaQuanHuyen(maQuanHuyen);
		}

		String maPhuongXa = (String)attributes.get("maPhuongXa");

		if (maPhuongXa != null) {
			setMaPhuongXa(maPhuongXa);
		}

		String dienThoai = (String)attributes.get("dienThoai");

		if (dienThoai != null) {
			setDienThoai(dienThoai);
		}

		String website = (String)attributes.get("website");

		if (website != null) {
			setWebsite(website);
		}

		String fax = (String)attributes.get("fax");

		if (fax != null) {
			setFax(fax);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		Long master = (Long)attributes.get("master");

		if (master != null) {
			setMaster(master);
		}

		Date ngayDangKi = (Date)attributes.get("ngayDangKi");

		if (ngayDangKi != null) {
			setNgayDangKi(ngayDangKi);
		}

		String hangTaiKhoan = (String)attributes.get("hangTaiKhoan");

		if (hangTaiKhoan != null) {
			setHangTaiKhoan(hangTaiKhoan);
		}

		String maKichHoat = (String)attributes.get("maKichHoat");

		if (maKichHoat != null) {
			setMaKichHoat(maKichHoat);
		}

		Date ngayKichHoat = (Date)attributes.get("ngayKichHoat");

		if (ngayKichHoat != null) {
			setNgayKichHoat(ngayKichHoat);
		}

		String soDangKyKinhDoanh = (String)attributes.get("soDangKyKinhDoanh");

		if (soDangKyKinhDoanh != null) {
			setSoDangKyKinhDoanh(soDangKyKinhDoanh);
		}

		Date ngayCapDkKd = (Date)attributes.get("ngayCapDkKd");

		if (ngayCapDkKd != null) {
			setNgayCapDkKd(ngayCapDkKd);
		}

		Date ngayHetHanDKKD = (Date)attributes.get("ngayHetHanDKKD");

		if (ngayHetHanDKKD != null) {
			setNgayHetHanDKKD(ngayHetHanDKKD);
		}

		String coQuanCapDkKd = (String)attributes.get("coQuanCapDkKd");

		if (coQuanCapDkKd != null) {
			setCoQuanCapDkKd(coQuanCapDkKd);
		}

		String loaiDoanhNghiep = (String)attributes.get("loaiDoanhNghiep");

		if (loaiDoanhNghiep != null) {
			setLoaiDoanhNghiep(loaiDoanhNghiep);
		}

		String nguoiDaiDien = (String)attributes.get("nguoiDaiDien");

		if (nguoiDaiDien != null) {
			setNguoiDaiDien(nguoiDaiDien);
		}

		String soDienThoaiNguoiDaiDien = (String)attributes.get(
				"soDienThoaiNguoiDaiDien");

		if (soDienThoaiNguoiDaiDien != null) {
			setSoDienThoaiNguoiDaiDien(soDienThoaiNguoiDaiDien);
		}

		String chucVuNguoiDaiDien = (String)attributes.get("chucVuNguoiDaiDien");

		if (chucVuNguoiDaiDien != null) {
			setChucVuNguoiDaiDien(chucVuNguoiDaiDien);
		}

		String tenTiengAnh = (String)attributes.get("tenTiengAnh");

		if (tenTiengAnh != null) {
			setTenTiengAnh(tenTiengAnh);
		}

		String tenVietTat = (String)attributes.get("tenVietTat");

		if (tenVietTat != null) {
			setTenVietTat(tenVietTat);
		}

		String soGpkdVanTaiBangOto = (String)attributes.get(
				"soGpkdVanTaiBangOto");

		if (soGpkdVanTaiBangOto != null) {
			setSoGpkdVanTaiBangOto(soGpkdVanTaiBangOto);
		}

		Date ngayCapGpkdVanTaiBangOto = (Date)attributes.get(
				"ngayCapGpkdVanTaiBangOto");

		if (ngayCapGpkdVanTaiBangOto != null) {
			setNgayCapGpkdVanTaiBangOto(ngayCapGpkdVanTaiBangOto);
		}

		String coQuanCapGpkdVanTaiBangOto = (String)attributes.get(
				"coQuanCapGpkdVanTaiBangOto");

		if (coQuanCapGpkdVanTaiBangOto != null) {
			setCoQuanCapGpkdVanTaiBangOto(coQuanCapGpkdVanTaiBangOto);
		}

		String maSoCongDan = (String)attributes.get("maSoCongDan");

		if (maSoCongDan != null) {
			setMaSoCongDan(maSoCongDan);
		}

		String tenCongDan = (String)attributes.get("tenCongDan");

		if (tenCongDan != null) {
			setTenCongDan(tenCongDan);
		}

		String quocTich = (String)attributes.get("quocTich");

		if (quocTich != null) {
			setQuocTich(quocTich);
		}

		String gioiTinh = (String)attributes.get("gioiTinh");

		if (gioiTinh != null) {
			setGioiTinh(gioiTinh);
		}

		Date ngayCapCMND = (Date)attributes.get("ngayCapCMND");

		if (ngayCapCMND != null) {
			setNgayCapCMND(ngayCapCMND);
		}

		String noiCapCMND = (String)attributes.get("noiCapCMND");

		if (noiCapCMND != null) {
			setNoiCapCMND(noiCapCMND);
		}

		String loaiNguoiLamThuTuc = (String)attributes.get("loaiNguoiLamThuTuc");

		if (loaiNguoiLamThuTuc != null) {
			setLoaiNguoiLamThuTuc(loaiNguoiLamThuTuc);
		}

		String namSinh = (String)attributes.get("namSinh");

		if (namSinh != null) {
			setNamSinh(namSinh);
		}

		Date ngaySinh = (Date)attributes.get("ngaySinh");

		if (ngaySinh != null) {
			setNgaySinh(ngaySinh);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	@Override
	public String getMaSoDoanhNghiep() {
		if (_maSoDoanhNghiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSoDoanhNghiep;
		}
	}

	@Override
	public void setMaSoDoanhNghiep(String maSoDoanhNghiep) {
		_maSoDoanhNghiep = maSoDoanhNghiep;
	}

	@Override
	public String getTenDoanhNghiep() {
		if (_tenDoanhNghiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDoanhNghiep;
		}
	}

	@Override
	public void setTenDoanhNghiep(String tenDoanhNghiep) {
		_tenDoanhNghiep = tenDoanhNghiep;
	}

	@Override
	public String getDiaChi() {
		if (_diaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChi;
		}
	}

	@Override
	public void setDiaChi(String diaChi) {
		_diaChi = diaChi;
	}

	@Override
	public String getMaTinhThanh() {
		if (_maTinhThanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinhThanh;
		}
	}

	@Override
	public void setMaTinhThanh(String maTinhThanh) {
		_maTinhThanh = maTinhThanh;
	}

	@Override
	public String getMaQuanHuyen() {
		if (_maQuanHuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maQuanHuyen;
		}
	}

	@Override
	public void setMaQuanHuyen(String maQuanHuyen) {
		_maQuanHuyen = maQuanHuyen;
	}

	@Override
	public String getMaPhuongXa() {
		if (_maPhuongXa == null) {
			return StringPool.BLANK;
		}
		else {
			return _maPhuongXa;
		}
	}

	@Override
	public void setMaPhuongXa(String maPhuongXa) {
		_maPhuongXa = maPhuongXa;
	}

	@Override
	public String getDienThoai() {
		if (_dienThoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoai;
		}
	}

	@Override
	public void setDienThoai(String dienThoai) {
		_dienThoai = dienThoai;
	}

	@Override
	public String getWebsite() {
		if (_website == null) {
			return StringPool.BLANK;
		}
		else {
			return _website;
		}
	}

	@Override
	public void setWebsite(String website) {
		_website = website;
	}

	@Override
	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	@Override
	public void setFax(String fax) {
		_fax = fax;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_columnBitmask |= EMAIL_COLUMN_BITMASK;

		if (_originalEmail == null) {
			_originalEmail = _email;
		}

		_email = email;
	}

	public String getOriginalEmail() {
		return GetterUtil.getString(_originalEmail);
	}

	@Override
	public long getMaster() {
		return _master;
	}

	@Override
	public void setMaster(long master) {
		_master = master;
	}

	@Override
	public Date getNgayDangKi() {
		return _ngayDangKi;
	}

	@Override
	public void setNgayDangKi(Date ngayDangKi) {
		_ngayDangKi = ngayDangKi;
	}

	@Override
	public String getHangTaiKhoan() {
		if (_hangTaiKhoan == null) {
			return StringPool.BLANK;
		}
		else {
			return _hangTaiKhoan;
		}
	}

	@Override
	public void setHangTaiKhoan(String hangTaiKhoan) {
		_hangTaiKhoan = hangTaiKhoan;
	}

	@Override
	public String getMaKichHoat() {
		if (_maKichHoat == null) {
			return StringPool.BLANK;
		}
		else {
			return _maKichHoat;
		}
	}

	@Override
	public void setMaKichHoat(String maKichHoat) {
		_maKichHoat = maKichHoat;
	}

	@Override
	public Date getNgayKichHoat() {
		return _ngayKichHoat;
	}

	@Override
	public void setNgayKichHoat(Date ngayKichHoat) {
		_ngayKichHoat = ngayKichHoat;
	}

	@Override
	public String getSoDangKyKinhDoanh() {
		if (_soDangKyKinhDoanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDangKyKinhDoanh;
		}
	}

	@Override
	public void setSoDangKyKinhDoanh(String soDangKyKinhDoanh) {
		_soDangKyKinhDoanh = soDangKyKinhDoanh;
	}

	@Override
	public Date getNgayCapDkKd() {
		return _ngayCapDkKd;
	}

	@Override
	public void setNgayCapDkKd(Date ngayCapDkKd) {
		_ngayCapDkKd = ngayCapDkKd;
	}

	@Override
	public Date getNgayHetHanDKKD() {
		return _ngayHetHanDKKD;
	}

	@Override
	public void setNgayHetHanDKKD(Date ngayHetHanDKKD) {
		_ngayHetHanDKKD = ngayHetHanDKKD;
	}

	@Override
	public String getCoQuanCapDkKd() {
		if (_coQuanCapDkKd == null) {
			return StringPool.BLANK;
		}
		else {
			return _coQuanCapDkKd;
		}
	}

	@Override
	public void setCoQuanCapDkKd(String coQuanCapDkKd) {
		_coQuanCapDkKd = coQuanCapDkKd;
	}

	@Override
	public String getLoaiDoanhNghiep() {
		if (_loaiDoanhNghiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiDoanhNghiep;
		}
	}

	@Override
	public void setLoaiDoanhNghiep(String loaiDoanhNghiep) {
		_loaiDoanhNghiep = loaiDoanhNghiep;
	}

	@Override
	public String getNguoiDaiDien() {
		if (_nguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiDaiDien;
		}
	}

	@Override
	public void setNguoiDaiDien(String nguoiDaiDien) {
		_nguoiDaiDien = nguoiDaiDien;
	}

	@Override
	public String getSoDienThoaiNguoiDaiDien() {
		if (_soDienThoaiNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDienThoaiNguoiDaiDien;
		}
	}

	@Override
	public void setSoDienThoaiNguoiDaiDien(String soDienThoaiNguoiDaiDien) {
		_soDienThoaiNguoiDaiDien = soDienThoaiNguoiDaiDien;
	}

	@Override
	public String getChucVuNguoiDaiDien() {
		if (_chucVuNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _chucVuNguoiDaiDien;
		}
	}

	@Override
	public void setChucVuNguoiDaiDien(String chucVuNguoiDaiDien) {
		_chucVuNguoiDaiDien = chucVuNguoiDaiDien;
	}

	@Override
	public String getTenTiengAnh() {
		if (_tenTiengAnh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenTiengAnh;
		}
	}

	@Override
	public void setTenTiengAnh(String tenTiengAnh) {
		_tenTiengAnh = tenTiengAnh;
	}

	@Override
	public String getTenVietTat() {
		if (_tenVietTat == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenVietTat;
		}
	}

	@Override
	public void setTenVietTat(String tenVietTat) {
		_tenVietTat = tenVietTat;
	}

	@Override
	public String getSoGpkdVanTaiBangOto() {
		if (_soGpkdVanTaiBangOto == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGpkdVanTaiBangOto;
		}
	}

	@Override
	public void setSoGpkdVanTaiBangOto(String soGpkdVanTaiBangOto) {
		_soGpkdVanTaiBangOto = soGpkdVanTaiBangOto;
	}

	@Override
	public Date getNgayCapGpkdVanTaiBangOto() {
		return _ngayCapGpkdVanTaiBangOto;
	}

	@Override
	public void setNgayCapGpkdVanTaiBangOto(Date ngayCapGpkdVanTaiBangOto) {
		_ngayCapGpkdVanTaiBangOto = ngayCapGpkdVanTaiBangOto;
	}

	@Override
	public String getCoQuanCapGpkdVanTaiBangOto() {
		if (_coQuanCapGpkdVanTaiBangOto == null) {
			return StringPool.BLANK;
		}
		else {
			return _coQuanCapGpkdVanTaiBangOto;
		}
	}

	@Override
	public void setCoQuanCapGpkdVanTaiBangOto(String coQuanCapGpkdVanTaiBangOto) {
		_coQuanCapGpkdVanTaiBangOto = coQuanCapGpkdVanTaiBangOto;
	}

	@Override
	public String getMaSoCongDan() {
		if (_maSoCongDan == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSoCongDan;
		}
	}

	@Override
	public void setMaSoCongDan(String maSoCongDan) {
		_maSoCongDan = maSoCongDan;
	}

	@Override
	public String getTenCongDan() {
		if (_tenCongDan == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenCongDan;
		}
	}

	@Override
	public void setTenCongDan(String tenCongDan) {
		_tenCongDan = tenCongDan;
	}

	@Override
	public String getQuocTich() {
		if (_quocTich == null) {
			return StringPool.BLANK;
		}
		else {
			return _quocTich;
		}
	}

	@Override
	public void setQuocTich(String quocTich) {
		_quocTich = quocTich;
	}

	@Override
	public String getGioiTinh() {
		if (_gioiTinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _gioiTinh;
		}
	}

	@Override
	public void setGioiTinh(String gioiTinh) {
		_gioiTinh = gioiTinh;
	}

	@Override
	public Date getNgayCapCMND() {
		return _ngayCapCMND;
	}

	@Override
	public void setNgayCapCMND(Date ngayCapCMND) {
		_ngayCapCMND = ngayCapCMND;
	}

	@Override
	public String getNoiCapCMND() {
		if (_noiCapCMND == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiCapCMND;
		}
	}

	@Override
	public void setNoiCapCMND(String noiCapCMND) {
		_noiCapCMND = noiCapCMND;
	}

	@Override
	public String getLoaiNguoiLamThuTuc() {
		if (_loaiNguoiLamThuTuc == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiNguoiLamThuTuc;
		}
	}

	@Override
	public void setLoaiNguoiLamThuTuc(String loaiNguoiLamThuTuc) {
		_columnBitmask |= LOAINGUOILAMTHUTUC_COLUMN_BITMASK;

		if (_originalLoaiNguoiLamThuTuc == null) {
			_originalLoaiNguoiLamThuTuc = _loaiNguoiLamThuTuc;
		}

		_loaiNguoiLamThuTuc = loaiNguoiLamThuTuc;
	}

	public String getOriginalLoaiNguoiLamThuTuc() {
		return GetterUtil.getString(_originalLoaiNguoiLamThuTuc);
	}

	@Override
	public String getNamSinh() {
		if (_namSinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _namSinh;
		}
	}

	@Override
	public void setNamSinh(String namSinh) {
		_namSinh = namSinh;
	}

	@Override
	public Date getNgaySinh() {
		return _ngaySinh;
	}

	@Override
	public void setNgaySinh(Date ngaySinh) {
		_ngaySinh = ngaySinh;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DnDoanhNghiep.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DnDoanhNghiep toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DnDoanhNghiep)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DnDoanhNghiepImpl dnDoanhNghiepImpl = new DnDoanhNghiepImpl();

		dnDoanhNghiepImpl.setId(getId());
		dnDoanhNghiepImpl.setMaSoDoanhNghiep(getMaSoDoanhNghiep());
		dnDoanhNghiepImpl.setTenDoanhNghiep(getTenDoanhNghiep());
		dnDoanhNghiepImpl.setDiaChi(getDiaChi());
		dnDoanhNghiepImpl.setMaTinhThanh(getMaTinhThanh());
		dnDoanhNghiepImpl.setMaQuanHuyen(getMaQuanHuyen());
		dnDoanhNghiepImpl.setMaPhuongXa(getMaPhuongXa());
		dnDoanhNghiepImpl.setDienThoai(getDienThoai());
		dnDoanhNghiepImpl.setWebsite(getWebsite());
		dnDoanhNghiepImpl.setFax(getFax());
		dnDoanhNghiepImpl.setEmail(getEmail());
		dnDoanhNghiepImpl.setMaster(getMaster());
		dnDoanhNghiepImpl.setNgayDangKi(getNgayDangKi());
		dnDoanhNghiepImpl.setHangTaiKhoan(getHangTaiKhoan());
		dnDoanhNghiepImpl.setMaKichHoat(getMaKichHoat());
		dnDoanhNghiepImpl.setNgayKichHoat(getNgayKichHoat());
		dnDoanhNghiepImpl.setSoDangKyKinhDoanh(getSoDangKyKinhDoanh());
		dnDoanhNghiepImpl.setNgayCapDkKd(getNgayCapDkKd());
		dnDoanhNghiepImpl.setNgayHetHanDKKD(getNgayHetHanDKKD());
		dnDoanhNghiepImpl.setCoQuanCapDkKd(getCoQuanCapDkKd());
		dnDoanhNghiepImpl.setLoaiDoanhNghiep(getLoaiDoanhNghiep());
		dnDoanhNghiepImpl.setNguoiDaiDien(getNguoiDaiDien());
		dnDoanhNghiepImpl.setSoDienThoaiNguoiDaiDien(getSoDienThoaiNguoiDaiDien());
		dnDoanhNghiepImpl.setChucVuNguoiDaiDien(getChucVuNguoiDaiDien());
		dnDoanhNghiepImpl.setTenTiengAnh(getTenTiengAnh());
		dnDoanhNghiepImpl.setTenVietTat(getTenVietTat());
		dnDoanhNghiepImpl.setSoGpkdVanTaiBangOto(getSoGpkdVanTaiBangOto());
		dnDoanhNghiepImpl.setNgayCapGpkdVanTaiBangOto(getNgayCapGpkdVanTaiBangOto());
		dnDoanhNghiepImpl.setCoQuanCapGpkdVanTaiBangOto(getCoQuanCapGpkdVanTaiBangOto());
		dnDoanhNghiepImpl.setMaSoCongDan(getMaSoCongDan());
		dnDoanhNghiepImpl.setTenCongDan(getTenCongDan());
		dnDoanhNghiepImpl.setQuocTich(getQuocTich());
		dnDoanhNghiepImpl.setGioiTinh(getGioiTinh());
		dnDoanhNghiepImpl.setNgayCapCMND(getNgayCapCMND());
		dnDoanhNghiepImpl.setNoiCapCMND(getNoiCapCMND());
		dnDoanhNghiepImpl.setLoaiNguoiLamThuTuc(getLoaiNguoiLamThuTuc());
		dnDoanhNghiepImpl.setNamSinh(getNamSinh());
		dnDoanhNghiepImpl.setNgaySinh(getNgaySinh());

		dnDoanhNghiepImpl.resetOriginalValues();

		return dnDoanhNghiepImpl;
	}

	@Override
	public int compareTo(DnDoanhNghiep dnDoanhNghiep) {
		int value = 0;

		if (getId() < dnDoanhNghiep.getId()) {
			value = -1;
		}
		else if (getId() > dnDoanhNghiep.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DnDoanhNghiep)) {
			return false;
		}

		DnDoanhNghiep dnDoanhNghiep = (DnDoanhNghiep)obj;

		long primaryKey = dnDoanhNghiep.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DnDoanhNghiepModelImpl dnDoanhNghiepModelImpl = this;

		dnDoanhNghiepModelImpl._originalId = dnDoanhNghiepModelImpl._id;

		dnDoanhNghiepModelImpl._setOriginalId = false;

		dnDoanhNghiepModelImpl._originalEmail = dnDoanhNghiepModelImpl._email;

		dnDoanhNghiepModelImpl._originalLoaiNguoiLamThuTuc = dnDoanhNghiepModelImpl._loaiNguoiLamThuTuc;

		dnDoanhNghiepModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DnDoanhNghiep> toCacheModel() {
		DnDoanhNghiepCacheModel dnDoanhNghiepCacheModel = new DnDoanhNghiepCacheModel();

		dnDoanhNghiepCacheModel.id = getId();

		dnDoanhNghiepCacheModel.maSoDoanhNghiep = getMaSoDoanhNghiep();

		String maSoDoanhNghiep = dnDoanhNghiepCacheModel.maSoDoanhNghiep;

		if ((maSoDoanhNghiep != null) && (maSoDoanhNghiep.length() == 0)) {
			dnDoanhNghiepCacheModel.maSoDoanhNghiep = null;
		}

		dnDoanhNghiepCacheModel.tenDoanhNghiep = getTenDoanhNghiep();

		String tenDoanhNghiep = dnDoanhNghiepCacheModel.tenDoanhNghiep;

		if ((tenDoanhNghiep != null) && (tenDoanhNghiep.length() == 0)) {
			dnDoanhNghiepCacheModel.tenDoanhNghiep = null;
		}

		dnDoanhNghiepCacheModel.diaChi = getDiaChi();

		String diaChi = dnDoanhNghiepCacheModel.diaChi;

		if ((diaChi != null) && (diaChi.length() == 0)) {
			dnDoanhNghiepCacheModel.diaChi = null;
		}

		dnDoanhNghiepCacheModel.maTinhThanh = getMaTinhThanh();

		String maTinhThanh = dnDoanhNghiepCacheModel.maTinhThanh;

		if ((maTinhThanh != null) && (maTinhThanh.length() == 0)) {
			dnDoanhNghiepCacheModel.maTinhThanh = null;
		}

		dnDoanhNghiepCacheModel.maQuanHuyen = getMaQuanHuyen();

		String maQuanHuyen = dnDoanhNghiepCacheModel.maQuanHuyen;

		if ((maQuanHuyen != null) && (maQuanHuyen.length() == 0)) {
			dnDoanhNghiepCacheModel.maQuanHuyen = null;
		}

		dnDoanhNghiepCacheModel.maPhuongXa = getMaPhuongXa();

		String maPhuongXa = dnDoanhNghiepCacheModel.maPhuongXa;

		if ((maPhuongXa != null) && (maPhuongXa.length() == 0)) {
			dnDoanhNghiepCacheModel.maPhuongXa = null;
		}

		dnDoanhNghiepCacheModel.dienThoai = getDienThoai();

		String dienThoai = dnDoanhNghiepCacheModel.dienThoai;

		if ((dienThoai != null) && (dienThoai.length() == 0)) {
			dnDoanhNghiepCacheModel.dienThoai = null;
		}

		dnDoanhNghiepCacheModel.website = getWebsite();

		String website = dnDoanhNghiepCacheModel.website;

		if ((website != null) && (website.length() == 0)) {
			dnDoanhNghiepCacheModel.website = null;
		}

		dnDoanhNghiepCacheModel.fax = getFax();

		String fax = dnDoanhNghiepCacheModel.fax;

		if ((fax != null) && (fax.length() == 0)) {
			dnDoanhNghiepCacheModel.fax = null;
		}

		dnDoanhNghiepCacheModel.email = getEmail();

		String email = dnDoanhNghiepCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			dnDoanhNghiepCacheModel.email = null;
		}

		dnDoanhNghiepCacheModel.master = getMaster();

		Date ngayDangKi = getNgayDangKi();

		if (ngayDangKi != null) {
			dnDoanhNghiepCacheModel.ngayDangKi = ngayDangKi.getTime();
		}
		else {
			dnDoanhNghiepCacheModel.ngayDangKi = Long.MIN_VALUE;
		}

		dnDoanhNghiepCacheModel.hangTaiKhoan = getHangTaiKhoan();

		String hangTaiKhoan = dnDoanhNghiepCacheModel.hangTaiKhoan;

		if ((hangTaiKhoan != null) && (hangTaiKhoan.length() == 0)) {
			dnDoanhNghiepCacheModel.hangTaiKhoan = null;
		}

		dnDoanhNghiepCacheModel.maKichHoat = getMaKichHoat();

		String maKichHoat = dnDoanhNghiepCacheModel.maKichHoat;

		if ((maKichHoat != null) && (maKichHoat.length() == 0)) {
			dnDoanhNghiepCacheModel.maKichHoat = null;
		}

		Date ngayKichHoat = getNgayKichHoat();

		if (ngayKichHoat != null) {
			dnDoanhNghiepCacheModel.ngayKichHoat = ngayKichHoat.getTime();
		}
		else {
			dnDoanhNghiepCacheModel.ngayKichHoat = Long.MIN_VALUE;
		}

		dnDoanhNghiepCacheModel.soDangKyKinhDoanh = getSoDangKyKinhDoanh();

		String soDangKyKinhDoanh = dnDoanhNghiepCacheModel.soDangKyKinhDoanh;

		if ((soDangKyKinhDoanh != null) && (soDangKyKinhDoanh.length() == 0)) {
			dnDoanhNghiepCacheModel.soDangKyKinhDoanh = null;
		}

		Date ngayCapDkKd = getNgayCapDkKd();

		if (ngayCapDkKd != null) {
			dnDoanhNghiepCacheModel.ngayCapDkKd = ngayCapDkKd.getTime();
		}
		else {
			dnDoanhNghiepCacheModel.ngayCapDkKd = Long.MIN_VALUE;
		}

		Date ngayHetHanDKKD = getNgayHetHanDKKD();

		if (ngayHetHanDKKD != null) {
			dnDoanhNghiepCacheModel.ngayHetHanDKKD = ngayHetHanDKKD.getTime();
		}
		else {
			dnDoanhNghiepCacheModel.ngayHetHanDKKD = Long.MIN_VALUE;
		}

		dnDoanhNghiepCacheModel.coQuanCapDkKd = getCoQuanCapDkKd();

		String coQuanCapDkKd = dnDoanhNghiepCacheModel.coQuanCapDkKd;

		if ((coQuanCapDkKd != null) && (coQuanCapDkKd.length() == 0)) {
			dnDoanhNghiepCacheModel.coQuanCapDkKd = null;
		}

		dnDoanhNghiepCacheModel.loaiDoanhNghiep = getLoaiDoanhNghiep();

		String loaiDoanhNghiep = dnDoanhNghiepCacheModel.loaiDoanhNghiep;

		if ((loaiDoanhNghiep != null) && (loaiDoanhNghiep.length() == 0)) {
			dnDoanhNghiepCacheModel.loaiDoanhNghiep = null;
		}

		dnDoanhNghiepCacheModel.nguoiDaiDien = getNguoiDaiDien();

		String nguoiDaiDien = dnDoanhNghiepCacheModel.nguoiDaiDien;

		if ((nguoiDaiDien != null) && (nguoiDaiDien.length() == 0)) {
			dnDoanhNghiepCacheModel.nguoiDaiDien = null;
		}

		dnDoanhNghiepCacheModel.soDienThoaiNguoiDaiDien = getSoDienThoaiNguoiDaiDien();

		String soDienThoaiNguoiDaiDien = dnDoanhNghiepCacheModel.soDienThoaiNguoiDaiDien;

		if ((soDienThoaiNguoiDaiDien != null) &&
				(soDienThoaiNguoiDaiDien.length() == 0)) {
			dnDoanhNghiepCacheModel.soDienThoaiNguoiDaiDien = null;
		}

		dnDoanhNghiepCacheModel.chucVuNguoiDaiDien = getChucVuNguoiDaiDien();

		String chucVuNguoiDaiDien = dnDoanhNghiepCacheModel.chucVuNguoiDaiDien;

		if ((chucVuNguoiDaiDien != null) && (chucVuNguoiDaiDien.length() == 0)) {
			dnDoanhNghiepCacheModel.chucVuNguoiDaiDien = null;
		}

		dnDoanhNghiepCacheModel.tenTiengAnh = getTenTiengAnh();

		String tenTiengAnh = dnDoanhNghiepCacheModel.tenTiengAnh;

		if ((tenTiengAnh != null) && (tenTiengAnh.length() == 0)) {
			dnDoanhNghiepCacheModel.tenTiengAnh = null;
		}

		dnDoanhNghiepCacheModel.tenVietTat = getTenVietTat();

		String tenVietTat = dnDoanhNghiepCacheModel.tenVietTat;

		if ((tenVietTat != null) && (tenVietTat.length() == 0)) {
			dnDoanhNghiepCacheModel.tenVietTat = null;
		}

		dnDoanhNghiepCacheModel.soGpkdVanTaiBangOto = getSoGpkdVanTaiBangOto();

		String soGpkdVanTaiBangOto = dnDoanhNghiepCacheModel.soGpkdVanTaiBangOto;

		if ((soGpkdVanTaiBangOto != null) &&
				(soGpkdVanTaiBangOto.length() == 0)) {
			dnDoanhNghiepCacheModel.soGpkdVanTaiBangOto = null;
		}

		Date ngayCapGpkdVanTaiBangOto = getNgayCapGpkdVanTaiBangOto();

		if (ngayCapGpkdVanTaiBangOto != null) {
			dnDoanhNghiepCacheModel.ngayCapGpkdVanTaiBangOto = ngayCapGpkdVanTaiBangOto.getTime();
		}
		else {
			dnDoanhNghiepCacheModel.ngayCapGpkdVanTaiBangOto = Long.MIN_VALUE;
		}

		dnDoanhNghiepCacheModel.coQuanCapGpkdVanTaiBangOto = getCoQuanCapGpkdVanTaiBangOto();

		String coQuanCapGpkdVanTaiBangOto = dnDoanhNghiepCacheModel.coQuanCapGpkdVanTaiBangOto;

		if ((coQuanCapGpkdVanTaiBangOto != null) &&
				(coQuanCapGpkdVanTaiBangOto.length() == 0)) {
			dnDoanhNghiepCacheModel.coQuanCapGpkdVanTaiBangOto = null;
		}

		dnDoanhNghiepCacheModel.maSoCongDan = getMaSoCongDan();

		String maSoCongDan = dnDoanhNghiepCacheModel.maSoCongDan;

		if ((maSoCongDan != null) && (maSoCongDan.length() == 0)) {
			dnDoanhNghiepCacheModel.maSoCongDan = null;
		}

		dnDoanhNghiepCacheModel.tenCongDan = getTenCongDan();

		String tenCongDan = dnDoanhNghiepCacheModel.tenCongDan;

		if ((tenCongDan != null) && (tenCongDan.length() == 0)) {
			dnDoanhNghiepCacheModel.tenCongDan = null;
		}

		dnDoanhNghiepCacheModel.quocTich = getQuocTich();

		String quocTich = dnDoanhNghiepCacheModel.quocTich;

		if ((quocTich != null) && (quocTich.length() == 0)) {
			dnDoanhNghiepCacheModel.quocTich = null;
		}

		dnDoanhNghiepCacheModel.gioiTinh = getGioiTinh();

		String gioiTinh = dnDoanhNghiepCacheModel.gioiTinh;

		if ((gioiTinh != null) && (gioiTinh.length() == 0)) {
			dnDoanhNghiepCacheModel.gioiTinh = null;
		}

		Date ngayCapCMND = getNgayCapCMND();

		if (ngayCapCMND != null) {
			dnDoanhNghiepCacheModel.ngayCapCMND = ngayCapCMND.getTime();
		}
		else {
			dnDoanhNghiepCacheModel.ngayCapCMND = Long.MIN_VALUE;
		}

		dnDoanhNghiepCacheModel.noiCapCMND = getNoiCapCMND();

		String noiCapCMND = dnDoanhNghiepCacheModel.noiCapCMND;

		if ((noiCapCMND != null) && (noiCapCMND.length() == 0)) {
			dnDoanhNghiepCacheModel.noiCapCMND = null;
		}

		dnDoanhNghiepCacheModel.loaiNguoiLamThuTuc = getLoaiNguoiLamThuTuc();

		String loaiNguoiLamThuTuc = dnDoanhNghiepCacheModel.loaiNguoiLamThuTuc;

		if ((loaiNguoiLamThuTuc != null) && (loaiNguoiLamThuTuc.length() == 0)) {
			dnDoanhNghiepCacheModel.loaiNguoiLamThuTuc = null;
		}

		dnDoanhNghiepCacheModel.namSinh = getNamSinh();

		String namSinh = dnDoanhNghiepCacheModel.namSinh;

		if ((namSinh != null) && (namSinh.length() == 0)) {
			dnDoanhNghiepCacheModel.namSinh = null;
		}

		Date ngaySinh = getNgaySinh();

		if (ngaySinh != null) {
			dnDoanhNghiepCacheModel.ngaySinh = ngaySinh.getTime();
		}
		else {
			dnDoanhNghiepCacheModel.ngaySinh = Long.MIN_VALUE;
		}

		return dnDoanhNghiepCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(77);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maSoDoanhNghiep=");
		sb.append(getMaSoDoanhNghiep());
		sb.append(", tenDoanhNghiep=");
		sb.append(getTenDoanhNghiep());
		sb.append(", diaChi=");
		sb.append(getDiaChi());
		sb.append(", maTinhThanh=");
		sb.append(getMaTinhThanh());
		sb.append(", maQuanHuyen=");
		sb.append(getMaQuanHuyen());
		sb.append(", maPhuongXa=");
		sb.append(getMaPhuongXa());
		sb.append(", dienThoai=");
		sb.append(getDienThoai());
		sb.append(", website=");
		sb.append(getWebsite());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", master=");
		sb.append(getMaster());
		sb.append(", ngayDangKi=");
		sb.append(getNgayDangKi());
		sb.append(", hangTaiKhoan=");
		sb.append(getHangTaiKhoan());
		sb.append(", maKichHoat=");
		sb.append(getMaKichHoat());
		sb.append(", ngayKichHoat=");
		sb.append(getNgayKichHoat());
		sb.append(", soDangKyKinhDoanh=");
		sb.append(getSoDangKyKinhDoanh());
		sb.append(", ngayCapDkKd=");
		sb.append(getNgayCapDkKd());
		sb.append(", ngayHetHanDKKD=");
		sb.append(getNgayHetHanDKKD());
		sb.append(", coQuanCapDkKd=");
		sb.append(getCoQuanCapDkKd());
		sb.append(", loaiDoanhNghiep=");
		sb.append(getLoaiDoanhNghiep());
		sb.append(", nguoiDaiDien=");
		sb.append(getNguoiDaiDien());
		sb.append(", soDienThoaiNguoiDaiDien=");
		sb.append(getSoDienThoaiNguoiDaiDien());
		sb.append(", chucVuNguoiDaiDien=");
		sb.append(getChucVuNguoiDaiDien());
		sb.append(", tenTiengAnh=");
		sb.append(getTenTiengAnh());
		sb.append(", tenVietTat=");
		sb.append(getTenVietTat());
		sb.append(", soGpkdVanTaiBangOto=");
		sb.append(getSoGpkdVanTaiBangOto());
		sb.append(", ngayCapGpkdVanTaiBangOto=");
		sb.append(getNgayCapGpkdVanTaiBangOto());
		sb.append(", coQuanCapGpkdVanTaiBangOto=");
		sb.append(getCoQuanCapGpkdVanTaiBangOto());
		sb.append(", maSoCongDan=");
		sb.append(getMaSoCongDan());
		sb.append(", tenCongDan=");
		sb.append(getTenCongDan());
		sb.append(", quocTich=");
		sb.append(getQuocTich());
		sb.append(", gioiTinh=");
		sb.append(getGioiTinh());
		sb.append(", ngayCapCMND=");
		sb.append(getNgayCapCMND());
		sb.append(", noiCapCMND=");
		sb.append(getNoiCapCMND());
		sb.append(", loaiNguoiLamThuTuc=");
		sb.append(getLoaiNguoiLamThuTuc());
		sb.append(", namSinh=");
		sb.append(getNamSinh());
		sb.append(", ngaySinh=");
		sb.append(getNgaySinh());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(118);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.doanhnghiep.model.DnDoanhNghiep");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoDoanhNghiep</column-name><column-value><![CDATA[");
		sb.append(getMaSoDoanhNghiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDoanhNghiep</column-name><column-value><![CDATA[");
		sb.append(getTenDoanhNghiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinhThanh</column-name><column-value><![CDATA[");
		sb.append(getMaTinhThanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maQuanHuyen</column-name><column-value><![CDATA[");
		sb.append(getMaQuanHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maPhuongXa</column-name><column-value><![CDATA[");
		sb.append(getMaPhuongXa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoai</column-name><column-value><![CDATA[");
		sb.append(getDienThoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>website</column-name><column-value><![CDATA[");
		sb.append(getWebsite());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>master</column-name><column-value><![CDATA[");
		sb.append(getMaster());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDangKi</column-name><column-value><![CDATA[");
		sb.append(getNgayDangKi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hangTaiKhoan</column-name><column-value><![CDATA[");
		sb.append(getHangTaiKhoan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maKichHoat</column-name><column-value><![CDATA[");
		sb.append(getMaKichHoat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKichHoat</column-name><column-value><![CDATA[");
		sb.append(getNgayKichHoat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDangKyKinhDoanh</column-name><column-value><![CDATA[");
		sb.append(getSoDangKyKinhDoanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapDkKd</column-name><column-value><![CDATA[");
		sb.append(getNgayCapDkKd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHanDKKD</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHanDKKD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCapDkKd</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapDkKd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiDoanhNghiep</column-name><column-value><![CDATA[");
		sb.append(getLoaiDoanhNghiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDienThoaiNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getSoDienThoaiNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chucVuNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getChucVuNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenTiengAnh</column-name><column-value><![CDATA[");
		sb.append(getTenTiengAnh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenVietTat</column-name><column-value><![CDATA[");
		sb.append(getTenVietTat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGpkdVanTaiBangOto</column-name><column-value><![CDATA[");
		sb.append(getSoGpkdVanTaiBangOto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGpkdVanTaiBangOto</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGpkdVanTaiBangOto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCapGpkdVanTaiBangOto</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapGpkdVanTaiBangOto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoCongDan</column-name><column-value><![CDATA[");
		sb.append(getMaSoCongDan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCongDan</column-name><column-value><![CDATA[");
		sb.append(getTenCongDan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quocTich</column-name><column-value><![CDATA[");
		sb.append(getQuocTich());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinh</column-name><column-value><![CDATA[");
		sb.append(getGioiTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapCMND</column-name><column-value><![CDATA[");
		sb.append(getNgayCapCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapCMND</column-name><column-value><![CDATA[");
		sb.append(getNoiCapCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiNguoiLamThuTuc</column-name><column-value><![CDATA[");
		sb.append(getLoaiNguoiLamThuTuc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namSinh</column-name><column-value><![CDATA[");
		sb.append(getNamSinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySinh</column-name><column-value><![CDATA[");
		sb.append(getNgaySinh());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DnDoanhNghiep.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DnDoanhNghiep.class
		};
	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private String _maSoDoanhNghiep;
	private String _tenDoanhNghiep;
	private String _diaChi;
	private String _maTinhThanh;
	private String _maQuanHuyen;
	private String _maPhuongXa;
	private String _dienThoai;
	private String _website;
	private String _fax;
	private String _email;
	private String _originalEmail;
	private long _master;
	private Date _ngayDangKi;
	private String _hangTaiKhoan;
	private String _maKichHoat;
	private Date _ngayKichHoat;
	private String _soDangKyKinhDoanh;
	private Date _ngayCapDkKd;
	private Date _ngayHetHanDKKD;
	private String _coQuanCapDkKd;
	private String _loaiDoanhNghiep;
	private String _nguoiDaiDien;
	private String _soDienThoaiNguoiDaiDien;
	private String _chucVuNguoiDaiDien;
	private String _tenTiengAnh;
	private String _tenVietTat;
	private String _soGpkdVanTaiBangOto;
	private Date _ngayCapGpkdVanTaiBangOto;
	private String _coQuanCapGpkdVanTaiBangOto;
	private String _maSoCongDan;
	private String _tenCongDan;
	private String _quocTich;
	private String _gioiTinh;
	private Date _ngayCapCMND;
	private String _noiCapCMND;
	private String _loaiNguoiLamThuTuc;
	private String _originalLoaiNguoiLamThuTuc;
	private String _namSinh;
	private Date _ngaySinh;
	private long _columnBitmask;
	private DnDoanhNghiep _escapedModel;
}