/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.motcua.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobpos;
import vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobposModel;
import vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobposSoap;
import vn.dtt.duongbo.dao.motcua.service.persistence.OEPUserMgtEmployee2jobposPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OEPUserMgtEmployee2jobpos service. Represents a row in the &quot;oep_usermgt_employee2jobpos&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobposModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OEPUserMgtEmployee2jobposImpl}.
 * </p>
 *
 * @author win_64
 * @see OEPUserMgtEmployee2jobposImpl
 * @see vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobpos
 * @see vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobposModel
 * @generated
 */
@JSON(strict = true)
public class OEPUserMgtEmployee2jobposModelImpl extends BaseModelImpl<OEPUserMgtEmployee2jobpos>
	implements OEPUserMgtEmployee2jobposModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a o e p user mgt employee2jobpos model instance should use the {@link vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobpos} interface instead.
	 */
	public static final String TABLE_NAME = "oep_usermgt_employee2jobpos";
	public static final Object[][] TABLE_COLUMNS = {
			{ "employeeId", Types.INTEGER },
			{ "jobPosId", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_usermgt_employee2jobpos (employeeId INTEGER not null,jobPosId INTEGER not null,primary key (employeeId, jobPosId))";
	public static final String TABLE_SQL_DROP = "drop table oep_usermgt_employee2jobpos";
	public static final String ORDER_BY_JPQL = " ORDER BY oepUserMgtEmployee2jobpos.id.employeeId ASC, oepUserMgtEmployee2jobpos.id.jobPosId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_usermgt_employee2jobpos.employeeId ASC, oep_usermgt_employee2jobpos.jobPosId ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobpos"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobpos"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OEPUserMgtEmployee2jobpos toModel(
		OEPUserMgtEmployee2jobposSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OEPUserMgtEmployee2jobpos model = new OEPUserMgtEmployee2jobposImpl();

		model.setEmployeeId(soapModel.getEmployeeId());
		model.setJobPosId(soapModel.getJobPosId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OEPUserMgtEmployee2jobpos> toModels(
		OEPUserMgtEmployee2jobposSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OEPUserMgtEmployee2jobpos> models = new ArrayList<OEPUserMgtEmployee2jobpos>(soapModels.length);

		for (OEPUserMgtEmployee2jobposSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobpos"));

	public OEPUserMgtEmployee2jobposModelImpl() {
	}

	@Override
	public OEPUserMgtEmployee2jobposPK getPrimaryKey() {
		return new OEPUserMgtEmployee2jobposPK(_employeeId, _jobPosId);
	}

	@Override
	public void setPrimaryKey(OEPUserMgtEmployee2jobposPK primaryKey) {
		setEmployeeId(primaryKey.employeeId);
		setJobPosId(primaryKey.jobPosId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new OEPUserMgtEmployee2jobposPK(_employeeId, _jobPosId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((OEPUserMgtEmployee2jobposPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return OEPUserMgtEmployee2jobpos.class;
	}

	@Override
	public String getModelClassName() {
		return OEPUserMgtEmployee2jobpos.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("employeeId", getEmployeeId());
		attributes.put("jobPosId", getJobPosId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer employeeId = (Integer)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Integer jobPosId = (Integer)attributes.get("jobPosId");

		if (jobPosId != null) {
			setJobPosId(jobPosId);
		}
	}

	@JSON
	@Override
	public int getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(int employeeId) {
		_employeeId = employeeId;
	}

	@JSON
	@Override
	public int getJobPosId() {
		return _jobPosId;
	}

	@Override
	public void setJobPosId(int jobPosId) {
		_jobPosId = jobPosId;
	}

	@Override
	public OEPUserMgtEmployee2jobpos toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OEPUserMgtEmployee2jobpos)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OEPUserMgtEmployee2jobposImpl oepUserMgtEmployee2jobposImpl = new OEPUserMgtEmployee2jobposImpl();

		oepUserMgtEmployee2jobposImpl.setEmployeeId(getEmployeeId());
		oepUserMgtEmployee2jobposImpl.setJobPosId(getJobPosId());

		oepUserMgtEmployee2jobposImpl.resetOriginalValues();

		return oepUserMgtEmployee2jobposImpl;
	}

	@Override
	public int compareTo(OEPUserMgtEmployee2jobpos oepUserMgtEmployee2jobpos) {
		OEPUserMgtEmployee2jobposPK primaryKey = oepUserMgtEmployee2jobpos.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OEPUserMgtEmployee2jobpos)) {
			return false;
		}

		OEPUserMgtEmployee2jobpos oepUserMgtEmployee2jobpos = (OEPUserMgtEmployee2jobpos)obj;

		OEPUserMgtEmployee2jobposPK primaryKey = oepUserMgtEmployee2jobpos.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<OEPUserMgtEmployee2jobpos> toCacheModel() {
		OEPUserMgtEmployee2jobposCacheModel oepUserMgtEmployee2jobposCacheModel = new OEPUserMgtEmployee2jobposCacheModel();

		oepUserMgtEmployee2jobposCacheModel.employeeId = getEmployeeId();

		oepUserMgtEmployee2jobposCacheModel.jobPosId = getJobPosId();

		return oepUserMgtEmployee2jobposCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{employeeId=");
		sb.append(getEmployeeId());
		sb.append(", jobPosId=");
		sb.append(getJobPosId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.motcua.model.OEPUserMgtEmployee2jobpos");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jobPosId</column-name><column-value><![CDATA[");
		sb.append(getJobPosId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = OEPUserMgtEmployee2jobpos.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			OEPUserMgtEmployee2jobpos.class
		};
	private int _employeeId;
	private int _jobPosId;
	private OEPUserMgtEmployee2jobpos _escapedModel;
}