/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.motcua.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnit;
import vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnitModel;
import vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnitSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OEPUserMgtWorkingUnit service. Represents a row in the &quot;oep_usermgt_workingunit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnitModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OEPUserMgtWorkingUnitImpl}.
 * </p>
 *
 * @author win_64
 * @see OEPUserMgtWorkingUnitImpl
 * @see vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnit
 * @see vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnitModel
 * @generated
 */
@JSON(strict = true)
public class OEPUserMgtWorkingUnitModelImpl extends BaseModelImpl<OEPUserMgtWorkingUnit>
	implements OEPUserMgtWorkingUnitModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a o e p user mgt working unit model instance should use the {@link vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnit} interface instead.
	 */
	public static final String TABLE_NAME = "oep_usermgt_workingunit";
	public static final Object[][] TABLE_COLUMNS = {
			{ "workingUnitId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "organizationId", Types.VARCHAR },
			{ "govAgentId", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "enname", Types.VARCHAR },
			{ "isRoot", Types.INTEGER },
			{ "parentWorkingUnitId", Types.BIGINT },
			{ "address", Types.VARCHAR },
			{ "cityNo", Types.VARCHAR },
			{ "cityName", Types.VARCHAR },
			{ "districtNo", Types.VARCHAR },
			{ "districtName", Types.VARCHAR },
			{ "wardNo", Types.VARCHAR },
			{ "wardName", Types.VARCHAR },
			{ "gpsPosition", Types.VARCHAR },
			{ "telNo", Types.VARCHAR },
			{ "fax", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "website", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_usermgt_workingunit (workingUnitId LONG not null primary key,userId LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,organizationId VARCHAR(75) null,govAgentId VARCHAR(75) null,name VARCHAR(75) null,enname VARCHAR(75) null,isRoot INTEGER,parentWorkingUnitId LONG,address VARCHAR(75) null,cityNo VARCHAR(75) null,cityName VARCHAR(75) null,districtNo VARCHAR(75) null,districtName VARCHAR(75) null,wardNo VARCHAR(75) null,wardName VARCHAR(75) null,gpsPosition VARCHAR(75) null,telNo VARCHAR(75) null,fax VARCHAR(75) null,email VARCHAR(75) null,website VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table oep_usermgt_workingunit";
	public static final String ORDER_BY_JPQL = " ORDER BY oepUserMgtWorkingUnit.workingUnitId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_usermgt_workingunit.workingUnitId ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnit"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnit"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnit"),
			true);
	public static long GOVAGENTID_COLUMN_BITMASK = 1L;
	public static long ORGANIZATIONID_COLUMN_BITMASK = 2L;
	public static long PARENTWORKINGUNITID_COLUMN_BITMASK = 4L;
	public static long WORKINGUNITID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OEPUserMgtWorkingUnit toModel(
		OEPUserMgtWorkingUnitSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OEPUserMgtWorkingUnit model = new OEPUserMgtWorkingUnitImpl();

		model.setWorkingUnitId(soapModel.getWorkingUnitId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setGovAgentId(soapModel.getGovAgentId());
		model.setName(soapModel.getName());
		model.setEnname(soapModel.getEnname());
		model.setIsRoot(soapModel.getIsRoot());
		model.setParentWorkingUnitId(soapModel.getParentWorkingUnitId());
		model.setAddress(soapModel.getAddress());
		model.setCityNo(soapModel.getCityNo());
		model.setCityName(soapModel.getCityName());
		model.setDistrictNo(soapModel.getDistrictNo());
		model.setDistrictName(soapModel.getDistrictName());
		model.setWardNo(soapModel.getWardNo());
		model.setWardName(soapModel.getWardName());
		model.setGpsPosition(soapModel.getGpsPosition());
		model.setTelNo(soapModel.getTelNo());
		model.setFax(soapModel.getFax());
		model.setEmail(soapModel.getEmail());
		model.setWebsite(soapModel.getWebsite());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OEPUserMgtWorkingUnit> toModels(
		OEPUserMgtWorkingUnitSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OEPUserMgtWorkingUnit> models = new ArrayList<OEPUserMgtWorkingUnit>(soapModels.length);

		for (OEPUserMgtWorkingUnitSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnit"));

	public OEPUserMgtWorkingUnitModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workingUnitId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkingUnitId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workingUnitId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OEPUserMgtWorkingUnit.class;
	}

	@Override
	public String getModelClassName() {
		return OEPUserMgtWorkingUnit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("workingUnitId", getWorkingUnitId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("govAgentId", getGovAgentId());
		attributes.put("name", getName());
		attributes.put("enname", getEnname());
		attributes.put("isRoot", getIsRoot());
		attributes.put("parentWorkingUnitId", getParentWorkingUnitId());
		attributes.put("address", getAddress());
		attributes.put("cityNo", getCityNo());
		attributes.put("cityName", getCityName());
		attributes.put("districtNo", getDistrictNo());
		attributes.put("districtName", getDistrictName());
		attributes.put("wardNo", getWardNo());
		attributes.put("wardName", getWardName());
		attributes.put("gpsPosition", getGpsPosition());
		attributes.put("telNo", getTelNo());
		attributes.put("fax", getFax());
		attributes.put("email", getEmail());
		attributes.put("website", getWebsite());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long workingUnitId = (Long)attributes.get("workingUnitId");

		if (workingUnitId != null) {
			setWorkingUnitId(workingUnitId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String organizationId = (String)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		String govAgentId = (String)attributes.get("govAgentId");

		if (govAgentId != null) {
			setGovAgentId(govAgentId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String enname = (String)attributes.get("enname");

		if (enname != null) {
			setEnname(enname);
		}

		Integer isRoot = (Integer)attributes.get("isRoot");

		if (isRoot != null) {
			setIsRoot(isRoot);
		}

		Long parentWorkingUnitId = (Long)attributes.get("parentWorkingUnitId");

		if (parentWorkingUnitId != null) {
			setParentWorkingUnitId(parentWorkingUnitId);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String cityNo = (String)attributes.get("cityNo");

		if (cityNo != null) {
			setCityNo(cityNo);
		}

		String cityName = (String)attributes.get("cityName");

		if (cityName != null) {
			setCityName(cityName);
		}

		String districtNo = (String)attributes.get("districtNo");

		if (districtNo != null) {
			setDistrictNo(districtNo);
		}

		String districtName = (String)attributes.get("districtName");

		if (districtName != null) {
			setDistrictName(districtName);
		}

		String wardNo = (String)attributes.get("wardNo");

		if (wardNo != null) {
			setWardNo(wardNo);
		}

		String wardName = (String)attributes.get("wardName");

		if (wardName != null) {
			setWardName(wardName);
		}

		String gpsPosition = (String)attributes.get("gpsPosition");

		if (gpsPosition != null) {
			setGpsPosition(gpsPosition);
		}

		String telNo = (String)attributes.get("telNo");

		if (telNo != null) {
			setTelNo(telNo);
		}

		String fax = (String)attributes.get("fax");

		if (fax != null) {
			setFax(fax);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String website = (String)attributes.get("website");

		if (website != null) {
			setWebsite(website);
		}
	}

	@JSON
	@Override
	public long getWorkingUnitId() {
		return _workingUnitId;
	}

	@Override
	public void setWorkingUnitId(long workingUnitId) {
		_columnBitmask = -1L;

		_workingUnitId = workingUnitId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getOrganizationId() {
		if (_organizationId == null) {
			return StringPool.BLANK;
		}
		else {
			return _organizationId;
		}
	}

	@Override
	public void setOrganizationId(String organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (_originalOrganizationId == null) {
			_originalOrganizationId = _organizationId;
		}

		_organizationId = organizationId;
	}

	public String getOriginalOrganizationId() {
		return GetterUtil.getString(_originalOrganizationId);
	}

	@JSON
	@Override
	public String getGovAgentId() {
		if (_govAgentId == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgentId;
		}
	}

	@Override
	public void setGovAgentId(String govAgentId) {
		_columnBitmask |= GOVAGENTID_COLUMN_BITMASK;

		if (_originalGovAgentId == null) {
			_originalGovAgentId = _govAgentId;
		}

		_govAgentId = govAgentId;
	}

	public String getOriginalGovAgentId() {
		return GetterUtil.getString(_originalGovAgentId);
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getEnname() {
		if (_enname == null) {
			return StringPool.BLANK;
		}
		else {
			return _enname;
		}
	}

	@Override
	public void setEnname(String enname) {
		_enname = enname;
	}

	@JSON
	@Override
	public int getIsRoot() {
		return _isRoot;
	}

	@Override
	public void setIsRoot(int isRoot) {
		_isRoot = isRoot;
	}

	@JSON
	@Override
	public long getParentWorkingUnitId() {
		return _parentWorkingUnitId;
	}

	@Override
	public void setParentWorkingUnitId(long parentWorkingUnitId) {
		_columnBitmask |= PARENTWORKINGUNITID_COLUMN_BITMASK;

		if (!_setOriginalParentWorkingUnitId) {
			_setOriginalParentWorkingUnitId = true;

			_originalParentWorkingUnitId = _parentWorkingUnitId;
		}

		_parentWorkingUnitId = parentWorkingUnitId;
	}

	public long getOriginalParentWorkingUnitId() {
		return _originalParentWorkingUnitId;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@JSON
	@Override
	public String getCityNo() {
		if (_cityNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _cityNo;
		}
	}

	@Override
	public void setCityNo(String cityNo) {
		_cityNo = cityNo;
	}

	@JSON
	@Override
	public String getCityName() {
		if (_cityName == null) {
			return StringPool.BLANK;
		}
		else {
			return _cityName;
		}
	}

	@Override
	public void setCityName(String cityName) {
		_cityName = cityName;
	}

	@JSON
	@Override
	public String getDistrictNo() {
		if (_districtNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _districtNo;
		}
	}

	@Override
	public void setDistrictNo(String districtNo) {
		_districtNo = districtNo;
	}

	@JSON
	@Override
	public String getDistrictName() {
		if (_districtName == null) {
			return StringPool.BLANK;
		}
		else {
			return _districtName;
		}
	}

	@Override
	public void setDistrictName(String districtName) {
		_districtName = districtName;
	}

	@JSON
	@Override
	public String getWardNo() {
		if (_wardNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _wardNo;
		}
	}

	@Override
	public void setWardNo(String wardNo) {
		_wardNo = wardNo;
	}

	@JSON
	@Override
	public String getWardName() {
		if (_wardName == null) {
			return StringPool.BLANK;
		}
		else {
			return _wardName;
		}
	}

	@Override
	public void setWardName(String wardName) {
		_wardName = wardName;
	}

	@JSON
	@Override
	public String getGpsPosition() {
		if (_gpsPosition == null) {
			return StringPool.BLANK;
		}
		else {
			return _gpsPosition;
		}
	}

	@Override
	public void setGpsPosition(String gpsPosition) {
		_gpsPosition = gpsPosition;
	}

	@JSON
	@Override
	public String getTelNo() {
		if (_telNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _telNo;
		}
	}

	@Override
	public void setTelNo(String telNo) {
		_telNo = telNo;
	}

	@JSON
	@Override
	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	@Override
	public void setFax(String fax) {
		_fax = fax;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getWebsite() {
		if (_website == null) {
			return StringPool.BLANK;
		}
		else {
			return _website;
		}
	}

	@Override
	public void setWebsite(String website) {
		_website = website;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			OEPUserMgtWorkingUnit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OEPUserMgtWorkingUnit toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OEPUserMgtWorkingUnit)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OEPUserMgtWorkingUnitImpl oepUserMgtWorkingUnitImpl = new OEPUserMgtWorkingUnitImpl();

		oepUserMgtWorkingUnitImpl.setWorkingUnitId(getWorkingUnitId());
		oepUserMgtWorkingUnitImpl.setUserId(getUserId());
		oepUserMgtWorkingUnitImpl.setGroupId(getGroupId());
		oepUserMgtWorkingUnitImpl.setCreateDate(getCreateDate());
		oepUserMgtWorkingUnitImpl.setModifiedDate(getModifiedDate());
		oepUserMgtWorkingUnitImpl.setOrganizationId(getOrganizationId());
		oepUserMgtWorkingUnitImpl.setGovAgentId(getGovAgentId());
		oepUserMgtWorkingUnitImpl.setName(getName());
		oepUserMgtWorkingUnitImpl.setEnname(getEnname());
		oepUserMgtWorkingUnitImpl.setIsRoot(getIsRoot());
		oepUserMgtWorkingUnitImpl.setParentWorkingUnitId(getParentWorkingUnitId());
		oepUserMgtWorkingUnitImpl.setAddress(getAddress());
		oepUserMgtWorkingUnitImpl.setCityNo(getCityNo());
		oepUserMgtWorkingUnitImpl.setCityName(getCityName());
		oepUserMgtWorkingUnitImpl.setDistrictNo(getDistrictNo());
		oepUserMgtWorkingUnitImpl.setDistrictName(getDistrictName());
		oepUserMgtWorkingUnitImpl.setWardNo(getWardNo());
		oepUserMgtWorkingUnitImpl.setWardName(getWardName());
		oepUserMgtWorkingUnitImpl.setGpsPosition(getGpsPosition());
		oepUserMgtWorkingUnitImpl.setTelNo(getTelNo());
		oepUserMgtWorkingUnitImpl.setFax(getFax());
		oepUserMgtWorkingUnitImpl.setEmail(getEmail());
		oepUserMgtWorkingUnitImpl.setWebsite(getWebsite());

		oepUserMgtWorkingUnitImpl.resetOriginalValues();

		return oepUserMgtWorkingUnitImpl;
	}

	@Override
	public int compareTo(OEPUserMgtWorkingUnit oepUserMgtWorkingUnit) {
		int value = 0;

		if (getWorkingUnitId() < oepUserMgtWorkingUnit.getWorkingUnitId()) {
			value = -1;
		}
		else if (getWorkingUnitId() > oepUserMgtWorkingUnit.getWorkingUnitId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OEPUserMgtWorkingUnit)) {
			return false;
		}

		OEPUserMgtWorkingUnit oepUserMgtWorkingUnit = (OEPUserMgtWorkingUnit)obj;

		long primaryKey = oepUserMgtWorkingUnit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		OEPUserMgtWorkingUnitModelImpl oepUserMgtWorkingUnitModelImpl = this;

		oepUserMgtWorkingUnitModelImpl._originalOrganizationId = oepUserMgtWorkingUnitModelImpl._organizationId;

		oepUserMgtWorkingUnitModelImpl._originalGovAgentId = oepUserMgtWorkingUnitModelImpl._govAgentId;

		oepUserMgtWorkingUnitModelImpl._originalParentWorkingUnitId = oepUserMgtWorkingUnitModelImpl._parentWorkingUnitId;

		oepUserMgtWorkingUnitModelImpl._setOriginalParentWorkingUnitId = false;

		oepUserMgtWorkingUnitModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OEPUserMgtWorkingUnit> toCacheModel() {
		OEPUserMgtWorkingUnitCacheModel oepUserMgtWorkingUnitCacheModel = new OEPUserMgtWorkingUnitCacheModel();

		oepUserMgtWorkingUnitCacheModel.workingUnitId = getWorkingUnitId();

		oepUserMgtWorkingUnitCacheModel.userId = getUserId();

		oepUserMgtWorkingUnitCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			oepUserMgtWorkingUnitCacheModel.createDate = createDate.getTime();
		}
		else {
			oepUserMgtWorkingUnitCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			oepUserMgtWorkingUnitCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			oepUserMgtWorkingUnitCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		oepUserMgtWorkingUnitCacheModel.organizationId = getOrganizationId();

		String organizationId = oepUserMgtWorkingUnitCacheModel.organizationId;

		if ((organizationId != null) && (organizationId.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.organizationId = null;
		}

		oepUserMgtWorkingUnitCacheModel.govAgentId = getGovAgentId();

		String govAgentId = oepUserMgtWorkingUnitCacheModel.govAgentId;

		if ((govAgentId != null) && (govAgentId.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.govAgentId = null;
		}

		oepUserMgtWorkingUnitCacheModel.name = getName();

		String name = oepUserMgtWorkingUnitCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.name = null;
		}

		oepUserMgtWorkingUnitCacheModel.enname = getEnname();

		String enname = oepUserMgtWorkingUnitCacheModel.enname;

		if ((enname != null) && (enname.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.enname = null;
		}

		oepUserMgtWorkingUnitCacheModel.isRoot = getIsRoot();

		oepUserMgtWorkingUnitCacheModel.parentWorkingUnitId = getParentWorkingUnitId();

		oepUserMgtWorkingUnitCacheModel.address = getAddress();

		String address = oepUserMgtWorkingUnitCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.address = null;
		}

		oepUserMgtWorkingUnitCacheModel.cityNo = getCityNo();

		String cityNo = oepUserMgtWorkingUnitCacheModel.cityNo;

		if ((cityNo != null) && (cityNo.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.cityNo = null;
		}

		oepUserMgtWorkingUnitCacheModel.cityName = getCityName();

		String cityName = oepUserMgtWorkingUnitCacheModel.cityName;

		if ((cityName != null) && (cityName.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.cityName = null;
		}

		oepUserMgtWorkingUnitCacheModel.districtNo = getDistrictNo();

		String districtNo = oepUserMgtWorkingUnitCacheModel.districtNo;

		if ((districtNo != null) && (districtNo.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.districtNo = null;
		}

		oepUserMgtWorkingUnitCacheModel.districtName = getDistrictName();

		String districtName = oepUserMgtWorkingUnitCacheModel.districtName;

		if ((districtName != null) && (districtName.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.districtName = null;
		}

		oepUserMgtWorkingUnitCacheModel.wardNo = getWardNo();

		String wardNo = oepUserMgtWorkingUnitCacheModel.wardNo;

		if ((wardNo != null) && (wardNo.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.wardNo = null;
		}

		oepUserMgtWorkingUnitCacheModel.wardName = getWardName();

		String wardName = oepUserMgtWorkingUnitCacheModel.wardName;

		if ((wardName != null) && (wardName.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.wardName = null;
		}

		oepUserMgtWorkingUnitCacheModel.gpsPosition = getGpsPosition();

		String gpsPosition = oepUserMgtWorkingUnitCacheModel.gpsPosition;

		if ((gpsPosition != null) && (gpsPosition.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.gpsPosition = null;
		}

		oepUserMgtWorkingUnitCacheModel.telNo = getTelNo();

		String telNo = oepUserMgtWorkingUnitCacheModel.telNo;

		if ((telNo != null) && (telNo.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.telNo = null;
		}

		oepUserMgtWorkingUnitCacheModel.fax = getFax();

		String fax = oepUserMgtWorkingUnitCacheModel.fax;

		if ((fax != null) && (fax.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.fax = null;
		}

		oepUserMgtWorkingUnitCacheModel.email = getEmail();

		String email = oepUserMgtWorkingUnitCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.email = null;
		}

		oepUserMgtWorkingUnitCacheModel.website = getWebsite();

		String website = oepUserMgtWorkingUnitCacheModel.website;

		if ((website != null) && (website.length() == 0)) {
			oepUserMgtWorkingUnitCacheModel.website = null;
		}

		return oepUserMgtWorkingUnitCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(47);

		sb.append("{workingUnitId=");
		sb.append(getWorkingUnitId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", govAgentId=");
		sb.append(getGovAgentId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", enname=");
		sb.append(getEnname());
		sb.append(", isRoot=");
		sb.append(getIsRoot());
		sb.append(", parentWorkingUnitId=");
		sb.append(getParentWorkingUnitId());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", cityNo=");
		sb.append(getCityNo());
		sb.append(", cityName=");
		sb.append(getCityName());
		sb.append(", districtNo=");
		sb.append(getDistrictNo());
		sb.append(", districtName=");
		sb.append(getDistrictName());
		sb.append(", wardNo=");
		sb.append(getWardNo());
		sb.append(", wardName=");
		sb.append(getWardName());
		sb.append(", gpsPosition=");
		sb.append(getGpsPosition());
		sb.append(", telNo=");
		sb.append(getTelNo());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", website=");
		sb.append(getWebsite());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(73);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.motcua.model.OEPUserMgtWorkingUnit");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>workingUnitId</column-name><column-value><![CDATA[");
		sb.append(getWorkingUnitId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgentId</column-name><column-value><![CDATA[");
		sb.append(getGovAgentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enname</column-name><column-value><![CDATA[");
		sb.append(getEnname());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isRoot</column-name><column-value><![CDATA[");
		sb.append(getIsRoot());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentWorkingUnitId</column-name><column-value><![CDATA[");
		sb.append(getParentWorkingUnitId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityNo</column-name><column-value><![CDATA[");
		sb.append(getCityNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityName</column-name><column-value><![CDATA[");
		sb.append(getCityName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>districtNo</column-name><column-value><![CDATA[");
		sb.append(getDistrictNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>districtName</column-name><column-value><![CDATA[");
		sb.append(getDistrictName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wardNo</column-name><column-value><![CDATA[");
		sb.append(getWardNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wardName</column-name><column-value><![CDATA[");
		sb.append(getWardName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gpsPosition</column-name><column-value><![CDATA[");
		sb.append(getGpsPosition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telNo</column-name><column-value><![CDATA[");
		sb.append(getTelNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>website</column-name><column-value><![CDATA[");
		sb.append(getWebsite());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = OEPUserMgtWorkingUnit.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			OEPUserMgtWorkingUnit.class
		};
	private long _workingUnitId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private String _organizationId;
	private String _originalOrganizationId;
	private String _govAgentId;
	private String _originalGovAgentId;
	private String _name;
	private String _enname;
	private int _isRoot;
	private long _parentWorkingUnitId;
	private long _originalParentWorkingUnitId;
	private boolean _setOriginalParentWorkingUnitId;
	private String _address;
	private String _cityNo;
	private String _cityName;
	private String _districtNo;
	private String _districtName;
	private String _wardNo;
	private String _wardName;
	private String _gpsPosition;
	private String _telNo;
	private String _fax;
	private String _email;
	private String _website;
	private long _columnBitmask;
	private OEPUserMgtWorkingUnit _escapedModel;
}