/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTe;
import vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTeModel;
import vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTeSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtThongTinHoSoQuocTe service. Represents a row in the &quot;nghiepvu_thongtinhoso_qlvt_capphep_gpkdvt_duongbo_quocte&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtThongTinHoSoQuocTeImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtThongTinHoSoQuocTeImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTe
 * @see vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTeModel
 * @generated
 */
@JSON(strict = true)
public class QlvtThongTinHoSoQuocTeModelImpl extends BaseModelImpl<QlvtThongTinHoSoQuocTe>
	implements QlvtThongTinHoSoQuocTeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt thong tin ho so quoc te model instance should use the {@link vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTe} interface instead.
	 */
	public static final String TABLE_NAME = "nghiepvu_thongtinhoso_qlvt_capphep_gpkdvt_duongbo_quocte";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "nghiepvu_thongtinhosoID", Types.BIGINT },
			{ "qlvt_capphep_gpkdvtID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table nghiepvu_thongtinhoso_qlvt_capphep_gpkdvt_duongbo_quocte (id LONG not null primary key,nghiepvu_thongtinhosoID LONG,qlvt_capphep_gpkdvtID LONG)";
	public static final String TABLE_SQL_DROP = "drop table nghiepvu_thongtinhoso_qlvt_capphep_gpkdvt_duongbo_quocte";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtThongTinHoSoQuocTe.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY nghiepvu_thongtinhoso_qlvt_capphep_gpkdvt_duongbo_quocte.id ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTe"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTe"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtThongTinHoSoQuocTe toModel(
		QlvtThongTinHoSoQuocTeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtThongTinHoSoQuocTe model = new QlvtThongTinHoSoQuocTeImpl();

		model.setId(soapModel.getId());
		model.setThongtinHoSoId(soapModel.getThongtinHoSoId());
		model.setGpkdvtID(soapModel.getGpkdvtID());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtThongTinHoSoQuocTe> toModels(
		QlvtThongTinHoSoQuocTeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtThongTinHoSoQuocTe> models = new ArrayList<QlvtThongTinHoSoQuocTe>(soapModels.length);

		for (QlvtThongTinHoSoQuocTeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTe"));

	public QlvtThongTinHoSoQuocTeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtThongTinHoSoQuocTe.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtThongTinHoSoQuocTe.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thongtinHoSoId", getThongtinHoSoId());
		attributes.put("gpkdvtID", getGpkdvtID());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long thongtinHoSoId = (Long)attributes.get("thongtinHoSoId");

		if (thongtinHoSoId != null) {
			setThongtinHoSoId(thongtinHoSoId);
		}

		Long gpkdvtID = (Long)attributes.get("gpkdvtID");

		if (gpkdvtID != null) {
			setGpkdvtID(gpkdvtID);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getThongtinHoSoId() {
		return _thongtinHoSoId;
	}

	@Override
	public void setThongtinHoSoId(long thongtinHoSoId) {
		_thongtinHoSoId = thongtinHoSoId;
	}

	@JSON
	@Override
	public long getGpkdvtID() {
		return _gpkdvtID;
	}

	@Override
	public void setGpkdvtID(long gpkdvtID) {
		_gpkdvtID = gpkdvtID;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtThongTinHoSoQuocTe.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtThongTinHoSoQuocTe toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtThongTinHoSoQuocTe)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtThongTinHoSoQuocTeImpl qlvtThongTinHoSoQuocTeImpl = new QlvtThongTinHoSoQuocTeImpl();

		qlvtThongTinHoSoQuocTeImpl.setId(getId());
		qlvtThongTinHoSoQuocTeImpl.setThongtinHoSoId(getThongtinHoSoId());
		qlvtThongTinHoSoQuocTeImpl.setGpkdvtID(getGpkdvtID());

		qlvtThongTinHoSoQuocTeImpl.resetOriginalValues();

		return qlvtThongTinHoSoQuocTeImpl;
	}

	@Override
	public int compareTo(QlvtThongTinHoSoQuocTe qlvtThongTinHoSoQuocTe) {
		int value = 0;

		if (getId() < qlvtThongTinHoSoQuocTe.getId()) {
			value = -1;
		}
		else if (getId() > qlvtThongTinHoSoQuocTe.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtThongTinHoSoQuocTe)) {
			return false;
		}

		QlvtThongTinHoSoQuocTe qlvtThongTinHoSoQuocTe = (QlvtThongTinHoSoQuocTe)obj;

		long primaryKey = qlvtThongTinHoSoQuocTe.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QlvtThongTinHoSoQuocTe> toCacheModel() {
		QlvtThongTinHoSoQuocTeCacheModel qlvtThongTinHoSoQuocTeCacheModel = new QlvtThongTinHoSoQuocTeCacheModel();

		qlvtThongTinHoSoQuocTeCacheModel.id = getId();

		qlvtThongTinHoSoQuocTeCacheModel.thongtinHoSoId = getThongtinHoSoId();

		qlvtThongTinHoSoQuocTeCacheModel.gpkdvtID = getGpkdvtID();

		return qlvtThongTinHoSoQuocTeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thongtinHoSoId=");
		sb.append(getThongtinHoSoId());
		sb.append(", gpkdvtID=");
		sb.append(getGpkdvtID());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoQuocTe");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongtinHoSoId</column-name><column-value><![CDATA[");
		sb.append(getThongtinHoSoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gpkdvtID</column-name><column-value><![CDATA[");
		sb.append(getGpkdvtID());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtThongTinHoSoQuocTe.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtThongTinHoSoQuocTe.class
		};
	private long _id;
	private long _thongtinHoSoId;
	private long _gpkdvtID;
	private QlvtThongTinHoSoQuocTe _escapedModel;
}