/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFile;
import vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFileModel;
import vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFileSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtQuanLyFile service. Represents a row in the &quot;nghiepvu_quanlyfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtQuanLyFileImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtQuanLyFileImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFile
 * @see vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFileModel
 * @generated
 */
@JSON(strict = true)
public class QlvtQuanLyFileModelImpl extends BaseModelImpl<QlvtQuanLyFile>
	implements QlvtQuanLyFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt quan ly file model instance should use the {@link vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFile} interface instead.
	 */
	public static final String TABLE_NAME = "nghiepvu_quanlyfile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TENFILE", Types.VARCHAR },
			{ "LOAIFILE", Types.BIGINT },
			{ "THONGTINFILE", Types.VARCHAR },
			{ "NGAYTAI", Types.TIMESTAMP },
			{ "NGAYCAP", Types.TIMESTAMP },
			{ "NGAYHETHAN", Types.TIMESTAMP },
			{ "IDFILE", Types.BIGINT },
			{ "TRANGTHAI", Types.VARCHAR },
			{ "DOANHNGHIEPID", Types.BIGINT },
			{ "TAIKHOAN", Types.BIGINT },
			{ "MIEUTA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table nghiepvu_quanlyfile (ID LONG not null primary key,TENFILE VARCHAR(75) null,LOAIFILE LONG,THONGTINFILE VARCHAR(75) null,NGAYTAI DATE null,NGAYCAP DATE null,NGAYHETHAN DATE null,IDFILE LONG,TRANGTHAI VARCHAR(75) null,DOANHNGHIEPID LONG,TAIKHOAN LONG,MIEUTA VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table nghiepvu_quanlyfile";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtQuanLyFile.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY nghiepvu_quanlyfile.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFile"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFile"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFile"),
			true);
	public static long DOANHNGHIEPID_COLUMN_BITMASK = 1L;
	public static long IDFILE_COLUMN_BITMASK = 2L;
	public static long ID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtQuanLyFile toModel(QlvtQuanLyFileSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtQuanLyFile model = new QlvtQuanLyFileImpl();

		model.setId(soapModel.getId());
		model.setTenFile(soapModel.getTenFile());
		model.setLoaiFile(soapModel.getLoaiFile());
		model.setThongTinFile(soapModel.getThongTinFile());
		model.setNgayTai(soapModel.getNgayTai());
		model.setNgayCap(soapModel.getNgayCap());
		model.setNgayHetHan(soapModel.getNgayHetHan());
		model.setIdFile(soapModel.getIdFile());
		model.setTrangThai(soapModel.getTrangThai());
		model.setDoanhNghiepId(soapModel.getDoanhNghiepId());
		model.setTaiKhoan(soapModel.getTaiKhoan());
		model.setMieuTa(soapModel.getMieuTa());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtQuanLyFile> toModels(QlvtQuanLyFileSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtQuanLyFile> models = new ArrayList<QlvtQuanLyFile>(soapModels.length);

		for (QlvtQuanLyFileSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFile"));

	public QlvtQuanLyFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtQuanLyFile.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtQuanLyFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("tenFile", getTenFile());
		attributes.put("loaiFile", getLoaiFile());
		attributes.put("thongTinFile", getThongTinFile());
		attributes.put("ngayTai", getNgayTai());
		attributes.put("ngayCap", getNgayCap());
		attributes.put("ngayHetHan", getNgayHetHan());
		attributes.put("idFile", getIdFile());
		attributes.put("trangThai", getTrangThai());
		attributes.put("doanhNghiepId", getDoanhNghiepId());
		attributes.put("taiKhoan", getTaiKhoan());
		attributes.put("mieuTa", getMieuTa());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String tenFile = (String)attributes.get("tenFile");

		if (tenFile != null) {
			setTenFile(tenFile);
		}

		Long loaiFile = (Long)attributes.get("loaiFile");

		if (loaiFile != null) {
			setLoaiFile(loaiFile);
		}

		String thongTinFile = (String)attributes.get("thongTinFile");

		if (thongTinFile != null) {
			setThongTinFile(thongTinFile);
		}

		Date ngayTai = (Date)attributes.get("ngayTai");

		if (ngayTai != null) {
			setNgayTai(ngayTai);
		}

		Date ngayCap = (Date)attributes.get("ngayCap");

		if (ngayCap != null) {
			setNgayCap(ngayCap);
		}

		Date ngayHetHan = (Date)attributes.get("ngayHetHan");

		if (ngayHetHan != null) {
			setNgayHetHan(ngayHetHan);
		}

		Long idFile = (Long)attributes.get("idFile");

		if (idFile != null) {
			setIdFile(idFile);
		}

		String trangThai = (String)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}

		Long doanhNghiepId = (Long)attributes.get("doanhNghiepId");

		if (doanhNghiepId != null) {
			setDoanhNghiepId(doanhNghiepId);
		}

		Long taiKhoan = (Long)attributes.get("taiKhoan");

		if (taiKhoan != null) {
			setTaiKhoan(taiKhoan);
		}

		String mieuTa = (String)attributes.get("mieuTa");

		if (mieuTa != null) {
			setMieuTa(mieuTa);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public String getTenFile() {
		if (_tenFile == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenFile;
		}
	}

	@Override
	public void setTenFile(String tenFile) {
		_tenFile = tenFile;
	}

	@JSON
	@Override
	public long getLoaiFile() {
		return _loaiFile;
	}

	@Override
	public void setLoaiFile(long loaiFile) {
		_loaiFile = loaiFile;
	}

	@JSON
	@Override
	public String getThongTinFile() {
		if (_thongTinFile == null) {
			return StringPool.BLANK;
		}
		else {
			return _thongTinFile;
		}
	}

	@Override
	public void setThongTinFile(String thongTinFile) {
		_thongTinFile = thongTinFile;
	}

	@JSON
	@Override
	public Date getNgayTai() {
		return _ngayTai;
	}

	@Override
	public void setNgayTai(Date ngayTai) {
		_ngayTai = ngayTai;
	}

	@JSON
	@Override
	public Date getNgayCap() {
		return _ngayCap;
	}

	@Override
	public void setNgayCap(Date ngayCap) {
		_ngayCap = ngayCap;
	}

	@JSON
	@Override
	public Date getNgayHetHan() {
		return _ngayHetHan;
	}

	@Override
	public void setNgayHetHan(Date ngayHetHan) {
		_ngayHetHan = ngayHetHan;
	}

	@JSON
	@Override
	public long getIdFile() {
		return _idFile;
	}

	@Override
	public void setIdFile(long idFile) {
		_columnBitmask |= IDFILE_COLUMN_BITMASK;

		if (!_setOriginalIdFile) {
			_setOriginalIdFile = true;

			_originalIdFile = _idFile;
		}

		_idFile = idFile;
	}

	public long getOriginalIdFile() {
		return _originalIdFile;
	}

	@JSON
	@Override
	public String getTrangThai() {
		if (_trangThai == null) {
			return StringPool.BLANK;
		}
		else {
			return _trangThai;
		}
	}

	@Override
	public void setTrangThai(String trangThai) {
		_trangThai = trangThai;
	}

	@JSON
	@Override
	public long getDoanhNghiepId() {
		return _doanhNghiepId;
	}

	@Override
	public void setDoanhNghiepId(long doanhNghiepId) {
		_columnBitmask |= DOANHNGHIEPID_COLUMN_BITMASK;

		if (!_setOriginalDoanhNghiepId) {
			_setOriginalDoanhNghiepId = true;

			_originalDoanhNghiepId = _doanhNghiepId;
		}

		_doanhNghiepId = doanhNghiepId;
	}

	public long getOriginalDoanhNghiepId() {
		return _originalDoanhNghiepId;
	}

	@JSON
	@Override
	public long getTaiKhoan() {
		return _taiKhoan;
	}

	@Override
	public void setTaiKhoan(long taiKhoan) {
		_taiKhoan = taiKhoan;
	}

	@JSON
	@Override
	public String getMieuTa() {
		if (_mieuTa == null) {
			return StringPool.BLANK;
		}
		else {
			return _mieuTa;
		}
	}

	@Override
	public void setMieuTa(String mieuTa) {
		_mieuTa = mieuTa;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtQuanLyFile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtQuanLyFile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtQuanLyFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtQuanLyFileImpl qlvtQuanLyFileImpl = new QlvtQuanLyFileImpl();

		qlvtQuanLyFileImpl.setId(getId());
		qlvtQuanLyFileImpl.setTenFile(getTenFile());
		qlvtQuanLyFileImpl.setLoaiFile(getLoaiFile());
		qlvtQuanLyFileImpl.setThongTinFile(getThongTinFile());
		qlvtQuanLyFileImpl.setNgayTai(getNgayTai());
		qlvtQuanLyFileImpl.setNgayCap(getNgayCap());
		qlvtQuanLyFileImpl.setNgayHetHan(getNgayHetHan());
		qlvtQuanLyFileImpl.setIdFile(getIdFile());
		qlvtQuanLyFileImpl.setTrangThai(getTrangThai());
		qlvtQuanLyFileImpl.setDoanhNghiepId(getDoanhNghiepId());
		qlvtQuanLyFileImpl.setTaiKhoan(getTaiKhoan());
		qlvtQuanLyFileImpl.setMieuTa(getMieuTa());

		qlvtQuanLyFileImpl.resetOriginalValues();

		return qlvtQuanLyFileImpl;
	}

	@Override
	public int compareTo(QlvtQuanLyFile qlvtQuanLyFile) {
		int value = 0;

		if (getId() < qlvtQuanLyFile.getId()) {
			value = -1;
		}
		else if (getId() > qlvtQuanLyFile.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtQuanLyFile)) {
			return false;
		}

		QlvtQuanLyFile qlvtQuanLyFile = (QlvtQuanLyFile)obj;

		long primaryKey = qlvtQuanLyFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		QlvtQuanLyFileModelImpl qlvtQuanLyFileModelImpl = this;

		qlvtQuanLyFileModelImpl._originalIdFile = qlvtQuanLyFileModelImpl._idFile;

		qlvtQuanLyFileModelImpl._setOriginalIdFile = false;

		qlvtQuanLyFileModelImpl._originalDoanhNghiepId = qlvtQuanLyFileModelImpl._doanhNghiepId;

		qlvtQuanLyFileModelImpl._setOriginalDoanhNghiepId = false;

		qlvtQuanLyFileModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<QlvtQuanLyFile> toCacheModel() {
		QlvtQuanLyFileCacheModel qlvtQuanLyFileCacheModel = new QlvtQuanLyFileCacheModel();

		qlvtQuanLyFileCacheModel.id = getId();

		qlvtQuanLyFileCacheModel.tenFile = getTenFile();

		String tenFile = qlvtQuanLyFileCacheModel.tenFile;

		if ((tenFile != null) && (tenFile.length() == 0)) {
			qlvtQuanLyFileCacheModel.tenFile = null;
		}

		qlvtQuanLyFileCacheModel.loaiFile = getLoaiFile();

		qlvtQuanLyFileCacheModel.thongTinFile = getThongTinFile();

		String thongTinFile = qlvtQuanLyFileCacheModel.thongTinFile;

		if ((thongTinFile != null) && (thongTinFile.length() == 0)) {
			qlvtQuanLyFileCacheModel.thongTinFile = null;
		}

		Date ngayTai = getNgayTai();

		if (ngayTai != null) {
			qlvtQuanLyFileCacheModel.ngayTai = ngayTai.getTime();
		}
		else {
			qlvtQuanLyFileCacheModel.ngayTai = Long.MIN_VALUE;
		}

		Date ngayCap = getNgayCap();

		if (ngayCap != null) {
			qlvtQuanLyFileCacheModel.ngayCap = ngayCap.getTime();
		}
		else {
			qlvtQuanLyFileCacheModel.ngayCap = Long.MIN_VALUE;
		}

		Date ngayHetHan = getNgayHetHan();

		if (ngayHetHan != null) {
			qlvtQuanLyFileCacheModel.ngayHetHan = ngayHetHan.getTime();
		}
		else {
			qlvtQuanLyFileCacheModel.ngayHetHan = Long.MIN_VALUE;
		}

		qlvtQuanLyFileCacheModel.idFile = getIdFile();

		qlvtQuanLyFileCacheModel.trangThai = getTrangThai();

		String trangThai = qlvtQuanLyFileCacheModel.trangThai;

		if ((trangThai != null) && (trangThai.length() == 0)) {
			qlvtQuanLyFileCacheModel.trangThai = null;
		}

		qlvtQuanLyFileCacheModel.doanhNghiepId = getDoanhNghiepId();

		qlvtQuanLyFileCacheModel.taiKhoan = getTaiKhoan();

		qlvtQuanLyFileCacheModel.mieuTa = getMieuTa();

		String mieuTa = qlvtQuanLyFileCacheModel.mieuTa;

		if ((mieuTa != null) && (mieuTa.length() == 0)) {
			qlvtQuanLyFileCacheModel.mieuTa = null;
		}

		return qlvtQuanLyFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", tenFile=");
		sb.append(getTenFile());
		sb.append(", loaiFile=");
		sb.append(getLoaiFile());
		sb.append(", thongTinFile=");
		sb.append(getThongTinFile());
		sb.append(", ngayTai=");
		sb.append(getNgayTai());
		sb.append(", ngayCap=");
		sb.append(getNgayCap());
		sb.append(", ngayHetHan=");
		sb.append(getNgayHetHan());
		sb.append(", idFile=");
		sb.append(getIdFile());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", doanhNghiepId=");
		sb.append(getDoanhNghiepId());
		sb.append(", taiKhoan=");
		sb.append(getTaiKhoan());
		sb.append(", mieuTa=");
		sb.append(getMieuTa());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.nghiepvu.model.QlvtQuanLyFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenFile</column-name><column-value><![CDATA[");
		sb.append(getTenFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiFile</column-name><column-value><![CDATA[");
		sb.append(getLoaiFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongTinFile</column-name><column-value><![CDATA[");
		sb.append(getThongTinFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTai</column-name><column-value><![CDATA[");
		sb.append(getNgayTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCap</column-name><column-value><![CDATA[");
		sb.append(getNgayCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHan</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idFile</column-name><column-value><![CDATA[");
		sb.append(getIdFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>doanhNghiepId</column-name><column-value><![CDATA[");
		sb.append(getDoanhNghiepId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoan</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mieuTa</column-name><column-value><![CDATA[");
		sb.append(getMieuTa());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtQuanLyFile.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtQuanLyFile.class
		};
	private long _id;
	private String _tenFile;
	private long _loaiFile;
	private String _thongTinFile;
	private Date _ngayTai;
	private Date _ngayCap;
	private Date _ngayHetHan;
	private long _idFile;
	private long _originalIdFile;
	private boolean _setOriginalIdFile;
	private String _trangThai;
	private long _doanhNghiepId;
	private long _originalDoanhNghiepId;
	private boolean _setOriginalDoanhNghiepId;
	private long _taiKhoan;
	private String _mieuTa;
	private long _columnBitmask;
	private QlvtQuanLyFile _escapedModel;
}