/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVan;
import vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVanModel;
import vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVanSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtThongTinHoSoLienVan service. Represents a row in the &quot;nghiepvu_thongtinhoso_qlvt_capphep_gplienvan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtThongTinHoSoLienVanImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtThongTinHoSoLienVanImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVan
 * @see vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVanModel
 * @generated
 */
@JSON(strict = true)
public class QlvtThongTinHoSoLienVanModelImpl extends BaseModelImpl<QlvtThongTinHoSoLienVan>
	implements QlvtThongTinHoSoLienVanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt thong tin ho so lien van model instance should use the {@link vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVan} interface instead.
	 */
	public static final String TABLE_NAME = "nghiepvu_thongtinhoso_qlvt_capphep_gplienvan";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "nghiepvu_thongtinhosoID", Types.BIGINT },
			{ "qlvt_capphep_gplienvanID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table nghiepvu_thongtinhoso_qlvt_capphep_gplienvan (id LONG not null primary key,nghiepvu_thongtinhosoID LONG,qlvt_capphep_gplienvanID LONG)";
	public static final String TABLE_SQL_DROP = "drop table nghiepvu_thongtinhoso_qlvt_capphep_gplienvan";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtThongTinHoSoLienVan.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY nghiepvu_thongtinhoso_qlvt_capphep_gplienvan.id ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVan"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVan"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtThongTinHoSoLienVan toModel(
		QlvtThongTinHoSoLienVanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtThongTinHoSoLienVan model = new QlvtThongTinHoSoLienVanImpl();

		model.setId(soapModel.getId());
		model.setThongtinHoSoId(soapModel.getThongtinHoSoId());
		model.setGplienvanID(soapModel.getGplienvanID());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtThongTinHoSoLienVan> toModels(
		QlvtThongTinHoSoLienVanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtThongTinHoSoLienVan> models = new ArrayList<QlvtThongTinHoSoLienVan>(soapModels.length);

		for (QlvtThongTinHoSoLienVanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVan"));

	public QlvtThongTinHoSoLienVanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtThongTinHoSoLienVan.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtThongTinHoSoLienVan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thongtinHoSoId", getThongtinHoSoId());
		attributes.put("gplienvanID", getGplienvanID());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long thongtinHoSoId = (Long)attributes.get("thongtinHoSoId");

		if (thongtinHoSoId != null) {
			setThongtinHoSoId(thongtinHoSoId);
		}

		Long gplienvanID = (Long)attributes.get("gplienvanID");

		if (gplienvanID != null) {
			setGplienvanID(gplienvanID);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getThongtinHoSoId() {
		return _thongtinHoSoId;
	}

	@Override
	public void setThongtinHoSoId(long thongtinHoSoId) {
		_thongtinHoSoId = thongtinHoSoId;
	}

	@JSON
	@Override
	public long getGplienvanID() {
		return _gplienvanID;
	}

	@Override
	public void setGplienvanID(long gplienvanID) {
		_gplienvanID = gplienvanID;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtThongTinHoSoLienVan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtThongTinHoSoLienVan toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtThongTinHoSoLienVan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtThongTinHoSoLienVanImpl qlvtThongTinHoSoLienVanImpl = new QlvtThongTinHoSoLienVanImpl();

		qlvtThongTinHoSoLienVanImpl.setId(getId());
		qlvtThongTinHoSoLienVanImpl.setThongtinHoSoId(getThongtinHoSoId());
		qlvtThongTinHoSoLienVanImpl.setGplienvanID(getGplienvanID());

		qlvtThongTinHoSoLienVanImpl.resetOriginalValues();

		return qlvtThongTinHoSoLienVanImpl;
	}

	@Override
	public int compareTo(QlvtThongTinHoSoLienVan qlvtThongTinHoSoLienVan) {
		int value = 0;

		if (getId() < qlvtThongTinHoSoLienVan.getId()) {
			value = -1;
		}
		else if (getId() > qlvtThongTinHoSoLienVan.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtThongTinHoSoLienVan)) {
			return false;
		}

		QlvtThongTinHoSoLienVan qlvtThongTinHoSoLienVan = (QlvtThongTinHoSoLienVan)obj;

		long primaryKey = qlvtThongTinHoSoLienVan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QlvtThongTinHoSoLienVan> toCacheModel() {
		QlvtThongTinHoSoLienVanCacheModel qlvtThongTinHoSoLienVanCacheModel = new QlvtThongTinHoSoLienVanCacheModel();

		qlvtThongTinHoSoLienVanCacheModel.id = getId();

		qlvtThongTinHoSoLienVanCacheModel.thongtinHoSoId = getThongtinHoSoId();

		qlvtThongTinHoSoLienVanCacheModel.gplienvanID = getGplienvanID();

		return qlvtThongTinHoSoLienVanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thongtinHoSoId=");
		sb.append(getThongtinHoSoId());
		sb.append(", gplienvanID=");
		sb.append(getGplienvanID());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.nghiepvu.model.QlvtThongTinHoSoLienVan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongtinHoSoId</column-name><column-value><![CDATA[");
		sb.append(getThongtinHoSoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gplienvanID</column-name><column-value><![CDATA[");
		sb.append(getGplienvanID());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtThongTinHoSoLienVan.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtThongTinHoSoLienVan.class
		};
	private long _id;
	private long _thongtinHoSoId;
	private long _gplienvanID;
	private QlvtThongTinHoSoLienVan _escapedModel;
}