/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.lienvan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QlvtCapPhepGplvPhuongTien service. Represents a row in the &quot;qlvt_capphep_gplienvan_phuongtien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.lienvan.model.impl.QlvtCapPhepGplvPhuongTienModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.lienvan.model.impl.QlvtCapPhepGplvPhuongTienImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtCapPhepGplvPhuongTien
 * @see vn.dtt.duongbo.dao.lienvan.model.impl.QlvtCapPhepGplvPhuongTienImpl
 * @see vn.dtt.duongbo.dao.lienvan.model.impl.QlvtCapPhepGplvPhuongTienModelImpl
 * @generated
 */
public interface QlvtCapPhepGplvPhuongTienModel extends BaseModel<QlvtCapPhepGplvPhuongTien> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt cap phep gplv phuong tien model instance should use the {@link QlvtCapPhepGplvPhuongTien} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the primary key of this qlvt cap phep gplv phuong tien
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt cap phep gplv phuong tien.
	 *
	 * @param primaryKey the primary key of this qlvt cap phep gplv phuong tien
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the ID of this qlvt cap phep gplv phuong tien
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt cap phep gplv phuong tien.
	 *
	 * @param id the ID of this qlvt cap phep gplv phuong tien
	 */
	public void setId(long id);

	/**
	 * Returns the giay phep lien van ID of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the giay phep lien van ID of this qlvt cap phep gplv phuong tien
	 */
	public long getGiayPhepLienVanId();

	/**
	 * Sets the giay phep lien van ID of this qlvt cap phep gplv phuong tien.
	 *
	 * @param giayPhepLienVanId the giay phep lien van ID of this qlvt cap phep gplv phuong tien
	 */
	public void setGiayPhepLienVanId(long giayPhepLienVanId);

	/**
	 * Returns the so phu hieu of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the so phu hieu of this qlvt cap phep gplv phuong tien
	 */
	@AutoEscape
	public String getSoPhuHieu();

	/**
	 * Sets the so phu hieu of this qlvt cap phep gplv phuong tien.
	 *
	 * @param soPhuHieu the so phu hieu of this qlvt cap phep gplv phuong tien
	 */
	public void setSoPhuHieu(String soPhuHieu);

	/**
	 * Returns the ngay cap phep of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the ngay cap phep of this qlvt cap phep gplv phuong tien
	 */
	public Date getNgayCapPhep();

	/**
	 * Sets the ngay cap phep of this qlvt cap phep gplv phuong tien.
	 *
	 * @param ngayCapPhep the ngay cap phep of this qlvt cap phep gplv phuong tien
	 */
	public void setNgayCapPhep(Date ngayCapPhep);

	/**
	 * Returns the ngay gia han of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the ngay gia han of this qlvt cap phep gplv phuong tien
	 */
	public Date getNgayGiaHan();

	/**
	 * Sets the ngay gia han of this qlvt cap phep gplv phuong tien.
	 *
	 * @param ngayGiaHan the ngay gia han of this qlvt cap phep gplv phuong tien
	 */
	public void setNgayGiaHan(Date ngayGiaHan);

	/**
	 * Returns the ngay het han of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the ngay het han of this qlvt cap phep gplv phuong tien
	 */
	public Date getNgayHetHan();

	/**
	 * Sets the ngay het han of this qlvt cap phep gplv phuong tien.
	 *
	 * @param ngayHetHan the ngay het han of this qlvt cap phep gplv phuong tien
	 */
	public void setNgayHetHan(Date ngayHetHan);

	/**
	 * Returns the cua khau of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the cua khau of this qlvt cap phep gplv phuong tien
	 */
	@AutoEscape
	public String getCuaKhau();

	/**
	 * Sets the cua khau of this qlvt cap phep gplv phuong tien.
	 *
	 * @param cuaKhau the cua khau of this qlvt cap phep gplv phuong tien
	 */
	public void setCuaKhau(String cuaKhau);

	/**
	 * Returns the ma cua khau of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the ma cua khau of this qlvt cap phep gplv phuong tien
	 */
	@AutoEscape
	public String getMaCuaKhau();

	/**
	 * Sets the ma cua khau of this qlvt cap phep gplv phuong tien.
	 *
	 * @param maCuaKhau the ma cua khau of this qlvt cap phep gplv phuong tien
	 */
	public void setMaCuaKhau(String maCuaKhau);

	/**
	 * Returns the hinh thuc hoat dong of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the hinh thuc hoat dong of this qlvt cap phep gplv phuong tien
	 */
	@AutoEscape
	public String getHinhThucHoatDong();

	/**
	 * Sets the hinh thuc hoat dong of this qlvt cap phep gplv phuong tien.
	 *
	 * @param hinhThucHoatDong the hinh thuc hoat dong of this qlvt cap phep gplv phuong tien
	 */
	public void setHinhThucHoatDong(String hinhThucHoatDong);

	/**
	 * Returns the thoi han phu hieu of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the thoi han phu hieu of this qlvt cap phep gplv phuong tien
	 */
	public Date getThoiHanPhuHieu();

	/**
	 * Sets the thoi han phu hieu of this qlvt cap phep gplv phuong tien.
	 *
	 * @param thoiHanPhuHieu the thoi han phu hieu of this qlvt cap phep gplv phuong tien
	 */
	public void setThoiHanPhuHieu(Date thoiHanPhuHieu);

	/**
	 * Returns the so huu of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the so huu of this qlvt cap phep gplv phuong tien
	 */
	public int getSoHuu();

	/**
	 * Sets the so huu of this qlvt cap phep gplv phuong tien.
	 *
	 * @param soHuu the so huu of this qlvt cap phep gplv phuong tien
	 */
	public void setSoHuu(int soHuu);

	/**
	 * Returns the chu so huu of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the chu so huu of this qlvt cap phep gplv phuong tien
	 */
	@AutoEscape
	public String getChuSoHuu();

	/**
	 * Sets the chu so huu of this qlvt cap phep gplv phuong tien.
	 *
	 * @param chuSoHuu the chu so huu of this qlvt cap phep gplv phuong tien
	 */
	public void setChuSoHuu(String chuSoHuu);

	/**
	 * Returns the thoi han cho thue of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the thoi han cho thue of this qlvt cap phep gplv phuong tien
	 */
	public Date getThoiHanChoThue();

	/**
	 * Sets the thoi han cho thue of this qlvt cap phep gplv phuong tien.
	 *
	 * @param thoiHanChoThue the thoi han cho thue of this qlvt cap phep gplv phuong tien
	 */
	public void setThoiHanChoThue(Date thoiHanChoThue);

	/**
	 * Returns the hop dong sau cung of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the hop dong sau cung of this qlvt cap phep gplv phuong tien
	 */
	public int getHopDongSauCung();

	/**
	 * Sets the hop dong sau cung of this qlvt cap phep gplv phuong tien.
	 *
	 * @param hopDongSauCung the hop dong sau cung of this qlvt cap phep gplv phuong tien
	 */
	public void setHopDongSauCung(int hopDongSauCung);

	/**
	 * Returns the muc phi of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the muc phi of this qlvt cap phep gplv phuong tien
	 */
	@AutoEscape
	public String getMucPhi();

	/**
	 * Sets the muc phi of this qlvt cap phep gplv phuong tien.
	 *
	 * @param mucPhi the muc phi of this qlvt cap phep gplv phuong tien
	 */
	public void setMucPhi(String mucPhi);

	/**
	 * Returns the thong tin xu ly vi pham of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the thong tin xu ly vi pham of this qlvt cap phep gplv phuong tien
	 */
	@AutoEscape
	public String getThongTinXuLyViPham();

	/**
	 * Sets the thong tin xu ly vi pham of this qlvt cap phep gplv phuong tien.
	 *
	 * @param thongTinXuLyViPham the thong tin xu ly vi pham of this qlvt cap phep gplv phuong tien
	 */
	public void setThongTinXuLyViPham(String thongTinXuLyViPham);

	/**
	 * Returns the trang thai of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the trang thai of this qlvt cap phep gplv phuong tien
	 */
	@AutoEscape
	public String getTrangThai();

	/**
	 * Sets the trang thai of this qlvt cap phep gplv phuong tien.
	 *
	 * @param trangThai the trang thai of this qlvt cap phep gplv phuong tien
	 */
	public void setTrangThai(String trangThai);

	/**
	 * Returns the file ID of this qlvt cap phep gplv phuong tien.
	 *
	 * @return the file ID of this qlvt cap phep gplv phuong tien
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this qlvt cap phep gplv phuong tien.
	 *
	 * @param fileId the file ID of this qlvt cap phep gplv phuong tien
	 */
	public void setFileId(long fileId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtCapPhepGplvPhuongTien qlvtCapPhepGplvPhuongTien);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtCapPhepGplvPhuongTien> toCacheModel();

	@Override
	public QlvtCapPhepGplvPhuongTien toEscapedModel();

	@Override
	public QlvtCapPhepGplvPhuongTien toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}