/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.lienvan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QlvtCapPhepGpLienVan service. Represents a row in the &quot;qlvt_capphep_gplienvan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.lienvan.model.impl.QlvtCapPhepGpLienVanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.lienvan.model.impl.QlvtCapPhepGpLienVanImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtCapPhepGpLienVan
 * @see vn.dtt.duongbo.dao.lienvan.model.impl.QlvtCapPhepGpLienVanImpl
 * @see vn.dtt.duongbo.dao.lienvan.model.impl.QlvtCapPhepGpLienVanModelImpl
 * @generated
 */
public interface QlvtCapPhepGpLienVanModel extends BaseModel<QlvtCapPhepGpLienVan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt cap phep gp lien van model instance should use the {@link QlvtCapPhepGpLienVan} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt cap phep gp lien van.
	 *
	 * @return the primary key of this qlvt cap phep gp lien van
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt cap phep gp lien van.
	 *
	 * @param primaryKey the primary key of this qlvt cap phep gp lien van
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt cap phep gp lien van.
	 *
	 * @return the ID of this qlvt cap phep gp lien van
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt cap phep gp lien van.
	 *
	 * @param id the ID of this qlvt cap phep gp lien van
	 */
	public void setId(long id);

	/**
	 * Returns the gpkdvt viet lao ID of this qlvt cap phep gp lien van.
	 *
	 * @return the gpkdvt viet lao ID of this qlvt cap phep gp lien van
	 */
	public long getGpkdvtVietLaoId();

	/**
	 * Sets the gpkdvt viet lao ID of this qlvt cap phep gp lien van.
	 *
	 * @param gpkdvtVietLaoId the gpkdvt viet lao ID of this qlvt cap phep gp lien van
	 */
	public void setGpkdvtVietLaoId(long gpkdvtVietLaoId);

	/**
	 * Returns the loai cap phep of this qlvt cap phep gp lien van.
	 *
	 * @return the loai cap phep of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getLoaiCapPhep();

	/**
	 * Sets the loai cap phep of this qlvt cap phep gp lien van.
	 *
	 * @param loaiCapPhep the loai cap phep of this qlvt cap phep gp lien van
	 */
	public void setLoaiCapPhep(String loaiCapPhep);

	/**
	 * Returns the loai giay phep lien van of this qlvt cap phep gp lien van.
	 *
	 * @return the loai giay phep lien van of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getLoaiGiayPhepLienVan();

	/**
	 * Sets the loai giay phep lien van of this qlvt cap phep gp lien van.
	 *
	 * @param loaiGiayPhepLienVan the loai giay phep lien van of this qlvt cap phep gp lien van
	 */
	public void setLoaiGiayPhepLienVan(String loaiGiayPhepLienVan);

	/**
	 * Returns the so giay phep lien van of this qlvt cap phep gp lien van.
	 *
	 * @return the so giay phep lien van of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getSoGiayPhepLienVan();

	/**
	 * Sets the so giay phep lien van of this qlvt cap phep gp lien van.
	 *
	 * @param soGiayPhepLienVan the so giay phep lien van of this qlvt cap phep gp lien van
	 */
	public void setSoGiayPhepLienVan(String soGiayPhepLienVan);

	/**
	 * Returns the ngay cap gplv of this qlvt cap phep gp lien van.
	 *
	 * @return the ngay cap gplv of this qlvt cap phep gp lien van
	 */
	public Date getNgayCapGplv();

	/**
	 * Sets the ngay cap gplv of this qlvt cap phep gp lien van.
	 *
	 * @param ngayCapGplv the ngay cap gplv of this qlvt cap phep gp lien van
	 */
	public void setNgayCapGplv(Date ngayCapGplv);

	/**
	 * Returns the ngay het han gplv of this qlvt cap phep gp lien van.
	 *
	 * @return the ngay het han gplv of this qlvt cap phep gp lien van
	 */
	public Date getNgayHetHanGplv();

	/**
	 * Sets the ngay het han gplv of this qlvt cap phep gp lien van.
	 *
	 * @param ngayHetHanGplv the ngay het han gplv of this qlvt cap phep gp lien van
	 */
	public void setNgayHetHanGplv(Date ngayHetHanGplv);

	/**
	 * Returns the co quan cp lien van of this qlvt cap phep gp lien van.
	 *
	 * @return the co quan cp lien van of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getCoQuanCpLienVan();

	/**
	 * Sets the co quan cp lien van of this qlvt cap phep gp lien van.
	 *
	 * @param coQuanCpLienVan the co quan cp lien van of this qlvt cap phep gp lien van
	 */
	public void setCoQuanCpLienVan(String coQuanCpLienVan);

	/**
	 * Returns the so cong van chap thuan t c d of this qlvt cap phep gp lien van.
	 *
	 * @return the so cong van chap thuan t c d of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getSoCongVanChapThuanTCD();

	/**
	 * Sets the so cong van chap thuan t c d of this qlvt cap phep gp lien van.
	 *
	 * @param soCongVanChapThuanTCD the so cong van chap thuan t c d of this qlvt cap phep gp lien van
	 */
	public void setSoCongVanChapThuanTCD(String soCongVanChapThuanTCD);

	/**
	 * Returns the ngay cong van chap thuan t c d of this qlvt cap phep gp lien van.
	 *
	 * @return the ngay cong van chap thuan t c d of this qlvt cap phep gp lien van
	 */
	public Date getNgayCongVanChapThuanTCD();

	/**
	 * Sets the ngay cong van chap thuan t c d of this qlvt cap phep gp lien van.
	 *
	 * @param ngayCongVanChapThuanTCD the ngay cong van chap thuan t c d of this qlvt cap phep gp lien van
	 */
	public void setNgayCongVanChapThuanTCD(Date ngayCongVanChapThuanTCD);

	/**
	 * Returns the tuyen tu of this qlvt cap phep gp lien van.
	 *
	 * @return the tuyen tu of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getTuyenTu();

	/**
	 * Sets the tuyen tu of this qlvt cap phep gp lien van.
	 *
	 * @param tuyenTu the tuyen tu of this qlvt cap phep gp lien van
	 */
	public void setTuyenTu(String tuyenTu);

	/**
	 * Returns the tuyen di of this qlvt cap phep gp lien van.
	 *
	 * @return the tuyen di of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getTuyenDi();

	/**
	 * Sets the tuyen di of this qlvt cap phep gp lien van.
	 *
	 * @param tuyenDi the tuyen di of this qlvt cap phep gp lien van
	 */
	public void setTuyenDi(String tuyenDi);

	/**
	 * Returns the cu ly of this qlvt cap phep gp lien van.
	 *
	 * @return the cu ly of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getCuLy();

	/**
	 * Sets the cu ly of this qlvt cap phep gp lien van.
	 *
	 * @param cuLy the cu ly of this qlvt cap phep gp lien van
	 */
	public void setCuLy(String cuLy);

	/**
	 * Returns the ma ben di of this qlvt cap phep gp lien van.
	 *
	 * @return the ma ben di of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getMaBenDi();

	/**
	 * Sets the ma ben di of this qlvt cap phep gp lien van.
	 *
	 * @param maBenDi the ma ben di of this qlvt cap phep gp lien van
	 */
	public void setMaBenDi(String maBenDi);

	/**
	 * Returns the ma ben den of this qlvt cap phep gp lien van.
	 *
	 * @return the ma ben den of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getMaBenDen();

	/**
	 * Sets the ma ben den of this qlvt cap phep gp lien van.
	 *
	 * @param maBenDen the ma ben den of this qlvt cap phep gp lien van
	 */
	public void setMaBenDen(String maBenDen);

	/**
	 * Returns the ma tinh di of this qlvt cap phep gp lien van.
	 *
	 * @return the ma tinh di of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getMaTinhDi();

	/**
	 * Sets the ma tinh di of this qlvt cap phep gp lien van.
	 *
	 * @param maTinhDi the ma tinh di of this qlvt cap phep gp lien van
	 */
	public void setMaTinhDi(String maTinhDi);

	/**
	 * Returns the ma tinh den of this qlvt cap phep gp lien van.
	 *
	 * @return the ma tinh den of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getMaTinhDen();

	/**
	 * Sets the ma tinh den of this qlvt cap phep gp lien van.
	 *
	 * @param maTinhDen the ma tinh den of this qlvt cap phep gp lien van
	 */
	public void setMaTinhDen(String maTinhDen);

	/**
	 * Returns the hanh trinh of this qlvt cap phep gp lien van.
	 *
	 * @return the hanh trinh of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getHanhTrinh();

	/**
	 * Sets the hanh trinh of this qlvt cap phep gp lien van.
	 *
	 * @param hanhTrinh the hanh trinh of this qlvt cap phep gp lien van
	 */
	public void setHanhTrinh(String hanhTrinh);

	/**
	 * Returns the muc phi of this qlvt cap phep gp lien van.
	 *
	 * @return the muc phi of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getMucPhi();

	/**
	 * Sets the muc phi of this qlvt cap phep gp lien van.
	 *
	 * @param mucPhi the muc phi of this qlvt cap phep gp lien van
	 */
	public void setMucPhi(String mucPhi);

	/**
	 * Returns the muc dich chuyen di of this qlvt cap phep gp lien van.
	 *
	 * @return the muc dich chuyen di of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getMucDichChuyenDi();

	/**
	 * Sets the muc dich chuyen di of this qlvt cap phep gp lien van.
	 *
	 * @param mucDichChuyenDi the muc dich chuyen di of this qlvt cap phep gp lien van
	 */
	public void setMucDichChuyenDi(String mucDichChuyenDi);

	/**
	 * Returns the file ID of this qlvt cap phep gp lien van.
	 *
	 * @return the file ID of this qlvt cap phep gp lien van
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this qlvt cap phep gp lien van.
	 *
	 * @param fileId the file ID of this qlvt cap phep gp lien van
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the trang thai of this qlvt cap phep gp lien van.
	 *
	 * @return the trang thai of this qlvt cap phep gp lien van
	 */
	@AutoEscape
	public String getTrangThai();

	/**
	 * Sets the trang thai of this qlvt cap phep gp lien van.
	 *
	 * @param trangThai the trang thai of this qlvt cap phep gp lien van
	 */
	public void setTrangThai(String trangThai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtCapPhepGpLienVan qlvtCapPhepGpLienVan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtCapPhepGpLienVan> toCacheModel();

	@Override
	public QlvtCapPhepGpLienVan toEscapedModel();

	@Override
	public QlvtCapPhepGpLienVan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}