/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QLVTCapPhepPhuHieuTuyen service. Represents a row in the &quot;qlvt_capphep_phuhieuxe_tuyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTCapPhepPhuHieuTuyenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTCapPhepPhuHieuTuyenImpl}.
 * </p>
 *
 * @author binhta
 * @see QLVTCapPhepPhuHieuTuyen
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTCapPhepPhuHieuTuyenImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTCapPhepPhuHieuTuyenModelImpl
 * @generated
 */
public interface QLVTCapPhepPhuHieuTuyenModel extends BaseModel<QLVTCapPhepPhuHieuTuyen> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a q l v t cap phep phu hieu tuyen model instance should use the {@link QLVTCapPhepPhuHieuTuyen} interface instead.
	 */

	/**
	 * Returns the primary key of this q l v t cap phep phu hieu tuyen.
	 *
	 * @return the primary key of this q l v t cap phep phu hieu tuyen
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this q l v t cap phep phu hieu tuyen.
	 *
	 * @param primaryKey the primary key of this q l v t cap phep phu hieu tuyen
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this q l v t cap phep phu hieu tuyen.
	 *
	 * @return the ID of this q l v t cap phep phu hieu tuyen
	 */
	public int getId();

	/**
	 * Sets the ID of this q l v t cap phep phu hieu tuyen.
	 *
	 * @param id the ID of this q l v t cap phep phu hieu tuyen
	 */
	public void setId(int id);

	/**
	 * Returns the pt cap phu hieu ID of this q l v t cap phep phu hieu tuyen.
	 *
	 * @return the pt cap phu hieu ID of this q l v t cap phep phu hieu tuyen
	 */
	public int getPtCapPhuHieuId();

	/**
	 * Sets the pt cap phu hieu ID of this q l v t cap phep phu hieu tuyen.
	 *
	 * @param ptCapPhuHieuId the pt cap phu hieu ID of this q l v t cap phep phu hieu tuyen
	 */
	public void setPtCapPhuHieuId(int ptCapPhuHieuId);

	/**
	 * Returns the ma tuyen of this q l v t cap phep phu hieu tuyen.
	 *
	 * @return the ma tuyen of this q l v t cap phep phu hieu tuyen
	 */
	@AutoEscape
	public String getMaTuyen();

	/**
	 * Sets the ma tuyen of this q l v t cap phep phu hieu tuyen.
	 *
	 * @param maTuyen the ma tuyen of this q l v t cap phep phu hieu tuyen
	 */
	public void setMaTuyen(String maTuyen);

	/**
	 * Returns the ten tuyen of this q l v t cap phep phu hieu tuyen.
	 *
	 * @return the ten tuyen of this q l v t cap phep phu hieu tuyen
	 */
	@AutoEscape
	public String getTenTuyen();

	/**
	 * Sets the ten tuyen of this q l v t cap phep phu hieu tuyen.
	 *
	 * @param tenTuyen the ten tuyen of this q l v t cap phep phu hieu tuyen
	 */
	public void setTenTuyen(String tenTuyen);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QLVTCapPhepPhuHieuTuyen qlvtCapPhepPhuHieuTuyen);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QLVTCapPhepPhuHieuTuyen> toCacheModel();

	@Override
	public QLVTCapPhepPhuHieuTuyen toEscapedModel();

	@Override
	public QLVTCapPhepPhuHieuTuyen toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}