/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QLVTXuLyBienHieu service. Represents a row in the &quot;qlvt_xuly_bienhieu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyBienHieuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyBienHieuImpl}.
 * </p>
 *
 * @author binhta
 * @see QLVTXuLyBienHieu
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyBienHieuImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyBienHieuModelImpl
 * @generated
 */
public interface QLVTXuLyBienHieuModel extends BaseModel<QLVTXuLyBienHieu> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a q l v t xu ly bien hieu model instance should use the {@link QLVTXuLyBienHieu} interface instead.
	 */

	/**
	 * Returns the primary key of this q l v t xu ly bien hieu.
	 *
	 * @return the primary key of this q l v t xu ly bien hieu
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this q l v t xu ly bien hieu.
	 *
	 * @param primaryKey the primary key of this q l v t xu ly bien hieu
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this q l v t xu ly bien hieu.
	 *
	 * @return the ID of this q l v t xu ly bien hieu
	 */
	public int getId();

	/**
	 * Sets the ID of this q l v t xu ly bien hieu.
	 *
	 * @param id the ID of this q l v t xu ly bien hieu
	 */
	public void setId(int id);

	/**
	 * Returns the thong tin xu ly ID of this q l v t xu ly bien hieu.
	 *
	 * @return the thong tin xu ly ID of this q l v t xu ly bien hieu
	 */
	public int getThongTinXuLyId();

	/**
	 * Sets the thong tin xu ly ID of this q l v t xu ly bien hieu.
	 *
	 * @param thongTinXuLyId the thong tin xu ly ID of this q l v t xu ly bien hieu
	 */
	public void setThongTinXuLyId(int thongTinXuLyId);

	/**
	 * Returns the linh vuc kinh doanh of this q l v t xu ly bien hieu.
	 *
	 * @return the linh vuc kinh doanh of this q l v t xu ly bien hieu
	 */
	@AutoEscape
	public String getLinhVucKinhDoanh();

	/**
	 * Sets the linh vuc kinh doanh of this q l v t xu ly bien hieu.
	 *
	 * @param LinhVucKinhDoanh the linh vuc kinh doanh of this q l v t xu ly bien hieu
	 */
	public void setLinhVucKinhDoanh(String LinhVucKinhDoanh);

	/**
	 * Returns the ly do cap lai of this q l v t xu ly bien hieu.
	 *
	 * @return the ly do cap lai of this q l v t xu ly bien hieu
	 */
	@AutoEscape
	public String getLyDoCapLai();

	/**
	 * Sets the ly do cap lai of this q l v t xu ly bien hieu.
	 *
	 * @param lyDoCapLai the ly do cap lai of this q l v t xu ly bien hieu
	 */
	public void setLyDoCapLai(String lyDoCapLai);

	/**
	 * Returns the gpkd luu hanh quoc te of this q l v t xu ly bien hieu.
	 *
	 * @return the gpkd luu hanh quoc te of this q l v t xu ly bien hieu
	 */
	@AutoEscape
	public String getGpkdLuuHanhQuocTe();

	/**
	 * Sets the gpkd luu hanh quoc te of this q l v t xu ly bien hieu.
	 *
	 * @param gpkdLuuHanhQuocTe the gpkd luu hanh quoc te of this q l v t xu ly bien hieu
	 */
	public void setGpkdLuuHanhQuocTe(String gpkdLuuHanhQuocTe);

	/**
	 * Returns the gpkd luu hanh quoc te c q c a p of this q l v t xu ly bien hieu.
	 *
	 * @return the gpkd luu hanh quoc te c q c a p of this q l v t xu ly bien hieu
	 */
	@AutoEscape
	public String getGpkdLuuHanhQuocTeCQCAP();

	/**
	 * Sets the gpkd luu hanh quoc te c q c a p of this q l v t xu ly bien hieu.
	 *
	 * @param gpkdLuuHanhQuocTeCQCAP the gpkd luu hanh quoc te c q c a p of this q l v t xu ly bien hieu
	 */
	public void setGpkdLuuHanhQuocTeCQCAP(String gpkdLuuHanhQuocTeCQCAP);

	/**
	 * Returns the gpkd luu hanh quoc te ngay cap of this q l v t xu ly bien hieu.
	 *
	 * @return the gpkd luu hanh quoc te ngay cap of this q l v t xu ly bien hieu
	 */
	public Date getGpkdLuuHanhQuocTeNgayCap();

	/**
	 * Sets the gpkd luu hanh quoc te ngay cap of this q l v t xu ly bien hieu.
	 *
	 * @param gpkdLuuHanhQuocTeNgayCap the gpkd luu hanh quoc te ngay cap of this q l v t xu ly bien hieu
	 */
	public void setGpkdLuuHanhQuocTeNgayCap(Date gpkdLuuHanhQuocTeNgayCap);

	/**
	 * Returns the gpkd luu hanh quoc te ngay het han of this q l v t xu ly bien hieu.
	 *
	 * @return the gpkd luu hanh quoc te ngay het han of this q l v t xu ly bien hieu
	 */
	public Date getGpkdLuuHanhQuocTeNgayHetHan();

	/**
	 * Sets the gpkd luu hanh quoc te ngay het han of this q l v t xu ly bien hieu.
	 *
	 * @param gpkdLuuHanhQuocTeNgayHetHan the gpkd luu hanh quoc te ngay het han of this q l v t xu ly bien hieu
	 */
	public void setGpkdLuuHanhQuocTeNgayHetHan(Date gpkdLuuHanhQuocTeNgayHetHan);

	/**
	 * Returns the so luong xe of this q l v t xu ly bien hieu.
	 *
	 * @return the so luong xe of this q l v t xu ly bien hieu
	 */
	@AutoEscape
	public String getSoLuongXe();

	/**
	 * Sets the so luong xe of this q l v t xu ly bien hieu.
	 *
	 * @param soLuongXe the so luong xe of this q l v t xu ly bien hieu
	 */
	public void setSoLuongXe(String soLuongXe);

	/**
	 * Returns the so luong b h p h nop lai of this q l v t xu ly bien hieu.
	 *
	 * @return the so luong b h p h nop lai of this q l v t xu ly bien hieu
	 */
	public int getSoLuongBHPHNopLai();

	/**
	 * Sets the so luong b h p h nop lai of this q l v t xu ly bien hieu.
	 *
	 * @param soLuongBHPHNopLai the so luong b h p h nop lai of this q l v t xu ly bien hieu
	 */
	public void setSoLuongBHPHNopLai(int soLuongBHPHNopLai);

	/**
	 * Returns the lap cap of this q l v t xu ly bien hieu.
	 *
	 * @return the lap cap of this q l v t xu ly bien hieu
	 */
	public int getLapCap();

	/**
	 * Sets the lap cap of this q l v t xu ly bien hieu.
	 *
	 * @param lapCap the lap cap of this q l v t xu ly bien hieu
	 */
	public void setLapCap(int lapCap);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QLVTXuLyBienHieu qlvtXuLyBienHieu);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QLVTXuLyBienHieu> toCacheModel();

	@Override
	public QLVTXuLyBienHieu toEscapedModel();

	@Override
	public QLVTXuLyBienHieu toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}