/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QLVTCapPhepBienHieuPhuongTien service. Represents a row in the &quot;qlvt_capphep_bienhieu_qlvt_phuongtienvantai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTCapPhepBienHieuPhuongTienModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTCapPhepBienHieuPhuongTienImpl}.
 * </p>
 *
 * @author binhta
 * @see QLVTCapPhepBienHieuPhuongTien
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTCapPhepBienHieuPhuongTienImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTCapPhepBienHieuPhuongTienModelImpl
 * @generated
 */
public interface QLVTCapPhepBienHieuPhuongTienModel extends BaseModel<QLVTCapPhepBienHieuPhuongTien> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a q l v t cap phep bien hieu phuong tien model instance should use the {@link QLVTCapPhepBienHieuPhuongTien} interface instead.
	 */

	/**
	 * Returns the primary key of this q l v t cap phep bien hieu phuong tien.
	 *
	 * @return the primary key of this q l v t cap phep bien hieu phuong tien
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this q l v t cap phep bien hieu phuong tien.
	 *
	 * @param primaryKey the primary key of this q l v t cap phep bien hieu phuong tien
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this q l v t cap phep bien hieu phuong tien.
	 *
	 * @return the ID of this q l v t cap phep bien hieu phuong tien
	 */
	public int getId();

	/**
	 * Sets the ID of this q l v t cap phep bien hieu phuong tien.
	 *
	 * @param id the ID of this q l v t cap phep bien hieu phuong tien
	 */
	public void setId(int id);

	/**
	 * Returns the qlvt cap hep bien hieu ID of this q l v t cap phep bien hieu phuong tien.
	 *
	 * @return the qlvt cap hep bien hieu ID of this q l v t cap phep bien hieu phuong tien
	 */
	public int getQlvtCapHepBienHieuId();

	/**
	 * Sets the qlvt cap hep bien hieu ID of this q l v t cap phep bien hieu phuong tien.
	 *
	 * @param qlvtCapHepBienHieuId the qlvt cap hep bien hieu ID of this q l v t cap phep bien hieu phuong tien
	 */
	public void setQlvtCapHepBienHieuId(int qlvtCapHepBienHieuId);

	/**
	 * Returns the qlvt phuong tien van tai ID of this q l v t cap phep bien hieu phuong tien.
	 *
	 * @return the qlvt phuong tien van tai ID of this q l v t cap phep bien hieu phuong tien
	 */
	public int getQlvtPhuongTienVanTaiId();

	/**
	 * Sets the qlvt phuong tien van tai ID of this q l v t cap phep bien hieu phuong tien.
	 *
	 * @param qlvtPhuongTienVanTaiId the qlvt phuong tien van tai ID of this q l v t cap phep bien hieu phuong tien
	 */
	public void setQlvtPhuongTienVanTaiId(int qlvtPhuongTienVanTaiId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		QLVTCapPhepBienHieuPhuongTien qlvtCapPhepBienHieuPhuongTien);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QLVTCapPhepBienHieuPhuongTien> toCacheModel();

	@Override
	public QLVTCapPhepBienHieuPhuongTien toEscapedModel();

	@Override
	public QLVTCapPhepBienHieuPhuongTien toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}