/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QLVTXuLyPhuHieu service. Represents a row in the &quot;qlvt_xuly_phuhieu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyPhuHieuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyPhuHieuImpl}.
 * </p>
 *
 * @author binhta
 * @see QLVTXuLyPhuHieu
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyPhuHieuImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl.QLVTXuLyPhuHieuModelImpl
 * @generated
 */
public interface QLVTXuLyPhuHieuModel extends BaseModel<QLVTXuLyPhuHieu> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a q l v t xu ly phu hieu model instance should use the {@link QLVTXuLyPhuHieu} interface instead.
	 */

	/**
	 * Returns the primary key of this q l v t xu ly phu hieu.
	 *
	 * @return the primary key of this q l v t xu ly phu hieu
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this q l v t xu ly phu hieu.
	 *
	 * @param primaryKey the primary key of this q l v t xu ly phu hieu
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this q l v t xu ly phu hieu.
	 *
	 * @return the ID of this q l v t xu ly phu hieu
	 */
	public int getId();

	/**
	 * Sets the ID of this q l v t xu ly phu hieu.
	 *
	 * @param id the ID of this q l v t xu ly phu hieu
	 */
	public void setId(int id);

	/**
	 * Returns the so luong b h p h nop lai of this q l v t xu ly phu hieu.
	 *
	 * @return the so luong b h p h nop lai of this q l v t xu ly phu hieu
	 */
	public int getSoLuongBHPHNopLai();

	/**
	 * Sets the so luong b h p h nop lai of this q l v t xu ly phu hieu.
	 *
	 * @param soLuongBHPHNopLai the so luong b h p h nop lai of this q l v t xu ly phu hieu
	 */
	public void setSoLuongBHPHNopLai(int soLuongBHPHNopLai);

	/**
	 * Returns the so luong bien hieu of this q l v t xu ly phu hieu.
	 *
	 * @return the so luong bien hieu of this q l v t xu ly phu hieu
	 */
	public int getSoLuongBienHieu();

	/**
	 * Sets the so luong bien hieu of this q l v t xu ly phu hieu.
	 *
	 * @param soLuongBienHieu the so luong bien hieu of this q l v t xu ly phu hieu
	 */
	public void setSoLuongBienHieu(int soLuongBienHieu);

	/**
	 * Returns the thong tin xu ly ID of this q l v t xu ly phu hieu.
	 *
	 * @return the thong tin xu ly ID of this q l v t xu ly phu hieu
	 */
	public int getThongTinXuLyId();

	/**
	 * Sets the thong tin xu ly ID of this q l v t xu ly phu hieu.
	 *
	 * @param thongTinXuLyId the thong tin xu ly ID of this q l v t xu ly phu hieu
	 */
	public void setThongTinXuLyId(int thongTinXuLyId);

	/**
	 * Returns the loai phu hieu of this q l v t xu ly phu hieu.
	 *
	 * @return the loai phu hieu of this q l v t xu ly phu hieu
	 */
	@AutoEscape
	public String getLoaiPhuHieu();

	/**
	 * Sets the loai phu hieu of this q l v t xu ly phu hieu.
	 *
	 * @param loaiPhuHieu the loai phu hieu of this q l v t xu ly phu hieu
	 */
	public void setLoaiPhuHieu(String loaiPhuHieu);

	/**
	 * Returns the so luong of this q l v t xu ly phu hieu.
	 *
	 * @return the so luong of this q l v t xu ly phu hieu
	 */
	public int getSoLuong();

	/**
	 * Sets the so luong of this q l v t xu ly phu hieu.
	 *
	 * @param soLuong the so luong of this q l v t xu ly phu hieu
	 */
	public void setSoLuong(int soLuong);

	/**
	 * Returns the so luong b h_ p h nop lai of this q l v t xu ly phu hieu.
	 *
	 * @return the so luong b h_ p h nop lai of this q l v t xu ly phu hieu
	 */
	public int getSoLuongBH_PHNopLai();

	/**
	 * Sets the so luong b h_ p h nop lai of this q l v t xu ly phu hieu.
	 *
	 * @param soLuongBH_PHNopLai the so luong b h_ p h nop lai of this q l v t xu ly phu hieu
	 */
	public void setSoLuongBH_PHNopLai(int soLuongBH_PHNopLai);

	/**
	 * Returns the sovb chap nhan tuyen of this q l v t xu ly phu hieu.
	 *
	 * @return the sovb chap nhan tuyen of this q l v t xu ly phu hieu
	 */
	@AutoEscape
	public String getSovbChapNhanTuyen();

	/**
	 * Sets the sovb chap nhan tuyen of this q l v t xu ly phu hieu.
	 *
	 * @param sovbChapNhanTuyen the sovb chap nhan tuyen of this q l v t xu ly phu hieu
	 */
	public void setSovbChapNhanTuyen(String sovbChapNhanTuyen);

	/**
	 * Returns the ngay cap v b chap nhan tuyen of this q l v t xu ly phu hieu.
	 *
	 * @return the ngay cap v b chap nhan tuyen of this q l v t xu ly phu hieu
	 */
	public Date getNgayCapVBChapNhanTuyen();

	/**
	 * Sets the ngay cap v b chap nhan tuyen of this q l v t xu ly phu hieu.
	 *
	 * @param ngayCapVBChapNhanTuyen the ngay cap v b chap nhan tuyen of this q l v t xu ly phu hieu
	 */
	public void setNgayCapVBChapNhanTuyen(Date ngayCapVBChapNhanTuyen);

	/**
	 * Returns the lan cap of this q l v t xu ly phu hieu.
	 *
	 * @return the lan cap of this q l v t xu ly phu hieu
	 */
	public int getLanCap();

	/**
	 * Sets the lan cap of this q l v t xu ly phu hieu.
	 *
	 * @param lanCap the lan cap of this q l v t xu ly phu hieu
	 */
	public void setLanCap(int lanCap);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QLVTXuLyPhuHieu qlvtXuLyPhuHieu);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QLVTXuLyPhuHieu> toCacheModel();

	@Override
	public QLVTXuLyPhuHieu toEscapedModel();

	@Override
	public QLVTXuLyPhuHieu toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}