/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbien.dao.vrcb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmGoods service. Represents a row in the &quot;DM_GOODS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbien.dao.vrcb.model.impl.DmGoodsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbien.dao.vrcb.model.impl.DmGoodsImpl}.
 * </p>
 *
 * @author longdm
 * @see DmGoods
 * @see vn.dtt.duongbien.dao.vrcb.model.impl.DmGoodsImpl
 * @see vn.dtt.duongbien.dao.vrcb.model.impl.DmGoodsModelImpl
 * @generated
 */
public interface DmGoodsModel extends BaseModel<DmGoods> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm goods model instance should use the {@link DmGoods} interface instead.
	 */

	/**
	 * Returns the primary key of this dm goods.
	 *
	 * @return the primary key of this dm goods
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this dm goods.
	 *
	 * @param primaryKey the primary key of this dm goods
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this dm goods.
	 *
	 * @return the ID of this dm goods
	 */
	public int getId();

	/**
	 * Sets the ID of this dm goods.
	 *
	 * @param id the ID of this dm goods
	 */
	public void setId(int id);

	/**
	 * Returns the goods item code of this dm goods.
	 *
	 * @return the goods item code of this dm goods
	 */
	@AutoEscape
	public String getGoodsItemCode();

	/**
	 * Sets the goods item code of this dm goods.
	 *
	 * @param goodsItemCode the goods item code of this dm goods
	 */
	public void setGoodsItemCode(String goodsItemCode);

	/**
	 * Returns the goods item name of this dm goods.
	 *
	 * @return the goods item name of this dm goods
	 */
	@AutoEscape
	public String getGoodsItemName();

	/**
	 * Sets the goods item name of this dm goods.
	 *
	 * @param goodsItemName the goods item name of this dm goods
	 */
	public void setGoodsItemName(String goodsItemName);

	/**
	 * Returns the goods item name v n of this dm goods.
	 *
	 * @return the goods item name v n of this dm goods
	 */
	@AutoEscape
	public String getGoodsItemNameVN();

	/**
	 * Sets the goods item name v n of this dm goods.
	 *
	 * @param goodsItemNameVN the goods item name v n of this dm goods
	 */
	public void setGoodsItemNameVN(String goodsItemNameVN);

	/**
	 * Returns the goods item order of this dm goods.
	 *
	 * @return the goods item order of this dm goods
	 */
	public int getGoodsItemOrder();

	/**
	 * Sets the goods item order of this dm goods.
	 *
	 * @param goodsItemOrder the goods item order of this dm goods
	 */
	public void setGoodsItemOrder(int goodsItemOrder);

	/**
	 * Returns the is delete of this dm goods.
	 *
	 * @return the is delete of this dm goods
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm goods.
	 *
	 * @param isDelete the is delete of this dm goods
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm goods.
	 *
	 * @return the marked as delete of this dm goods
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm goods.
	 *
	 * @param markedAsDelete the marked as delete of this dm goods
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm goods.
	 *
	 * @return the modified date of this dm goods
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm goods.
	 *
	 * @param modifiedDate the modified date of this dm goods
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm goods.
	 *
	 * @return the requested date of this dm goods
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm goods.
	 *
	 * @param requestedDate the requested date of this dm goods
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm goods.
	 *
	 * @return the sync version of this dm goods
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm goods.
	 *
	 * @param syncVersion the sync version of this dm goods
	 */
	public void setSyncVersion(String syncVersion);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DmGoods dmGoods);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DmGoods> toCacheModel();

	@Override
	public DmGoods toEscapedModel();

	@Override
	public DmGoods toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}