/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbien.dao.vrcb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmGtOrganization service. Represents a row in the &quot;DM_GT_ORGANIZATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbien.dao.vrcb.model.impl.DmGtOrganizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbien.dao.vrcb.model.impl.DmGtOrganizationImpl}.
 * </p>
 *
 * @author longdm
 * @see DmGtOrganization
 * @see vn.dtt.duongbien.dao.vrcb.model.impl.DmGtOrganizationImpl
 * @see vn.dtt.duongbien.dao.vrcb.model.impl.DmGtOrganizationModelImpl
 * @generated
 */
public interface DmGtOrganizationModel extends BaseModel<DmGtOrganization> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm gt organization model instance should use the {@link DmGtOrganization} interface instead.
	 */

	/**
	 * Returns the primary key of this dm gt organization.
	 *
	 * @return the primary key of this dm gt organization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dm gt organization.
	 *
	 * @param primaryKey the primary key of this dm gt organization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dm gt organization.
	 *
	 * @return the ID of this dm gt organization
	 */
	public long getId();

	/**
	 * Sets the ID of this dm gt organization.
	 *
	 * @param id the ID of this dm gt organization
	 */
	public void setId(long id);

	/**
	 * Returns the organization code of this dm gt organization.
	 *
	 * @return the organization code of this dm gt organization
	 */
	@AutoEscape
	public String getOrganizationCode();

	/**
	 * Sets the organization code of this dm gt organization.
	 *
	 * @param organizationCode the organization code of this dm gt organization
	 */
	public void setOrganizationCode(String organizationCode);

	/**
	 * Returns the organization name of this dm gt organization.
	 *
	 * @return the organization name of this dm gt organization
	 */
	@AutoEscape
	public String getOrganizationName();

	/**
	 * Sets the organization name of this dm gt organization.
	 *
	 * @param organizationName the organization name of this dm gt organization
	 */
	public void setOrganizationName(String organizationName);

	/**
	 * Returns the organization name v n of this dm gt organization.
	 *
	 * @return the organization name v n of this dm gt organization
	 */
	@AutoEscape
	public String getOrganizationNameVN();

	/**
	 * Sets the organization name v n of this dm gt organization.
	 *
	 * @param organizationNameVN the organization name v n of this dm gt organization
	 */
	public void setOrganizationNameVN(String organizationNameVN);

	/**
	 * Returns the organizationorder of this dm gt organization.
	 *
	 * @return the organizationorder of this dm gt organization
	 */
	public int getOrganizationorder();

	/**
	 * Sets the organizationorder of this dm gt organization.
	 *
	 * @param organizationorder the organizationorder of this dm gt organization
	 */
	public void setOrganizationorder(int organizationorder);

	/**
	 * Returns the is delete of this dm gt organization.
	 *
	 * @return the is delete of this dm gt organization
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm gt organization.
	 *
	 * @param isDelete the is delete of this dm gt organization
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm gt organization.
	 *
	 * @return the marked as delete of this dm gt organization
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm gt organization.
	 *
	 * @param markedAsDelete the marked as delete of this dm gt organization
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm gt organization.
	 *
	 * @return the modified date of this dm gt organization
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm gt organization.
	 *
	 * @param modifiedDate the modified date of this dm gt organization
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm gt organization.
	 *
	 * @return the requested date of this dm gt organization
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm gt organization.
	 *
	 * @param requestedDate the requested date of this dm gt organization
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm gt organization.
	 *
	 * @return the sync version of this dm gt organization
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm gt organization.
	 *
	 * @param syncVersion the sync version of this dm gt organization
	 */
	public void setSyncVersion(String syncVersion);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DmGtOrganization dmGtOrganization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DmGtOrganization> toCacheModel();

	@Override
	public DmGtOrganization toEscapedModel();

	@Override
	public DmGtOrganization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}