/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbien.dao.vrcb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ResponseBo service. Represents a row in the &quot;responsebo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbien.dao.vrcb.model.impl.ResponseBoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbien.dao.vrcb.model.impl.ResponseBoImpl}.
 * </p>
 *
 * @author longdm
 * @see ResponseBo
 * @see vn.dtt.duongbien.dao.vrcb.model.impl.ResponseBoImpl
 * @see vn.dtt.duongbien.dao.vrcb.model.impl.ResponseBoModelImpl
 * @generated
 */
public interface ResponseBoModel extends BaseModel<ResponseBo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a response bo model instance should use the {@link ResponseBo} interface instead.
	 */

	/**
	 * Returns the primary key of this response bo.
	 *
	 * @return the primary key of this response bo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this response bo.
	 *
	 * @param primaryKey the primary key of this response bo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this response bo.
	 *
	 * @return the ID of this response bo
	 */
	public long getId();

	/**
	 * Sets the ID of this response bo.
	 *
	 * @param id the ID of this response bo
	 */
	public void setId(long id);

	/**
	 * Returns the is success of this response bo.
	 *
	 * @return the is success of this response bo
	 */
	public int getIsSuccess();

	/**
	 * Sets the is success of this response bo.
	 *
	 * @param isSuccess the is success of this response bo
	 */
	public void setIsSuccess(int isSuccess);

	/**
	 * Returns the error message of this response bo.
	 *
	 * @return the error message of this response bo
	 */
	@AutoEscape
	public String getErrorMessage();

	/**
	 * Sets the error message of this response bo.
	 *
	 * @param errorMessage the error message of this response bo
	 */
	public void setErrorMessage(String errorMessage);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ResponseBo responseBo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ResponseBo> toCacheModel();

	@Override
	public ResponseBo toEscapedModel();

	@Override
	public ResponseBo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}