/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbien.dao.vrcb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TempShipStoresItems service. Represents a row in the &quot;TEMP_SHIP_STORES_ITEMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbien.dao.vrcb.model.impl.TempShipStoresItemsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbien.dao.vrcb.model.impl.TempShipStoresItemsImpl}.
 * </p>
 *
 * @author longdm
 * @see TempShipStoresItems
 * @see vn.dtt.duongbien.dao.vrcb.model.impl.TempShipStoresItemsImpl
 * @see vn.dtt.duongbien.dao.vrcb.model.impl.TempShipStoresItemsModelImpl
 * @generated
 */
public interface TempShipStoresItemsModel extends BaseModel<TempShipStoresItems> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp ship stores items model instance should use the {@link TempShipStoresItems} interface instead.
	 */

	/**
	 * Returns the primary key of this temp ship stores items.
	 *
	 * @return the primary key of this temp ship stores items
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp ship stores items.
	 *
	 * @param primaryKey the primary key of this temp ship stores items
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp ship stores items.
	 *
	 * @return the ID of this temp ship stores items
	 */
	public long getId();

	/**
	 * Sets the ID of this temp ship stores items.
	 *
	 * @param id the ID of this temp ship stores items
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp ship stores items.
	 *
	 * @return the request code of this temp ship stores items
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp ship stores items.
	 *
	 * @param requestCode the request code of this temp ship stores items
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the shipsstore item code of this temp ship stores items.
	 *
	 * @return the shipsstore item code of this temp ship stores items
	 */
	@AutoEscape
	public String getShipsstoreItemCode();

	/**
	 * Sets the shipsstore item code of this temp ship stores items.
	 *
	 * @param shipsstoreItemCode the shipsstore item code of this temp ship stores items
	 */
	public void setShipsstoreItemCode(String shipsstoreItemCode);

	/**
	 * Returns the name of article of this temp ship stores items.
	 *
	 * @return the name of article of this temp ship stores items
	 */
	@AutoEscape
	public String getNameOfArticle();

	/**
	 * Sets the name of article of this temp ship stores items.
	 *
	 * @param nameOfArticle the name of article of this temp ship stores items
	 */
	public void setNameOfArticle(String nameOfArticle);

	/**
	 * Returns the quantity of this temp ship stores items.
	 *
	 * @return the quantity of this temp ship stores items
	 */
	@AutoEscape
	public String getQuantity();

	/**
	 * Sets the quantity of this temp ship stores items.
	 *
	 * @param quantity the quantity of this temp ship stores items
	 */
	public void setQuantity(String quantity);

	/**
	 * Returns the quantity unit of this temp ship stores items.
	 *
	 * @return the quantity unit of this temp ship stores items
	 */
	@AutoEscape
	public String getQuantityUnit();

	/**
	 * Sets the quantity unit of this temp ship stores items.
	 *
	 * @param quantityUnit the quantity unit of this temp ship stores items
	 */
	public void setQuantityUnit(String quantityUnit);

	/**
	 * Returns the location on boat of this temp ship stores items.
	 *
	 * @return the location on boat of this temp ship stores items
	 */
	@AutoEscape
	public String getLocationOnBoat();

	/**
	 * Sets the location on boat of this temp ship stores items.
	 *
	 * @param locationOnBoat the location on boat of this temp ship stores items
	 */
	public void setLocationOnBoat(String locationOnBoat);

	/**
	 * Returns the use in boat of this temp ship stores items.
	 *
	 * @return the use in boat of this temp ship stores items
	 */
	public int getUseInBoat();

	/**
	 * Sets the use in boat of this temp ship stores items.
	 *
	 * @param useInBoat the use in boat of this temp ship stores items
	 */
	public void setUseInBoat(int useInBoat);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TempShipStoresItems tempShipStoresItems);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TempShipStoresItems> toCacheModel();

	@Override
	public TempShipStoresItems toEscapedModel();

	@Override
	public TempShipStoresItems toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}