/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTien;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTienModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the QLVTCapPhepPhuHieuPhuongTien service. Represents a row in the &quot;qlvt_capphep_phuhieuxe_qlvt_phuongtienvantai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTienModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QLVTCapPhepPhuHieuPhuongTienImpl}.
 * </p>
 *
 * @author binhta
 * @see QLVTCapPhepPhuHieuPhuongTienImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTien
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTienModel
 * @generated
 */
public class QLVTCapPhepPhuHieuPhuongTienModelImpl extends BaseModelImpl<QLVTCapPhepPhuHieuPhuongTien>
	implements QLVTCapPhepPhuHieuPhuongTienModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a q l v t cap phep phu hieu phuong tien model instance should use the {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTien} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_capphep_phuhieuxe_qlvt_phuongtienvantai";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "qlvt_capphep_phuhieuxeID", Types.INTEGER },
			{ "qlvt_phuongtienvantaiID", Types.INTEGER },
			{ "TRANGTHAI", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_capphep_phuhieuxe_qlvt_phuongtienvantai (ID INTEGER not null primary key,qlvt_capphep_phuhieuxeID INTEGER,qlvt_phuongtienvantaiID INTEGER,TRANGTHAI VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_capphep_phuhieuxe_qlvt_phuongtienvantai";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtCapPhepPhuHieuPhuongTien.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_capphep_phuhieuxe_qlvt_phuongtienvantai.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTien"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTien"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTien"));

	public QLVTCapPhepPhuHieuPhuongTienModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QLVTCapPhepPhuHieuPhuongTien.class;
	}

	@Override
	public String getModelClassName() {
		return QLVTCapPhepPhuHieuPhuongTien.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("qlvtCapPhepPhuHieuXeId", getQlvtCapPhepPhuHieuXeId());
		attributes.put("qlvtPhuongTienVanTaiId", getQlvtPhuongTienVanTaiId());
		attributes.put("trangThai", getTrangThai());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer qlvtCapPhepPhuHieuXeId = (Integer)attributes.get(
				"qlvtCapPhepPhuHieuXeId");

		if (qlvtCapPhepPhuHieuXeId != null) {
			setQlvtCapPhepPhuHieuXeId(qlvtCapPhepPhuHieuXeId);
		}

		Integer qlvtPhuongTienVanTaiId = (Integer)attributes.get(
				"qlvtPhuongTienVanTaiId");

		if (qlvtPhuongTienVanTaiId != null) {
			setQlvtPhuongTienVanTaiId(qlvtPhuongTienVanTaiId);
		}

		String trangThai = (String)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@Override
	public int getQlvtCapPhepPhuHieuXeId() {
		return _qlvtCapPhepPhuHieuXeId;
	}

	@Override
	public void setQlvtCapPhepPhuHieuXeId(int qlvtCapPhepPhuHieuXeId) {
		_qlvtCapPhepPhuHieuXeId = qlvtCapPhepPhuHieuXeId;
	}

	@Override
	public int getQlvtPhuongTienVanTaiId() {
		return _qlvtPhuongTienVanTaiId;
	}

	@Override
	public void setQlvtPhuongTienVanTaiId(int qlvtPhuongTienVanTaiId) {
		_qlvtPhuongTienVanTaiId = qlvtPhuongTienVanTaiId;
	}

	@Override
	public String getTrangThai() {
		if (_trangThai == null) {
			return StringPool.BLANK;
		}
		else {
			return _trangThai;
		}
	}

	@Override
	public void setTrangThai(String trangThai) {
		_trangThai = trangThai;
	}

	@Override
	public QLVTCapPhepPhuHieuPhuongTien toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QLVTCapPhepPhuHieuPhuongTien)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QLVTCapPhepPhuHieuPhuongTienImpl qlvtCapPhepPhuHieuPhuongTienImpl = new QLVTCapPhepPhuHieuPhuongTienImpl();

		qlvtCapPhepPhuHieuPhuongTienImpl.setId(getId());
		qlvtCapPhepPhuHieuPhuongTienImpl.setQlvtCapPhepPhuHieuXeId(getQlvtCapPhepPhuHieuXeId());
		qlvtCapPhepPhuHieuPhuongTienImpl.setQlvtPhuongTienVanTaiId(getQlvtPhuongTienVanTaiId());
		qlvtCapPhepPhuHieuPhuongTienImpl.setTrangThai(getTrangThai());

		qlvtCapPhepPhuHieuPhuongTienImpl.resetOriginalValues();

		return qlvtCapPhepPhuHieuPhuongTienImpl;
	}

	@Override
	public int compareTo(
		QLVTCapPhepPhuHieuPhuongTien qlvtCapPhepPhuHieuPhuongTien) {
		int primaryKey = qlvtCapPhepPhuHieuPhuongTien.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QLVTCapPhepPhuHieuPhuongTien)) {
			return false;
		}

		QLVTCapPhepPhuHieuPhuongTien qlvtCapPhepPhuHieuPhuongTien = (QLVTCapPhepPhuHieuPhuongTien)obj;

		int primaryKey = qlvtCapPhepPhuHieuPhuongTien.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QLVTCapPhepPhuHieuPhuongTien> toCacheModel() {
		QLVTCapPhepPhuHieuPhuongTienCacheModel qlvtCapPhepPhuHieuPhuongTienCacheModel =
			new QLVTCapPhepPhuHieuPhuongTienCacheModel();

		qlvtCapPhepPhuHieuPhuongTienCacheModel.id = getId();

		qlvtCapPhepPhuHieuPhuongTienCacheModel.qlvtCapPhepPhuHieuXeId = getQlvtCapPhepPhuHieuXeId();

		qlvtCapPhepPhuHieuPhuongTienCacheModel.qlvtPhuongTienVanTaiId = getQlvtPhuongTienVanTaiId();

		qlvtCapPhepPhuHieuPhuongTienCacheModel.trangThai = getTrangThai();

		String trangThai = qlvtCapPhepPhuHieuPhuongTienCacheModel.trangThai;

		if ((trangThai != null) && (trangThai.length() == 0)) {
			qlvtCapPhepPhuHieuPhuongTienCacheModel.trangThai = null;
		}

		return qlvtCapPhepPhuHieuPhuongTienCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", qlvtCapPhepPhuHieuXeId=");
		sb.append(getQlvtCapPhepPhuHieuXeId());
		sb.append(", qlvtPhuongTienVanTaiId=");
		sb.append(getQlvtPhuongTienVanTaiId());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuPhuongTien");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>qlvtCapPhepPhuHieuXeId</column-name><column-value><![CDATA[");
		sb.append(getQlvtCapPhepPhuHieuXeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>qlvtPhuongTienVanTaiId</column-name><column-value><![CDATA[");
		sb.append(getQlvtPhuongTienVanTaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QLVTCapPhepPhuHieuPhuongTien.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QLVTCapPhepPhuHieuPhuongTien.class
		};
	private int _id;
	private int _qlvtCapPhepPhuHieuXeId;
	private int _qlvtPhuongTienVanTaiId;
	private String _trangThai;
	private QLVTCapPhepPhuHieuPhuongTien _escapedModel;
}