/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyen;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyenModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the QLVTCapPhepPhuHieuTuyen service. Represents a row in the &quot;qlvt_capphep_phuhieuxe_tuyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyenModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QLVTCapPhepPhuHieuTuyenImpl}.
 * </p>
 *
 * @author binhta
 * @see QLVTCapPhepPhuHieuTuyenImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyen
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyenModel
 * @generated
 */
public class QLVTCapPhepPhuHieuTuyenModelImpl extends BaseModelImpl<QLVTCapPhepPhuHieuTuyen>
	implements QLVTCapPhepPhuHieuTuyenModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a q l v t cap phep phu hieu tuyen model instance should use the {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyen} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_capphep_phuhieuxe_tuyen";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "PTCAPPHUHIEUID", Types.INTEGER },
			{ "MATUYEN", Types.VARCHAR },
			{ "TENTUYEN", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_capphep_phuhieuxe_tuyen (ID INTEGER not null primary key,PTCAPPHUHIEUID INTEGER,MATUYEN VARCHAR(75) null,TENTUYEN VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_capphep_phuhieuxe_tuyen";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtCapPhepPhuHieuTuyen.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_capphep_phuhieuxe_tuyen.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyen"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyen"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyen"));

	public QLVTCapPhepPhuHieuTuyenModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QLVTCapPhepPhuHieuTuyen.class;
	}

	@Override
	public String getModelClassName() {
		return QLVTCapPhepPhuHieuTuyen.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("ptCapPhuHieuId", getPtCapPhuHieuId());
		attributes.put("maTuyen", getMaTuyen());
		attributes.put("tenTuyen", getTenTuyen());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer ptCapPhuHieuId = (Integer)attributes.get("ptCapPhuHieuId");

		if (ptCapPhuHieuId != null) {
			setPtCapPhuHieuId(ptCapPhuHieuId);
		}

		String maTuyen = (String)attributes.get("maTuyen");

		if (maTuyen != null) {
			setMaTuyen(maTuyen);
		}

		String tenTuyen = (String)attributes.get("tenTuyen");

		if (tenTuyen != null) {
			setTenTuyen(tenTuyen);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@Override
	public int getPtCapPhuHieuId() {
		return _ptCapPhuHieuId;
	}

	@Override
	public void setPtCapPhuHieuId(int ptCapPhuHieuId) {
		_ptCapPhuHieuId = ptCapPhuHieuId;
	}

	@Override
	public String getMaTuyen() {
		if (_maTuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTuyen;
		}
	}

	@Override
	public void setMaTuyen(String maTuyen) {
		_maTuyen = maTuyen;
	}

	@Override
	public String getTenTuyen() {
		if (_tenTuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenTuyen;
		}
	}

	@Override
	public void setTenTuyen(String tenTuyen) {
		_tenTuyen = tenTuyen;
	}

	@Override
	public QLVTCapPhepPhuHieuTuyen toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QLVTCapPhepPhuHieuTuyen)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QLVTCapPhepPhuHieuTuyenImpl qlvtCapPhepPhuHieuTuyenImpl = new QLVTCapPhepPhuHieuTuyenImpl();

		qlvtCapPhepPhuHieuTuyenImpl.setId(getId());
		qlvtCapPhepPhuHieuTuyenImpl.setPtCapPhuHieuId(getPtCapPhuHieuId());
		qlvtCapPhepPhuHieuTuyenImpl.setMaTuyen(getMaTuyen());
		qlvtCapPhepPhuHieuTuyenImpl.setTenTuyen(getTenTuyen());

		qlvtCapPhepPhuHieuTuyenImpl.resetOriginalValues();

		return qlvtCapPhepPhuHieuTuyenImpl;
	}

	@Override
	public int compareTo(QLVTCapPhepPhuHieuTuyen qlvtCapPhepPhuHieuTuyen) {
		int primaryKey = qlvtCapPhepPhuHieuTuyen.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QLVTCapPhepPhuHieuTuyen)) {
			return false;
		}

		QLVTCapPhepPhuHieuTuyen qlvtCapPhepPhuHieuTuyen = (QLVTCapPhepPhuHieuTuyen)obj;

		int primaryKey = qlvtCapPhepPhuHieuTuyen.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QLVTCapPhepPhuHieuTuyen> toCacheModel() {
		QLVTCapPhepPhuHieuTuyenCacheModel qlvtCapPhepPhuHieuTuyenCacheModel = new QLVTCapPhepPhuHieuTuyenCacheModel();

		qlvtCapPhepPhuHieuTuyenCacheModel.id = getId();

		qlvtCapPhepPhuHieuTuyenCacheModel.ptCapPhuHieuId = getPtCapPhuHieuId();

		qlvtCapPhepPhuHieuTuyenCacheModel.maTuyen = getMaTuyen();

		String maTuyen = qlvtCapPhepPhuHieuTuyenCacheModel.maTuyen;

		if ((maTuyen != null) && (maTuyen.length() == 0)) {
			qlvtCapPhepPhuHieuTuyenCacheModel.maTuyen = null;
		}

		qlvtCapPhepPhuHieuTuyenCacheModel.tenTuyen = getTenTuyen();

		String tenTuyen = qlvtCapPhepPhuHieuTuyenCacheModel.tenTuyen;

		if ((tenTuyen != null) && (tenTuyen.length() == 0)) {
			qlvtCapPhepPhuHieuTuyenCacheModel.tenTuyen = null;
		}

		return qlvtCapPhepPhuHieuTuyenCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ptCapPhuHieuId=");
		sb.append(getPtCapPhuHieuId());
		sb.append(", maTuyen=");
		sb.append(getMaTuyen());
		sb.append(", tenTuyen=");
		sb.append(getTenTuyen());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuTuyen");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ptCapPhuHieuId</column-name><column-value><![CDATA[");
		sb.append(getPtCapPhuHieuId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTuyen</column-name><column-value><![CDATA[");
		sb.append(getMaTuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenTuyen</column-name><column-value><![CDATA[");
		sb.append(getTenTuyen());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QLVTCapPhepPhuHieuTuyen.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QLVTCapPhepPhuHieuTuyen.class
		};
	private int _id;
	private int _ptCapPhuHieuId;
	private String _maTuyen;
	private String _tenTuyen;
	private QLVTCapPhepPhuHieuTuyen _escapedModel;
}