/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieu;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the QLVTCapPhepPhuHieu service. Represents a row in the &quot;qlvt_capphep_phuhieuxe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QLVTCapPhepPhuHieuImpl}.
 * </p>
 *
 * @author binhta
 * @see QLVTCapPhepPhuHieuImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieu
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieuModel
 * @generated
 */
public class QLVTCapPhepPhuHieuModelImpl extends BaseModelImpl<QLVTCapPhepPhuHieu>
	implements QLVTCapPhepPhuHieuModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a q l v t cap phep phu hieu model instance should use the {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieu} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_capphep_phuhieuxe";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "THONGTINHOSOID", Types.INTEGER },
			{ "LOAIHINHKINHDOANHID", Types.INTEGER },
			{ "SOPHUHIEU", Types.INTEGER },
			{ "COQUANCAPLANDAUID", Types.INTEGER },
			{ "COQUANCAPPHEPID", Types.INTEGER },
			{ "NGAYCAPPHUHIEU", Types.TIMESTAMP },
			{ "THOIHANPHUHIEU", Types.TIMESTAMP },
			{ "NOISANXUAT", Types.VARCHAR },
			{ "NAMSANXUAT", Types.INTEGER },
			{ "MATUYENCODINH", Types.VARCHAR },
			{ "LOAIPHUHIEU", Types.VARCHAR },
			{ "LANGIAHAN", Types.INTEGER },
			{ "NGAYCAPLANDAU", Types.TIMESTAMP },
			{ "GHICHU", Types.VARCHAR },
			{ "TRANGTHAI", Types.VARCHAR },
			{ "FILEID", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_capphep_phuhieuxe (ID INTEGER not null primary key,THONGTINHOSOID INTEGER,LOAIHINHKINHDOANHID INTEGER,SOPHUHIEU INTEGER,COQUANCAPLANDAUID INTEGER,COQUANCAPPHEPID INTEGER,NGAYCAPPHUHIEU DATE null,THOIHANPHUHIEU DATE null,NOISANXUAT VARCHAR(75) null,NAMSANXUAT INTEGER,MATUYENCODINH VARCHAR(75) null,LOAIPHUHIEU VARCHAR(75) null,LANGIAHAN INTEGER,NGAYCAPLANDAU DATE null,GHICHU VARCHAR(75) null,TRANGTHAI VARCHAR(75) null,FILEID INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_capphep_phuhieuxe";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtCapPhepPhuHieu.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_capphep_phuhieuxe.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieu"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieu"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieu"));

	public QLVTCapPhepPhuHieuModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QLVTCapPhepPhuHieu.class;
	}

	@Override
	public String getModelClassName() {
		return QLVTCapPhepPhuHieu.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thongTinHoSoId", getThongTinHoSoId());
		attributes.put("loaiHinhKinhDoanhId", getLoaiHinhKinhDoanhId());
		attributes.put("soPhuHieu", getSoPhuHieu());
		attributes.put("coQuanCapLanDauId", getCoQuanCapLanDauId());
		attributes.put("CoQuanCapPhepId", getCoQuanCapPhepId());
		attributes.put("ngayCapPhuHieu", getNgayCapPhuHieu());
		attributes.put("thoiHanPhuHieu", getThoiHanPhuHieu());
		attributes.put("noiSanXuat", getNoiSanXuat());
		attributes.put("namSanXuat", getNamSanXuat());
		attributes.put("maTuyenCoDinh", getMaTuyenCoDinh());
		attributes.put("loaiPhuHieu", getLoaiPhuHieu());
		attributes.put("lanGiaHan", getLanGiaHan());
		attributes.put("ngayCapLanDau", getNgayCapLanDau());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("trangThai", getTrangThai());
		attributes.put("fileId", getFileId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer thongTinHoSoId = (Integer)attributes.get("thongTinHoSoId");

		if (thongTinHoSoId != null) {
			setThongTinHoSoId(thongTinHoSoId);
		}

		Integer loaiHinhKinhDoanhId = (Integer)attributes.get(
				"loaiHinhKinhDoanhId");

		if (loaiHinhKinhDoanhId != null) {
			setLoaiHinhKinhDoanhId(loaiHinhKinhDoanhId);
		}

		Integer soPhuHieu = (Integer)attributes.get("soPhuHieu");

		if (soPhuHieu != null) {
			setSoPhuHieu(soPhuHieu);
		}

		Integer coQuanCapLanDauId = (Integer)attributes.get("coQuanCapLanDauId");

		if (coQuanCapLanDauId != null) {
			setCoQuanCapLanDauId(coQuanCapLanDauId);
		}

		Integer CoQuanCapPhepId = (Integer)attributes.get("CoQuanCapPhepId");

		if (CoQuanCapPhepId != null) {
			setCoQuanCapPhepId(CoQuanCapPhepId);
		}

		Date ngayCapPhuHieu = (Date)attributes.get("ngayCapPhuHieu");

		if (ngayCapPhuHieu != null) {
			setNgayCapPhuHieu(ngayCapPhuHieu);
		}

		Date thoiHanPhuHieu = (Date)attributes.get("thoiHanPhuHieu");

		if (thoiHanPhuHieu != null) {
			setThoiHanPhuHieu(thoiHanPhuHieu);
		}

		String noiSanXuat = (String)attributes.get("noiSanXuat");

		if (noiSanXuat != null) {
			setNoiSanXuat(noiSanXuat);
		}

		Integer namSanXuat = (Integer)attributes.get("namSanXuat");

		if (namSanXuat != null) {
			setNamSanXuat(namSanXuat);
		}

		String maTuyenCoDinh = (String)attributes.get("maTuyenCoDinh");

		if (maTuyenCoDinh != null) {
			setMaTuyenCoDinh(maTuyenCoDinh);
		}

		String loaiPhuHieu = (String)attributes.get("loaiPhuHieu");

		if (loaiPhuHieu != null) {
			setLoaiPhuHieu(loaiPhuHieu);
		}

		Integer lanGiaHan = (Integer)attributes.get("lanGiaHan");

		if (lanGiaHan != null) {
			setLanGiaHan(lanGiaHan);
		}

		Date ngayCapLanDau = (Date)attributes.get("ngayCapLanDau");

		if (ngayCapLanDau != null) {
			setNgayCapLanDau(ngayCapLanDau);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		String trangThai = (String)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}

		Integer fileId = (Integer)attributes.get("fileId");

		if (fileId != null) {
			setFileId(fileId);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@Override
	public int getThongTinHoSoId() {
		return _thongTinHoSoId;
	}

	@Override
	public void setThongTinHoSoId(int thongTinHoSoId) {
		_thongTinHoSoId = thongTinHoSoId;
	}

	@Override
	public int getLoaiHinhKinhDoanhId() {
		return _loaiHinhKinhDoanhId;
	}

	@Override
	public void setLoaiHinhKinhDoanhId(int loaiHinhKinhDoanhId) {
		_loaiHinhKinhDoanhId = loaiHinhKinhDoanhId;
	}

	@Override
	public int getSoPhuHieu() {
		return _soPhuHieu;
	}

	@Override
	public void setSoPhuHieu(int soPhuHieu) {
		_soPhuHieu = soPhuHieu;
	}

	@Override
	public int getCoQuanCapLanDauId() {
		return _coQuanCapLanDauId;
	}

	@Override
	public void setCoQuanCapLanDauId(int coQuanCapLanDauId) {
		_coQuanCapLanDauId = coQuanCapLanDauId;
	}

	@Override
	public int getCoQuanCapPhepId() {
		return _CoQuanCapPhepId;
	}

	@Override
	public void setCoQuanCapPhepId(int CoQuanCapPhepId) {
		_CoQuanCapPhepId = CoQuanCapPhepId;
	}

	@Override
	public Date getNgayCapPhuHieu() {
		return _ngayCapPhuHieu;
	}

	@Override
	public void setNgayCapPhuHieu(Date ngayCapPhuHieu) {
		_ngayCapPhuHieu = ngayCapPhuHieu;
	}

	@Override
	public Date getThoiHanPhuHieu() {
		return _thoiHanPhuHieu;
	}

	@Override
	public void setThoiHanPhuHieu(Date thoiHanPhuHieu) {
		_thoiHanPhuHieu = thoiHanPhuHieu;
	}

	@Override
	public String getNoiSanXuat() {
		if (_noiSanXuat == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiSanXuat;
		}
	}

	@Override
	public void setNoiSanXuat(String noiSanXuat) {
		_noiSanXuat = noiSanXuat;
	}

	@Override
	public int getNamSanXuat() {
		return _namSanXuat;
	}

	@Override
	public void setNamSanXuat(int namSanXuat) {
		_namSanXuat = namSanXuat;
	}

	@Override
	public String getMaTuyenCoDinh() {
		if (_maTuyenCoDinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTuyenCoDinh;
		}
	}

	@Override
	public void setMaTuyenCoDinh(String maTuyenCoDinh) {
		_maTuyenCoDinh = maTuyenCoDinh;
	}

	@Override
	public String getLoaiPhuHieu() {
		if (_loaiPhuHieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiPhuHieu;
		}
	}

	@Override
	public void setLoaiPhuHieu(String loaiPhuHieu) {
		_loaiPhuHieu = loaiPhuHieu;
	}

	@Override
	public int getLanGiaHan() {
		return _lanGiaHan;
	}

	@Override
	public void setLanGiaHan(int lanGiaHan) {
		_lanGiaHan = lanGiaHan;
	}

	@Override
	public Date getNgayCapLanDau() {
		return _ngayCapLanDau;
	}

	@Override
	public void setNgayCapLanDau(Date ngayCapLanDau) {
		_ngayCapLanDau = ngayCapLanDau;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public String getTrangThai() {
		if (_trangThai == null) {
			return StringPool.BLANK;
		}
		else {
			return _trangThai;
		}
	}

	@Override
	public void setTrangThai(String trangThai) {
		_trangThai = trangThai;
	}

	@Override
	public int getFileId() {
		return _fileId;
	}

	@Override
	public void setFileId(int fileId) {
		_fileId = fileId;
	}

	@Override
	public QLVTCapPhepPhuHieu toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QLVTCapPhepPhuHieu)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QLVTCapPhepPhuHieuImpl qlvtCapPhepPhuHieuImpl = new QLVTCapPhepPhuHieuImpl();

		qlvtCapPhepPhuHieuImpl.setId(getId());
		qlvtCapPhepPhuHieuImpl.setThongTinHoSoId(getThongTinHoSoId());
		qlvtCapPhepPhuHieuImpl.setLoaiHinhKinhDoanhId(getLoaiHinhKinhDoanhId());
		qlvtCapPhepPhuHieuImpl.setSoPhuHieu(getSoPhuHieu());
		qlvtCapPhepPhuHieuImpl.setCoQuanCapLanDauId(getCoQuanCapLanDauId());
		qlvtCapPhepPhuHieuImpl.setCoQuanCapPhepId(getCoQuanCapPhepId());
		qlvtCapPhepPhuHieuImpl.setNgayCapPhuHieu(getNgayCapPhuHieu());
		qlvtCapPhepPhuHieuImpl.setThoiHanPhuHieu(getThoiHanPhuHieu());
		qlvtCapPhepPhuHieuImpl.setNoiSanXuat(getNoiSanXuat());
		qlvtCapPhepPhuHieuImpl.setNamSanXuat(getNamSanXuat());
		qlvtCapPhepPhuHieuImpl.setMaTuyenCoDinh(getMaTuyenCoDinh());
		qlvtCapPhepPhuHieuImpl.setLoaiPhuHieu(getLoaiPhuHieu());
		qlvtCapPhepPhuHieuImpl.setLanGiaHan(getLanGiaHan());
		qlvtCapPhepPhuHieuImpl.setNgayCapLanDau(getNgayCapLanDau());
		qlvtCapPhepPhuHieuImpl.setGhiChu(getGhiChu());
		qlvtCapPhepPhuHieuImpl.setTrangThai(getTrangThai());
		qlvtCapPhepPhuHieuImpl.setFileId(getFileId());

		qlvtCapPhepPhuHieuImpl.resetOriginalValues();

		return qlvtCapPhepPhuHieuImpl;
	}

	@Override
	public int compareTo(QLVTCapPhepPhuHieu qlvtCapPhepPhuHieu) {
		int primaryKey = qlvtCapPhepPhuHieu.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QLVTCapPhepPhuHieu)) {
			return false;
		}

		QLVTCapPhepPhuHieu qlvtCapPhepPhuHieu = (QLVTCapPhepPhuHieu)obj;

		int primaryKey = qlvtCapPhepPhuHieu.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QLVTCapPhepPhuHieu> toCacheModel() {
		QLVTCapPhepPhuHieuCacheModel qlvtCapPhepPhuHieuCacheModel = new QLVTCapPhepPhuHieuCacheModel();

		qlvtCapPhepPhuHieuCacheModel.id = getId();

		qlvtCapPhepPhuHieuCacheModel.thongTinHoSoId = getThongTinHoSoId();

		qlvtCapPhepPhuHieuCacheModel.loaiHinhKinhDoanhId = getLoaiHinhKinhDoanhId();

		qlvtCapPhepPhuHieuCacheModel.soPhuHieu = getSoPhuHieu();

		qlvtCapPhepPhuHieuCacheModel.coQuanCapLanDauId = getCoQuanCapLanDauId();

		qlvtCapPhepPhuHieuCacheModel.CoQuanCapPhepId = getCoQuanCapPhepId();

		Date ngayCapPhuHieu = getNgayCapPhuHieu();

		if (ngayCapPhuHieu != null) {
			qlvtCapPhepPhuHieuCacheModel.ngayCapPhuHieu = ngayCapPhuHieu.getTime();
		}
		else {
			qlvtCapPhepPhuHieuCacheModel.ngayCapPhuHieu = Long.MIN_VALUE;
		}

		Date thoiHanPhuHieu = getThoiHanPhuHieu();

		if (thoiHanPhuHieu != null) {
			qlvtCapPhepPhuHieuCacheModel.thoiHanPhuHieu = thoiHanPhuHieu.getTime();
		}
		else {
			qlvtCapPhepPhuHieuCacheModel.thoiHanPhuHieu = Long.MIN_VALUE;
		}

		qlvtCapPhepPhuHieuCacheModel.noiSanXuat = getNoiSanXuat();

		String noiSanXuat = qlvtCapPhepPhuHieuCacheModel.noiSanXuat;

		if ((noiSanXuat != null) && (noiSanXuat.length() == 0)) {
			qlvtCapPhepPhuHieuCacheModel.noiSanXuat = null;
		}

		qlvtCapPhepPhuHieuCacheModel.namSanXuat = getNamSanXuat();

		qlvtCapPhepPhuHieuCacheModel.maTuyenCoDinh = getMaTuyenCoDinh();

		String maTuyenCoDinh = qlvtCapPhepPhuHieuCacheModel.maTuyenCoDinh;

		if ((maTuyenCoDinh != null) && (maTuyenCoDinh.length() == 0)) {
			qlvtCapPhepPhuHieuCacheModel.maTuyenCoDinh = null;
		}

		qlvtCapPhepPhuHieuCacheModel.loaiPhuHieu = getLoaiPhuHieu();

		String loaiPhuHieu = qlvtCapPhepPhuHieuCacheModel.loaiPhuHieu;

		if ((loaiPhuHieu != null) && (loaiPhuHieu.length() == 0)) {
			qlvtCapPhepPhuHieuCacheModel.loaiPhuHieu = null;
		}

		qlvtCapPhepPhuHieuCacheModel.lanGiaHan = getLanGiaHan();

		Date ngayCapLanDau = getNgayCapLanDau();

		if (ngayCapLanDau != null) {
			qlvtCapPhepPhuHieuCacheModel.ngayCapLanDau = ngayCapLanDau.getTime();
		}
		else {
			qlvtCapPhepPhuHieuCacheModel.ngayCapLanDau = Long.MIN_VALUE;
		}

		qlvtCapPhepPhuHieuCacheModel.ghiChu = getGhiChu();

		String ghiChu = qlvtCapPhepPhuHieuCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			qlvtCapPhepPhuHieuCacheModel.ghiChu = null;
		}

		qlvtCapPhepPhuHieuCacheModel.trangThai = getTrangThai();

		String trangThai = qlvtCapPhepPhuHieuCacheModel.trangThai;

		if ((trangThai != null) && (trangThai.length() == 0)) {
			qlvtCapPhepPhuHieuCacheModel.trangThai = null;
		}

		qlvtCapPhepPhuHieuCacheModel.fileId = getFileId();

		return qlvtCapPhepPhuHieuCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(35);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thongTinHoSoId=");
		sb.append(getThongTinHoSoId());
		sb.append(", loaiHinhKinhDoanhId=");
		sb.append(getLoaiHinhKinhDoanhId());
		sb.append(", soPhuHieu=");
		sb.append(getSoPhuHieu());
		sb.append(", coQuanCapLanDauId=");
		sb.append(getCoQuanCapLanDauId());
		sb.append(", CoQuanCapPhepId=");
		sb.append(getCoQuanCapPhepId());
		sb.append(", ngayCapPhuHieu=");
		sb.append(getNgayCapPhuHieu());
		sb.append(", thoiHanPhuHieu=");
		sb.append(getThoiHanPhuHieu());
		sb.append(", noiSanXuat=");
		sb.append(getNoiSanXuat());
		sb.append(", namSanXuat=");
		sb.append(getNamSanXuat());
		sb.append(", maTuyenCoDinh=");
		sb.append(getMaTuyenCoDinh());
		sb.append(", loaiPhuHieu=");
		sb.append(getLoaiPhuHieu());
		sb.append(", lanGiaHan=");
		sb.append(getLanGiaHan());
		sb.append(", ngayCapLanDau=");
		sb.append(getNgayCapLanDau());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", fileId=");
		sb.append(getFileId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(55);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTCapPhepPhuHieu");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongTinHoSoId</column-name><column-value><![CDATA[");
		sb.append(getThongTinHoSoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiHinhKinhDoanhId</column-name><column-value><![CDATA[");
		sb.append(getLoaiHinhKinhDoanhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soPhuHieu</column-name><column-value><![CDATA[");
		sb.append(getSoPhuHieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCapLanDauId</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapLanDauId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CoQuanCapPhepId</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapPhepId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapPhuHieu</column-name><column-value><![CDATA[");
		sb.append(getNgayCapPhuHieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thoiHanPhuHieu</column-name><column-value><![CDATA[");
		sb.append(getThoiHanPhuHieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiSanXuat</column-name><column-value><![CDATA[");
		sb.append(getNoiSanXuat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namSanXuat</column-name><column-value><![CDATA[");
		sb.append(getNamSanXuat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTuyenCoDinh</column-name><column-value><![CDATA[");
		sb.append(getMaTuyenCoDinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiPhuHieu</column-name><column-value><![CDATA[");
		sb.append(getLoaiPhuHieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lanGiaHan</column-name><column-value><![CDATA[");
		sb.append(getLanGiaHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapLanDau</column-name><column-value><![CDATA[");
		sb.append(getNgayCapLanDau());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileId</column-name><column-value><![CDATA[");
		sb.append(getFileId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QLVTCapPhepPhuHieu.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QLVTCapPhepPhuHieu.class
		};
	private int _id;
	private int _thongTinHoSoId;
	private int _loaiHinhKinhDoanhId;
	private int _soPhuHieu;
	private int _coQuanCapLanDauId;
	private int _CoQuanCapPhepId;
	private Date _ngayCapPhuHieu;
	private Date _thoiHanPhuHieu;
	private String _noiSanXuat;
	private int _namSanXuat;
	private String _maTuyenCoDinh;
	private String _loaiPhuHieu;
	private int _lanGiaHan;
	private Date _ngayCapLanDau;
	private String _ghiChu;
	private String _trangThai;
	private int _fileId;
	private QLVTCapPhepPhuHieu _escapedModel;
}