/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.capbienhieuphuhieu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTien;
import vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTienModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the QLVTXuLyPhuHieuPhuongTien service. Represents a row in the &quot;qlvt_xuly_phuhieu_phuongtien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTienModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QLVTXuLyPhuHieuPhuongTienImpl}.
 * </p>
 *
 * @author binhta
 * @see QLVTXuLyPhuHieuPhuongTienImpl
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTien
 * @see vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTienModel
 * @generated
 */
public class QLVTXuLyPhuHieuPhuongTienModelImpl extends BaseModelImpl<QLVTXuLyPhuHieuPhuongTien>
	implements QLVTXuLyPhuHieuPhuongTienModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a q l v t xu ly phu hieu phuong tien model instance should use the {@link vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTien} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_xuly_phuhieu_phuongtien";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "CAPPHUHIEU_ID", Types.INTEGER },
			{ "NHANHIEU", Types.VARCHAR },
			{ "BIENSO", Types.VARCHAR },
			{ "TRONGTAI", Types.INTEGER },
			{ "SOCHONGOI", Types.INTEGER },
			{ "NOISANXUAT", Types.VARCHAR },
			{ "NAMSANXUAT", Types.INTEGER },
			{ "MATUYENCODINH", Types.VARCHAR },
			{ "LOAITUYEN", Types.VARCHAR },
			{ "HINHTHUCSOHUUXE", Types.VARCHAR },
			{ "LINHVUCKINHDOANH_XEDULICH", Types.VARCHAR },
			{ "NIENHANSUDUNG_GIAYDANGKIEM", Types.INTEGER },
			{ "NIENHANSUDUNG_ND86", Types.INTEGER },
			{ "DOANHNGHIEPSOHUU_THUE", Types.VARCHAR },
			{ "THOIHANTHUE", Types.TIMESTAMP },
			{ "HOPDONGSAUCUNG", Types.INTEGER },
			{ "KETQUAXULY", Types.VARCHAR },
			{ "SOPHUHIEUDUOCCAP", Types.VARCHAR },
			{ "THOIHANDUOCCAPPHEP", Types.TIMESTAMP },
			{ "LOAIPHUHIEUXINCAP", Types.VARCHAR },
			{ "LYDOKHONGDAT", Types.VARCHAR },
			{ "COGIATRIDEN", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_xuly_phuhieu_phuongtien (ID INTEGER not null primary key,CAPPHUHIEU_ID INTEGER,NHANHIEU VARCHAR(75) null,BIENSO VARCHAR(75) null,TRONGTAI INTEGER,SOCHONGOI INTEGER,NOISANXUAT VARCHAR(75) null,NAMSANXUAT INTEGER,MATUYENCODINH VARCHAR(75) null,LOAITUYEN VARCHAR(75) null,HINHTHUCSOHUUXE VARCHAR(75) null,LINHVUCKINHDOANH_XEDULICH VARCHAR(75) null,NIENHANSUDUNG_GIAYDANGKIEM INTEGER,NIENHANSUDUNG_ND86 INTEGER,DOANHNGHIEPSOHUU_THUE VARCHAR(75) null,THOIHANTHUE DATE null,HOPDONGSAUCUNG INTEGER,KETQUAXULY VARCHAR(75) null,SOPHUHIEUDUOCCAP VARCHAR(75) null,THOIHANDUOCCAPPHEP DATE null,LOAIPHUHIEUXINCAP VARCHAR(75) null,LYDOKHONGDAT VARCHAR(75) null,COGIATRIDEN DATE null)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_xuly_phuhieu_phuongtien";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtXuLyPhuHieuPhuongTien.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_xuly_phuhieu_phuongtien.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTien"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTien"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTien"),
			true);
	public static long CAPPHUHIEUID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTien"));

	public QLVTXuLyPhuHieuPhuongTienModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QLVTXuLyPhuHieuPhuongTien.class;
	}

	@Override
	public String getModelClassName() {
		return QLVTXuLyPhuHieuPhuongTien.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("capPhuHieuID", getCapPhuHieuID());
		attributes.put("nhanHieu", getNhanHieu());
		attributes.put("bienSo", getBienSo());
		attributes.put("trongTai", getTrongTai());
		attributes.put("soChoNgoi", getSoChoNgoi());
		attributes.put("noiSanXuat", getNoiSanXuat());
		attributes.put("namSanXuat", getNamSanXuat());
		attributes.put("maTuyenCoDinh", getMaTuyenCoDinh());
		attributes.put("loaiTuyen", getLoaiTuyen());
		attributes.put("hinhThucSoHuuXe", getHinhThucSoHuuXe());
		attributes.put("linhVucKinhDoanhXeDuLich", getLinhVucKinhDoanhXeDuLich());
		attributes.put("nienHanSuDungGiayDangKiem",
			getNienHanSuDungGiayDangKiem());
		attributes.put("nienHanSuDungND86", getNienHanSuDungND86());
		attributes.put("doanhNghiepSoHuuThue", getDoanhNghiepSoHuuThue());
		attributes.put("thoiHanThue", getThoiHanThue());
		attributes.put("hopDongSauCung", getHopDongSauCung());
		attributes.put("ketQuaXuLy", getKetQuaXuLy());
		attributes.put("soPhuHieuDuocCap", getSoPhuHieuDuocCap());
		attributes.put("thoiHanDuocCapPhep", getThoiHanDuocCapPhep());
		attributes.put("loaiPhuHieuXinCap", getLoaiPhuHieuXinCap());
		attributes.put("lyDoKhongDat", getLyDoKhongDat());
		attributes.put("coGiaTriDen", getCoGiaTriDen());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer capPhuHieuID = (Integer)attributes.get("capPhuHieuID");

		if (capPhuHieuID != null) {
			setCapPhuHieuID(capPhuHieuID);
		}

		String nhanHieu = (String)attributes.get("nhanHieu");

		if (nhanHieu != null) {
			setNhanHieu(nhanHieu);
		}

		String bienSo = (String)attributes.get("bienSo");

		if (bienSo != null) {
			setBienSo(bienSo);
		}

		Integer trongTai = (Integer)attributes.get("trongTai");

		if (trongTai != null) {
			setTrongTai(trongTai);
		}

		Integer soChoNgoi = (Integer)attributes.get("soChoNgoi");

		if (soChoNgoi != null) {
			setSoChoNgoi(soChoNgoi);
		}

		String noiSanXuat = (String)attributes.get("noiSanXuat");

		if (noiSanXuat != null) {
			setNoiSanXuat(noiSanXuat);
		}

		Integer namSanXuat = (Integer)attributes.get("namSanXuat");

		if (namSanXuat != null) {
			setNamSanXuat(namSanXuat);
		}

		String maTuyenCoDinh = (String)attributes.get("maTuyenCoDinh");

		if (maTuyenCoDinh != null) {
			setMaTuyenCoDinh(maTuyenCoDinh);
		}

		String loaiTuyen = (String)attributes.get("loaiTuyen");

		if (loaiTuyen != null) {
			setLoaiTuyen(loaiTuyen);
		}

		String hinhThucSoHuuXe = (String)attributes.get("hinhThucSoHuuXe");

		if (hinhThucSoHuuXe != null) {
			setHinhThucSoHuuXe(hinhThucSoHuuXe);
		}

		String linhVucKinhDoanhXeDuLich = (String)attributes.get(
				"linhVucKinhDoanhXeDuLich");

		if (linhVucKinhDoanhXeDuLich != null) {
			setLinhVucKinhDoanhXeDuLich(linhVucKinhDoanhXeDuLich);
		}

		Integer nienHanSuDungGiayDangKiem = (Integer)attributes.get(
				"nienHanSuDungGiayDangKiem");

		if (nienHanSuDungGiayDangKiem != null) {
			setNienHanSuDungGiayDangKiem(nienHanSuDungGiayDangKiem);
		}

		Integer nienHanSuDungND86 = (Integer)attributes.get("nienHanSuDungND86");

		if (nienHanSuDungND86 != null) {
			setNienHanSuDungND86(nienHanSuDungND86);
		}

		String doanhNghiepSoHuuThue = (String)attributes.get(
				"doanhNghiepSoHuuThue");

		if (doanhNghiepSoHuuThue != null) {
			setDoanhNghiepSoHuuThue(doanhNghiepSoHuuThue);
		}

		Date thoiHanThue = (Date)attributes.get("thoiHanThue");

		if (thoiHanThue != null) {
			setThoiHanThue(thoiHanThue);
		}

		Integer hopDongSauCung = (Integer)attributes.get("hopDongSauCung");

		if (hopDongSauCung != null) {
			setHopDongSauCung(hopDongSauCung);
		}

		String ketQuaXuLy = (String)attributes.get("ketQuaXuLy");

		if (ketQuaXuLy != null) {
			setKetQuaXuLy(ketQuaXuLy);
		}

		String soPhuHieuDuocCap = (String)attributes.get("soPhuHieuDuocCap");

		if (soPhuHieuDuocCap != null) {
			setSoPhuHieuDuocCap(soPhuHieuDuocCap);
		}

		Date thoiHanDuocCapPhep = (Date)attributes.get("thoiHanDuocCapPhep");

		if (thoiHanDuocCapPhep != null) {
			setThoiHanDuocCapPhep(thoiHanDuocCapPhep);
		}

		String loaiPhuHieuXinCap = (String)attributes.get("loaiPhuHieuXinCap");

		if (loaiPhuHieuXinCap != null) {
			setLoaiPhuHieuXinCap(loaiPhuHieuXinCap);
		}

		String lyDoKhongDat = (String)attributes.get("lyDoKhongDat");

		if (lyDoKhongDat != null) {
			setLyDoKhongDat(lyDoKhongDat);
		}

		Date coGiaTriDen = (Date)attributes.get("coGiaTriDen");

		if (coGiaTriDen != null) {
			setCoGiaTriDen(coGiaTriDen);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@Override
	public int getCapPhuHieuID() {
		return _capPhuHieuID;
	}

	@Override
	public void setCapPhuHieuID(int capPhuHieuID) {
		_columnBitmask |= CAPPHUHIEUID_COLUMN_BITMASK;

		if (!_setOriginalCapPhuHieuID) {
			_setOriginalCapPhuHieuID = true;

			_originalCapPhuHieuID = _capPhuHieuID;
		}

		_capPhuHieuID = capPhuHieuID;
	}

	public int getOriginalCapPhuHieuID() {
		return _originalCapPhuHieuID;
	}

	@Override
	public String getNhanHieu() {
		if (_nhanHieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _nhanHieu;
		}
	}

	@Override
	public void setNhanHieu(String nhanHieu) {
		_nhanHieu = nhanHieu;
	}

	@Override
	public String getBienSo() {
		if (_bienSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _bienSo;
		}
	}

	@Override
	public void setBienSo(String bienSo) {
		_bienSo = bienSo;
	}

	@Override
	public int getTrongTai() {
		return _trongTai;
	}

	@Override
	public void setTrongTai(int trongTai) {
		_trongTai = trongTai;
	}

	@Override
	public int getSoChoNgoi() {
		return _soChoNgoi;
	}

	@Override
	public void setSoChoNgoi(int soChoNgoi) {
		_soChoNgoi = soChoNgoi;
	}

	@Override
	public String getNoiSanXuat() {
		if (_noiSanXuat == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiSanXuat;
		}
	}

	@Override
	public void setNoiSanXuat(String noiSanXuat) {
		_noiSanXuat = noiSanXuat;
	}

	@Override
	public int getNamSanXuat() {
		return _namSanXuat;
	}

	@Override
	public void setNamSanXuat(int namSanXuat) {
		_namSanXuat = namSanXuat;
	}

	@Override
	public String getMaTuyenCoDinh() {
		if (_maTuyenCoDinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTuyenCoDinh;
		}
	}

	@Override
	public void setMaTuyenCoDinh(String maTuyenCoDinh) {
		_maTuyenCoDinh = maTuyenCoDinh;
	}

	@Override
	public String getLoaiTuyen() {
		if (_loaiTuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiTuyen;
		}
	}

	@Override
	public void setLoaiTuyen(String loaiTuyen) {
		_loaiTuyen = loaiTuyen;
	}

	@Override
	public String getHinhThucSoHuuXe() {
		if (_hinhThucSoHuuXe == null) {
			return StringPool.BLANK;
		}
		else {
			return _hinhThucSoHuuXe;
		}
	}

	@Override
	public void setHinhThucSoHuuXe(String hinhThucSoHuuXe) {
		_hinhThucSoHuuXe = hinhThucSoHuuXe;
	}

	@Override
	public String getLinhVucKinhDoanhXeDuLich() {
		if (_linhVucKinhDoanhXeDuLich == null) {
			return StringPool.BLANK;
		}
		else {
			return _linhVucKinhDoanhXeDuLich;
		}
	}

	@Override
	public void setLinhVucKinhDoanhXeDuLich(String linhVucKinhDoanhXeDuLich) {
		_linhVucKinhDoanhXeDuLich = linhVucKinhDoanhXeDuLich;
	}

	@Override
	public int getNienHanSuDungGiayDangKiem() {
		return _nienHanSuDungGiayDangKiem;
	}

	@Override
	public void setNienHanSuDungGiayDangKiem(int nienHanSuDungGiayDangKiem) {
		_nienHanSuDungGiayDangKiem = nienHanSuDungGiayDangKiem;
	}

	@Override
	public int getNienHanSuDungND86() {
		return _nienHanSuDungND86;
	}

	@Override
	public void setNienHanSuDungND86(int nienHanSuDungND86) {
		_nienHanSuDungND86 = nienHanSuDungND86;
	}

	@Override
	public String getDoanhNghiepSoHuuThue() {
		if (_doanhNghiepSoHuuThue == null) {
			return StringPool.BLANK;
		}
		else {
			return _doanhNghiepSoHuuThue;
		}
	}

	@Override
	public void setDoanhNghiepSoHuuThue(String doanhNghiepSoHuuThue) {
		_doanhNghiepSoHuuThue = doanhNghiepSoHuuThue;
	}

	@Override
	public Date getThoiHanThue() {
		return _thoiHanThue;
	}

	@Override
	public void setThoiHanThue(Date thoiHanThue) {
		_thoiHanThue = thoiHanThue;
	}

	@Override
	public int getHopDongSauCung() {
		return _hopDongSauCung;
	}

	@Override
	public void setHopDongSauCung(int hopDongSauCung) {
		_hopDongSauCung = hopDongSauCung;
	}

	@Override
	public String getKetQuaXuLy() {
		if (_ketQuaXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ketQuaXuLy;
		}
	}

	@Override
	public void setKetQuaXuLy(String ketQuaXuLy) {
		_ketQuaXuLy = ketQuaXuLy;
	}

	@Override
	public String getSoPhuHieuDuocCap() {
		if (_soPhuHieuDuocCap == null) {
			return StringPool.BLANK;
		}
		else {
			return _soPhuHieuDuocCap;
		}
	}

	@Override
	public void setSoPhuHieuDuocCap(String soPhuHieuDuocCap) {
		_soPhuHieuDuocCap = soPhuHieuDuocCap;
	}

	@Override
	public Date getThoiHanDuocCapPhep() {
		return _thoiHanDuocCapPhep;
	}

	@Override
	public void setThoiHanDuocCapPhep(Date thoiHanDuocCapPhep) {
		_thoiHanDuocCapPhep = thoiHanDuocCapPhep;
	}

	@Override
	public String getLoaiPhuHieuXinCap() {
		if (_loaiPhuHieuXinCap == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiPhuHieuXinCap;
		}
	}

	@Override
	public void setLoaiPhuHieuXinCap(String loaiPhuHieuXinCap) {
		_loaiPhuHieuXinCap = loaiPhuHieuXinCap;
	}

	@Override
	public String getLyDoKhongDat() {
		if (_lyDoKhongDat == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongDat;
		}
	}

	@Override
	public void setLyDoKhongDat(String lyDoKhongDat) {
		_lyDoKhongDat = lyDoKhongDat;
	}

	@Override
	public Date getCoGiaTriDen() {
		return _coGiaTriDen;
	}

	@Override
	public void setCoGiaTriDen(Date coGiaTriDen) {
		_coGiaTriDen = coGiaTriDen;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public QLVTXuLyPhuHieuPhuongTien toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QLVTXuLyPhuHieuPhuongTien)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QLVTXuLyPhuHieuPhuongTienImpl qlvtXuLyPhuHieuPhuongTienImpl = new QLVTXuLyPhuHieuPhuongTienImpl();

		qlvtXuLyPhuHieuPhuongTienImpl.setId(getId());
		qlvtXuLyPhuHieuPhuongTienImpl.setCapPhuHieuID(getCapPhuHieuID());
		qlvtXuLyPhuHieuPhuongTienImpl.setNhanHieu(getNhanHieu());
		qlvtXuLyPhuHieuPhuongTienImpl.setBienSo(getBienSo());
		qlvtXuLyPhuHieuPhuongTienImpl.setTrongTai(getTrongTai());
		qlvtXuLyPhuHieuPhuongTienImpl.setSoChoNgoi(getSoChoNgoi());
		qlvtXuLyPhuHieuPhuongTienImpl.setNoiSanXuat(getNoiSanXuat());
		qlvtXuLyPhuHieuPhuongTienImpl.setNamSanXuat(getNamSanXuat());
		qlvtXuLyPhuHieuPhuongTienImpl.setMaTuyenCoDinh(getMaTuyenCoDinh());
		qlvtXuLyPhuHieuPhuongTienImpl.setLoaiTuyen(getLoaiTuyen());
		qlvtXuLyPhuHieuPhuongTienImpl.setHinhThucSoHuuXe(getHinhThucSoHuuXe());
		qlvtXuLyPhuHieuPhuongTienImpl.setLinhVucKinhDoanhXeDuLich(getLinhVucKinhDoanhXeDuLich());
		qlvtXuLyPhuHieuPhuongTienImpl.setNienHanSuDungGiayDangKiem(getNienHanSuDungGiayDangKiem());
		qlvtXuLyPhuHieuPhuongTienImpl.setNienHanSuDungND86(getNienHanSuDungND86());
		qlvtXuLyPhuHieuPhuongTienImpl.setDoanhNghiepSoHuuThue(getDoanhNghiepSoHuuThue());
		qlvtXuLyPhuHieuPhuongTienImpl.setThoiHanThue(getThoiHanThue());
		qlvtXuLyPhuHieuPhuongTienImpl.setHopDongSauCung(getHopDongSauCung());
		qlvtXuLyPhuHieuPhuongTienImpl.setKetQuaXuLy(getKetQuaXuLy());
		qlvtXuLyPhuHieuPhuongTienImpl.setSoPhuHieuDuocCap(getSoPhuHieuDuocCap());
		qlvtXuLyPhuHieuPhuongTienImpl.setThoiHanDuocCapPhep(getThoiHanDuocCapPhep());
		qlvtXuLyPhuHieuPhuongTienImpl.setLoaiPhuHieuXinCap(getLoaiPhuHieuXinCap());
		qlvtXuLyPhuHieuPhuongTienImpl.setLyDoKhongDat(getLyDoKhongDat());
		qlvtXuLyPhuHieuPhuongTienImpl.setCoGiaTriDen(getCoGiaTriDen());

		qlvtXuLyPhuHieuPhuongTienImpl.resetOriginalValues();

		return qlvtXuLyPhuHieuPhuongTienImpl;
	}

	@Override
	public int compareTo(QLVTXuLyPhuHieuPhuongTien qlvtXuLyPhuHieuPhuongTien) {
		int primaryKey = qlvtXuLyPhuHieuPhuongTien.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QLVTXuLyPhuHieuPhuongTien)) {
			return false;
		}

		QLVTXuLyPhuHieuPhuongTien qlvtXuLyPhuHieuPhuongTien = (QLVTXuLyPhuHieuPhuongTien)obj;

		int primaryKey = qlvtXuLyPhuHieuPhuongTien.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		QLVTXuLyPhuHieuPhuongTienModelImpl qlvtXuLyPhuHieuPhuongTienModelImpl = this;

		qlvtXuLyPhuHieuPhuongTienModelImpl._originalCapPhuHieuID = qlvtXuLyPhuHieuPhuongTienModelImpl._capPhuHieuID;

		qlvtXuLyPhuHieuPhuongTienModelImpl._setOriginalCapPhuHieuID = false;

		qlvtXuLyPhuHieuPhuongTienModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<QLVTXuLyPhuHieuPhuongTien> toCacheModel() {
		QLVTXuLyPhuHieuPhuongTienCacheModel qlvtXuLyPhuHieuPhuongTienCacheModel = new QLVTXuLyPhuHieuPhuongTienCacheModel();

		qlvtXuLyPhuHieuPhuongTienCacheModel.id = getId();

		qlvtXuLyPhuHieuPhuongTienCacheModel.capPhuHieuID = getCapPhuHieuID();

		qlvtXuLyPhuHieuPhuongTienCacheModel.nhanHieu = getNhanHieu();

		String nhanHieu = qlvtXuLyPhuHieuPhuongTienCacheModel.nhanHieu;

		if ((nhanHieu != null) && (nhanHieu.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.nhanHieu = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.bienSo = getBienSo();

		String bienSo = qlvtXuLyPhuHieuPhuongTienCacheModel.bienSo;

		if ((bienSo != null) && (bienSo.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.bienSo = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.trongTai = getTrongTai();

		qlvtXuLyPhuHieuPhuongTienCacheModel.soChoNgoi = getSoChoNgoi();

		qlvtXuLyPhuHieuPhuongTienCacheModel.noiSanXuat = getNoiSanXuat();

		String noiSanXuat = qlvtXuLyPhuHieuPhuongTienCacheModel.noiSanXuat;

		if ((noiSanXuat != null) && (noiSanXuat.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.noiSanXuat = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.namSanXuat = getNamSanXuat();

		qlvtXuLyPhuHieuPhuongTienCacheModel.maTuyenCoDinh = getMaTuyenCoDinh();

		String maTuyenCoDinh = qlvtXuLyPhuHieuPhuongTienCacheModel.maTuyenCoDinh;

		if ((maTuyenCoDinh != null) && (maTuyenCoDinh.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.maTuyenCoDinh = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.loaiTuyen = getLoaiTuyen();

		String loaiTuyen = qlvtXuLyPhuHieuPhuongTienCacheModel.loaiTuyen;

		if ((loaiTuyen != null) && (loaiTuyen.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.loaiTuyen = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.hinhThucSoHuuXe = getHinhThucSoHuuXe();

		String hinhThucSoHuuXe = qlvtXuLyPhuHieuPhuongTienCacheModel.hinhThucSoHuuXe;

		if ((hinhThucSoHuuXe != null) && (hinhThucSoHuuXe.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.hinhThucSoHuuXe = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.linhVucKinhDoanhXeDuLich = getLinhVucKinhDoanhXeDuLich();

		String linhVucKinhDoanhXeDuLich = qlvtXuLyPhuHieuPhuongTienCacheModel.linhVucKinhDoanhXeDuLich;

		if ((linhVucKinhDoanhXeDuLich != null) &&
				(linhVucKinhDoanhXeDuLich.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.linhVucKinhDoanhXeDuLich = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.nienHanSuDungGiayDangKiem = getNienHanSuDungGiayDangKiem();

		qlvtXuLyPhuHieuPhuongTienCacheModel.nienHanSuDungND86 = getNienHanSuDungND86();

		qlvtXuLyPhuHieuPhuongTienCacheModel.doanhNghiepSoHuuThue = getDoanhNghiepSoHuuThue();

		String doanhNghiepSoHuuThue = qlvtXuLyPhuHieuPhuongTienCacheModel.doanhNghiepSoHuuThue;

		if ((doanhNghiepSoHuuThue != null) &&
				(doanhNghiepSoHuuThue.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.doanhNghiepSoHuuThue = null;
		}

		Date thoiHanThue = getThoiHanThue();

		if (thoiHanThue != null) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.thoiHanThue = thoiHanThue.getTime();
		}
		else {
			qlvtXuLyPhuHieuPhuongTienCacheModel.thoiHanThue = Long.MIN_VALUE;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.hopDongSauCung = getHopDongSauCung();

		qlvtXuLyPhuHieuPhuongTienCacheModel.ketQuaXuLy = getKetQuaXuLy();

		String ketQuaXuLy = qlvtXuLyPhuHieuPhuongTienCacheModel.ketQuaXuLy;

		if ((ketQuaXuLy != null) && (ketQuaXuLy.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.ketQuaXuLy = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.soPhuHieuDuocCap = getSoPhuHieuDuocCap();

		String soPhuHieuDuocCap = qlvtXuLyPhuHieuPhuongTienCacheModel.soPhuHieuDuocCap;

		if ((soPhuHieuDuocCap != null) && (soPhuHieuDuocCap.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.soPhuHieuDuocCap = null;
		}

		Date thoiHanDuocCapPhep = getThoiHanDuocCapPhep();

		if (thoiHanDuocCapPhep != null) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.thoiHanDuocCapPhep = thoiHanDuocCapPhep.getTime();
		}
		else {
			qlvtXuLyPhuHieuPhuongTienCacheModel.thoiHanDuocCapPhep = Long.MIN_VALUE;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.loaiPhuHieuXinCap = getLoaiPhuHieuXinCap();

		String loaiPhuHieuXinCap = qlvtXuLyPhuHieuPhuongTienCacheModel.loaiPhuHieuXinCap;

		if ((loaiPhuHieuXinCap != null) && (loaiPhuHieuXinCap.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.loaiPhuHieuXinCap = null;
		}

		qlvtXuLyPhuHieuPhuongTienCacheModel.lyDoKhongDat = getLyDoKhongDat();

		String lyDoKhongDat = qlvtXuLyPhuHieuPhuongTienCacheModel.lyDoKhongDat;

		if ((lyDoKhongDat != null) && (lyDoKhongDat.length() == 0)) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.lyDoKhongDat = null;
		}

		Date coGiaTriDen = getCoGiaTriDen();

		if (coGiaTriDen != null) {
			qlvtXuLyPhuHieuPhuongTienCacheModel.coGiaTriDen = coGiaTriDen.getTime();
		}
		else {
			qlvtXuLyPhuHieuPhuongTienCacheModel.coGiaTriDen = Long.MIN_VALUE;
		}

		return qlvtXuLyPhuHieuPhuongTienCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(47);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", capPhuHieuID=");
		sb.append(getCapPhuHieuID());
		sb.append(", nhanHieu=");
		sb.append(getNhanHieu());
		sb.append(", bienSo=");
		sb.append(getBienSo());
		sb.append(", trongTai=");
		sb.append(getTrongTai());
		sb.append(", soChoNgoi=");
		sb.append(getSoChoNgoi());
		sb.append(", noiSanXuat=");
		sb.append(getNoiSanXuat());
		sb.append(", namSanXuat=");
		sb.append(getNamSanXuat());
		sb.append(", maTuyenCoDinh=");
		sb.append(getMaTuyenCoDinh());
		sb.append(", loaiTuyen=");
		sb.append(getLoaiTuyen());
		sb.append(", hinhThucSoHuuXe=");
		sb.append(getHinhThucSoHuuXe());
		sb.append(", linhVucKinhDoanhXeDuLich=");
		sb.append(getLinhVucKinhDoanhXeDuLich());
		sb.append(", nienHanSuDungGiayDangKiem=");
		sb.append(getNienHanSuDungGiayDangKiem());
		sb.append(", nienHanSuDungND86=");
		sb.append(getNienHanSuDungND86());
		sb.append(", doanhNghiepSoHuuThue=");
		sb.append(getDoanhNghiepSoHuuThue());
		sb.append(", thoiHanThue=");
		sb.append(getThoiHanThue());
		sb.append(", hopDongSauCung=");
		sb.append(getHopDongSauCung());
		sb.append(", ketQuaXuLy=");
		sb.append(getKetQuaXuLy());
		sb.append(", soPhuHieuDuocCap=");
		sb.append(getSoPhuHieuDuocCap());
		sb.append(", thoiHanDuocCapPhep=");
		sb.append(getThoiHanDuocCapPhep());
		sb.append(", loaiPhuHieuXinCap=");
		sb.append(getLoaiPhuHieuXinCap());
		sb.append(", lyDoKhongDat=");
		sb.append(getLyDoKhongDat());
		sb.append(", coGiaTriDen=");
		sb.append(getCoGiaTriDen());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(73);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.duongbo.dao.capbienhieuphuhieu.model.QLVTXuLyPhuHieuPhuongTien");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>capPhuHieuID</column-name><column-value><![CDATA[");
		sb.append(getCapPhuHieuID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhanHieu</column-name><column-value><![CDATA[");
		sb.append(getNhanHieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bienSo</column-name><column-value><![CDATA[");
		sb.append(getBienSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trongTai</column-name><column-value><![CDATA[");
		sb.append(getTrongTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soChoNgoi</column-name><column-value><![CDATA[");
		sb.append(getSoChoNgoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiSanXuat</column-name><column-value><![CDATA[");
		sb.append(getNoiSanXuat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namSanXuat</column-name><column-value><![CDATA[");
		sb.append(getNamSanXuat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTuyenCoDinh</column-name><column-value><![CDATA[");
		sb.append(getMaTuyenCoDinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiTuyen</column-name><column-value><![CDATA[");
		sb.append(getLoaiTuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hinhThucSoHuuXe</column-name><column-value><![CDATA[");
		sb.append(getHinhThucSoHuuXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>linhVucKinhDoanhXeDuLich</column-name><column-value><![CDATA[");
		sb.append(getLinhVucKinhDoanhXeDuLich());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nienHanSuDungGiayDangKiem</column-name><column-value><![CDATA[");
		sb.append(getNienHanSuDungGiayDangKiem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nienHanSuDungND86</column-name><column-value><![CDATA[");
		sb.append(getNienHanSuDungND86());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>doanhNghiepSoHuuThue</column-name><column-value><![CDATA[");
		sb.append(getDoanhNghiepSoHuuThue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thoiHanThue</column-name><column-value><![CDATA[");
		sb.append(getThoiHanThue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hopDongSauCung</column-name><column-value><![CDATA[");
		sb.append(getHopDongSauCung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketQuaXuLy</column-name><column-value><![CDATA[");
		sb.append(getKetQuaXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soPhuHieuDuocCap</column-name><column-value><![CDATA[");
		sb.append(getSoPhuHieuDuocCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thoiHanDuocCapPhep</column-name><column-value><![CDATA[");
		sb.append(getThoiHanDuocCapPhep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiPhuHieuXinCap</column-name><column-value><![CDATA[");
		sb.append(getLoaiPhuHieuXinCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongDat</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongDat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coGiaTriDen</column-name><column-value><![CDATA[");
		sb.append(getCoGiaTriDen());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QLVTXuLyPhuHieuPhuongTien.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QLVTXuLyPhuHieuPhuongTien.class
		};
	private int _id;
	private int _capPhuHieuID;
	private int _originalCapPhuHieuID;
	private boolean _setOriginalCapPhuHieuID;
	private String _nhanHieu;
	private String _bienSo;
	private int _trongTai;
	private int _soChoNgoi;
	private String _noiSanXuat;
	private int _namSanXuat;
	private String _maTuyenCoDinh;
	private String _loaiTuyen;
	private String _hinhThucSoHuuXe;
	private String _linhVucKinhDoanhXeDuLich;
	private int _nienHanSuDungGiayDangKiem;
	private int _nienHanSuDungND86;
	private String _doanhNghiepSoHuuThue;
	private Date _thoiHanThue;
	private int _hopDongSauCung;
	private String _ketQuaXuLy;
	private String _soPhuHieuDuocCap;
	private Date _thoiHanDuocCapPhep;
	private String _loaiPhuHieuXinCap;
	private String _lyDoKhongDat;
	private Date _coGiaTriDen;
	private long _columnBitmask;
	private QLVTXuLyPhuHieuPhuongTien _escapedModel;
}