/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.doanhnghiep.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DnDoanhNghiep service. Represents a row in the &quot;dn_nguoilamthutuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.doanhnghiep.model.impl.DnDoanhNghiepModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.doanhnghiep.model.impl.DnDoanhNghiepImpl}.
 * </p>
 *
 * @author win_64
 * @see DnDoanhNghiep
 * @see vn.dtt.duongbo.dao.doanhnghiep.model.impl.DnDoanhNghiepImpl
 * @see vn.dtt.duongbo.dao.doanhnghiep.model.impl.DnDoanhNghiepModelImpl
 * @generated
 */
public interface DnDoanhNghiepModel extends BaseModel<DnDoanhNghiep> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dn doanh nghiep model instance should use the {@link DnDoanhNghiep} interface instead.
	 */

	/**
	 * Returns the primary key of this dn doanh nghiep.
	 *
	 * @return the primary key of this dn doanh nghiep
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dn doanh nghiep.
	 *
	 * @param primaryKey the primary key of this dn doanh nghiep
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dn doanh nghiep.
	 *
	 * @return the ID of this dn doanh nghiep
	 */
	public long getId();

	/**
	 * Sets the ID of this dn doanh nghiep.
	 *
	 * @param id the ID of this dn doanh nghiep
	 */
	public void setId(long id);

	/**
	 * Returns the ma so doanh nghiep of this dn doanh nghiep.
	 *
	 * @return the ma so doanh nghiep of this dn doanh nghiep
	 */
	@AutoEscape
	public String getMaSoDoanhNghiep();

	/**
	 * Sets the ma so doanh nghiep of this dn doanh nghiep.
	 *
	 * @param maSoDoanhNghiep the ma so doanh nghiep of this dn doanh nghiep
	 */
	public void setMaSoDoanhNghiep(String maSoDoanhNghiep);

	/**
	 * Returns the ten doanh nghiep of this dn doanh nghiep.
	 *
	 * @return the ten doanh nghiep of this dn doanh nghiep
	 */
	@AutoEscape
	public String getTenDoanhNghiep();

	/**
	 * Sets the ten doanh nghiep of this dn doanh nghiep.
	 *
	 * @param tenDoanhNghiep the ten doanh nghiep of this dn doanh nghiep
	 */
	public void setTenDoanhNghiep(String tenDoanhNghiep);

	/**
	 * Returns the dia chi of this dn doanh nghiep.
	 *
	 * @return the dia chi of this dn doanh nghiep
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this dn doanh nghiep.
	 *
	 * @param diaChi the dia chi of this dn doanh nghiep
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the ma tinh thanh of this dn doanh nghiep.
	 *
	 * @return the ma tinh thanh of this dn doanh nghiep
	 */
	@AutoEscape
	public String getMaTinhThanh();

	/**
	 * Sets the ma tinh thanh of this dn doanh nghiep.
	 *
	 * @param maTinhThanh the ma tinh thanh of this dn doanh nghiep
	 */
	public void setMaTinhThanh(String maTinhThanh);

	/**
	 * Returns the ma quan huyen of this dn doanh nghiep.
	 *
	 * @return the ma quan huyen of this dn doanh nghiep
	 */
	@AutoEscape
	public String getMaQuanHuyen();

	/**
	 * Sets the ma quan huyen of this dn doanh nghiep.
	 *
	 * @param maQuanHuyen the ma quan huyen of this dn doanh nghiep
	 */
	public void setMaQuanHuyen(String maQuanHuyen);

	/**
	 * Returns the ma phuong xa of this dn doanh nghiep.
	 *
	 * @return the ma phuong xa of this dn doanh nghiep
	 */
	@AutoEscape
	public String getMaPhuongXa();

	/**
	 * Sets the ma phuong xa of this dn doanh nghiep.
	 *
	 * @param maPhuongXa the ma phuong xa of this dn doanh nghiep
	 */
	public void setMaPhuongXa(String maPhuongXa);

	/**
	 * Returns the dien thoai of this dn doanh nghiep.
	 *
	 * @return the dien thoai of this dn doanh nghiep
	 */
	@AutoEscape
	public String getDienThoai();

	/**
	 * Sets the dien thoai of this dn doanh nghiep.
	 *
	 * @param dienThoai the dien thoai of this dn doanh nghiep
	 */
	public void setDienThoai(String dienThoai);

	/**
	 * Returns the website of this dn doanh nghiep.
	 *
	 * @return the website of this dn doanh nghiep
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this dn doanh nghiep.
	 *
	 * @param website the website of this dn doanh nghiep
	 */
	public void setWebsite(String website);

	/**
	 * Returns the fax of this dn doanh nghiep.
	 *
	 * @return the fax of this dn doanh nghiep
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this dn doanh nghiep.
	 *
	 * @param fax the fax of this dn doanh nghiep
	 */
	public void setFax(String fax);

	/**
	 * Returns the email of this dn doanh nghiep.
	 *
	 * @return the email of this dn doanh nghiep
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this dn doanh nghiep.
	 *
	 * @param email the email of this dn doanh nghiep
	 */
	public void setEmail(String email);

	/**
	 * Returns the master of this dn doanh nghiep.
	 *
	 * @return the master of this dn doanh nghiep
	 */
	public long getMaster();

	/**
	 * Sets the master of this dn doanh nghiep.
	 *
	 * @param master the master of this dn doanh nghiep
	 */
	public void setMaster(long master);

	/**
	 * Returns the ngay dang ki of this dn doanh nghiep.
	 *
	 * @return the ngay dang ki of this dn doanh nghiep
	 */
	public Date getNgayDangKi();

	/**
	 * Sets the ngay dang ki of this dn doanh nghiep.
	 *
	 * @param ngayDangKi the ngay dang ki of this dn doanh nghiep
	 */
	public void setNgayDangKi(Date ngayDangKi);

	/**
	 * Returns the hang tai khoan of this dn doanh nghiep.
	 *
	 * @return the hang tai khoan of this dn doanh nghiep
	 */
	@AutoEscape
	public String getHangTaiKhoan();

	/**
	 * Sets the hang tai khoan of this dn doanh nghiep.
	 *
	 * @param hangTaiKhoan the hang tai khoan of this dn doanh nghiep
	 */
	public void setHangTaiKhoan(String hangTaiKhoan);

	/**
	 * Returns the ma kich hoat of this dn doanh nghiep.
	 *
	 * @return the ma kich hoat of this dn doanh nghiep
	 */
	@AutoEscape
	public String getMaKichHoat();

	/**
	 * Sets the ma kich hoat of this dn doanh nghiep.
	 *
	 * @param maKichHoat the ma kich hoat of this dn doanh nghiep
	 */
	public void setMaKichHoat(String maKichHoat);

	/**
	 * Returns the ngay kich hoat of this dn doanh nghiep.
	 *
	 * @return the ngay kich hoat of this dn doanh nghiep
	 */
	public Date getNgayKichHoat();

	/**
	 * Sets the ngay kich hoat of this dn doanh nghiep.
	 *
	 * @param ngayKichHoat the ngay kich hoat of this dn doanh nghiep
	 */
	public void setNgayKichHoat(Date ngayKichHoat);

	/**
	 * Returns the so dang ky kinh doanh of this dn doanh nghiep.
	 *
	 * @return the so dang ky kinh doanh of this dn doanh nghiep
	 */
	@AutoEscape
	public String getSoDangKyKinhDoanh();

	/**
	 * Sets the so dang ky kinh doanh of this dn doanh nghiep.
	 *
	 * @param soDangKyKinhDoanh the so dang ky kinh doanh of this dn doanh nghiep
	 */
	public void setSoDangKyKinhDoanh(String soDangKyKinhDoanh);

	/**
	 * Returns the ngay cap dk kd of this dn doanh nghiep.
	 *
	 * @return the ngay cap dk kd of this dn doanh nghiep
	 */
	public Date getNgayCapDkKd();

	/**
	 * Sets the ngay cap dk kd of this dn doanh nghiep.
	 *
	 * @param ngayCapDkKd the ngay cap dk kd of this dn doanh nghiep
	 */
	public void setNgayCapDkKd(Date ngayCapDkKd);

	/**
	 * Returns the ngay het han d k k d of this dn doanh nghiep.
	 *
	 * @return the ngay het han d k k d of this dn doanh nghiep
	 */
	public Date getNgayHetHanDKKD();

	/**
	 * Sets the ngay het han d k k d of this dn doanh nghiep.
	 *
	 * @param ngayHetHanDKKD the ngay het han d k k d of this dn doanh nghiep
	 */
	public void setNgayHetHanDKKD(Date ngayHetHanDKKD);

	/**
	 * Returns the co quan cap dk kd of this dn doanh nghiep.
	 *
	 * @return the co quan cap dk kd of this dn doanh nghiep
	 */
	@AutoEscape
	public String getCoQuanCapDkKd();

	/**
	 * Sets the co quan cap dk kd of this dn doanh nghiep.
	 *
	 * @param coQuanCapDkKd the co quan cap dk kd of this dn doanh nghiep
	 */
	public void setCoQuanCapDkKd(String coQuanCapDkKd);

	/**
	 * Returns the loai doanh nghiep of this dn doanh nghiep.
	 *
	 * @return the loai doanh nghiep of this dn doanh nghiep
	 */
	@AutoEscape
	public String getLoaiDoanhNghiep();

	/**
	 * Sets the loai doanh nghiep of this dn doanh nghiep.
	 *
	 * @param loaiDoanhNghiep the loai doanh nghiep of this dn doanh nghiep
	 */
	public void setLoaiDoanhNghiep(String loaiDoanhNghiep);

	/**
	 * Returns the nguoi dai dien of this dn doanh nghiep.
	 *
	 * @return the nguoi dai dien of this dn doanh nghiep
	 */
	@AutoEscape
	public String getNguoiDaiDien();

	/**
	 * Sets the nguoi dai dien of this dn doanh nghiep.
	 *
	 * @param nguoiDaiDien the nguoi dai dien of this dn doanh nghiep
	 */
	public void setNguoiDaiDien(String nguoiDaiDien);

	/**
	 * Returns the so dien thoai nguoi dai dien of this dn doanh nghiep.
	 *
	 * @return the so dien thoai nguoi dai dien of this dn doanh nghiep
	 */
	@AutoEscape
	public String getSoDienThoaiNguoiDaiDien();

	/**
	 * Sets the so dien thoai nguoi dai dien of this dn doanh nghiep.
	 *
	 * @param soDienThoaiNguoiDaiDien the so dien thoai nguoi dai dien of this dn doanh nghiep
	 */
	public void setSoDienThoaiNguoiDaiDien(String soDienThoaiNguoiDaiDien);

	/**
	 * Returns the chuc vu nguoi dai dien of this dn doanh nghiep.
	 *
	 * @return the chuc vu nguoi dai dien of this dn doanh nghiep
	 */
	@AutoEscape
	public String getChucVuNguoiDaiDien();

	/**
	 * Sets the chuc vu nguoi dai dien of this dn doanh nghiep.
	 *
	 * @param chucVuNguoiDaiDien the chuc vu nguoi dai dien of this dn doanh nghiep
	 */
	public void setChucVuNguoiDaiDien(String chucVuNguoiDaiDien);

	/**
	 * Returns the ten tieng anh of this dn doanh nghiep.
	 *
	 * @return the ten tieng anh of this dn doanh nghiep
	 */
	@AutoEscape
	public String getTenTiengAnh();

	/**
	 * Sets the ten tieng anh of this dn doanh nghiep.
	 *
	 * @param tenTiengAnh the ten tieng anh of this dn doanh nghiep
	 */
	public void setTenTiengAnh(String tenTiengAnh);

	/**
	 * Returns the ten viet tat of this dn doanh nghiep.
	 *
	 * @return the ten viet tat of this dn doanh nghiep
	 */
	@AutoEscape
	public String getTenVietTat();

	/**
	 * Sets the ten viet tat of this dn doanh nghiep.
	 *
	 * @param tenVietTat the ten viet tat of this dn doanh nghiep
	 */
	public void setTenVietTat(String tenVietTat);

	/**
	 * Returns the so gpkd van tai bang oto of this dn doanh nghiep.
	 *
	 * @return the so gpkd van tai bang oto of this dn doanh nghiep
	 */
	@AutoEscape
	public String getSoGpkdVanTaiBangOto();

	/**
	 * Sets the so gpkd van tai bang oto of this dn doanh nghiep.
	 *
	 * @param soGpkdVanTaiBangOto the so gpkd van tai bang oto of this dn doanh nghiep
	 */
	public void setSoGpkdVanTaiBangOto(String soGpkdVanTaiBangOto);

	/**
	 * Returns the ngay cap gpkd van tai bang oto of this dn doanh nghiep.
	 *
	 * @return the ngay cap gpkd van tai bang oto of this dn doanh nghiep
	 */
	public Date getNgayCapGpkdVanTaiBangOto();

	/**
	 * Sets the ngay cap gpkd van tai bang oto of this dn doanh nghiep.
	 *
	 * @param ngayCapGpkdVanTaiBangOto the ngay cap gpkd van tai bang oto of this dn doanh nghiep
	 */
	public void setNgayCapGpkdVanTaiBangOto(Date ngayCapGpkdVanTaiBangOto);

	/**
	 * Returns the co quan cap gpkd van tai bang oto of this dn doanh nghiep.
	 *
	 * @return the co quan cap gpkd van tai bang oto of this dn doanh nghiep
	 */
	@AutoEscape
	public String getCoQuanCapGpkdVanTaiBangOto();

	/**
	 * Sets the co quan cap gpkd van tai bang oto of this dn doanh nghiep.
	 *
	 * @param coQuanCapGpkdVanTaiBangOto the co quan cap gpkd van tai bang oto of this dn doanh nghiep
	 */
	public void setCoQuanCapGpkdVanTaiBangOto(String coQuanCapGpkdVanTaiBangOto);

	/**
	 * Returns the ma so cong dan of this dn doanh nghiep.
	 *
	 * @return the ma so cong dan of this dn doanh nghiep
	 */
	@AutoEscape
	public String getMaSoCongDan();

	/**
	 * Sets the ma so cong dan of this dn doanh nghiep.
	 *
	 * @param maSoCongDan the ma so cong dan of this dn doanh nghiep
	 */
	public void setMaSoCongDan(String maSoCongDan);

	/**
	 * Returns the ten cong dan of this dn doanh nghiep.
	 *
	 * @return the ten cong dan of this dn doanh nghiep
	 */
	@AutoEscape
	public String getTenCongDan();

	/**
	 * Sets the ten cong dan of this dn doanh nghiep.
	 *
	 * @param tenCongDan the ten cong dan of this dn doanh nghiep
	 */
	public void setTenCongDan(String tenCongDan);

	/**
	 * Returns the quoc tich of this dn doanh nghiep.
	 *
	 * @return the quoc tich of this dn doanh nghiep
	 */
	@AutoEscape
	public String getQuocTich();

	/**
	 * Sets the quoc tich of this dn doanh nghiep.
	 *
	 * @param quocTich the quoc tich of this dn doanh nghiep
	 */
	public void setQuocTich(String quocTich);

	/**
	 * Returns the gioi tinh of this dn doanh nghiep.
	 *
	 * @return the gioi tinh of this dn doanh nghiep
	 */
	@AutoEscape
	public String getGioiTinh();

	/**
	 * Sets the gioi tinh of this dn doanh nghiep.
	 *
	 * @param gioiTinh the gioi tinh of this dn doanh nghiep
	 */
	public void setGioiTinh(String gioiTinh);

	/**
	 * Returns the ngay cap c m n d of this dn doanh nghiep.
	 *
	 * @return the ngay cap c m n d of this dn doanh nghiep
	 */
	public Date getNgayCapCMND();

	/**
	 * Sets the ngay cap c m n d of this dn doanh nghiep.
	 *
	 * @param ngayCapCMND the ngay cap c m n d of this dn doanh nghiep
	 */
	public void setNgayCapCMND(Date ngayCapCMND);

	/**
	 * Returns the noi cap c m n d of this dn doanh nghiep.
	 *
	 * @return the noi cap c m n d of this dn doanh nghiep
	 */
	@AutoEscape
	public String getNoiCapCMND();

	/**
	 * Sets the noi cap c m n d of this dn doanh nghiep.
	 *
	 * @param noiCapCMND the noi cap c m n d of this dn doanh nghiep
	 */
	public void setNoiCapCMND(String noiCapCMND);

	/**
	 * Returns the loai nguoi lam thu tuc of this dn doanh nghiep.
	 *
	 * @return the loai nguoi lam thu tuc of this dn doanh nghiep
	 */
	@AutoEscape
	public String getLoaiNguoiLamThuTuc();

	/**
	 * Sets the loai nguoi lam thu tuc of this dn doanh nghiep.
	 *
	 * @param loaiNguoiLamThuTuc the loai nguoi lam thu tuc of this dn doanh nghiep
	 */
	public void setLoaiNguoiLamThuTuc(String loaiNguoiLamThuTuc);

	/**
	 * Returns the nam sinh of this dn doanh nghiep.
	 *
	 * @return the nam sinh of this dn doanh nghiep
	 */
	@AutoEscape
	public String getNamSinh();

	/**
	 * Sets the nam sinh of this dn doanh nghiep.
	 *
	 * @param namSinh the nam sinh of this dn doanh nghiep
	 */
	public void setNamSinh(String namSinh);

	/**
	 * Returns the ngay sinh of this dn doanh nghiep.
	 *
	 * @return the ngay sinh of this dn doanh nghiep
	 */
	public Date getNgaySinh();

	/**
	 * Sets the ngay sinh of this dn doanh nghiep.
	 *
	 * @param ngaySinh the ngay sinh of this dn doanh nghiep
	 */
	public void setNgaySinh(Date ngaySinh);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DnDoanhNghiep dnDoanhNghiep);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DnDoanhNghiep> toCacheModel();

	@Override
	public DnDoanhNghiep toEscapedModel();

	@Override
	public DnDoanhNghiep toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}