/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.noidia.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOto;
import vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOtoModel;
import vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOtoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtXuLyGpkdvtBangOto service. Represents a row in the &quot;qlvt_xuly_gpkdvt_bangoto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOtoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtXuLyGpkdvtBangOtoImpl}.
 * </p>
 *
 * @author NoiPham
 * @see QlvtXuLyGpkdvtBangOtoImpl
 * @see vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOto
 * @see vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOtoModel
 * @generated
 */
@JSON(strict = true)
public class QlvtXuLyGpkdvtBangOtoModelImpl extends BaseModelImpl<QlvtXuLyGpkdvtBangOto>
	implements QlvtXuLyGpkdvtBangOtoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt xu ly gpkdvt bang oto model instance should use the {@link vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOto} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_xuly_gpkdvt_bangoto";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "THONGTINXULYID", Types.INTEGER },
			{ "LOAIHINHCAP", Types.VARCHAR },
			{ "SOGPKDVANTAIBANGOTO", Types.VARCHAR },
			{ "NGAYCAPGPKDVANTAIBANGOTO", Types.TIMESTAMP },
			{ "COQUANCAPGPKDVANTAIBANGOTO", Types.VARCHAR },
			{ "NGAYHETHANGPKDVANTAIBANGOTO", Types.TIMESTAMP },
			{ "NGUOITRUCTIEPDIEUHANH", Types.VARCHAR },
			{ "SOCMT_NGUOIDIEUHANH", Types.VARCHAR },
			{ "NGAYCAP_NGUOIDIEUHANH", Types.TIMESTAMP },
			{ "NOICAP_NGUOIDIEUHANH", Types.VARCHAR },
			{ "BANGCAP_NGUOIDIEUHANH", Types.VARCHAR },
			{ "THOIGIANBATDAUDIEUHANH", Types.TIMESTAMP },
			{ "THOIGIANKETTHUCDIEUHANH", Types.TIMESTAMP },
			{ "SOGIAYPHEP_NGUOIDIEUHANH", Types.VARCHAR },
			{ "LANCAP_NGUOIDIEUHANH", Types.INTEGER },
			{ "NGAYCAP_CCDIEUHANH", Types.TIMESTAMP },
			{ "NGAYHETHAN_CCDIEUHANH", Types.TIMESTAMP },
			{ "KETQUAXULY", Types.VARCHAR },
			{ "LYDOKHONGDAT", Types.VARCHAR },
			{ "KETQUAUXULY_NGUOIDIEUHANH", Types.VARCHAR },
			{ "LYDOKHONGDAT_NGUOIDIEUHANH", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_xuly_gpkdvt_bangoto (ID LONG not null primary key,THONGTINXULYID INTEGER,LOAIHINHCAP VARCHAR(75) null,SOGPKDVANTAIBANGOTO VARCHAR(75) null,NGAYCAPGPKDVANTAIBANGOTO DATE null,COQUANCAPGPKDVANTAIBANGOTO VARCHAR(75) null,NGAYHETHANGPKDVANTAIBANGOTO DATE null,NGUOITRUCTIEPDIEUHANH VARCHAR(75) null,SOCMT_NGUOIDIEUHANH VARCHAR(75) null,NGAYCAP_NGUOIDIEUHANH DATE null,NOICAP_NGUOIDIEUHANH VARCHAR(75) null,BANGCAP_NGUOIDIEUHANH VARCHAR(75) null,THOIGIANBATDAUDIEUHANH DATE null,THOIGIANKETTHUCDIEUHANH DATE null,SOGIAYPHEP_NGUOIDIEUHANH VARCHAR(75) null,LANCAP_NGUOIDIEUHANH INTEGER,NGAYCAP_CCDIEUHANH DATE null,NGAYHETHAN_CCDIEUHANH DATE null,KETQUAXULY VARCHAR(75) null,LYDOKHONGDAT VARCHAR(75) null,KETQUAUXULY_NGUOIDIEUHANH VARCHAR(75) null,LYDOKHONGDAT_NGUOIDIEUHANH VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_xuly_gpkdvt_bangoto";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtXuLyGpkdvtBangOto.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_xuly_gpkdvt_bangoto.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOto"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOto"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOto"),
			true);
	public static long THONGTINXULYID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtXuLyGpkdvtBangOto toModel(
		QlvtXuLyGpkdvtBangOtoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtXuLyGpkdvtBangOto model = new QlvtXuLyGpkdvtBangOtoImpl();

		model.setId(soapModel.getId());
		model.setThongTinXuLyId(soapModel.getThongTinXuLyId());
		model.setLoaiHinhCap(soapModel.getLoaiHinhCap());
		model.setSoGpkdVanTaiBangOto(soapModel.getSoGpkdVanTaiBangOto());
		model.setNgayCapGpkdVanTaiBangOto(soapModel.getNgayCapGpkdVanTaiBangOto());
		model.setCoQuanCapGpkdVanTaiBangOto(soapModel.getCoQuanCapGpkdVanTaiBangOto());
		model.setNgayHetHanGpkdVanTaiBangOto(soapModel.getNgayHetHanGpkdVanTaiBangOto());
		model.setNguoiTrucTiepDieuHanh(soapModel.getNguoiTrucTiepDieuHanh());
		model.setSoCmtNguoiDieuHanh(soapModel.getSoCmtNguoiDieuHanh());
		model.setNgayCapNguoiDieuHanh(soapModel.getNgayCapNguoiDieuHanh());
		model.setNoiCapNguoiDieuHanh(soapModel.getNoiCapNguoiDieuHanh());
		model.setBangCapNguoiDieuHanh(soapModel.getBangCapNguoiDieuHanh());
		model.setThoiGianBatDauDieuHanh(soapModel.getThoiGianBatDauDieuHanh());
		model.setThoiGianKetThucDieuHanh(soapModel.getThoiGianKetThucDieuHanh());
		model.setSoGiayPhepNguoiDieuHanh(soapModel.getSoGiayPhepNguoiDieuHanh());
		model.setLanCapNguoiDieuHanh(soapModel.getLanCapNguoiDieuHanh());
		model.setNgayCapCcDieuHanh(soapModel.getNgayCapCcDieuHanh());
		model.setNgayHetHanCcDieuHanh(soapModel.getNgayHetHanCcDieuHanh());
		model.setKetQuaXuLy(soapModel.getKetQuaXuLy());
		model.setLyDoKhongDat(soapModel.getLyDoKhongDat());
		model.setKetQuaXuLyNguoiDieuHanh(soapModel.getKetQuaXuLyNguoiDieuHanh());
		model.setLyDoKhongDatNguoiDieuHanh(soapModel.getLyDoKhongDatNguoiDieuHanh());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtXuLyGpkdvtBangOto> toModels(
		QlvtXuLyGpkdvtBangOtoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtXuLyGpkdvtBangOto> models = new ArrayList<QlvtXuLyGpkdvtBangOto>(soapModels.length);

		for (QlvtXuLyGpkdvtBangOtoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOto"));

	public QlvtXuLyGpkdvtBangOtoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtXuLyGpkdvtBangOto.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtXuLyGpkdvtBangOto.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thongTinXuLyId", getThongTinXuLyId());
		attributes.put("loaiHinhCap", getLoaiHinhCap());
		attributes.put("soGpkdVanTaiBangOto", getSoGpkdVanTaiBangOto());
		attributes.put("ngayCapGpkdVanTaiBangOto", getNgayCapGpkdVanTaiBangOto());
		attributes.put("coQuanCapGpkdVanTaiBangOto",
			getCoQuanCapGpkdVanTaiBangOto());
		attributes.put("ngayHetHanGpkdVanTaiBangOto",
			getNgayHetHanGpkdVanTaiBangOto());
		attributes.put("nguoiTrucTiepDieuHanh", getNguoiTrucTiepDieuHanh());
		attributes.put("soCmtNguoiDieuHanh", getSoCmtNguoiDieuHanh());
		attributes.put("ngayCapNguoiDieuHanh", getNgayCapNguoiDieuHanh());
		attributes.put("noiCapNguoiDieuHanh", getNoiCapNguoiDieuHanh());
		attributes.put("bangCapNguoiDieuHanh", getBangCapNguoiDieuHanh());
		attributes.put("thoiGianBatDauDieuHanh", getThoiGianBatDauDieuHanh());
		attributes.put("thoiGianKetThucDieuHanh", getThoiGianKetThucDieuHanh());
		attributes.put("soGiayPhepNguoiDieuHanh", getSoGiayPhepNguoiDieuHanh());
		attributes.put("lanCapNguoiDieuHanh", getLanCapNguoiDieuHanh());
		attributes.put("ngayCapCcDieuHanh", getNgayCapCcDieuHanh());
		attributes.put("ngayHetHanCcDieuHanh", getNgayHetHanCcDieuHanh());
		attributes.put("ketQuaXuLy", getKetQuaXuLy());
		attributes.put("lyDoKhongDat", getLyDoKhongDat());
		attributes.put("ketQuaXuLyNguoiDieuHanh", getKetQuaXuLyNguoiDieuHanh());
		attributes.put("lyDoKhongDatNguoiDieuHanh",
			getLyDoKhongDatNguoiDieuHanh());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer thongTinXuLyId = (Integer)attributes.get("thongTinXuLyId");

		if (thongTinXuLyId != null) {
			setThongTinXuLyId(thongTinXuLyId);
		}

		String loaiHinhCap = (String)attributes.get("loaiHinhCap");

		if (loaiHinhCap != null) {
			setLoaiHinhCap(loaiHinhCap);
		}

		String soGpkdVanTaiBangOto = (String)attributes.get(
				"soGpkdVanTaiBangOto");

		if (soGpkdVanTaiBangOto != null) {
			setSoGpkdVanTaiBangOto(soGpkdVanTaiBangOto);
		}

		Date ngayCapGpkdVanTaiBangOto = (Date)attributes.get(
				"ngayCapGpkdVanTaiBangOto");

		if (ngayCapGpkdVanTaiBangOto != null) {
			setNgayCapGpkdVanTaiBangOto(ngayCapGpkdVanTaiBangOto);
		}

		String coQuanCapGpkdVanTaiBangOto = (String)attributes.get(
				"coQuanCapGpkdVanTaiBangOto");

		if (coQuanCapGpkdVanTaiBangOto != null) {
			setCoQuanCapGpkdVanTaiBangOto(coQuanCapGpkdVanTaiBangOto);
		}

		Date ngayHetHanGpkdVanTaiBangOto = (Date)attributes.get(
				"ngayHetHanGpkdVanTaiBangOto");

		if (ngayHetHanGpkdVanTaiBangOto != null) {
			setNgayHetHanGpkdVanTaiBangOto(ngayHetHanGpkdVanTaiBangOto);
		}

		String nguoiTrucTiepDieuHanh = (String)attributes.get(
				"nguoiTrucTiepDieuHanh");

		if (nguoiTrucTiepDieuHanh != null) {
			setNguoiTrucTiepDieuHanh(nguoiTrucTiepDieuHanh);
		}

		String soCmtNguoiDieuHanh = (String)attributes.get("soCmtNguoiDieuHanh");

		if (soCmtNguoiDieuHanh != null) {
			setSoCmtNguoiDieuHanh(soCmtNguoiDieuHanh);
		}

		Date ngayCapNguoiDieuHanh = (Date)attributes.get("ngayCapNguoiDieuHanh");

		if (ngayCapNguoiDieuHanh != null) {
			setNgayCapNguoiDieuHanh(ngayCapNguoiDieuHanh);
		}

		String noiCapNguoiDieuHanh = (String)attributes.get(
				"noiCapNguoiDieuHanh");

		if (noiCapNguoiDieuHanh != null) {
			setNoiCapNguoiDieuHanh(noiCapNguoiDieuHanh);
		}

		String bangCapNguoiDieuHanh = (String)attributes.get(
				"bangCapNguoiDieuHanh");

		if (bangCapNguoiDieuHanh != null) {
			setBangCapNguoiDieuHanh(bangCapNguoiDieuHanh);
		}

		Date thoiGianBatDauDieuHanh = (Date)attributes.get(
				"thoiGianBatDauDieuHanh");

		if (thoiGianBatDauDieuHanh != null) {
			setThoiGianBatDauDieuHanh(thoiGianBatDauDieuHanh);
		}

		Date thoiGianKetThucDieuHanh = (Date)attributes.get(
				"thoiGianKetThucDieuHanh");

		if (thoiGianKetThucDieuHanh != null) {
			setThoiGianKetThucDieuHanh(thoiGianKetThucDieuHanh);
		}

		String soGiayPhepNguoiDieuHanh = (String)attributes.get(
				"soGiayPhepNguoiDieuHanh");

		if (soGiayPhepNguoiDieuHanh != null) {
			setSoGiayPhepNguoiDieuHanh(soGiayPhepNguoiDieuHanh);
		}

		Integer lanCapNguoiDieuHanh = (Integer)attributes.get(
				"lanCapNguoiDieuHanh");

		if (lanCapNguoiDieuHanh != null) {
			setLanCapNguoiDieuHanh(lanCapNguoiDieuHanh);
		}

		Date ngayCapCcDieuHanh = (Date)attributes.get("ngayCapCcDieuHanh");

		if (ngayCapCcDieuHanh != null) {
			setNgayCapCcDieuHanh(ngayCapCcDieuHanh);
		}

		Date ngayHetHanCcDieuHanh = (Date)attributes.get("ngayHetHanCcDieuHanh");

		if (ngayHetHanCcDieuHanh != null) {
			setNgayHetHanCcDieuHanh(ngayHetHanCcDieuHanh);
		}

		String ketQuaXuLy = (String)attributes.get("ketQuaXuLy");

		if (ketQuaXuLy != null) {
			setKetQuaXuLy(ketQuaXuLy);
		}

		String lyDoKhongDat = (String)attributes.get("lyDoKhongDat");

		if (lyDoKhongDat != null) {
			setLyDoKhongDat(lyDoKhongDat);
		}

		String ketQuaXuLyNguoiDieuHanh = (String)attributes.get(
				"ketQuaXuLyNguoiDieuHanh");

		if (ketQuaXuLyNguoiDieuHanh != null) {
			setKetQuaXuLyNguoiDieuHanh(ketQuaXuLyNguoiDieuHanh);
		}

		String lyDoKhongDatNguoiDieuHanh = (String)attributes.get(
				"lyDoKhongDatNguoiDieuHanh");

		if (lyDoKhongDatNguoiDieuHanh != null) {
			setLyDoKhongDatNguoiDieuHanh(lyDoKhongDatNguoiDieuHanh);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public int getThongTinXuLyId() {
		return _thongTinXuLyId;
	}

	@Override
	public void setThongTinXuLyId(int thongTinXuLyId) {
		_columnBitmask |= THONGTINXULYID_COLUMN_BITMASK;

		if (!_setOriginalThongTinXuLyId) {
			_setOriginalThongTinXuLyId = true;

			_originalThongTinXuLyId = _thongTinXuLyId;
		}

		_thongTinXuLyId = thongTinXuLyId;
	}

	public int getOriginalThongTinXuLyId() {
		return _originalThongTinXuLyId;
	}

	@JSON
	@Override
	public String getLoaiHinhCap() {
		if (_loaiHinhCap == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiHinhCap;
		}
	}

	@Override
	public void setLoaiHinhCap(String loaiHinhCap) {
		_loaiHinhCap = loaiHinhCap;
	}

	@JSON
	@Override
	public String getSoGpkdVanTaiBangOto() {
		if (_soGpkdVanTaiBangOto == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGpkdVanTaiBangOto;
		}
	}

	@Override
	public void setSoGpkdVanTaiBangOto(String soGpkdVanTaiBangOto) {
		_soGpkdVanTaiBangOto = soGpkdVanTaiBangOto;
	}

	@JSON
	@Override
	public Date getNgayCapGpkdVanTaiBangOto() {
		return _ngayCapGpkdVanTaiBangOto;
	}

	@Override
	public void setNgayCapGpkdVanTaiBangOto(Date ngayCapGpkdVanTaiBangOto) {
		_ngayCapGpkdVanTaiBangOto = ngayCapGpkdVanTaiBangOto;
	}

	@JSON
	@Override
	public String getCoQuanCapGpkdVanTaiBangOto() {
		if (_coQuanCapGpkdVanTaiBangOto == null) {
			return StringPool.BLANK;
		}
		else {
			return _coQuanCapGpkdVanTaiBangOto;
		}
	}

	@Override
	public void setCoQuanCapGpkdVanTaiBangOto(String coQuanCapGpkdVanTaiBangOto) {
		_coQuanCapGpkdVanTaiBangOto = coQuanCapGpkdVanTaiBangOto;
	}

	@JSON
	@Override
	public Date getNgayHetHanGpkdVanTaiBangOto() {
		return _ngayHetHanGpkdVanTaiBangOto;
	}

	@Override
	public void setNgayHetHanGpkdVanTaiBangOto(Date ngayHetHanGpkdVanTaiBangOto) {
		_ngayHetHanGpkdVanTaiBangOto = ngayHetHanGpkdVanTaiBangOto;
	}

	@JSON
	@Override
	public String getNguoiTrucTiepDieuHanh() {
		if (_nguoiTrucTiepDieuHanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTrucTiepDieuHanh;
		}
	}

	@Override
	public void setNguoiTrucTiepDieuHanh(String nguoiTrucTiepDieuHanh) {
		_nguoiTrucTiepDieuHanh = nguoiTrucTiepDieuHanh;
	}

	@JSON
	@Override
	public String getSoCmtNguoiDieuHanh() {
		if (_soCmtNguoiDieuHanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _soCmtNguoiDieuHanh;
		}
	}

	@Override
	public void setSoCmtNguoiDieuHanh(String soCmtNguoiDieuHanh) {
		_soCmtNguoiDieuHanh = soCmtNguoiDieuHanh;
	}

	@JSON
	@Override
	public Date getNgayCapNguoiDieuHanh() {
		return _ngayCapNguoiDieuHanh;
	}

	@Override
	public void setNgayCapNguoiDieuHanh(Date ngayCapNguoiDieuHanh) {
		_ngayCapNguoiDieuHanh = ngayCapNguoiDieuHanh;
	}

	@JSON
	@Override
	public String getNoiCapNguoiDieuHanh() {
		if (_noiCapNguoiDieuHanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiCapNguoiDieuHanh;
		}
	}

	@Override
	public void setNoiCapNguoiDieuHanh(String noiCapNguoiDieuHanh) {
		_noiCapNguoiDieuHanh = noiCapNguoiDieuHanh;
	}

	@JSON
	@Override
	public String getBangCapNguoiDieuHanh() {
		if (_bangCapNguoiDieuHanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _bangCapNguoiDieuHanh;
		}
	}

	@Override
	public void setBangCapNguoiDieuHanh(String bangCapNguoiDieuHanh) {
		_bangCapNguoiDieuHanh = bangCapNguoiDieuHanh;
	}

	@JSON
	@Override
	public Date getThoiGianBatDauDieuHanh() {
		return _thoiGianBatDauDieuHanh;
	}

	@Override
	public void setThoiGianBatDauDieuHanh(Date thoiGianBatDauDieuHanh) {
		_thoiGianBatDauDieuHanh = thoiGianBatDauDieuHanh;
	}

	@JSON
	@Override
	public Date getThoiGianKetThucDieuHanh() {
		return _thoiGianKetThucDieuHanh;
	}

	@Override
	public void setThoiGianKetThucDieuHanh(Date thoiGianKetThucDieuHanh) {
		_thoiGianKetThucDieuHanh = thoiGianKetThucDieuHanh;
	}

	@JSON
	@Override
	public String getSoGiayPhepNguoiDieuHanh() {
		if (_soGiayPhepNguoiDieuHanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGiayPhepNguoiDieuHanh;
		}
	}

	@Override
	public void setSoGiayPhepNguoiDieuHanh(String soGiayPhepNguoiDieuHanh) {
		_soGiayPhepNguoiDieuHanh = soGiayPhepNguoiDieuHanh;
	}

	@JSON
	@Override
	public int getLanCapNguoiDieuHanh() {
		return _lanCapNguoiDieuHanh;
	}

	@Override
	public void setLanCapNguoiDieuHanh(int lanCapNguoiDieuHanh) {
		_lanCapNguoiDieuHanh = lanCapNguoiDieuHanh;
	}

	@JSON
	@Override
	public Date getNgayCapCcDieuHanh() {
		return _ngayCapCcDieuHanh;
	}

	@Override
	public void setNgayCapCcDieuHanh(Date ngayCapCcDieuHanh) {
		_ngayCapCcDieuHanh = ngayCapCcDieuHanh;
	}

	@JSON
	@Override
	public Date getNgayHetHanCcDieuHanh() {
		return _ngayHetHanCcDieuHanh;
	}

	@Override
	public void setNgayHetHanCcDieuHanh(Date ngayHetHanCcDieuHanh) {
		_ngayHetHanCcDieuHanh = ngayHetHanCcDieuHanh;
	}

	@JSON
	@Override
	public String getKetQuaXuLy() {
		if (_ketQuaXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ketQuaXuLy;
		}
	}

	@Override
	public void setKetQuaXuLy(String ketQuaXuLy) {
		_ketQuaXuLy = ketQuaXuLy;
	}

	@JSON
	@Override
	public String getLyDoKhongDat() {
		if (_lyDoKhongDat == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongDat;
		}
	}

	@Override
	public void setLyDoKhongDat(String lyDoKhongDat) {
		_lyDoKhongDat = lyDoKhongDat;
	}

	@JSON
	@Override
	public String getKetQuaXuLyNguoiDieuHanh() {
		if (_ketQuaXuLyNguoiDieuHanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _ketQuaXuLyNguoiDieuHanh;
		}
	}

	@Override
	public void setKetQuaXuLyNguoiDieuHanh(String ketQuaXuLyNguoiDieuHanh) {
		_ketQuaXuLyNguoiDieuHanh = ketQuaXuLyNguoiDieuHanh;
	}

	@JSON
	@Override
	public String getLyDoKhongDatNguoiDieuHanh() {
		if (_lyDoKhongDatNguoiDieuHanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongDatNguoiDieuHanh;
		}
	}

	@Override
	public void setLyDoKhongDatNguoiDieuHanh(String lyDoKhongDatNguoiDieuHanh) {
		_lyDoKhongDatNguoiDieuHanh = lyDoKhongDatNguoiDieuHanh;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtXuLyGpkdvtBangOto.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtXuLyGpkdvtBangOto toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtXuLyGpkdvtBangOto)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtXuLyGpkdvtBangOtoImpl qlvtXuLyGpkdvtBangOtoImpl = new QlvtXuLyGpkdvtBangOtoImpl();

		qlvtXuLyGpkdvtBangOtoImpl.setId(getId());
		qlvtXuLyGpkdvtBangOtoImpl.setThongTinXuLyId(getThongTinXuLyId());
		qlvtXuLyGpkdvtBangOtoImpl.setLoaiHinhCap(getLoaiHinhCap());
		qlvtXuLyGpkdvtBangOtoImpl.setSoGpkdVanTaiBangOto(getSoGpkdVanTaiBangOto());
		qlvtXuLyGpkdvtBangOtoImpl.setNgayCapGpkdVanTaiBangOto(getNgayCapGpkdVanTaiBangOto());
		qlvtXuLyGpkdvtBangOtoImpl.setCoQuanCapGpkdVanTaiBangOto(getCoQuanCapGpkdVanTaiBangOto());
		qlvtXuLyGpkdvtBangOtoImpl.setNgayHetHanGpkdVanTaiBangOto(getNgayHetHanGpkdVanTaiBangOto());
		qlvtXuLyGpkdvtBangOtoImpl.setNguoiTrucTiepDieuHanh(getNguoiTrucTiepDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setSoCmtNguoiDieuHanh(getSoCmtNguoiDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setNgayCapNguoiDieuHanh(getNgayCapNguoiDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setNoiCapNguoiDieuHanh(getNoiCapNguoiDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setBangCapNguoiDieuHanh(getBangCapNguoiDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setThoiGianBatDauDieuHanh(getThoiGianBatDauDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setThoiGianKetThucDieuHanh(getThoiGianKetThucDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setSoGiayPhepNguoiDieuHanh(getSoGiayPhepNguoiDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setLanCapNguoiDieuHanh(getLanCapNguoiDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setNgayCapCcDieuHanh(getNgayCapCcDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setNgayHetHanCcDieuHanh(getNgayHetHanCcDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setKetQuaXuLy(getKetQuaXuLy());
		qlvtXuLyGpkdvtBangOtoImpl.setLyDoKhongDat(getLyDoKhongDat());
		qlvtXuLyGpkdvtBangOtoImpl.setKetQuaXuLyNguoiDieuHanh(getKetQuaXuLyNguoiDieuHanh());
		qlvtXuLyGpkdvtBangOtoImpl.setLyDoKhongDatNguoiDieuHanh(getLyDoKhongDatNguoiDieuHanh());

		qlvtXuLyGpkdvtBangOtoImpl.resetOriginalValues();

		return qlvtXuLyGpkdvtBangOtoImpl;
	}

	@Override
	public int compareTo(QlvtXuLyGpkdvtBangOto qlvtXuLyGpkdvtBangOto) {
		int value = 0;

		if (getId() < qlvtXuLyGpkdvtBangOto.getId()) {
			value = -1;
		}
		else if (getId() > qlvtXuLyGpkdvtBangOto.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtXuLyGpkdvtBangOto)) {
			return false;
		}

		QlvtXuLyGpkdvtBangOto qlvtXuLyGpkdvtBangOto = (QlvtXuLyGpkdvtBangOto)obj;

		long primaryKey = qlvtXuLyGpkdvtBangOto.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		QlvtXuLyGpkdvtBangOtoModelImpl qlvtXuLyGpkdvtBangOtoModelImpl = this;

		qlvtXuLyGpkdvtBangOtoModelImpl._originalThongTinXuLyId = qlvtXuLyGpkdvtBangOtoModelImpl._thongTinXuLyId;

		qlvtXuLyGpkdvtBangOtoModelImpl._setOriginalThongTinXuLyId = false;

		qlvtXuLyGpkdvtBangOtoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<QlvtXuLyGpkdvtBangOto> toCacheModel() {
		QlvtXuLyGpkdvtBangOtoCacheModel qlvtXuLyGpkdvtBangOtoCacheModel = new QlvtXuLyGpkdvtBangOtoCacheModel();

		qlvtXuLyGpkdvtBangOtoCacheModel.id = getId();

		qlvtXuLyGpkdvtBangOtoCacheModel.thongTinXuLyId = getThongTinXuLyId();

		qlvtXuLyGpkdvtBangOtoCacheModel.loaiHinhCap = getLoaiHinhCap();

		String loaiHinhCap = qlvtXuLyGpkdvtBangOtoCacheModel.loaiHinhCap;

		if ((loaiHinhCap != null) && (loaiHinhCap.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.loaiHinhCap = null;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.soGpkdVanTaiBangOto = getSoGpkdVanTaiBangOto();

		String soGpkdVanTaiBangOto = qlvtXuLyGpkdvtBangOtoCacheModel.soGpkdVanTaiBangOto;

		if ((soGpkdVanTaiBangOto != null) &&
				(soGpkdVanTaiBangOto.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.soGpkdVanTaiBangOto = null;
		}

		Date ngayCapGpkdVanTaiBangOto = getNgayCapGpkdVanTaiBangOto();

		if (ngayCapGpkdVanTaiBangOto != null) {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayCapGpkdVanTaiBangOto = ngayCapGpkdVanTaiBangOto.getTime();
		}
		else {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayCapGpkdVanTaiBangOto = Long.MIN_VALUE;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.coQuanCapGpkdVanTaiBangOto = getCoQuanCapGpkdVanTaiBangOto();

		String coQuanCapGpkdVanTaiBangOto = qlvtXuLyGpkdvtBangOtoCacheModel.coQuanCapGpkdVanTaiBangOto;

		if ((coQuanCapGpkdVanTaiBangOto != null) &&
				(coQuanCapGpkdVanTaiBangOto.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.coQuanCapGpkdVanTaiBangOto = null;
		}

		Date ngayHetHanGpkdVanTaiBangOto = getNgayHetHanGpkdVanTaiBangOto();

		if (ngayHetHanGpkdVanTaiBangOto != null) {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayHetHanGpkdVanTaiBangOto = ngayHetHanGpkdVanTaiBangOto.getTime();
		}
		else {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayHetHanGpkdVanTaiBangOto = Long.MIN_VALUE;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.nguoiTrucTiepDieuHanh = getNguoiTrucTiepDieuHanh();

		String nguoiTrucTiepDieuHanh = qlvtXuLyGpkdvtBangOtoCacheModel.nguoiTrucTiepDieuHanh;

		if ((nguoiTrucTiepDieuHanh != null) &&
				(nguoiTrucTiepDieuHanh.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.nguoiTrucTiepDieuHanh = null;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.soCmtNguoiDieuHanh = getSoCmtNguoiDieuHanh();

		String soCmtNguoiDieuHanh = qlvtXuLyGpkdvtBangOtoCacheModel.soCmtNguoiDieuHanh;

		if ((soCmtNguoiDieuHanh != null) && (soCmtNguoiDieuHanh.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.soCmtNguoiDieuHanh = null;
		}

		Date ngayCapNguoiDieuHanh = getNgayCapNguoiDieuHanh();

		if (ngayCapNguoiDieuHanh != null) {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayCapNguoiDieuHanh = ngayCapNguoiDieuHanh.getTime();
		}
		else {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayCapNguoiDieuHanh = Long.MIN_VALUE;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.noiCapNguoiDieuHanh = getNoiCapNguoiDieuHanh();

		String noiCapNguoiDieuHanh = qlvtXuLyGpkdvtBangOtoCacheModel.noiCapNguoiDieuHanh;

		if ((noiCapNguoiDieuHanh != null) &&
				(noiCapNguoiDieuHanh.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.noiCapNguoiDieuHanh = null;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.bangCapNguoiDieuHanh = getBangCapNguoiDieuHanh();

		String bangCapNguoiDieuHanh = qlvtXuLyGpkdvtBangOtoCacheModel.bangCapNguoiDieuHanh;

		if ((bangCapNguoiDieuHanh != null) &&
				(bangCapNguoiDieuHanh.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.bangCapNguoiDieuHanh = null;
		}

		Date thoiGianBatDauDieuHanh = getThoiGianBatDauDieuHanh();

		if (thoiGianBatDauDieuHanh != null) {
			qlvtXuLyGpkdvtBangOtoCacheModel.thoiGianBatDauDieuHanh = thoiGianBatDauDieuHanh.getTime();
		}
		else {
			qlvtXuLyGpkdvtBangOtoCacheModel.thoiGianBatDauDieuHanh = Long.MIN_VALUE;
		}

		Date thoiGianKetThucDieuHanh = getThoiGianKetThucDieuHanh();

		if (thoiGianKetThucDieuHanh != null) {
			qlvtXuLyGpkdvtBangOtoCacheModel.thoiGianKetThucDieuHanh = thoiGianKetThucDieuHanh.getTime();
		}
		else {
			qlvtXuLyGpkdvtBangOtoCacheModel.thoiGianKetThucDieuHanh = Long.MIN_VALUE;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.soGiayPhepNguoiDieuHanh = getSoGiayPhepNguoiDieuHanh();

		String soGiayPhepNguoiDieuHanh = qlvtXuLyGpkdvtBangOtoCacheModel.soGiayPhepNguoiDieuHanh;

		if ((soGiayPhepNguoiDieuHanh != null) &&
				(soGiayPhepNguoiDieuHanh.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.soGiayPhepNguoiDieuHanh = null;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.lanCapNguoiDieuHanh = getLanCapNguoiDieuHanh();

		Date ngayCapCcDieuHanh = getNgayCapCcDieuHanh();

		if (ngayCapCcDieuHanh != null) {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayCapCcDieuHanh = ngayCapCcDieuHanh.getTime();
		}
		else {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayCapCcDieuHanh = Long.MIN_VALUE;
		}

		Date ngayHetHanCcDieuHanh = getNgayHetHanCcDieuHanh();

		if (ngayHetHanCcDieuHanh != null) {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayHetHanCcDieuHanh = ngayHetHanCcDieuHanh.getTime();
		}
		else {
			qlvtXuLyGpkdvtBangOtoCacheModel.ngayHetHanCcDieuHanh = Long.MIN_VALUE;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.ketQuaXuLy = getKetQuaXuLy();

		String ketQuaXuLy = qlvtXuLyGpkdvtBangOtoCacheModel.ketQuaXuLy;

		if ((ketQuaXuLy != null) && (ketQuaXuLy.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.ketQuaXuLy = null;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.lyDoKhongDat = getLyDoKhongDat();

		String lyDoKhongDat = qlvtXuLyGpkdvtBangOtoCacheModel.lyDoKhongDat;

		if ((lyDoKhongDat != null) && (lyDoKhongDat.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.lyDoKhongDat = null;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.ketQuaXuLyNguoiDieuHanh = getKetQuaXuLyNguoiDieuHanh();

		String ketQuaXuLyNguoiDieuHanh = qlvtXuLyGpkdvtBangOtoCacheModel.ketQuaXuLyNguoiDieuHanh;

		if ((ketQuaXuLyNguoiDieuHanh != null) &&
				(ketQuaXuLyNguoiDieuHanh.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.ketQuaXuLyNguoiDieuHanh = null;
		}

		qlvtXuLyGpkdvtBangOtoCacheModel.lyDoKhongDatNguoiDieuHanh = getLyDoKhongDatNguoiDieuHanh();

		String lyDoKhongDatNguoiDieuHanh = qlvtXuLyGpkdvtBangOtoCacheModel.lyDoKhongDatNguoiDieuHanh;

		if ((lyDoKhongDatNguoiDieuHanh != null) &&
				(lyDoKhongDatNguoiDieuHanh.length() == 0)) {
			qlvtXuLyGpkdvtBangOtoCacheModel.lyDoKhongDatNguoiDieuHanh = null;
		}

		return qlvtXuLyGpkdvtBangOtoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(45);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thongTinXuLyId=");
		sb.append(getThongTinXuLyId());
		sb.append(", loaiHinhCap=");
		sb.append(getLoaiHinhCap());
		sb.append(", soGpkdVanTaiBangOto=");
		sb.append(getSoGpkdVanTaiBangOto());
		sb.append(", ngayCapGpkdVanTaiBangOto=");
		sb.append(getNgayCapGpkdVanTaiBangOto());
		sb.append(", coQuanCapGpkdVanTaiBangOto=");
		sb.append(getCoQuanCapGpkdVanTaiBangOto());
		sb.append(", ngayHetHanGpkdVanTaiBangOto=");
		sb.append(getNgayHetHanGpkdVanTaiBangOto());
		sb.append(", nguoiTrucTiepDieuHanh=");
		sb.append(getNguoiTrucTiepDieuHanh());
		sb.append(", soCmtNguoiDieuHanh=");
		sb.append(getSoCmtNguoiDieuHanh());
		sb.append(", ngayCapNguoiDieuHanh=");
		sb.append(getNgayCapNguoiDieuHanh());
		sb.append(", noiCapNguoiDieuHanh=");
		sb.append(getNoiCapNguoiDieuHanh());
		sb.append(", bangCapNguoiDieuHanh=");
		sb.append(getBangCapNguoiDieuHanh());
		sb.append(", thoiGianBatDauDieuHanh=");
		sb.append(getThoiGianBatDauDieuHanh());
		sb.append(", thoiGianKetThucDieuHanh=");
		sb.append(getThoiGianKetThucDieuHanh());
		sb.append(", soGiayPhepNguoiDieuHanh=");
		sb.append(getSoGiayPhepNguoiDieuHanh());
		sb.append(", lanCapNguoiDieuHanh=");
		sb.append(getLanCapNguoiDieuHanh());
		sb.append(", ngayCapCcDieuHanh=");
		sb.append(getNgayCapCcDieuHanh());
		sb.append(", ngayHetHanCcDieuHanh=");
		sb.append(getNgayHetHanCcDieuHanh());
		sb.append(", ketQuaXuLy=");
		sb.append(getKetQuaXuLy());
		sb.append(", lyDoKhongDat=");
		sb.append(getLyDoKhongDat());
		sb.append(", ketQuaXuLyNguoiDieuHanh=");
		sb.append(getKetQuaXuLyNguoiDieuHanh());
		sb.append(", lyDoKhongDatNguoiDieuHanh=");
		sb.append(getLyDoKhongDatNguoiDieuHanh());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(70);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.noidia.model.QlvtXuLyGpkdvtBangOto");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongTinXuLyId</column-name><column-value><![CDATA[");
		sb.append(getThongTinXuLyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiHinhCap</column-name><column-value><![CDATA[");
		sb.append(getLoaiHinhCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGpkdVanTaiBangOto</column-name><column-value><![CDATA[");
		sb.append(getSoGpkdVanTaiBangOto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGpkdVanTaiBangOto</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGpkdVanTaiBangOto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCapGpkdVanTaiBangOto</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapGpkdVanTaiBangOto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHanGpkdVanTaiBangOto</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHanGpkdVanTaiBangOto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTrucTiepDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getNguoiTrucTiepDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soCmtNguoiDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getSoCmtNguoiDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapNguoiDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getNgayCapNguoiDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapNguoiDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getNoiCapNguoiDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bangCapNguoiDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getBangCapNguoiDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thoiGianBatDauDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getThoiGianBatDauDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thoiGianKetThucDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getThoiGianKetThucDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGiayPhepNguoiDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getSoGiayPhepNguoiDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lanCapNguoiDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getLanCapNguoiDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapCcDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getNgayCapCcDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHanCcDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHanCcDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketQuaXuLy</column-name><column-value><![CDATA[");
		sb.append(getKetQuaXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongDat</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongDat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketQuaXuLyNguoiDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getKetQuaXuLyNguoiDieuHanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongDatNguoiDieuHanh</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongDatNguoiDieuHanh());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtXuLyGpkdvtBangOto.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtXuLyGpkdvtBangOto.class
		};
	private long _id;
	private int _thongTinXuLyId;
	private int _originalThongTinXuLyId;
	private boolean _setOriginalThongTinXuLyId;
	private String _loaiHinhCap;
	private String _soGpkdVanTaiBangOto;
	private Date _ngayCapGpkdVanTaiBangOto;
	private String _coQuanCapGpkdVanTaiBangOto;
	private Date _ngayHetHanGpkdVanTaiBangOto;
	private String _nguoiTrucTiepDieuHanh;
	private String _soCmtNguoiDieuHanh;
	private Date _ngayCapNguoiDieuHanh;
	private String _noiCapNguoiDieuHanh;
	private String _bangCapNguoiDieuHanh;
	private Date _thoiGianBatDauDieuHanh;
	private Date _thoiGianKetThucDieuHanh;
	private String _soGiayPhepNguoiDieuHanh;
	private int _lanCapNguoiDieuHanh;
	private Date _ngayCapCcDieuHanh;
	private Date _ngayHetHanCcDieuHanh;
	private String _ketQuaXuLy;
	private String _lyDoKhongDat;
	private String _ketQuaXuLyNguoiDieuHanh;
	private String _lyDoKhongDatNguoiDieuHanh;
	private long _columnBitmask;
	private QlvtXuLyGpkdvtBangOto _escapedModel;
}