/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.lienvan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplv;
import vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplvModel;
import vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplvSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtThongTinHoSoCapPhepGplv service. Represents a row in the &quot;nghiepvu_thongtinhoso_qlvt_capphep_gplienvan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplvModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtThongTinHoSoCapPhepGplvImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtThongTinHoSoCapPhepGplvImpl
 * @see vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplv
 * @see vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplvModel
 * @generated
 */
@JSON(strict = true)
public class QlvtThongTinHoSoCapPhepGplvModelImpl extends BaseModelImpl<QlvtThongTinHoSoCapPhepGplv>
	implements QlvtThongTinHoSoCapPhepGplvModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt thong tin ho so cap phep gplv model instance should use the {@link vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplv} interface instead.
	 */
	public static final String TABLE_NAME = "nghiepvu_thongtinhoso_qlvt_capphep_gplienvan";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "nghiepvu_thongtinhosoID", Types.BIGINT },
			{ "qlvt_capphep_gplienvanID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table nghiepvu_thongtinhoso_qlvt_capphep_gplienvan (ID LONG not null primary key,nghiepvu_thongtinhosoID LONG,qlvt_capphep_gplienvanID LONG)";
	public static final String TABLE_SQL_DROP = "drop table nghiepvu_thongtinhoso_qlvt_capphep_gplienvan";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtThongTinHoSoCapPhepGplv.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY nghiepvu_thongtinhoso_qlvt_capphep_gplienvan.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplv"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplv"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtThongTinHoSoCapPhepGplv toModel(
		QlvtThongTinHoSoCapPhepGplvSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtThongTinHoSoCapPhepGplv model = new QlvtThongTinHoSoCapPhepGplvImpl();

		model.setId(soapModel.getId());
		model.setThongtinhosoId(soapModel.getThongtinhosoId());
		model.setCapphepGplienvanId(soapModel.getCapphepGplienvanId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtThongTinHoSoCapPhepGplv> toModels(
		QlvtThongTinHoSoCapPhepGplvSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtThongTinHoSoCapPhepGplv> models = new ArrayList<QlvtThongTinHoSoCapPhepGplv>(soapModels.length);

		for (QlvtThongTinHoSoCapPhepGplvSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplv"));

	public QlvtThongTinHoSoCapPhepGplvModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtThongTinHoSoCapPhepGplv.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtThongTinHoSoCapPhepGplv.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thongtinhosoId", getThongtinhosoId());
		attributes.put("capphepGplienvanId", getCapphepGplienvanId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long thongtinhosoId = (Long)attributes.get("thongtinhosoId");

		if (thongtinhosoId != null) {
			setThongtinhosoId(thongtinhosoId);
		}

		Long capphepGplienvanId = (Long)attributes.get("capphepGplienvanId");

		if (capphepGplienvanId != null) {
			setCapphepGplienvanId(capphepGplienvanId);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getThongtinhosoId() {
		return _thongtinhosoId;
	}

	@Override
	public void setThongtinhosoId(long thongtinhosoId) {
		_thongtinhosoId = thongtinhosoId;
	}

	@JSON
	@Override
	public long getCapphepGplienvanId() {
		return _capphepGplienvanId;
	}

	@Override
	public void setCapphepGplienvanId(long capphepGplienvanId) {
		_capphepGplienvanId = capphepGplienvanId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtThongTinHoSoCapPhepGplv.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtThongTinHoSoCapPhepGplv toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtThongTinHoSoCapPhepGplv)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtThongTinHoSoCapPhepGplvImpl qlvtThongTinHoSoCapPhepGplvImpl = new QlvtThongTinHoSoCapPhepGplvImpl();

		qlvtThongTinHoSoCapPhepGplvImpl.setId(getId());
		qlvtThongTinHoSoCapPhepGplvImpl.setThongtinhosoId(getThongtinhosoId());
		qlvtThongTinHoSoCapPhepGplvImpl.setCapphepGplienvanId(getCapphepGplienvanId());

		qlvtThongTinHoSoCapPhepGplvImpl.resetOriginalValues();

		return qlvtThongTinHoSoCapPhepGplvImpl;
	}

	@Override
	public int compareTo(
		QlvtThongTinHoSoCapPhepGplv qlvtThongTinHoSoCapPhepGplv) {
		int value = 0;

		if (getId() < qlvtThongTinHoSoCapPhepGplv.getId()) {
			value = -1;
		}
		else if (getId() > qlvtThongTinHoSoCapPhepGplv.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtThongTinHoSoCapPhepGplv)) {
			return false;
		}

		QlvtThongTinHoSoCapPhepGplv qlvtThongTinHoSoCapPhepGplv = (QlvtThongTinHoSoCapPhepGplv)obj;

		long primaryKey = qlvtThongTinHoSoCapPhepGplv.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QlvtThongTinHoSoCapPhepGplv> toCacheModel() {
		QlvtThongTinHoSoCapPhepGplvCacheModel qlvtThongTinHoSoCapPhepGplvCacheModel =
			new QlvtThongTinHoSoCapPhepGplvCacheModel();

		qlvtThongTinHoSoCapPhepGplvCacheModel.id = getId();

		qlvtThongTinHoSoCapPhepGplvCacheModel.thongtinhosoId = getThongtinhosoId();

		qlvtThongTinHoSoCapPhepGplvCacheModel.capphepGplienvanId = getCapphepGplienvanId();

		return qlvtThongTinHoSoCapPhepGplvCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thongtinhosoId=");
		sb.append(getThongtinhosoId());
		sb.append(", capphepGplienvanId=");
		sb.append(getCapphepGplienvanId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.duongbo.dao.lienvan.model.QlvtThongTinHoSoCapPhepGplv");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongtinhosoId</column-name><column-value><![CDATA[");
		sb.append(getThongtinhosoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>capphepGplienvanId</column-name><column-value><![CDATA[");
		sb.append(getCapphepGplienvanId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtThongTinHoSoCapPhepGplv.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtThongTinHoSoCapPhepGplv.class
		};
	private long _id;
	private long _thongtinhosoId;
	private long _capphepGplienvanId;
	private QlvtThongTinHoSoCapPhepGplv _escapedModel;
}