/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.lienvan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTe;
import vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTeModel;
import vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTeSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtCapPhepGpkdvtDuongboQuocTe service. Represents a row in the &quot;qlvt_capphep_gpkdvt_duongbo_quocte&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtCapPhepGpkdvtDuongboQuocTeImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtCapPhepGpkdvtDuongboQuocTeImpl
 * @see vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTe
 * @see vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTeModel
 * @generated
 */
@JSON(strict = true)
public class QlvtCapPhepGpkdvtDuongboQuocTeModelImpl extends BaseModelImpl<QlvtCapPhepGpkdvtDuongboQuocTe>
	implements QlvtCapPhepGpkdvtDuongboQuocTeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt cap phep gpkdvt duongbo quoc te model instance should use the {@link vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTe} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_capphep_gpkdvt_duongbo_quocte";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "GPKDVT_OTOID", Types.BIGINT },
			{ "SOGIAYPHEPVANTAI_QUOCTE", Types.VARCHAR },
			{ "COQUANCAPLANDAUID", Types.BIGINT },
			{ "NGAYCAPGIAYPHEPVANTAI", Types.TIMESTAMP },
			{ "COQUANCAPGIAYPHEPVANTAID", Types.BIGINT },
			{ "NGAYGIAHAN", Types.TIMESTAMP },
			{ "NGAYHETHAN", Types.TIMESTAMP },
			{ "LANGIAHAN", Types.INTEGER },
			{ "FILEID", Types.BIGINT },
			{ "TRANGTHAI", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_capphep_gpkdvt_duongbo_quocte (ID LONG not null primary key,GPKDVT_OTOID LONG,SOGIAYPHEPVANTAI_QUOCTE VARCHAR(75) null,COQUANCAPLANDAUID LONG,NGAYCAPGIAYPHEPVANTAI DATE null,COQUANCAPGIAYPHEPVANTAID LONG,NGAYGIAHAN DATE null,NGAYHETHAN DATE null,LANGIAHAN INTEGER,FILEID LONG,TRANGTHAI VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_capphep_gpkdvt_duongbo_quocte";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtCapPhepGpkdvtDuongboQuocTe.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_capphep_gpkdvt_duongbo_quocte.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTe"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTe"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtCapPhepGpkdvtDuongboQuocTe toModel(
		QlvtCapPhepGpkdvtDuongboQuocTeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtCapPhepGpkdvtDuongboQuocTe model = new QlvtCapPhepGpkdvtDuongboQuocTeImpl();

		model.setId(soapModel.getId());
		model.setGpKinhDoanhVanTaiOtoId(soapModel.getGpKinhDoanhVanTaiOtoId());
		model.setSoGpvtQuocTe(soapModel.getSoGpvtQuocTe());
		model.setCoQuanCapLanDauId(soapModel.getCoQuanCapLanDauId());
		model.setNgayCapGpvt(soapModel.getNgayCapGpvt());
		model.setCoQuanCapGpvtId(soapModel.getCoQuanCapGpvtId());
		model.setNgayGiaHan(soapModel.getNgayGiaHan());
		model.setNgayHetHan(soapModel.getNgayHetHan());
		model.setLanGiaHan(soapModel.getLanGiaHan());
		model.setFileId(soapModel.getFileId());
		model.setTrangThai(soapModel.getTrangThai());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtCapPhepGpkdvtDuongboQuocTe> toModels(
		QlvtCapPhepGpkdvtDuongboQuocTeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtCapPhepGpkdvtDuongboQuocTe> models = new ArrayList<QlvtCapPhepGpkdvtDuongboQuocTe>(soapModels.length);

		for (QlvtCapPhepGpkdvtDuongboQuocTeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTe"));

	public QlvtCapPhepGpkdvtDuongboQuocTeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtCapPhepGpkdvtDuongboQuocTe.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtCapPhepGpkdvtDuongboQuocTe.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("gpKinhDoanhVanTaiOtoId", getGpKinhDoanhVanTaiOtoId());
		attributes.put("soGpvtQuocTe", getSoGpvtQuocTe());
		attributes.put("coQuanCapLanDauId", getCoQuanCapLanDauId());
		attributes.put("ngayCapGpvt", getNgayCapGpvt());
		attributes.put("coQuanCapGpvtId", getCoQuanCapGpvtId());
		attributes.put("ngayGiaHan", getNgayGiaHan());
		attributes.put("ngayHetHan", getNgayHetHan());
		attributes.put("lanGiaHan", getLanGiaHan());
		attributes.put("fileId", getFileId());
		attributes.put("trangThai", getTrangThai());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long gpKinhDoanhVanTaiOtoId = (Long)attributes.get(
				"gpKinhDoanhVanTaiOtoId");

		if (gpKinhDoanhVanTaiOtoId != null) {
			setGpKinhDoanhVanTaiOtoId(gpKinhDoanhVanTaiOtoId);
		}

		String soGpvtQuocTe = (String)attributes.get("soGpvtQuocTe");

		if (soGpvtQuocTe != null) {
			setSoGpvtQuocTe(soGpvtQuocTe);
		}

		Long coQuanCapLanDauId = (Long)attributes.get("coQuanCapLanDauId");

		if (coQuanCapLanDauId != null) {
			setCoQuanCapLanDauId(coQuanCapLanDauId);
		}

		Date ngayCapGpvt = (Date)attributes.get("ngayCapGpvt");

		if (ngayCapGpvt != null) {
			setNgayCapGpvt(ngayCapGpvt);
		}

		Long coQuanCapGpvtId = (Long)attributes.get("coQuanCapGpvtId");

		if (coQuanCapGpvtId != null) {
			setCoQuanCapGpvtId(coQuanCapGpvtId);
		}

		Date ngayGiaHan = (Date)attributes.get("ngayGiaHan");

		if (ngayGiaHan != null) {
			setNgayGiaHan(ngayGiaHan);
		}

		Date ngayHetHan = (Date)attributes.get("ngayHetHan");

		if (ngayHetHan != null) {
			setNgayHetHan(ngayHetHan);
		}

		Integer lanGiaHan = (Integer)attributes.get("lanGiaHan");

		if (lanGiaHan != null) {
			setLanGiaHan(lanGiaHan);
		}

		Long fileId = (Long)attributes.get("fileId");

		if (fileId != null) {
			setFileId(fileId);
		}

		String trangThai = (String)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getGpKinhDoanhVanTaiOtoId() {
		return _gpKinhDoanhVanTaiOtoId;
	}

	@Override
	public void setGpKinhDoanhVanTaiOtoId(long gpKinhDoanhVanTaiOtoId) {
		_gpKinhDoanhVanTaiOtoId = gpKinhDoanhVanTaiOtoId;
	}

	@JSON
	@Override
	public String getSoGpvtQuocTe() {
		if (_soGpvtQuocTe == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGpvtQuocTe;
		}
	}

	@Override
	public void setSoGpvtQuocTe(String soGpvtQuocTe) {
		_soGpvtQuocTe = soGpvtQuocTe;
	}

	@JSON
	@Override
	public long getCoQuanCapLanDauId() {
		return _coQuanCapLanDauId;
	}

	@Override
	public void setCoQuanCapLanDauId(long coQuanCapLanDauId) {
		_coQuanCapLanDauId = coQuanCapLanDauId;
	}

	@JSON
	@Override
	public Date getNgayCapGpvt() {
		return _ngayCapGpvt;
	}

	@Override
	public void setNgayCapGpvt(Date ngayCapGpvt) {
		_ngayCapGpvt = ngayCapGpvt;
	}

	@JSON
	@Override
	public long getCoQuanCapGpvtId() {
		return _coQuanCapGpvtId;
	}

	@Override
	public void setCoQuanCapGpvtId(long coQuanCapGpvtId) {
		_coQuanCapGpvtId = coQuanCapGpvtId;
	}

	@JSON
	@Override
	public Date getNgayGiaHan() {
		return _ngayGiaHan;
	}

	@Override
	public void setNgayGiaHan(Date ngayGiaHan) {
		_ngayGiaHan = ngayGiaHan;
	}

	@JSON
	@Override
	public Date getNgayHetHan() {
		return _ngayHetHan;
	}

	@Override
	public void setNgayHetHan(Date ngayHetHan) {
		_ngayHetHan = ngayHetHan;
	}

	@JSON
	@Override
	public int getLanGiaHan() {
		return _lanGiaHan;
	}

	@Override
	public void setLanGiaHan(int lanGiaHan) {
		_lanGiaHan = lanGiaHan;
	}

	@JSON
	@Override
	public long getFileId() {
		return _fileId;
	}

	@Override
	public void setFileId(long fileId) {
		_fileId = fileId;
	}

	@JSON
	@Override
	public String getTrangThai() {
		if (_trangThai == null) {
			return StringPool.BLANK;
		}
		else {
			return _trangThai;
		}
	}

	@Override
	public void setTrangThai(String trangThai) {
		_trangThai = trangThai;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtCapPhepGpkdvtDuongboQuocTe.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtCapPhepGpkdvtDuongboQuocTe toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtCapPhepGpkdvtDuongboQuocTe)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtCapPhepGpkdvtDuongboQuocTeImpl qlvtCapPhepGpkdvtDuongboQuocTeImpl = new QlvtCapPhepGpkdvtDuongboQuocTeImpl();

		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setId(getId());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setGpKinhDoanhVanTaiOtoId(getGpKinhDoanhVanTaiOtoId());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setSoGpvtQuocTe(getSoGpvtQuocTe());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setCoQuanCapLanDauId(getCoQuanCapLanDauId());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setNgayCapGpvt(getNgayCapGpvt());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setCoQuanCapGpvtId(getCoQuanCapGpvtId());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setNgayGiaHan(getNgayGiaHan());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setNgayHetHan(getNgayHetHan());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setLanGiaHan(getLanGiaHan());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setFileId(getFileId());
		qlvtCapPhepGpkdvtDuongboQuocTeImpl.setTrangThai(getTrangThai());

		qlvtCapPhepGpkdvtDuongboQuocTeImpl.resetOriginalValues();

		return qlvtCapPhepGpkdvtDuongboQuocTeImpl;
	}

	@Override
	public int compareTo(
		QlvtCapPhepGpkdvtDuongboQuocTe qlvtCapPhepGpkdvtDuongboQuocTe) {
		int value = 0;

		if (getId() < qlvtCapPhepGpkdvtDuongboQuocTe.getId()) {
			value = -1;
		}
		else if (getId() > qlvtCapPhepGpkdvtDuongboQuocTe.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtCapPhepGpkdvtDuongboQuocTe)) {
			return false;
		}

		QlvtCapPhepGpkdvtDuongboQuocTe qlvtCapPhepGpkdvtDuongboQuocTe = (QlvtCapPhepGpkdvtDuongboQuocTe)obj;

		long primaryKey = qlvtCapPhepGpkdvtDuongboQuocTe.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QlvtCapPhepGpkdvtDuongboQuocTe> toCacheModel() {
		QlvtCapPhepGpkdvtDuongboQuocTeCacheModel qlvtCapPhepGpkdvtDuongboQuocTeCacheModel =
			new QlvtCapPhepGpkdvtDuongboQuocTeCacheModel();

		qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.id = getId();

		qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.gpKinhDoanhVanTaiOtoId = getGpKinhDoanhVanTaiOtoId();

		qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.soGpvtQuocTe = getSoGpvtQuocTe();

		String soGpvtQuocTe = qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.soGpvtQuocTe;

		if ((soGpvtQuocTe != null) && (soGpvtQuocTe.length() == 0)) {
			qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.soGpvtQuocTe = null;
		}

		qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.coQuanCapLanDauId = getCoQuanCapLanDauId();

		Date ngayCapGpvt = getNgayCapGpvt();

		if (ngayCapGpvt != null) {
			qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.ngayCapGpvt = ngayCapGpvt.getTime();
		}
		else {
			qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.ngayCapGpvt = Long.MIN_VALUE;
		}

		qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.coQuanCapGpvtId = getCoQuanCapGpvtId();

		Date ngayGiaHan = getNgayGiaHan();

		if (ngayGiaHan != null) {
			qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.ngayGiaHan = ngayGiaHan.getTime();
		}
		else {
			qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.ngayGiaHan = Long.MIN_VALUE;
		}

		Date ngayHetHan = getNgayHetHan();

		if (ngayHetHan != null) {
			qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.ngayHetHan = ngayHetHan.getTime();
		}
		else {
			qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.ngayHetHan = Long.MIN_VALUE;
		}

		qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.lanGiaHan = getLanGiaHan();

		qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.fileId = getFileId();

		qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.trangThai = getTrangThai();

		String trangThai = qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.trangThai;

		if ((trangThai != null) && (trangThai.length() == 0)) {
			qlvtCapPhepGpkdvtDuongboQuocTeCacheModel.trangThai = null;
		}

		return qlvtCapPhepGpkdvtDuongboQuocTeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", gpKinhDoanhVanTaiOtoId=");
		sb.append(getGpKinhDoanhVanTaiOtoId());
		sb.append(", soGpvtQuocTe=");
		sb.append(getSoGpvtQuocTe());
		sb.append(", coQuanCapLanDauId=");
		sb.append(getCoQuanCapLanDauId());
		sb.append(", ngayCapGpvt=");
		sb.append(getNgayCapGpvt());
		sb.append(", coQuanCapGpvtId=");
		sb.append(getCoQuanCapGpvtId());
		sb.append(", ngayGiaHan=");
		sb.append(getNgayGiaHan());
		sb.append(", ngayHetHan=");
		sb.append(getNgayHetHan());
		sb.append(", lanGiaHan=");
		sb.append(getLanGiaHan());
		sb.append(", fileId=");
		sb.append(getFileId());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpkdvtDuongboQuocTe");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gpKinhDoanhVanTaiOtoId</column-name><column-value><![CDATA[");
		sb.append(getGpKinhDoanhVanTaiOtoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGpvtQuocTe</column-name><column-value><![CDATA[");
		sb.append(getSoGpvtQuocTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCapLanDauId</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapLanDauId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGpvt</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGpvt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCapGpvtId</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapGpvtId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayGiaHan</column-name><column-value><![CDATA[");
		sb.append(getNgayGiaHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHan</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lanGiaHan</column-name><column-value><![CDATA[");
		sb.append(getLanGiaHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileId</column-name><column-value><![CDATA[");
		sb.append(getFileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtCapPhepGpkdvtDuongboQuocTe.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtCapPhepGpkdvtDuongboQuocTe.class
		};
	private long _id;
	private long _gpKinhDoanhVanTaiOtoId;
	private String _soGpvtQuocTe;
	private long _coQuanCapLanDauId;
	private Date _ngayCapGpvt;
	private long _coQuanCapGpvtId;
	private Date _ngayGiaHan;
	private Date _ngayHetHan;
	private int _lanGiaHan;
	private long _fileId;
	private String _trangThai;
	private QlvtCapPhepGpkdvtDuongboQuocTe _escapedModel;
}