/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.lienvan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVan;
import vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVanModel;
import vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVanSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtCapPhepGpLienVan service. Represents a row in the &quot;qlvt_capphep_gplienvan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtCapPhepGpLienVanImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtCapPhepGpLienVanImpl
 * @see vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVan
 * @see vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVanModel
 * @generated
 */
@JSON(strict = true)
public class QlvtCapPhepGpLienVanModelImpl extends BaseModelImpl<QlvtCapPhepGpLienVan>
	implements QlvtCapPhepGpLienVanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt cap phep gp lien van model instance should use the {@link vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVan} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_capphep_gplienvan";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "GPKDVT_VIETLAOID", Types.BIGINT },
			{ "LOAICAPPHEP", Types.VARCHAR },
			{ "LOAIGIAYPHEPLIENVAN", Types.VARCHAR },
			{ "SOGIAYPHEPLIENVAN", Types.VARCHAR },
			{ "NGAYCAPGIAYPHEPLIENVAN", Types.TIMESTAMP },
			{ "NGAYHETHANGIAYPHEPLIENVAN", Types.TIMESTAMP },
			{ "COQUANCAPPHEPLIENVAN", Types.VARCHAR },
			{ "SOCONGVANCHAPTHUANTCD", Types.VARCHAR },
			{ "NGAYCONGVANCHAPTHUANTCD", Types.TIMESTAMP },
			{ "TUYENTU", Types.VARCHAR },
			{ "TUYENDI", Types.VARCHAR },
			{ "CULY", Types.VARCHAR },
			{ "MABENDI", Types.VARCHAR },
			{ "MABENDEN", Types.VARCHAR },
			{ "MATINHDI", Types.VARCHAR },
			{ "MATINHDEN", Types.VARCHAR },
			{ "HANHTRINH", Types.VARCHAR },
			{ "MUCPHI", Types.VARCHAR },
			{ "MUCDICHCHUYENDI", Types.VARCHAR },
			{ "FILEID", Types.BIGINT },
			{ "TRANGTHAI", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_capphep_gplienvan (ID LONG not null primary key,GPKDVT_VIETLAOID LONG,LOAICAPPHEP VARCHAR(75) null,LOAIGIAYPHEPLIENVAN VARCHAR(75) null,SOGIAYPHEPLIENVAN VARCHAR(75) null,NGAYCAPGIAYPHEPLIENVAN DATE null,NGAYHETHANGIAYPHEPLIENVAN DATE null,COQUANCAPPHEPLIENVAN VARCHAR(75) null,SOCONGVANCHAPTHUANTCD VARCHAR(75) null,NGAYCONGVANCHAPTHUANTCD DATE null,TUYENTU VARCHAR(75) null,TUYENDI VARCHAR(75) null,CULY VARCHAR(75) null,MABENDI VARCHAR(75) null,MABENDEN VARCHAR(75) null,MATINHDI VARCHAR(75) null,MATINHDEN VARCHAR(75) null,HANHTRINH VARCHAR(75) null,MUCPHI VARCHAR(75) null,MUCDICHCHUYENDI VARCHAR(75) null,FILEID LONG,TRANGTHAI VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_capphep_gplienvan";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtCapPhepGpLienVan.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_capphep_gplienvan.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVan"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVan"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtCapPhepGpLienVan toModel(
		QlvtCapPhepGpLienVanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtCapPhepGpLienVan model = new QlvtCapPhepGpLienVanImpl();

		model.setId(soapModel.getId());
		model.setGpkdvtVietLaoId(soapModel.getGpkdvtVietLaoId());
		model.setLoaiCapPhep(soapModel.getLoaiCapPhep());
		model.setLoaiGiayPhepLienVan(soapModel.getLoaiGiayPhepLienVan());
		model.setSoGiayPhepLienVan(soapModel.getSoGiayPhepLienVan());
		model.setNgayCapGplv(soapModel.getNgayCapGplv());
		model.setNgayHetHanGplv(soapModel.getNgayHetHanGplv());
		model.setCoQuanCpLienVan(soapModel.getCoQuanCpLienVan());
		model.setSoCongVanChapThuanTCD(soapModel.getSoCongVanChapThuanTCD());
		model.setNgayCongVanChapThuanTCD(soapModel.getNgayCongVanChapThuanTCD());
		model.setTuyenTu(soapModel.getTuyenTu());
		model.setTuyenDi(soapModel.getTuyenDi());
		model.setCuLy(soapModel.getCuLy());
		model.setMaBenDi(soapModel.getMaBenDi());
		model.setMaBenDen(soapModel.getMaBenDen());
		model.setMaTinhDi(soapModel.getMaTinhDi());
		model.setMaTinhDen(soapModel.getMaTinhDen());
		model.setHanhTrinh(soapModel.getHanhTrinh());
		model.setMucPhi(soapModel.getMucPhi());
		model.setMucDichChuyenDi(soapModel.getMucDichChuyenDi());
		model.setFileId(soapModel.getFileId());
		model.setTrangThai(soapModel.getTrangThai());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtCapPhepGpLienVan> toModels(
		QlvtCapPhepGpLienVanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtCapPhepGpLienVan> models = new ArrayList<QlvtCapPhepGpLienVan>(soapModels.length);

		for (QlvtCapPhepGpLienVanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVan"));

	public QlvtCapPhepGpLienVanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtCapPhepGpLienVan.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtCapPhepGpLienVan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("gpkdvtVietLaoId", getGpkdvtVietLaoId());
		attributes.put("loaiCapPhep", getLoaiCapPhep());
		attributes.put("loaiGiayPhepLienVan", getLoaiGiayPhepLienVan());
		attributes.put("soGiayPhepLienVan", getSoGiayPhepLienVan());
		attributes.put("ngayCapGplv", getNgayCapGplv());
		attributes.put("ngayHetHanGplv", getNgayHetHanGplv());
		attributes.put("coQuanCpLienVan", getCoQuanCpLienVan());
		attributes.put("soCongVanChapThuanTCD", getSoCongVanChapThuanTCD());
		attributes.put("ngayCongVanChapThuanTCD", getNgayCongVanChapThuanTCD());
		attributes.put("tuyenTu", getTuyenTu());
		attributes.put("tuyenDi", getTuyenDi());
		attributes.put("cuLy", getCuLy());
		attributes.put("maBenDi", getMaBenDi());
		attributes.put("maBenDen", getMaBenDen());
		attributes.put("maTinhDi", getMaTinhDi());
		attributes.put("maTinhDen", getMaTinhDen());
		attributes.put("hanhTrinh", getHanhTrinh());
		attributes.put("mucPhi", getMucPhi());
		attributes.put("mucDichChuyenDi", getMucDichChuyenDi());
		attributes.put("fileId", getFileId());
		attributes.put("trangThai", getTrangThai());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long gpkdvtVietLaoId = (Long)attributes.get("gpkdvtVietLaoId");

		if (gpkdvtVietLaoId != null) {
			setGpkdvtVietLaoId(gpkdvtVietLaoId);
		}

		String loaiCapPhep = (String)attributes.get("loaiCapPhep");

		if (loaiCapPhep != null) {
			setLoaiCapPhep(loaiCapPhep);
		}

		String loaiGiayPhepLienVan = (String)attributes.get(
				"loaiGiayPhepLienVan");

		if (loaiGiayPhepLienVan != null) {
			setLoaiGiayPhepLienVan(loaiGiayPhepLienVan);
		}

		String soGiayPhepLienVan = (String)attributes.get("soGiayPhepLienVan");

		if (soGiayPhepLienVan != null) {
			setSoGiayPhepLienVan(soGiayPhepLienVan);
		}

		Date ngayCapGplv = (Date)attributes.get("ngayCapGplv");

		if (ngayCapGplv != null) {
			setNgayCapGplv(ngayCapGplv);
		}

		Date ngayHetHanGplv = (Date)attributes.get("ngayHetHanGplv");

		if (ngayHetHanGplv != null) {
			setNgayHetHanGplv(ngayHetHanGplv);
		}

		String coQuanCpLienVan = (String)attributes.get("coQuanCpLienVan");

		if (coQuanCpLienVan != null) {
			setCoQuanCpLienVan(coQuanCpLienVan);
		}

		String soCongVanChapThuanTCD = (String)attributes.get(
				"soCongVanChapThuanTCD");

		if (soCongVanChapThuanTCD != null) {
			setSoCongVanChapThuanTCD(soCongVanChapThuanTCD);
		}

		Date ngayCongVanChapThuanTCD = (Date)attributes.get(
				"ngayCongVanChapThuanTCD");

		if (ngayCongVanChapThuanTCD != null) {
			setNgayCongVanChapThuanTCD(ngayCongVanChapThuanTCD);
		}

		String tuyenTu = (String)attributes.get("tuyenTu");

		if (tuyenTu != null) {
			setTuyenTu(tuyenTu);
		}

		String tuyenDi = (String)attributes.get("tuyenDi");

		if (tuyenDi != null) {
			setTuyenDi(tuyenDi);
		}

		String cuLy = (String)attributes.get("cuLy");

		if (cuLy != null) {
			setCuLy(cuLy);
		}

		String maBenDi = (String)attributes.get("maBenDi");

		if (maBenDi != null) {
			setMaBenDi(maBenDi);
		}

		String maBenDen = (String)attributes.get("maBenDen");

		if (maBenDen != null) {
			setMaBenDen(maBenDen);
		}

		String maTinhDi = (String)attributes.get("maTinhDi");

		if (maTinhDi != null) {
			setMaTinhDi(maTinhDi);
		}

		String maTinhDen = (String)attributes.get("maTinhDen");

		if (maTinhDen != null) {
			setMaTinhDen(maTinhDen);
		}

		String hanhTrinh = (String)attributes.get("hanhTrinh");

		if (hanhTrinh != null) {
			setHanhTrinh(hanhTrinh);
		}

		String mucPhi = (String)attributes.get("mucPhi");

		if (mucPhi != null) {
			setMucPhi(mucPhi);
		}

		String mucDichChuyenDi = (String)attributes.get("mucDichChuyenDi");

		if (mucDichChuyenDi != null) {
			setMucDichChuyenDi(mucDichChuyenDi);
		}

		Long fileId = (Long)attributes.get("fileId");

		if (fileId != null) {
			setFileId(fileId);
		}

		String trangThai = (String)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getGpkdvtVietLaoId() {
		return _gpkdvtVietLaoId;
	}

	@Override
	public void setGpkdvtVietLaoId(long gpkdvtVietLaoId) {
		_gpkdvtVietLaoId = gpkdvtVietLaoId;
	}

	@JSON
	@Override
	public String getLoaiCapPhep() {
		if (_loaiCapPhep == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiCapPhep;
		}
	}

	@Override
	public void setLoaiCapPhep(String loaiCapPhep) {
		_loaiCapPhep = loaiCapPhep;
	}

	@JSON
	@Override
	public String getLoaiGiayPhepLienVan() {
		if (_loaiGiayPhepLienVan == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiGiayPhepLienVan;
		}
	}

	@Override
	public void setLoaiGiayPhepLienVan(String loaiGiayPhepLienVan) {
		_loaiGiayPhepLienVan = loaiGiayPhepLienVan;
	}

	@JSON
	@Override
	public String getSoGiayPhepLienVan() {
		if (_soGiayPhepLienVan == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGiayPhepLienVan;
		}
	}

	@Override
	public void setSoGiayPhepLienVan(String soGiayPhepLienVan) {
		_soGiayPhepLienVan = soGiayPhepLienVan;
	}

	@JSON
	@Override
	public Date getNgayCapGplv() {
		return _ngayCapGplv;
	}

	@Override
	public void setNgayCapGplv(Date ngayCapGplv) {
		_ngayCapGplv = ngayCapGplv;
	}

	@JSON
	@Override
	public Date getNgayHetHanGplv() {
		return _ngayHetHanGplv;
	}

	@Override
	public void setNgayHetHanGplv(Date ngayHetHanGplv) {
		_ngayHetHanGplv = ngayHetHanGplv;
	}

	@JSON
	@Override
	public String getCoQuanCpLienVan() {
		if (_coQuanCpLienVan == null) {
			return StringPool.BLANK;
		}
		else {
			return _coQuanCpLienVan;
		}
	}

	@Override
	public void setCoQuanCpLienVan(String coQuanCpLienVan) {
		_coQuanCpLienVan = coQuanCpLienVan;
	}

	@JSON
	@Override
	public String getSoCongVanChapThuanTCD() {
		if (_soCongVanChapThuanTCD == null) {
			return StringPool.BLANK;
		}
		else {
			return _soCongVanChapThuanTCD;
		}
	}

	@Override
	public void setSoCongVanChapThuanTCD(String soCongVanChapThuanTCD) {
		_soCongVanChapThuanTCD = soCongVanChapThuanTCD;
	}

	@JSON
	@Override
	public Date getNgayCongVanChapThuanTCD() {
		return _ngayCongVanChapThuanTCD;
	}

	@Override
	public void setNgayCongVanChapThuanTCD(Date ngayCongVanChapThuanTCD) {
		_ngayCongVanChapThuanTCD = ngayCongVanChapThuanTCD;
	}

	@JSON
	@Override
	public String getTuyenTu() {
		if (_tuyenTu == null) {
			return StringPool.BLANK;
		}
		else {
			return _tuyenTu;
		}
	}

	@Override
	public void setTuyenTu(String tuyenTu) {
		_tuyenTu = tuyenTu;
	}

	@JSON
	@Override
	public String getTuyenDi() {
		if (_tuyenDi == null) {
			return StringPool.BLANK;
		}
		else {
			return _tuyenDi;
		}
	}

	@Override
	public void setTuyenDi(String tuyenDi) {
		_tuyenDi = tuyenDi;
	}

	@JSON
	@Override
	public String getCuLy() {
		if (_cuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _cuLy;
		}
	}

	@Override
	public void setCuLy(String cuLy) {
		_cuLy = cuLy;
	}

	@JSON
	@Override
	public String getMaBenDi() {
		if (_maBenDi == null) {
			return StringPool.BLANK;
		}
		else {
			return _maBenDi;
		}
	}

	@Override
	public void setMaBenDi(String maBenDi) {
		_maBenDi = maBenDi;
	}

	@JSON
	@Override
	public String getMaBenDen() {
		if (_maBenDen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maBenDen;
		}
	}

	@Override
	public void setMaBenDen(String maBenDen) {
		_maBenDen = maBenDen;
	}

	@JSON
	@Override
	public String getMaTinhDi() {
		if (_maTinhDi == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinhDi;
		}
	}

	@Override
	public void setMaTinhDi(String maTinhDi) {
		_maTinhDi = maTinhDi;
	}

	@JSON
	@Override
	public String getMaTinhDen() {
		if (_maTinhDen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinhDen;
		}
	}

	@Override
	public void setMaTinhDen(String maTinhDen) {
		_maTinhDen = maTinhDen;
	}

	@JSON
	@Override
	public String getHanhTrinh() {
		if (_hanhTrinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _hanhTrinh;
		}
	}

	@Override
	public void setHanhTrinh(String hanhTrinh) {
		_hanhTrinh = hanhTrinh;
	}

	@JSON
	@Override
	public String getMucPhi() {
		if (_mucPhi == null) {
			return StringPool.BLANK;
		}
		else {
			return _mucPhi;
		}
	}

	@Override
	public void setMucPhi(String mucPhi) {
		_mucPhi = mucPhi;
	}

	@JSON
	@Override
	public String getMucDichChuyenDi() {
		if (_mucDichChuyenDi == null) {
			return StringPool.BLANK;
		}
		else {
			return _mucDichChuyenDi;
		}
	}

	@Override
	public void setMucDichChuyenDi(String mucDichChuyenDi) {
		_mucDichChuyenDi = mucDichChuyenDi;
	}

	@JSON
	@Override
	public long getFileId() {
		return _fileId;
	}

	@Override
	public void setFileId(long fileId) {
		_fileId = fileId;
	}

	@JSON
	@Override
	public String getTrangThai() {
		if (_trangThai == null) {
			return StringPool.BLANK;
		}
		else {
			return _trangThai;
		}
	}

	@Override
	public void setTrangThai(String trangThai) {
		_trangThai = trangThai;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtCapPhepGpLienVan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtCapPhepGpLienVan toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtCapPhepGpLienVan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtCapPhepGpLienVanImpl qlvtCapPhepGpLienVanImpl = new QlvtCapPhepGpLienVanImpl();

		qlvtCapPhepGpLienVanImpl.setId(getId());
		qlvtCapPhepGpLienVanImpl.setGpkdvtVietLaoId(getGpkdvtVietLaoId());
		qlvtCapPhepGpLienVanImpl.setLoaiCapPhep(getLoaiCapPhep());
		qlvtCapPhepGpLienVanImpl.setLoaiGiayPhepLienVan(getLoaiGiayPhepLienVan());
		qlvtCapPhepGpLienVanImpl.setSoGiayPhepLienVan(getSoGiayPhepLienVan());
		qlvtCapPhepGpLienVanImpl.setNgayCapGplv(getNgayCapGplv());
		qlvtCapPhepGpLienVanImpl.setNgayHetHanGplv(getNgayHetHanGplv());
		qlvtCapPhepGpLienVanImpl.setCoQuanCpLienVan(getCoQuanCpLienVan());
		qlvtCapPhepGpLienVanImpl.setSoCongVanChapThuanTCD(getSoCongVanChapThuanTCD());
		qlvtCapPhepGpLienVanImpl.setNgayCongVanChapThuanTCD(getNgayCongVanChapThuanTCD());
		qlvtCapPhepGpLienVanImpl.setTuyenTu(getTuyenTu());
		qlvtCapPhepGpLienVanImpl.setTuyenDi(getTuyenDi());
		qlvtCapPhepGpLienVanImpl.setCuLy(getCuLy());
		qlvtCapPhepGpLienVanImpl.setMaBenDi(getMaBenDi());
		qlvtCapPhepGpLienVanImpl.setMaBenDen(getMaBenDen());
		qlvtCapPhepGpLienVanImpl.setMaTinhDi(getMaTinhDi());
		qlvtCapPhepGpLienVanImpl.setMaTinhDen(getMaTinhDen());
		qlvtCapPhepGpLienVanImpl.setHanhTrinh(getHanhTrinh());
		qlvtCapPhepGpLienVanImpl.setMucPhi(getMucPhi());
		qlvtCapPhepGpLienVanImpl.setMucDichChuyenDi(getMucDichChuyenDi());
		qlvtCapPhepGpLienVanImpl.setFileId(getFileId());
		qlvtCapPhepGpLienVanImpl.setTrangThai(getTrangThai());

		qlvtCapPhepGpLienVanImpl.resetOriginalValues();

		return qlvtCapPhepGpLienVanImpl;
	}

	@Override
	public int compareTo(QlvtCapPhepGpLienVan qlvtCapPhepGpLienVan) {
		int value = 0;

		if (getId() < qlvtCapPhepGpLienVan.getId()) {
			value = -1;
		}
		else if (getId() > qlvtCapPhepGpLienVan.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtCapPhepGpLienVan)) {
			return false;
		}

		QlvtCapPhepGpLienVan qlvtCapPhepGpLienVan = (QlvtCapPhepGpLienVan)obj;

		long primaryKey = qlvtCapPhepGpLienVan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QlvtCapPhepGpLienVan> toCacheModel() {
		QlvtCapPhepGpLienVanCacheModel qlvtCapPhepGpLienVanCacheModel = new QlvtCapPhepGpLienVanCacheModel();

		qlvtCapPhepGpLienVanCacheModel.id = getId();

		qlvtCapPhepGpLienVanCacheModel.gpkdvtVietLaoId = getGpkdvtVietLaoId();

		qlvtCapPhepGpLienVanCacheModel.loaiCapPhep = getLoaiCapPhep();

		String loaiCapPhep = qlvtCapPhepGpLienVanCacheModel.loaiCapPhep;

		if ((loaiCapPhep != null) && (loaiCapPhep.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.loaiCapPhep = null;
		}

		qlvtCapPhepGpLienVanCacheModel.loaiGiayPhepLienVan = getLoaiGiayPhepLienVan();

		String loaiGiayPhepLienVan = qlvtCapPhepGpLienVanCacheModel.loaiGiayPhepLienVan;

		if ((loaiGiayPhepLienVan != null) &&
				(loaiGiayPhepLienVan.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.loaiGiayPhepLienVan = null;
		}

		qlvtCapPhepGpLienVanCacheModel.soGiayPhepLienVan = getSoGiayPhepLienVan();

		String soGiayPhepLienVan = qlvtCapPhepGpLienVanCacheModel.soGiayPhepLienVan;

		if ((soGiayPhepLienVan != null) && (soGiayPhepLienVan.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.soGiayPhepLienVan = null;
		}

		Date ngayCapGplv = getNgayCapGplv();

		if (ngayCapGplv != null) {
			qlvtCapPhepGpLienVanCacheModel.ngayCapGplv = ngayCapGplv.getTime();
		}
		else {
			qlvtCapPhepGpLienVanCacheModel.ngayCapGplv = Long.MIN_VALUE;
		}

		Date ngayHetHanGplv = getNgayHetHanGplv();

		if (ngayHetHanGplv != null) {
			qlvtCapPhepGpLienVanCacheModel.ngayHetHanGplv = ngayHetHanGplv.getTime();
		}
		else {
			qlvtCapPhepGpLienVanCacheModel.ngayHetHanGplv = Long.MIN_VALUE;
		}

		qlvtCapPhepGpLienVanCacheModel.coQuanCpLienVan = getCoQuanCpLienVan();

		String coQuanCpLienVan = qlvtCapPhepGpLienVanCacheModel.coQuanCpLienVan;

		if ((coQuanCpLienVan != null) && (coQuanCpLienVan.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.coQuanCpLienVan = null;
		}

		qlvtCapPhepGpLienVanCacheModel.soCongVanChapThuanTCD = getSoCongVanChapThuanTCD();

		String soCongVanChapThuanTCD = qlvtCapPhepGpLienVanCacheModel.soCongVanChapThuanTCD;

		if ((soCongVanChapThuanTCD != null) &&
				(soCongVanChapThuanTCD.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.soCongVanChapThuanTCD = null;
		}

		Date ngayCongVanChapThuanTCD = getNgayCongVanChapThuanTCD();

		if (ngayCongVanChapThuanTCD != null) {
			qlvtCapPhepGpLienVanCacheModel.ngayCongVanChapThuanTCD = ngayCongVanChapThuanTCD.getTime();
		}
		else {
			qlvtCapPhepGpLienVanCacheModel.ngayCongVanChapThuanTCD = Long.MIN_VALUE;
		}

		qlvtCapPhepGpLienVanCacheModel.tuyenTu = getTuyenTu();

		String tuyenTu = qlvtCapPhepGpLienVanCacheModel.tuyenTu;

		if ((tuyenTu != null) && (tuyenTu.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.tuyenTu = null;
		}

		qlvtCapPhepGpLienVanCacheModel.tuyenDi = getTuyenDi();

		String tuyenDi = qlvtCapPhepGpLienVanCacheModel.tuyenDi;

		if ((tuyenDi != null) && (tuyenDi.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.tuyenDi = null;
		}

		qlvtCapPhepGpLienVanCacheModel.cuLy = getCuLy();

		String cuLy = qlvtCapPhepGpLienVanCacheModel.cuLy;

		if ((cuLy != null) && (cuLy.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.cuLy = null;
		}

		qlvtCapPhepGpLienVanCacheModel.maBenDi = getMaBenDi();

		String maBenDi = qlvtCapPhepGpLienVanCacheModel.maBenDi;

		if ((maBenDi != null) && (maBenDi.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.maBenDi = null;
		}

		qlvtCapPhepGpLienVanCacheModel.maBenDen = getMaBenDen();

		String maBenDen = qlvtCapPhepGpLienVanCacheModel.maBenDen;

		if ((maBenDen != null) && (maBenDen.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.maBenDen = null;
		}

		qlvtCapPhepGpLienVanCacheModel.maTinhDi = getMaTinhDi();

		String maTinhDi = qlvtCapPhepGpLienVanCacheModel.maTinhDi;

		if ((maTinhDi != null) && (maTinhDi.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.maTinhDi = null;
		}

		qlvtCapPhepGpLienVanCacheModel.maTinhDen = getMaTinhDen();

		String maTinhDen = qlvtCapPhepGpLienVanCacheModel.maTinhDen;

		if ((maTinhDen != null) && (maTinhDen.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.maTinhDen = null;
		}

		qlvtCapPhepGpLienVanCacheModel.hanhTrinh = getHanhTrinh();

		String hanhTrinh = qlvtCapPhepGpLienVanCacheModel.hanhTrinh;

		if ((hanhTrinh != null) && (hanhTrinh.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.hanhTrinh = null;
		}

		qlvtCapPhepGpLienVanCacheModel.mucPhi = getMucPhi();

		String mucPhi = qlvtCapPhepGpLienVanCacheModel.mucPhi;

		if ((mucPhi != null) && (mucPhi.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.mucPhi = null;
		}

		qlvtCapPhepGpLienVanCacheModel.mucDichChuyenDi = getMucDichChuyenDi();

		String mucDichChuyenDi = qlvtCapPhepGpLienVanCacheModel.mucDichChuyenDi;

		if ((mucDichChuyenDi != null) && (mucDichChuyenDi.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.mucDichChuyenDi = null;
		}

		qlvtCapPhepGpLienVanCacheModel.fileId = getFileId();

		qlvtCapPhepGpLienVanCacheModel.trangThai = getTrangThai();

		String trangThai = qlvtCapPhepGpLienVanCacheModel.trangThai;

		if ((trangThai != null) && (trangThai.length() == 0)) {
			qlvtCapPhepGpLienVanCacheModel.trangThai = null;
		}

		return qlvtCapPhepGpLienVanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(45);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", gpkdvtVietLaoId=");
		sb.append(getGpkdvtVietLaoId());
		sb.append(", loaiCapPhep=");
		sb.append(getLoaiCapPhep());
		sb.append(", loaiGiayPhepLienVan=");
		sb.append(getLoaiGiayPhepLienVan());
		sb.append(", soGiayPhepLienVan=");
		sb.append(getSoGiayPhepLienVan());
		sb.append(", ngayCapGplv=");
		sb.append(getNgayCapGplv());
		sb.append(", ngayHetHanGplv=");
		sb.append(getNgayHetHanGplv());
		sb.append(", coQuanCpLienVan=");
		sb.append(getCoQuanCpLienVan());
		sb.append(", soCongVanChapThuanTCD=");
		sb.append(getSoCongVanChapThuanTCD());
		sb.append(", ngayCongVanChapThuanTCD=");
		sb.append(getNgayCongVanChapThuanTCD());
		sb.append(", tuyenTu=");
		sb.append(getTuyenTu());
		sb.append(", tuyenDi=");
		sb.append(getTuyenDi());
		sb.append(", cuLy=");
		sb.append(getCuLy());
		sb.append(", maBenDi=");
		sb.append(getMaBenDi());
		sb.append(", maBenDen=");
		sb.append(getMaBenDen());
		sb.append(", maTinhDi=");
		sb.append(getMaTinhDi());
		sb.append(", maTinhDen=");
		sb.append(getMaTinhDen());
		sb.append(", hanhTrinh=");
		sb.append(getHanhTrinh());
		sb.append(", mucPhi=");
		sb.append(getMucPhi());
		sb.append(", mucDichChuyenDi=");
		sb.append(getMucDichChuyenDi());
		sb.append(", fileId=");
		sb.append(getFileId());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(70);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.lienvan.model.QlvtCapPhepGpLienVan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gpkdvtVietLaoId</column-name><column-value><![CDATA[");
		sb.append(getGpkdvtVietLaoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiCapPhep</column-name><column-value><![CDATA[");
		sb.append(getLoaiCapPhep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiGiayPhepLienVan</column-name><column-value><![CDATA[");
		sb.append(getLoaiGiayPhepLienVan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGiayPhepLienVan</column-name><column-value><![CDATA[");
		sb.append(getSoGiayPhepLienVan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGplv</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGplv());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHanGplv</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHanGplv());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCpLienVan</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCpLienVan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soCongVanChapThuanTCD</column-name><column-value><![CDATA[");
		sb.append(getSoCongVanChapThuanTCD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCongVanChapThuanTCD</column-name><column-value><![CDATA[");
		sb.append(getNgayCongVanChapThuanTCD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tuyenTu</column-name><column-value><![CDATA[");
		sb.append(getTuyenTu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tuyenDi</column-name><column-value><![CDATA[");
		sb.append(getTuyenDi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cuLy</column-name><column-value><![CDATA[");
		sb.append(getCuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maBenDi</column-name><column-value><![CDATA[");
		sb.append(getMaBenDi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maBenDen</column-name><column-value><![CDATA[");
		sb.append(getMaBenDen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinhDi</column-name><column-value><![CDATA[");
		sb.append(getMaTinhDi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinhDen</column-name><column-value><![CDATA[");
		sb.append(getMaTinhDen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hanhTrinh</column-name><column-value><![CDATA[");
		sb.append(getHanhTrinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mucPhi</column-name><column-value><![CDATA[");
		sb.append(getMucPhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mucDichChuyenDi</column-name><column-value><![CDATA[");
		sb.append(getMucDichChuyenDi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileId</column-name><column-value><![CDATA[");
		sb.append(getFileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtCapPhepGpLienVan.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtCapPhepGpLienVan.class
		};
	private long _id;
	private long _gpkdvtVietLaoId;
	private String _loaiCapPhep;
	private String _loaiGiayPhepLienVan;
	private String _soGiayPhepLienVan;
	private Date _ngayCapGplv;
	private Date _ngayHetHanGplv;
	private String _coQuanCpLienVan;
	private String _soCongVanChapThuanTCD;
	private Date _ngayCongVanChapThuanTCD;
	private String _tuyenTu;
	private String _tuyenDi;
	private String _cuLy;
	private String _maBenDi;
	private String _maBenDen;
	private String _maTinhDi;
	private String _maTinhDen;
	private String _hanhTrinh;
	private String _mucPhi;
	private String _mucDichChuyenDi;
	private long _fileId;
	private String _trangThai;
	private QlvtCapPhepGpLienVan _escapedModel;
}