/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.lienvan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVan;
import vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVanModel;
import vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVanSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QlvtXuLyGpLienVan service. Represents a row in the &quot;qlvt_xuly_gplienvan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtXuLyGpLienVanImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtXuLyGpLienVanImpl
 * @see vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVan
 * @see vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVanModel
 * @generated
 */
@JSON(strict = true)
public class QlvtXuLyGpLienVanModelImpl extends BaseModelImpl<QlvtXuLyGpLienVan>
	implements QlvtXuLyGpLienVanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt xu ly gp lien van model instance should use the {@link vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVan} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_xuly_gplienvan";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "THONGTINXULYID", Types.BIGINT },
			{ "LOAICAPPHEP", Types.VARCHAR },
			{ "SOGPVT", Types.VARCHAR },
			{ "NGAYCAP_GPVT", Types.TIMESTAMP },
			{ "SOCONGVANCHAPTHUANTCD", Types.VARCHAR },
			{ "NGAYCONGVANCHAPTHUANTCD", Types.TIMESTAMP },
			{ "TUYENTU", Types.VARCHAR },
			{ "TUYENDI", Types.VARCHAR },
			{ "CULY", Types.VARCHAR },
			{ "MABENDI", Types.VARCHAR },
			{ "MABENDEN", Types.VARCHAR },
			{ "MATINHDI", Types.VARCHAR },
			{ "MATINHDEN", Types.VARCHAR },
			{ "HANHTRINH", Types.VARCHAR },
			{ "MUCPHI", Types.VARCHAR },
			{ "MUCDICHCHUYENDI", Types.VARCHAR },
			{ "LOAIGIAYPHEPLIENVAN", Types.VARCHAR },
			{ "SOGIAYPHEPLIENVAN", Types.VARCHAR },
			{ "NGAYCAPGIAYPHEPLIENVAN", Types.TIMESTAMP },
			{ "NGAYHETHANGIAYPHEPLIENVAN", Types.TIMESTAMP },
			{ "COQUANCAPPHEPLIENVAN", Types.VARCHAR },
			{ "KETQUAXULY", Types.VARCHAR },
			{ "LYDOKHONGDAT", Types.VARCHAR },
			{ "NGAYCAPGIAYPHEPLIENVAN_LANDAU", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_xuly_gplienvan (ID LONG not null primary key,THONGTINXULYID LONG,LOAICAPPHEP VARCHAR(75) null,SOGPVT VARCHAR(75) null,NGAYCAP_GPVT DATE null,SOCONGVANCHAPTHUANTCD VARCHAR(75) null,NGAYCONGVANCHAPTHUANTCD DATE null,TUYENTU VARCHAR(75) null,TUYENDI VARCHAR(75) null,CULY VARCHAR(75) null,MABENDI VARCHAR(75) null,MABENDEN VARCHAR(75) null,MATINHDI VARCHAR(75) null,MATINHDEN VARCHAR(75) null,HANHTRINH VARCHAR(75) null,MUCPHI VARCHAR(75) null,MUCDICHCHUYENDI VARCHAR(75) null,LOAIGIAYPHEPLIENVAN VARCHAR(75) null,SOGIAYPHEPLIENVAN VARCHAR(75) null,NGAYCAPGIAYPHEPLIENVAN DATE null,NGAYHETHANGIAYPHEPLIENVAN DATE null,COQUANCAPPHEPLIENVAN VARCHAR(75) null,KETQUAXULY VARCHAR(75) null,LYDOKHONGDAT VARCHAR(75) null,NGAYCAPGIAYPHEPLIENVAN_LANDAU DATE null)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_xuly_gplienvan";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtXuLyGpLienVan.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_xuly_gplienvan.ID ASC";
	public static final String DATA_SOURCE = "nghiepvuDataSource";
	public static final String SESSION_FACTORY = "nghiepvuSessionFactory";
	public static final String TX_MANAGER = "nghiepvuTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVan"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVan"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVan"),
			true);
	public static long THONGTINXULYID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static QlvtXuLyGpLienVan toModel(QlvtXuLyGpLienVanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		QlvtXuLyGpLienVan model = new QlvtXuLyGpLienVanImpl();

		model.setId(soapModel.getId());
		model.setThongTinXuLyId(soapModel.getThongTinXuLyId());
		model.setLoaiCapPhep(soapModel.getLoaiCapPhep());
		model.setSoGpvt(soapModel.getSoGpvt());
		model.setNgayCapGpvt(soapModel.getNgayCapGpvt());
		model.setSoCongVanChapThuanTcd(soapModel.getSoCongVanChapThuanTcd());
		model.setNgayCongVanChapThuanTCD(soapModel.getNgayCongVanChapThuanTCD());
		model.setTuyenTu(soapModel.getTuyenTu());
		model.setTuyenDi(soapModel.getTuyenDi());
		model.setCuLy(soapModel.getCuLy());
		model.setMaBenDi(soapModel.getMaBenDi());
		model.setMaBenDen(soapModel.getMaBenDen());
		model.setMaTinhDi(soapModel.getMaTinhDi());
		model.setMaTinhDen(soapModel.getMaTinhDen());
		model.setHanhTrinh(soapModel.getHanhTrinh());
		model.setMucPhi(soapModel.getMucPhi());
		model.setMucDichChuyenDi(soapModel.getMucDichChuyenDi());
		model.setLoaiGiayPhepLienVan(soapModel.getLoaiGiayPhepLienVan());
		model.setSoGiayPhepLienVan(soapModel.getSoGiayPhepLienVan());
		model.setNgayCapGiayPhepLienVan(soapModel.getNgayCapGiayPhepLienVan());
		model.setNgayHetHanGiayPhepLienVan(soapModel.getNgayHetHanGiayPhepLienVan());
		model.setCoQuanCapPhepLienVan(soapModel.getCoQuanCapPhepLienVan());
		model.setKetQuaXuLy(soapModel.getKetQuaXuLy());
		model.setLyDoKhongDat(soapModel.getLyDoKhongDat());
		model.setNgayCapGiayPhepLienVan_LanDau(soapModel.getNgayCapGiayPhepLienVan_LanDau());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<QlvtXuLyGpLienVan> toModels(
		QlvtXuLyGpLienVanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<QlvtXuLyGpLienVan> models = new ArrayList<QlvtXuLyGpLienVan>(soapModels.length);

		for (QlvtXuLyGpLienVanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVan"));

	public QlvtXuLyGpLienVanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtXuLyGpLienVan.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtXuLyGpLienVan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thongTinXuLyId", getThongTinXuLyId());
		attributes.put("loaiCapPhep", getLoaiCapPhep());
		attributes.put("soGpvt", getSoGpvt());
		attributes.put("ngayCapGpvt", getNgayCapGpvt());
		attributes.put("soCongVanChapThuanTcd", getSoCongVanChapThuanTcd());
		attributes.put("ngayCongVanChapThuanTCD", getNgayCongVanChapThuanTCD());
		attributes.put("tuyenTu", getTuyenTu());
		attributes.put("tuyenDi", getTuyenDi());
		attributes.put("cuLy", getCuLy());
		attributes.put("maBenDi", getMaBenDi());
		attributes.put("maBenDen", getMaBenDen());
		attributes.put("maTinhDi", getMaTinhDi());
		attributes.put("maTinhDen", getMaTinhDen());
		attributes.put("hanhTrinh", getHanhTrinh());
		attributes.put("mucPhi", getMucPhi());
		attributes.put("mucDichChuyenDi", getMucDichChuyenDi());
		attributes.put("loaiGiayPhepLienVan", getLoaiGiayPhepLienVan());
		attributes.put("soGiayPhepLienVan", getSoGiayPhepLienVan());
		attributes.put("ngayCapGiayPhepLienVan", getNgayCapGiayPhepLienVan());
		attributes.put("ngayHetHanGiayPhepLienVan",
			getNgayHetHanGiayPhepLienVan());
		attributes.put("coQuanCapPhepLienVan", getCoQuanCapPhepLienVan());
		attributes.put("ketQuaXuLy", getKetQuaXuLy());
		attributes.put("lyDoKhongDat", getLyDoKhongDat());
		attributes.put("ngayCapGiayPhepLienVan_LanDau",
			getNgayCapGiayPhepLienVan_LanDau());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long thongTinXuLyId = (Long)attributes.get("thongTinXuLyId");

		if (thongTinXuLyId != null) {
			setThongTinXuLyId(thongTinXuLyId);
		}

		String loaiCapPhep = (String)attributes.get("loaiCapPhep");

		if (loaiCapPhep != null) {
			setLoaiCapPhep(loaiCapPhep);
		}

		String soGpvt = (String)attributes.get("soGpvt");

		if (soGpvt != null) {
			setSoGpvt(soGpvt);
		}

		Date ngayCapGpvt = (Date)attributes.get("ngayCapGpvt");

		if (ngayCapGpvt != null) {
			setNgayCapGpvt(ngayCapGpvt);
		}

		String soCongVanChapThuanTcd = (String)attributes.get(
				"soCongVanChapThuanTcd");

		if (soCongVanChapThuanTcd != null) {
			setSoCongVanChapThuanTcd(soCongVanChapThuanTcd);
		}

		Date ngayCongVanChapThuanTCD = (Date)attributes.get(
				"ngayCongVanChapThuanTCD");

		if (ngayCongVanChapThuanTCD != null) {
			setNgayCongVanChapThuanTCD(ngayCongVanChapThuanTCD);
		}

		String tuyenTu = (String)attributes.get("tuyenTu");

		if (tuyenTu != null) {
			setTuyenTu(tuyenTu);
		}

		String tuyenDi = (String)attributes.get("tuyenDi");

		if (tuyenDi != null) {
			setTuyenDi(tuyenDi);
		}

		String cuLy = (String)attributes.get("cuLy");

		if (cuLy != null) {
			setCuLy(cuLy);
		}

		String maBenDi = (String)attributes.get("maBenDi");

		if (maBenDi != null) {
			setMaBenDi(maBenDi);
		}

		String maBenDen = (String)attributes.get("maBenDen");

		if (maBenDen != null) {
			setMaBenDen(maBenDen);
		}

		String maTinhDi = (String)attributes.get("maTinhDi");

		if (maTinhDi != null) {
			setMaTinhDi(maTinhDi);
		}

		String maTinhDen = (String)attributes.get("maTinhDen");

		if (maTinhDen != null) {
			setMaTinhDen(maTinhDen);
		}

		String hanhTrinh = (String)attributes.get("hanhTrinh");

		if (hanhTrinh != null) {
			setHanhTrinh(hanhTrinh);
		}

		String mucPhi = (String)attributes.get("mucPhi");

		if (mucPhi != null) {
			setMucPhi(mucPhi);
		}

		String mucDichChuyenDi = (String)attributes.get("mucDichChuyenDi");

		if (mucDichChuyenDi != null) {
			setMucDichChuyenDi(mucDichChuyenDi);
		}

		String loaiGiayPhepLienVan = (String)attributes.get(
				"loaiGiayPhepLienVan");

		if (loaiGiayPhepLienVan != null) {
			setLoaiGiayPhepLienVan(loaiGiayPhepLienVan);
		}

		String soGiayPhepLienVan = (String)attributes.get("soGiayPhepLienVan");

		if (soGiayPhepLienVan != null) {
			setSoGiayPhepLienVan(soGiayPhepLienVan);
		}

		Date ngayCapGiayPhepLienVan = (Date)attributes.get(
				"ngayCapGiayPhepLienVan");

		if (ngayCapGiayPhepLienVan != null) {
			setNgayCapGiayPhepLienVan(ngayCapGiayPhepLienVan);
		}

		Date ngayHetHanGiayPhepLienVan = (Date)attributes.get(
				"ngayHetHanGiayPhepLienVan");

		if (ngayHetHanGiayPhepLienVan != null) {
			setNgayHetHanGiayPhepLienVan(ngayHetHanGiayPhepLienVan);
		}

		String coQuanCapPhepLienVan = (String)attributes.get(
				"coQuanCapPhepLienVan");

		if (coQuanCapPhepLienVan != null) {
			setCoQuanCapPhepLienVan(coQuanCapPhepLienVan);
		}

		String ketQuaXuLy = (String)attributes.get("ketQuaXuLy");

		if (ketQuaXuLy != null) {
			setKetQuaXuLy(ketQuaXuLy);
		}

		String lyDoKhongDat = (String)attributes.get("lyDoKhongDat");

		if (lyDoKhongDat != null) {
			setLyDoKhongDat(lyDoKhongDat);
		}

		Date ngayCapGiayPhepLienVan_LanDau = (Date)attributes.get(
				"ngayCapGiayPhepLienVan_LanDau");

		if (ngayCapGiayPhepLienVan_LanDau != null) {
			setNgayCapGiayPhepLienVan_LanDau(ngayCapGiayPhepLienVan_LanDau);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getThongTinXuLyId() {
		return _thongTinXuLyId;
	}

	@Override
	public void setThongTinXuLyId(long thongTinXuLyId) {
		_columnBitmask |= THONGTINXULYID_COLUMN_BITMASK;

		if (!_setOriginalThongTinXuLyId) {
			_setOriginalThongTinXuLyId = true;

			_originalThongTinXuLyId = _thongTinXuLyId;
		}

		_thongTinXuLyId = thongTinXuLyId;
	}

	public long getOriginalThongTinXuLyId() {
		return _originalThongTinXuLyId;
	}

	@JSON
	@Override
	public String getLoaiCapPhep() {
		if (_loaiCapPhep == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiCapPhep;
		}
	}

	@Override
	public void setLoaiCapPhep(String loaiCapPhep) {
		_loaiCapPhep = loaiCapPhep;
	}

	@JSON
	@Override
	public String getSoGpvt() {
		if (_soGpvt == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGpvt;
		}
	}

	@Override
	public void setSoGpvt(String soGpvt) {
		_soGpvt = soGpvt;
	}

	@JSON
	@Override
	public Date getNgayCapGpvt() {
		return _ngayCapGpvt;
	}

	@Override
	public void setNgayCapGpvt(Date ngayCapGpvt) {
		_ngayCapGpvt = ngayCapGpvt;
	}

	@JSON
	@Override
	public String getSoCongVanChapThuanTcd() {
		if (_soCongVanChapThuanTcd == null) {
			return StringPool.BLANK;
		}
		else {
			return _soCongVanChapThuanTcd;
		}
	}

	@Override
	public void setSoCongVanChapThuanTcd(String soCongVanChapThuanTcd) {
		_soCongVanChapThuanTcd = soCongVanChapThuanTcd;
	}

	@JSON
	@Override
	public Date getNgayCongVanChapThuanTCD() {
		return _ngayCongVanChapThuanTCD;
	}

	@Override
	public void setNgayCongVanChapThuanTCD(Date ngayCongVanChapThuanTCD) {
		_ngayCongVanChapThuanTCD = ngayCongVanChapThuanTCD;
	}

	@JSON
	@Override
	public String getTuyenTu() {
		if (_tuyenTu == null) {
			return StringPool.BLANK;
		}
		else {
			return _tuyenTu;
		}
	}

	@Override
	public void setTuyenTu(String tuyenTu) {
		_tuyenTu = tuyenTu;
	}

	@JSON
	@Override
	public String getTuyenDi() {
		if (_tuyenDi == null) {
			return StringPool.BLANK;
		}
		else {
			return _tuyenDi;
		}
	}

	@Override
	public void setTuyenDi(String tuyenDi) {
		_tuyenDi = tuyenDi;
	}

	@JSON
	@Override
	public String getCuLy() {
		if (_cuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _cuLy;
		}
	}

	@Override
	public void setCuLy(String cuLy) {
		_cuLy = cuLy;
	}

	@JSON
	@Override
	public String getMaBenDi() {
		if (_maBenDi == null) {
			return StringPool.BLANK;
		}
		else {
			return _maBenDi;
		}
	}

	@Override
	public void setMaBenDi(String maBenDi) {
		_maBenDi = maBenDi;
	}

	@JSON
	@Override
	public String getMaBenDen() {
		if (_maBenDen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maBenDen;
		}
	}

	@Override
	public void setMaBenDen(String maBenDen) {
		_maBenDen = maBenDen;
	}

	@JSON
	@Override
	public String getMaTinhDi() {
		if (_maTinhDi == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinhDi;
		}
	}

	@Override
	public void setMaTinhDi(String maTinhDi) {
		_maTinhDi = maTinhDi;
	}

	@JSON
	@Override
	public String getMaTinhDen() {
		if (_maTinhDen == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTinhDen;
		}
	}

	@Override
	public void setMaTinhDen(String maTinhDen) {
		_maTinhDen = maTinhDen;
	}

	@JSON
	@Override
	public String getHanhTrinh() {
		if (_hanhTrinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _hanhTrinh;
		}
	}

	@Override
	public void setHanhTrinh(String hanhTrinh) {
		_hanhTrinh = hanhTrinh;
	}

	@JSON
	@Override
	public String getMucPhi() {
		if (_mucPhi == null) {
			return StringPool.BLANK;
		}
		else {
			return _mucPhi;
		}
	}

	@Override
	public void setMucPhi(String mucPhi) {
		_mucPhi = mucPhi;
	}

	@JSON
	@Override
	public String getMucDichChuyenDi() {
		if (_mucDichChuyenDi == null) {
			return StringPool.BLANK;
		}
		else {
			return _mucDichChuyenDi;
		}
	}

	@Override
	public void setMucDichChuyenDi(String mucDichChuyenDi) {
		_mucDichChuyenDi = mucDichChuyenDi;
	}

	@JSON
	@Override
	public String getLoaiGiayPhepLienVan() {
		if (_loaiGiayPhepLienVan == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiGiayPhepLienVan;
		}
	}

	@Override
	public void setLoaiGiayPhepLienVan(String loaiGiayPhepLienVan) {
		_loaiGiayPhepLienVan = loaiGiayPhepLienVan;
	}

	@JSON
	@Override
	public String getSoGiayPhepLienVan() {
		if (_soGiayPhepLienVan == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGiayPhepLienVan;
		}
	}

	@Override
	public void setSoGiayPhepLienVan(String soGiayPhepLienVan) {
		_soGiayPhepLienVan = soGiayPhepLienVan;
	}

	@JSON
	@Override
	public Date getNgayCapGiayPhepLienVan() {
		return _ngayCapGiayPhepLienVan;
	}

	@Override
	public void setNgayCapGiayPhepLienVan(Date ngayCapGiayPhepLienVan) {
		_ngayCapGiayPhepLienVan = ngayCapGiayPhepLienVan;
	}

	@JSON
	@Override
	public Date getNgayHetHanGiayPhepLienVan() {
		return _ngayHetHanGiayPhepLienVan;
	}

	@Override
	public void setNgayHetHanGiayPhepLienVan(Date ngayHetHanGiayPhepLienVan) {
		_ngayHetHanGiayPhepLienVan = ngayHetHanGiayPhepLienVan;
	}

	@JSON
	@Override
	public String getCoQuanCapPhepLienVan() {
		if (_coQuanCapPhepLienVan == null) {
			return StringPool.BLANK;
		}
		else {
			return _coQuanCapPhepLienVan;
		}
	}

	@Override
	public void setCoQuanCapPhepLienVan(String coQuanCapPhepLienVan) {
		_coQuanCapPhepLienVan = coQuanCapPhepLienVan;
	}

	@JSON
	@Override
	public String getKetQuaXuLy() {
		if (_ketQuaXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ketQuaXuLy;
		}
	}

	@Override
	public void setKetQuaXuLy(String ketQuaXuLy) {
		_ketQuaXuLy = ketQuaXuLy;
	}

	@JSON
	@Override
	public String getLyDoKhongDat() {
		if (_lyDoKhongDat == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoKhongDat;
		}
	}

	@Override
	public void setLyDoKhongDat(String lyDoKhongDat) {
		_lyDoKhongDat = lyDoKhongDat;
	}

	@JSON
	@Override
	public Date getNgayCapGiayPhepLienVan_LanDau() {
		return _ngayCapGiayPhepLienVan_LanDau;
	}

	@Override
	public void setNgayCapGiayPhepLienVan_LanDau(
		Date ngayCapGiayPhepLienVan_LanDau) {
		_ngayCapGiayPhepLienVan_LanDau = ngayCapGiayPhepLienVan_LanDau;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtXuLyGpLienVan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtXuLyGpLienVan toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtXuLyGpLienVan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtXuLyGpLienVanImpl qlvtXuLyGpLienVanImpl = new QlvtXuLyGpLienVanImpl();

		qlvtXuLyGpLienVanImpl.setId(getId());
		qlvtXuLyGpLienVanImpl.setThongTinXuLyId(getThongTinXuLyId());
		qlvtXuLyGpLienVanImpl.setLoaiCapPhep(getLoaiCapPhep());
		qlvtXuLyGpLienVanImpl.setSoGpvt(getSoGpvt());
		qlvtXuLyGpLienVanImpl.setNgayCapGpvt(getNgayCapGpvt());
		qlvtXuLyGpLienVanImpl.setSoCongVanChapThuanTcd(getSoCongVanChapThuanTcd());
		qlvtXuLyGpLienVanImpl.setNgayCongVanChapThuanTCD(getNgayCongVanChapThuanTCD());
		qlvtXuLyGpLienVanImpl.setTuyenTu(getTuyenTu());
		qlvtXuLyGpLienVanImpl.setTuyenDi(getTuyenDi());
		qlvtXuLyGpLienVanImpl.setCuLy(getCuLy());
		qlvtXuLyGpLienVanImpl.setMaBenDi(getMaBenDi());
		qlvtXuLyGpLienVanImpl.setMaBenDen(getMaBenDen());
		qlvtXuLyGpLienVanImpl.setMaTinhDi(getMaTinhDi());
		qlvtXuLyGpLienVanImpl.setMaTinhDen(getMaTinhDen());
		qlvtXuLyGpLienVanImpl.setHanhTrinh(getHanhTrinh());
		qlvtXuLyGpLienVanImpl.setMucPhi(getMucPhi());
		qlvtXuLyGpLienVanImpl.setMucDichChuyenDi(getMucDichChuyenDi());
		qlvtXuLyGpLienVanImpl.setLoaiGiayPhepLienVan(getLoaiGiayPhepLienVan());
		qlvtXuLyGpLienVanImpl.setSoGiayPhepLienVan(getSoGiayPhepLienVan());
		qlvtXuLyGpLienVanImpl.setNgayCapGiayPhepLienVan(getNgayCapGiayPhepLienVan());
		qlvtXuLyGpLienVanImpl.setNgayHetHanGiayPhepLienVan(getNgayHetHanGiayPhepLienVan());
		qlvtXuLyGpLienVanImpl.setCoQuanCapPhepLienVan(getCoQuanCapPhepLienVan());
		qlvtXuLyGpLienVanImpl.setKetQuaXuLy(getKetQuaXuLy());
		qlvtXuLyGpLienVanImpl.setLyDoKhongDat(getLyDoKhongDat());
		qlvtXuLyGpLienVanImpl.setNgayCapGiayPhepLienVan_LanDau(getNgayCapGiayPhepLienVan_LanDau());

		qlvtXuLyGpLienVanImpl.resetOriginalValues();

		return qlvtXuLyGpLienVanImpl;
	}

	@Override
	public int compareTo(QlvtXuLyGpLienVan qlvtXuLyGpLienVan) {
		int value = 0;

		if (getId() < qlvtXuLyGpLienVan.getId()) {
			value = -1;
		}
		else if (getId() > qlvtXuLyGpLienVan.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtXuLyGpLienVan)) {
			return false;
		}

		QlvtXuLyGpLienVan qlvtXuLyGpLienVan = (QlvtXuLyGpLienVan)obj;

		long primaryKey = qlvtXuLyGpLienVan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		QlvtXuLyGpLienVanModelImpl qlvtXuLyGpLienVanModelImpl = this;

		qlvtXuLyGpLienVanModelImpl._originalThongTinXuLyId = qlvtXuLyGpLienVanModelImpl._thongTinXuLyId;

		qlvtXuLyGpLienVanModelImpl._setOriginalThongTinXuLyId = false;

		qlvtXuLyGpLienVanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<QlvtXuLyGpLienVan> toCacheModel() {
		QlvtXuLyGpLienVanCacheModel qlvtXuLyGpLienVanCacheModel = new QlvtXuLyGpLienVanCacheModel();

		qlvtXuLyGpLienVanCacheModel.id = getId();

		qlvtXuLyGpLienVanCacheModel.thongTinXuLyId = getThongTinXuLyId();

		qlvtXuLyGpLienVanCacheModel.loaiCapPhep = getLoaiCapPhep();

		String loaiCapPhep = qlvtXuLyGpLienVanCacheModel.loaiCapPhep;

		if ((loaiCapPhep != null) && (loaiCapPhep.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.loaiCapPhep = null;
		}

		qlvtXuLyGpLienVanCacheModel.soGpvt = getSoGpvt();

		String soGpvt = qlvtXuLyGpLienVanCacheModel.soGpvt;

		if ((soGpvt != null) && (soGpvt.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.soGpvt = null;
		}

		Date ngayCapGpvt = getNgayCapGpvt();

		if (ngayCapGpvt != null) {
			qlvtXuLyGpLienVanCacheModel.ngayCapGpvt = ngayCapGpvt.getTime();
		}
		else {
			qlvtXuLyGpLienVanCacheModel.ngayCapGpvt = Long.MIN_VALUE;
		}

		qlvtXuLyGpLienVanCacheModel.soCongVanChapThuanTcd = getSoCongVanChapThuanTcd();

		String soCongVanChapThuanTcd = qlvtXuLyGpLienVanCacheModel.soCongVanChapThuanTcd;

		if ((soCongVanChapThuanTcd != null) &&
				(soCongVanChapThuanTcd.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.soCongVanChapThuanTcd = null;
		}

		Date ngayCongVanChapThuanTCD = getNgayCongVanChapThuanTCD();

		if (ngayCongVanChapThuanTCD != null) {
			qlvtXuLyGpLienVanCacheModel.ngayCongVanChapThuanTCD = ngayCongVanChapThuanTCD.getTime();
		}
		else {
			qlvtXuLyGpLienVanCacheModel.ngayCongVanChapThuanTCD = Long.MIN_VALUE;
		}

		qlvtXuLyGpLienVanCacheModel.tuyenTu = getTuyenTu();

		String tuyenTu = qlvtXuLyGpLienVanCacheModel.tuyenTu;

		if ((tuyenTu != null) && (tuyenTu.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.tuyenTu = null;
		}

		qlvtXuLyGpLienVanCacheModel.tuyenDi = getTuyenDi();

		String tuyenDi = qlvtXuLyGpLienVanCacheModel.tuyenDi;

		if ((tuyenDi != null) && (tuyenDi.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.tuyenDi = null;
		}

		qlvtXuLyGpLienVanCacheModel.cuLy = getCuLy();

		String cuLy = qlvtXuLyGpLienVanCacheModel.cuLy;

		if ((cuLy != null) && (cuLy.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.cuLy = null;
		}

		qlvtXuLyGpLienVanCacheModel.maBenDi = getMaBenDi();

		String maBenDi = qlvtXuLyGpLienVanCacheModel.maBenDi;

		if ((maBenDi != null) && (maBenDi.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.maBenDi = null;
		}

		qlvtXuLyGpLienVanCacheModel.maBenDen = getMaBenDen();

		String maBenDen = qlvtXuLyGpLienVanCacheModel.maBenDen;

		if ((maBenDen != null) && (maBenDen.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.maBenDen = null;
		}

		qlvtXuLyGpLienVanCacheModel.maTinhDi = getMaTinhDi();

		String maTinhDi = qlvtXuLyGpLienVanCacheModel.maTinhDi;

		if ((maTinhDi != null) && (maTinhDi.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.maTinhDi = null;
		}

		qlvtXuLyGpLienVanCacheModel.maTinhDen = getMaTinhDen();

		String maTinhDen = qlvtXuLyGpLienVanCacheModel.maTinhDen;

		if ((maTinhDen != null) && (maTinhDen.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.maTinhDen = null;
		}

		qlvtXuLyGpLienVanCacheModel.hanhTrinh = getHanhTrinh();

		String hanhTrinh = qlvtXuLyGpLienVanCacheModel.hanhTrinh;

		if ((hanhTrinh != null) && (hanhTrinh.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.hanhTrinh = null;
		}

		qlvtXuLyGpLienVanCacheModel.mucPhi = getMucPhi();

		String mucPhi = qlvtXuLyGpLienVanCacheModel.mucPhi;

		if ((mucPhi != null) && (mucPhi.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.mucPhi = null;
		}

		qlvtXuLyGpLienVanCacheModel.mucDichChuyenDi = getMucDichChuyenDi();

		String mucDichChuyenDi = qlvtXuLyGpLienVanCacheModel.mucDichChuyenDi;

		if ((mucDichChuyenDi != null) && (mucDichChuyenDi.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.mucDichChuyenDi = null;
		}

		qlvtXuLyGpLienVanCacheModel.loaiGiayPhepLienVan = getLoaiGiayPhepLienVan();

		String loaiGiayPhepLienVan = qlvtXuLyGpLienVanCacheModel.loaiGiayPhepLienVan;

		if ((loaiGiayPhepLienVan != null) &&
				(loaiGiayPhepLienVan.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.loaiGiayPhepLienVan = null;
		}

		qlvtXuLyGpLienVanCacheModel.soGiayPhepLienVan = getSoGiayPhepLienVan();

		String soGiayPhepLienVan = qlvtXuLyGpLienVanCacheModel.soGiayPhepLienVan;

		if ((soGiayPhepLienVan != null) && (soGiayPhepLienVan.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.soGiayPhepLienVan = null;
		}

		Date ngayCapGiayPhepLienVan = getNgayCapGiayPhepLienVan();

		if (ngayCapGiayPhepLienVan != null) {
			qlvtXuLyGpLienVanCacheModel.ngayCapGiayPhepLienVan = ngayCapGiayPhepLienVan.getTime();
		}
		else {
			qlvtXuLyGpLienVanCacheModel.ngayCapGiayPhepLienVan = Long.MIN_VALUE;
		}

		Date ngayHetHanGiayPhepLienVan = getNgayHetHanGiayPhepLienVan();

		if (ngayHetHanGiayPhepLienVan != null) {
			qlvtXuLyGpLienVanCacheModel.ngayHetHanGiayPhepLienVan = ngayHetHanGiayPhepLienVan.getTime();
		}
		else {
			qlvtXuLyGpLienVanCacheModel.ngayHetHanGiayPhepLienVan = Long.MIN_VALUE;
		}

		qlvtXuLyGpLienVanCacheModel.coQuanCapPhepLienVan = getCoQuanCapPhepLienVan();

		String coQuanCapPhepLienVan = qlvtXuLyGpLienVanCacheModel.coQuanCapPhepLienVan;

		if ((coQuanCapPhepLienVan != null) &&
				(coQuanCapPhepLienVan.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.coQuanCapPhepLienVan = null;
		}

		qlvtXuLyGpLienVanCacheModel.ketQuaXuLy = getKetQuaXuLy();

		String ketQuaXuLy = qlvtXuLyGpLienVanCacheModel.ketQuaXuLy;

		if ((ketQuaXuLy != null) && (ketQuaXuLy.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.ketQuaXuLy = null;
		}

		qlvtXuLyGpLienVanCacheModel.lyDoKhongDat = getLyDoKhongDat();

		String lyDoKhongDat = qlvtXuLyGpLienVanCacheModel.lyDoKhongDat;

		if ((lyDoKhongDat != null) && (lyDoKhongDat.length() == 0)) {
			qlvtXuLyGpLienVanCacheModel.lyDoKhongDat = null;
		}

		Date ngayCapGiayPhepLienVan_LanDau = getNgayCapGiayPhepLienVan_LanDau();

		if (ngayCapGiayPhepLienVan_LanDau != null) {
			qlvtXuLyGpLienVanCacheModel.ngayCapGiayPhepLienVan_LanDau = ngayCapGiayPhepLienVan_LanDau.getTime();
		}
		else {
			qlvtXuLyGpLienVanCacheModel.ngayCapGiayPhepLienVan_LanDau = Long.MIN_VALUE;
		}

		return qlvtXuLyGpLienVanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(51);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thongTinXuLyId=");
		sb.append(getThongTinXuLyId());
		sb.append(", loaiCapPhep=");
		sb.append(getLoaiCapPhep());
		sb.append(", soGpvt=");
		sb.append(getSoGpvt());
		sb.append(", ngayCapGpvt=");
		sb.append(getNgayCapGpvt());
		sb.append(", soCongVanChapThuanTcd=");
		sb.append(getSoCongVanChapThuanTcd());
		sb.append(", ngayCongVanChapThuanTCD=");
		sb.append(getNgayCongVanChapThuanTCD());
		sb.append(", tuyenTu=");
		sb.append(getTuyenTu());
		sb.append(", tuyenDi=");
		sb.append(getTuyenDi());
		sb.append(", cuLy=");
		sb.append(getCuLy());
		sb.append(", maBenDi=");
		sb.append(getMaBenDi());
		sb.append(", maBenDen=");
		sb.append(getMaBenDen());
		sb.append(", maTinhDi=");
		sb.append(getMaTinhDi());
		sb.append(", maTinhDen=");
		sb.append(getMaTinhDen());
		sb.append(", hanhTrinh=");
		sb.append(getHanhTrinh());
		sb.append(", mucPhi=");
		sb.append(getMucPhi());
		sb.append(", mucDichChuyenDi=");
		sb.append(getMucDichChuyenDi());
		sb.append(", loaiGiayPhepLienVan=");
		sb.append(getLoaiGiayPhepLienVan());
		sb.append(", soGiayPhepLienVan=");
		sb.append(getSoGiayPhepLienVan());
		sb.append(", ngayCapGiayPhepLienVan=");
		sb.append(getNgayCapGiayPhepLienVan());
		sb.append(", ngayHetHanGiayPhepLienVan=");
		sb.append(getNgayHetHanGiayPhepLienVan());
		sb.append(", coQuanCapPhepLienVan=");
		sb.append(getCoQuanCapPhepLienVan());
		sb.append(", ketQuaXuLy=");
		sb.append(getKetQuaXuLy());
		sb.append(", lyDoKhongDat=");
		sb.append(getLyDoKhongDat());
		sb.append(", ngayCapGiayPhepLienVan_LanDau=");
		sb.append(getNgayCapGiayPhepLienVan_LanDau());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(79);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.lienvan.model.QlvtXuLyGpLienVan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongTinXuLyId</column-name><column-value><![CDATA[");
		sb.append(getThongTinXuLyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiCapPhep</column-name><column-value><![CDATA[");
		sb.append(getLoaiCapPhep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGpvt</column-name><column-value><![CDATA[");
		sb.append(getSoGpvt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGpvt</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGpvt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soCongVanChapThuanTcd</column-name><column-value><![CDATA[");
		sb.append(getSoCongVanChapThuanTcd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCongVanChapThuanTCD</column-name><column-value><![CDATA[");
		sb.append(getNgayCongVanChapThuanTCD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tuyenTu</column-name><column-value><![CDATA[");
		sb.append(getTuyenTu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tuyenDi</column-name><column-value><![CDATA[");
		sb.append(getTuyenDi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cuLy</column-name><column-value><![CDATA[");
		sb.append(getCuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maBenDi</column-name><column-value><![CDATA[");
		sb.append(getMaBenDi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maBenDen</column-name><column-value><![CDATA[");
		sb.append(getMaBenDen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinhDi</column-name><column-value><![CDATA[");
		sb.append(getMaTinhDi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinhDen</column-name><column-value><![CDATA[");
		sb.append(getMaTinhDen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hanhTrinh</column-name><column-value><![CDATA[");
		sb.append(getHanhTrinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mucPhi</column-name><column-value><![CDATA[");
		sb.append(getMucPhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mucDichChuyenDi</column-name><column-value><![CDATA[");
		sb.append(getMucDichChuyenDi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiGiayPhepLienVan</column-name><column-value><![CDATA[");
		sb.append(getLoaiGiayPhepLienVan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGiayPhepLienVan</column-name><column-value><![CDATA[");
		sb.append(getSoGiayPhepLienVan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGiayPhepLienVan</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGiayPhepLienVan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHanGiayPhepLienVan</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHanGiayPhepLienVan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCapPhepLienVan</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapPhepLienVan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ketQuaXuLy</column-name><column-value><![CDATA[");
		sb.append(getKetQuaXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoKhongDat</column-name><column-value><![CDATA[");
		sb.append(getLyDoKhongDat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGiayPhepLienVan_LanDau</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGiayPhepLienVan_LanDau());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtXuLyGpLienVan.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtXuLyGpLienVan.class
		};
	private long _id;
	private long _thongTinXuLyId;
	private long _originalThongTinXuLyId;
	private boolean _setOriginalThongTinXuLyId;
	private String _loaiCapPhep;
	private String _soGpvt;
	private Date _ngayCapGpvt;
	private String _soCongVanChapThuanTcd;
	private Date _ngayCongVanChapThuanTCD;
	private String _tuyenTu;
	private String _tuyenDi;
	private String _cuLy;
	private String _maBenDi;
	private String _maBenDen;
	private String _maTinhDi;
	private String _maTinhDen;
	private String _hanhTrinh;
	private String _mucPhi;
	private String _mucDichChuyenDi;
	private String _loaiGiayPhepLienVan;
	private String _soGiayPhepLienVan;
	private Date _ngayCapGiayPhepLienVan;
	private Date _ngayHetHanGiayPhepLienVan;
	private String _coQuanCapPhepLienVan;
	private String _ketQuaXuLy;
	private String _lyDoKhongDat;
	private Date _ngayCapGiayPhepLienVan_LanDau;
	private long _columnBitmask;
	private QlvtXuLyGpLienVan _escapedModel;
}