/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.quocte.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QlvtXuLyKTTQuocTeBieuDoXe service. Represents a row in the &quot;qlvt_xuly_ktt_quocte_bieudoxe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.quocte.model.impl.QlvtXuLyKTTQuocTeBieuDoXeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.quocte.model.impl.QlvtXuLyKTTQuocTeBieuDoXeImpl}.
 * </p>
 *
 * @author NoiPham
 * @see QlvtXuLyKTTQuocTeBieuDoXe
 * @see vn.dtt.duongbo.dao.quocte.model.impl.QlvtXuLyKTTQuocTeBieuDoXeImpl
 * @see vn.dtt.duongbo.dao.quocte.model.impl.QlvtXuLyKTTQuocTeBieuDoXeModelImpl
 * @generated
 */
public interface QlvtXuLyKTTQuocTeBieuDoXeModel extends BaseModel<QlvtXuLyKTTQuocTeBieuDoXe> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt xu ly k t t quoc te bieu do xe model instance should use the {@link QlvtXuLyKTTQuocTeBieuDoXe} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the primary key of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param primaryKey the primary key of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the ID of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param id the ID of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setId(long id);

	/**
	 * Returns the ktt quoc te ID of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the ktt quoc te ID of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public int getKttQuocTeId();

	/**
	 * Sets the ktt quoc te ID of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param kttQuocTeId the ktt quoc te ID of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setKttQuocTeId(int kttQuocTeId);

	/**
	 * Returns the loai luot of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the loai luot of this qlvt xu ly k t t quoc te bieu do xe
	 */
	@AutoEscape
	public String getLoaiLuot();

	/**
	 * Sets the loai luot of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param loaiLuot the loai luot of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setLoaiLuot(String loaiLuot);

	/**
	 * Returns the so thu tu luot of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the so thu tu luot of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public int getSoThuTuLuot();

	/**
	 * Sets the so thu tu luot of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param soThuTuLuot the so thu tu luot of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setSoThuTuLuot(int soThuTuLuot);

	/**
	 * Returns the ma ben of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the ma ben of this qlvt xu ly k t t quoc te bieu do xe
	 */
	@AutoEscape
	public String getMaBen();

	/**
	 * Sets the ma ben of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param maBen the ma ben of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setMaBen(String maBen);

	/**
	 * Returns the gio xuat ben of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the gio xuat ben of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public int getGioXuatBen();

	/**
	 * Sets the gio xuat ben of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param gioXuatBen the gio xuat ben of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setGioXuatBen(int gioXuatBen);

	/**
	 * Returns the phu xuat ben of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the phu xuat ben of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public int getPhuXuatBen();

	/**
	 * Sets the phu xuat ben of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param phuXuatBen the phu xuat ben of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setPhuXuatBen(int phuXuatBen);

	/**
	 * Returns the tan xuat of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @return the tan xuat of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public int getTanXuat();

	/**
	 * Sets the tan xuat of this qlvt xu ly k t t quoc te bieu do xe.
	 *
	 * @param tanXuat the tan xuat of this qlvt xu ly k t t quoc te bieu do xe
	 */
	public void setTanXuat(int tanXuat);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtXuLyKTTQuocTeBieuDoXe qlvtXuLyKTTQuocTeBieuDoXe);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtXuLyKTTQuocTeBieuDoXe> toCacheModel();

	@Override
	public QlvtXuLyKTTQuocTeBieuDoXe toEscapedModel();

	@Override
	public QlvtXuLyKTTQuocTeBieuDoXe toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}