/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.common.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.common.model.DmDataVersion;
import vn.dtt.duongbo.dao.common.model.DmDataVersionModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DmDataVersion service. Represents a row in the &quot;dm_dataversion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.common.model.DmDataVersionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DmDataVersionImpl}.
 * </p>
 *
 * @author win_64
 * @see DmDataVersionImpl
 * @see vn.dtt.duongbo.dao.common.model.DmDataVersion
 * @see vn.dtt.duongbo.dao.common.model.DmDataVersionModel
 * @generated
 */
public class DmDataVersionModelImpl extends BaseModelImpl<DmDataVersion>
	implements DmDataVersionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dm data version model instance should use the {@link vn.dtt.duongbo.dao.common.model.DmDataVersion} interface instead.
	 */
	public static final String TABLE_NAME = "dm_dataversion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "datagroupid", Types.BIGINT },
			{ "version", Types.VARCHAR },
			{ "issuedtime", Types.TIMESTAMP },
			{ "validatedfrom", Types.TIMESTAMP },
			{ "validatedto", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table dm_dataversion (id LONG not null primary key,datagroupid LONG,version VARCHAR(75) null,issuedtime DATE null,validatedfrom DATE null,validatedto DATE null)";
	public static final String TABLE_SQL_DROP = "drop table dm_dataversion";
	public static final String ORDER_BY_JPQL = " ORDER BY dmDataVersion.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY dm_dataversion.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.common.model.DmDataVersion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.common.model.DmDataVersion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.common.model.DmDataVersion"));

	public DmDataVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DmDataVersion.class;
	}

	@Override
	public String getModelClassName() {
		return DmDataVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("dataGroupId", getDataGroupId());
		attributes.put("version", getVersion());
		attributes.put("issuedTime", getIssuedTime());
		attributes.put("validateDFrom", getValidateDFrom());
		attributes.put("validatedTo", getValidatedTo());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long dataGroupId = (Long)attributes.get("dataGroupId");

		if (dataGroupId != null) {
			setDataGroupId(dataGroupId);
		}

		String version = (String)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}

		Date issuedTime = (Date)attributes.get("issuedTime");

		if (issuedTime != null) {
			setIssuedTime(issuedTime);
		}

		Date validateDFrom = (Date)attributes.get("validateDFrom");

		if (validateDFrom != null) {
			setValidateDFrom(validateDFrom);
		}

		Date validatedTo = (Date)attributes.get("validatedTo");

		if (validatedTo != null) {
			setValidatedTo(validatedTo);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getDataGroupId() {
		return _dataGroupId;
	}

	@Override
	public void setDataGroupId(long dataGroupId) {
		_dataGroupId = dataGroupId;
	}

	@Override
	public String getVersion() {
		if (_version == null) {
			return StringPool.BLANK;
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		_version = version;
	}

	@Override
	public Date getIssuedTime() {
		return _issuedTime;
	}

	@Override
	public void setIssuedTime(Date issuedTime) {
		_issuedTime = issuedTime;
	}

	@Override
	public Date getValidateDFrom() {
		return _validateDFrom;
	}

	@Override
	public void setValidateDFrom(Date validateDFrom) {
		_validateDFrom = validateDFrom;
	}

	@Override
	public Date getValidatedTo() {
		return _validatedTo;
	}

	@Override
	public void setValidatedTo(Date validatedTo) {
		_validatedTo = validatedTo;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DmDataVersion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DmDataVersion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DmDataVersion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DmDataVersionImpl dmDataVersionImpl = new DmDataVersionImpl();

		dmDataVersionImpl.setId(getId());
		dmDataVersionImpl.setDataGroupId(getDataGroupId());
		dmDataVersionImpl.setVersion(getVersion());
		dmDataVersionImpl.setIssuedTime(getIssuedTime());
		dmDataVersionImpl.setValidateDFrom(getValidateDFrom());
		dmDataVersionImpl.setValidatedTo(getValidatedTo());

		dmDataVersionImpl.resetOriginalValues();

		return dmDataVersionImpl;
	}

	@Override
	public int compareTo(DmDataVersion dmDataVersion) {
		int value = 0;

		if (getId() < dmDataVersion.getId()) {
			value = -1;
		}
		else if (getId() > dmDataVersion.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DmDataVersion)) {
			return false;
		}

		DmDataVersion dmDataVersion = (DmDataVersion)obj;

		long primaryKey = dmDataVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DmDataVersion> toCacheModel() {
		DmDataVersionCacheModel dmDataVersionCacheModel = new DmDataVersionCacheModel();

		dmDataVersionCacheModel.id = getId();

		dmDataVersionCacheModel.dataGroupId = getDataGroupId();

		dmDataVersionCacheModel.version = getVersion();

		String version = dmDataVersionCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			dmDataVersionCacheModel.version = null;
		}

		Date issuedTime = getIssuedTime();

		if (issuedTime != null) {
			dmDataVersionCacheModel.issuedTime = issuedTime.getTime();
		}
		else {
			dmDataVersionCacheModel.issuedTime = Long.MIN_VALUE;
		}

		Date validateDFrom = getValidateDFrom();

		if (validateDFrom != null) {
			dmDataVersionCacheModel.validateDFrom = validateDFrom.getTime();
		}
		else {
			dmDataVersionCacheModel.validateDFrom = Long.MIN_VALUE;
		}

		Date validatedTo = getValidatedTo();

		if (validatedTo != null) {
			dmDataVersionCacheModel.validatedTo = validatedTo.getTime();
		}
		else {
			dmDataVersionCacheModel.validatedTo = Long.MIN_VALUE;
		}

		return dmDataVersionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", dataGroupId=");
		sb.append(getDataGroupId());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append(", issuedTime=");
		sb.append(getIssuedTime());
		sb.append(", validateDFrom=");
		sb.append(getValidateDFrom());
		sb.append(", validatedTo=");
		sb.append(getValidatedTo());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.common.model.DmDataVersion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataGroupId</column-name><column-value><![CDATA[");
		sb.append(getDataGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>issuedTime</column-name><column-value><![CDATA[");
		sb.append(getIssuedTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>validateDFrom</column-name><column-value><![CDATA[");
		sb.append(getValidateDFrom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>validatedTo</column-name><column-value><![CDATA[");
		sb.append(getValidatedTo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DmDataVersion.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DmDataVersion.class
		};
	private long _id;
	private long _dataGroupId;
	private String _version;
	private Date _issuedTime;
	private Date _validateDFrom;
	private Date _validatedTo;
	private DmDataVersion _escapedModel;
}