/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.common.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieu;
import vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieuModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the QlvtPhuongTienCapBienHieu service. Represents a row in the &quot;qlvt_phuongtiencapbienhieu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieuModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QlvtPhuongTienCapBienHieuImpl}.
 * </p>
 *
 * @author win_64
 * @see QlvtPhuongTienCapBienHieuImpl
 * @see vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieu
 * @see vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieuModel
 * @generated
 */
public class QlvtPhuongTienCapBienHieuModelImpl extends BaseModelImpl<QlvtPhuongTienCapBienHieu>
	implements QlvtPhuongTienCapBienHieuModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qlvt phuong tien cap bien hieu model instance should use the {@link vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieu} interface instead.
	 */
	public static final String TABLE_NAME = "qlvt_phuongtiencapbienhieu";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "NHANHIEU", Types.VARCHAR },
			{ "BIENSO", Types.VARCHAR },
			{ "SOKHUNG", Types.VARCHAR },
			{ "SOMAY", Types.VARCHAR },
			{ "NAMSANXUAT", Types.VARCHAR },
			{ "MAUSON", Types.VARCHAR },
			{ "SOCHONGOI", Types.BIGINT },
			{ "NOIDUNGHOSOID", Types.BIGINT },
			{ "HOSOTHUTUCID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table qlvt_phuongtiencapbienhieu (ID LONG not null primary key,NHANHIEU VARCHAR(75) null,BIENSO VARCHAR(75) null,SOKHUNG VARCHAR(75) null,SOMAY VARCHAR(75) null,NAMSANXUAT VARCHAR(75) null,MAUSON VARCHAR(75) null,SOCHONGOI LONG,NOIDUNGHOSOID LONG,HOSOTHUTUCID LONG)";
	public static final String TABLE_SQL_DROP = "drop table qlvt_phuongtiencapbienhieu";
	public static final String ORDER_BY_JPQL = " ORDER BY qlvtPhuongTienCapBienHieu.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY qlvt_phuongtiencapbienhieu.ID ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieu"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieu"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieu"),
			true);
	public static long NOIDUNGHOSOID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieu"));

	public QlvtPhuongTienCapBienHieuModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QlvtPhuongTienCapBienHieu.class;
	}

	@Override
	public String getModelClassName() {
		return QlvtPhuongTienCapBienHieu.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("NhanHieu", getNhanHieu());
		attributes.put("BienSo", getBienSo());
		attributes.put("SoKhung", getSoKhung());
		attributes.put("SoMay", getSoMay());
		attributes.put("NamSanXuat", getNamSanXuat());
		attributes.put("MauSon", getMauSon());
		attributes.put("SoChoNgoi", getSoChoNgoi());
		attributes.put("NoiDungHoSoId", getNoiDungHoSoId());
		attributes.put("HoSoThuTucId", getHoSoThuTucId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String NhanHieu = (String)attributes.get("NhanHieu");

		if (NhanHieu != null) {
			setNhanHieu(NhanHieu);
		}

		String BienSo = (String)attributes.get("BienSo");

		if (BienSo != null) {
			setBienSo(BienSo);
		}

		String SoKhung = (String)attributes.get("SoKhung");

		if (SoKhung != null) {
			setSoKhung(SoKhung);
		}

		String SoMay = (String)attributes.get("SoMay");

		if (SoMay != null) {
			setSoMay(SoMay);
		}

		String NamSanXuat = (String)attributes.get("NamSanXuat");

		if (NamSanXuat != null) {
			setNamSanXuat(NamSanXuat);
		}

		String MauSon = (String)attributes.get("MauSon");

		if (MauSon != null) {
			setMauSon(MauSon);
		}

		Long SoChoNgoi = (Long)attributes.get("SoChoNgoi");

		if (SoChoNgoi != null) {
			setSoChoNgoi(SoChoNgoi);
		}

		Long NoiDungHoSoId = (Long)attributes.get("NoiDungHoSoId");

		if (NoiDungHoSoId != null) {
			setNoiDungHoSoId(NoiDungHoSoId);
		}

		Long HoSoThuTucId = (Long)attributes.get("HoSoThuTucId");

		if (HoSoThuTucId != null) {
			setHoSoThuTucId(HoSoThuTucId);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public String getNhanHieu() {
		if (_NhanHieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _NhanHieu;
		}
	}

	@Override
	public void setNhanHieu(String NhanHieu) {
		_NhanHieu = NhanHieu;
	}

	@Override
	public String getBienSo() {
		if (_BienSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _BienSo;
		}
	}

	@Override
	public void setBienSo(String BienSo) {
		_BienSo = BienSo;
	}

	@Override
	public String getSoKhung() {
		if (_SoKhung == null) {
			return StringPool.BLANK;
		}
		else {
			return _SoKhung;
		}
	}

	@Override
	public void setSoKhung(String SoKhung) {
		_SoKhung = SoKhung;
	}

	@Override
	public String getSoMay() {
		if (_SoMay == null) {
			return StringPool.BLANK;
		}
		else {
			return _SoMay;
		}
	}

	@Override
	public void setSoMay(String SoMay) {
		_SoMay = SoMay;
	}

	@Override
	public String getNamSanXuat() {
		if (_NamSanXuat == null) {
			return StringPool.BLANK;
		}
		else {
			return _NamSanXuat;
		}
	}

	@Override
	public void setNamSanXuat(String NamSanXuat) {
		_NamSanXuat = NamSanXuat;
	}

	@Override
	public String getMauSon() {
		if (_MauSon == null) {
			return StringPool.BLANK;
		}
		else {
			return _MauSon;
		}
	}

	@Override
	public void setMauSon(String MauSon) {
		_MauSon = MauSon;
	}

	@Override
	public long getSoChoNgoi() {
		return _SoChoNgoi;
	}

	@Override
	public void setSoChoNgoi(long SoChoNgoi) {
		_SoChoNgoi = SoChoNgoi;
	}

	@Override
	public long getNoiDungHoSoId() {
		return _NoiDungHoSoId;
	}

	@Override
	public void setNoiDungHoSoId(long NoiDungHoSoId) {
		_columnBitmask |= NOIDUNGHOSOID_COLUMN_BITMASK;

		if (!_setOriginalNoiDungHoSoId) {
			_setOriginalNoiDungHoSoId = true;

			_originalNoiDungHoSoId = _NoiDungHoSoId;
		}

		_NoiDungHoSoId = NoiDungHoSoId;
	}

	public long getOriginalNoiDungHoSoId() {
		return _originalNoiDungHoSoId;
	}

	@Override
	public long getHoSoThuTucId() {
		return _HoSoThuTucId;
	}

	@Override
	public void setHoSoThuTucId(long HoSoThuTucId) {
		_HoSoThuTucId = HoSoThuTucId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QlvtPhuongTienCapBienHieu.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QlvtPhuongTienCapBienHieu toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QlvtPhuongTienCapBienHieu)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QlvtPhuongTienCapBienHieuImpl qlvtPhuongTienCapBienHieuImpl = new QlvtPhuongTienCapBienHieuImpl();

		qlvtPhuongTienCapBienHieuImpl.setId(getId());
		qlvtPhuongTienCapBienHieuImpl.setNhanHieu(getNhanHieu());
		qlvtPhuongTienCapBienHieuImpl.setBienSo(getBienSo());
		qlvtPhuongTienCapBienHieuImpl.setSoKhung(getSoKhung());
		qlvtPhuongTienCapBienHieuImpl.setSoMay(getSoMay());
		qlvtPhuongTienCapBienHieuImpl.setNamSanXuat(getNamSanXuat());
		qlvtPhuongTienCapBienHieuImpl.setMauSon(getMauSon());
		qlvtPhuongTienCapBienHieuImpl.setSoChoNgoi(getSoChoNgoi());
		qlvtPhuongTienCapBienHieuImpl.setNoiDungHoSoId(getNoiDungHoSoId());
		qlvtPhuongTienCapBienHieuImpl.setHoSoThuTucId(getHoSoThuTucId());

		qlvtPhuongTienCapBienHieuImpl.resetOriginalValues();

		return qlvtPhuongTienCapBienHieuImpl;
	}

	@Override
	public int compareTo(QlvtPhuongTienCapBienHieu qlvtPhuongTienCapBienHieu) {
		int value = 0;

		if (getId() < qlvtPhuongTienCapBienHieu.getId()) {
			value = -1;
		}
		else if (getId() > qlvtPhuongTienCapBienHieu.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QlvtPhuongTienCapBienHieu)) {
			return false;
		}

		QlvtPhuongTienCapBienHieu qlvtPhuongTienCapBienHieu = (QlvtPhuongTienCapBienHieu)obj;

		long primaryKey = qlvtPhuongTienCapBienHieu.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		QlvtPhuongTienCapBienHieuModelImpl qlvtPhuongTienCapBienHieuModelImpl = this;

		qlvtPhuongTienCapBienHieuModelImpl._originalNoiDungHoSoId = qlvtPhuongTienCapBienHieuModelImpl._NoiDungHoSoId;

		qlvtPhuongTienCapBienHieuModelImpl._setOriginalNoiDungHoSoId = false;

		qlvtPhuongTienCapBienHieuModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<QlvtPhuongTienCapBienHieu> toCacheModel() {
		QlvtPhuongTienCapBienHieuCacheModel qlvtPhuongTienCapBienHieuCacheModel = new QlvtPhuongTienCapBienHieuCacheModel();

		qlvtPhuongTienCapBienHieuCacheModel.id = getId();

		qlvtPhuongTienCapBienHieuCacheModel.NhanHieu = getNhanHieu();

		String NhanHieu = qlvtPhuongTienCapBienHieuCacheModel.NhanHieu;

		if ((NhanHieu != null) && (NhanHieu.length() == 0)) {
			qlvtPhuongTienCapBienHieuCacheModel.NhanHieu = null;
		}

		qlvtPhuongTienCapBienHieuCacheModel.BienSo = getBienSo();

		String BienSo = qlvtPhuongTienCapBienHieuCacheModel.BienSo;

		if ((BienSo != null) && (BienSo.length() == 0)) {
			qlvtPhuongTienCapBienHieuCacheModel.BienSo = null;
		}

		qlvtPhuongTienCapBienHieuCacheModel.SoKhung = getSoKhung();

		String SoKhung = qlvtPhuongTienCapBienHieuCacheModel.SoKhung;

		if ((SoKhung != null) && (SoKhung.length() == 0)) {
			qlvtPhuongTienCapBienHieuCacheModel.SoKhung = null;
		}

		qlvtPhuongTienCapBienHieuCacheModel.SoMay = getSoMay();

		String SoMay = qlvtPhuongTienCapBienHieuCacheModel.SoMay;

		if ((SoMay != null) && (SoMay.length() == 0)) {
			qlvtPhuongTienCapBienHieuCacheModel.SoMay = null;
		}

		qlvtPhuongTienCapBienHieuCacheModel.NamSanXuat = getNamSanXuat();

		String NamSanXuat = qlvtPhuongTienCapBienHieuCacheModel.NamSanXuat;

		if ((NamSanXuat != null) && (NamSanXuat.length() == 0)) {
			qlvtPhuongTienCapBienHieuCacheModel.NamSanXuat = null;
		}

		qlvtPhuongTienCapBienHieuCacheModel.MauSon = getMauSon();

		String MauSon = qlvtPhuongTienCapBienHieuCacheModel.MauSon;

		if ((MauSon != null) && (MauSon.length() == 0)) {
			qlvtPhuongTienCapBienHieuCacheModel.MauSon = null;
		}

		qlvtPhuongTienCapBienHieuCacheModel.SoChoNgoi = getSoChoNgoi();

		qlvtPhuongTienCapBienHieuCacheModel.NoiDungHoSoId = getNoiDungHoSoId();

		qlvtPhuongTienCapBienHieuCacheModel.HoSoThuTucId = getHoSoThuTucId();

		return qlvtPhuongTienCapBienHieuCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", NhanHieu=");
		sb.append(getNhanHieu());
		sb.append(", BienSo=");
		sb.append(getBienSo());
		sb.append(", SoKhung=");
		sb.append(getSoKhung());
		sb.append(", SoMay=");
		sb.append(getSoMay());
		sb.append(", NamSanXuat=");
		sb.append(getNamSanXuat());
		sb.append(", MauSon=");
		sb.append(getMauSon());
		sb.append(", SoChoNgoi=");
		sb.append(getSoChoNgoi());
		sb.append(", NoiDungHoSoId=");
		sb.append(getNoiDungHoSoId());
		sb.append(", HoSoThuTucId=");
		sb.append(getHoSoThuTucId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.common.model.QlvtPhuongTienCapBienHieu");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NhanHieu</column-name><column-value><![CDATA[");
		sb.append(getNhanHieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>BienSo</column-name><column-value><![CDATA[");
		sb.append(getBienSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoKhung</column-name><column-value><![CDATA[");
		sb.append(getSoKhung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoMay</column-name><column-value><![CDATA[");
		sb.append(getSoMay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NamSanXuat</column-name><column-value><![CDATA[");
		sb.append(getNamSanXuat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MauSon</column-name><column-value><![CDATA[");
		sb.append(getMauSon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoChoNgoi</column-name><column-value><![CDATA[");
		sb.append(getSoChoNgoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NoiDungHoSoId</column-name><column-value><![CDATA[");
		sb.append(getNoiDungHoSoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HoSoThuTucId</column-name><column-value><![CDATA[");
		sb.append(getHoSoThuTucId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = QlvtPhuongTienCapBienHieu.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			QlvtPhuongTienCapBienHieu.class
		};
	private long _id;
	private String _NhanHieu;
	private String _BienSo;
	private String _SoKhung;
	private String _SoMay;
	private String _NamSanXuat;
	private String _MauSon;
	private long _SoChoNgoi;
	private long _NoiDungHoSoId;
	private long _originalNoiDungHoSoId;
	private boolean _setOriginalNoiDungHoSoId;
	private long _HoSoThuTucId;
	private long _columnBitmask;
	private QlvtPhuongTienCapBienHieu _escapedModel;
}