/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.common.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHien;
import vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHienModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TthcDoiTuongThucHien service. Represents a row in the &quot;tthc_thutuchanhchinh_doituongthuchien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHienModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TthcDoiTuongThucHienImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcDoiTuongThucHienImpl
 * @see vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHien
 * @see vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHienModel
 * @generated
 */
public class TthcDoiTuongThucHienModelImpl extends BaseModelImpl<TthcDoiTuongThucHien>
	implements TthcDoiTuongThucHienModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tthc doi tuong thuc hien model instance should use the {@link vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHien} interface instead.
	 */
	public static final String TABLE_NAME = "tthc_thutuchanhchinh_doituongthuchien";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "tthc_id", Types.BIGINT },
			{ "loaidoituongthuchien", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table tthc_thutuchanhchinh_doituongthuchien (id LONG not null primary key,tthc_id LONG,loaidoituongthuchien VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table tthc_thutuchanhchinh_doituongthuchien";
	public static final String ORDER_BY_JPQL = " ORDER BY tthcDoiTuongThucHien.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY tthc_thutuchanhchinh_doituongthuchien.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHien"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHien"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHien"),
			true);
	public static long LOAIDOITUONGTHUCHIEN_COLUMN_BITMASK = 1L;
	public static long THUTUCHANHCHINHID_COLUMN_BITMASK = 2L;
	public static long ID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHien"));

	public TthcDoiTuongThucHienModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TthcDoiTuongThucHien.class;
	}

	@Override
	public String getModelClassName() {
		return TthcDoiTuongThucHien.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thuTucHanhChinhId", getThuTucHanhChinhId());
		attributes.put("loaiDoiTuongThucHien", getLoaiDoiTuongThucHien());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long thuTucHanhChinhId = (Long)attributes.get("thuTucHanhChinhId");

		if (thuTucHanhChinhId != null) {
			setThuTucHanhChinhId(thuTucHanhChinhId);
		}

		String loaiDoiTuongThucHien = (String)attributes.get(
				"loaiDoiTuongThucHien");

		if (loaiDoiTuongThucHien != null) {
			setLoaiDoiTuongThucHien(loaiDoiTuongThucHien);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public long getThuTucHanhChinhId() {
		return _thuTucHanhChinhId;
	}

	@Override
	public void setThuTucHanhChinhId(long thuTucHanhChinhId) {
		_columnBitmask |= THUTUCHANHCHINHID_COLUMN_BITMASK;

		if (!_setOriginalThuTucHanhChinhId) {
			_setOriginalThuTucHanhChinhId = true;

			_originalThuTucHanhChinhId = _thuTucHanhChinhId;
		}

		_thuTucHanhChinhId = thuTucHanhChinhId;
	}

	public long getOriginalThuTucHanhChinhId() {
		return _originalThuTucHanhChinhId;
	}

	@Override
	public String getLoaiDoiTuongThucHien() {
		if (_loaiDoiTuongThucHien == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiDoiTuongThucHien;
		}
	}

	@Override
	public void setLoaiDoiTuongThucHien(String loaiDoiTuongThucHien) {
		_columnBitmask |= LOAIDOITUONGTHUCHIEN_COLUMN_BITMASK;

		if (_originalLoaiDoiTuongThucHien == null) {
			_originalLoaiDoiTuongThucHien = _loaiDoiTuongThucHien;
		}

		_loaiDoiTuongThucHien = loaiDoiTuongThucHien;
	}

	public String getOriginalLoaiDoiTuongThucHien() {
		return GetterUtil.getString(_originalLoaiDoiTuongThucHien);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TthcDoiTuongThucHien.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TthcDoiTuongThucHien toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TthcDoiTuongThucHien)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TthcDoiTuongThucHienImpl tthcDoiTuongThucHienImpl = new TthcDoiTuongThucHienImpl();

		tthcDoiTuongThucHienImpl.setId(getId());
		tthcDoiTuongThucHienImpl.setThuTucHanhChinhId(getThuTucHanhChinhId());
		tthcDoiTuongThucHienImpl.setLoaiDoiTuongThucHien(getLoaiDoiTuongThucHien());

		tthcDoiTuongThucHienImpl.resetOriginalValues();

		return tthcDoiTuongThucHienImpl;
	}

	@Override
	public int compareTo(TthcDoiTuongThucHien tthcDoiTuongThucHien) {
		int value = 0;

		if (getId() < tthcDoiTuongThucHien.getId()) {
			value = -1;
		}
		else if (getId() > tthcDoiTuongThucHien.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TthcDoiTuongThucHien)) {
			return false;
		}

		TthcDoiTuongThucHien tthcDoiTuongThucHien = (TthcDoiTuongThucHien)obj;

		long primaryKey = tthcDoiTuongThucHien.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TthcDoiTuongThucHienModelImpl tthcDoiTuongThucHienModelImpl = this;

		tthcDoiTuongThucHienModelImpl._originalThuTucHanhChinhId = tthcDoiTuongThucHienModelImpl._thuTucHanhChinhId;

		tthcDoiTuongThucHienModelImpl._setOriginalThuTucHanhChinhId = false;

		tthcDoiTuongThucHienModelImpl._originalLoaiDoiTuongThucHien = tthcDoiTuongThucHienModelImpl._loaiDoiTuongThucHien;

		tthcDoiTuongThucHienModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TthcDoiTuongThucHien> toCacheModel() {
		TthcDoiTuongThucHienCacheModel tthcDoiTuongThucHienCacheModel = new TthcDoiTuongThucHienCacheModel();

		tthcDoiTuongThucHienCacheModel.id = getId();

		tthcDoiTuongThucHienCacheModel.thuTucHanhChinhId = getThuTucHanhChinhId();

		tthcDoiTuongThucHienCacheModel.loaiDoiTuongThucHien = getLoaiDoiTuongThucHien();

		String loaiDoiTuongThucHien = tthcDoiTuongThucHienCacheModel.loaiDoiTuongThucHien;

		if ((loaiDoiTuongThucHien != null) &&
				(loaiDoiTuongThucHien.length() == 0)) {
			tthcDoiTuongThucHienCacheModel.loaiDoiTuongThucHien = null;
		}

		return tthcDoiTuongThucHienCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thuTucHanhChinhId=");
		sb.append(getThuTucHanhChinhId());
		sb.append(", loaiDoiTuongThucHien=");
		sb.append(getLoaiDoiTuongThucHien());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.common.model.TthcDoiTuongThucHien");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thuTucHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getThuTucHanhChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiDoiTuongThucHien</column-name><column-value><![CDATA[");
		sb.append(getLoaiDoiTuongThucHien());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TthcDoiTuongThucHien.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TthcDoiTuongThucHien.class
		};
	private long _id;
	private long _thuTucHanhChinhId;
	private long _originalThuTucHanhChinhId;
	private boolean _setOriginalThuTucHanhChinhId;
	private String _loaiDoiTuongThucHien;
	private String _originalLoaiDoiTuongThucHien;
	private long _columnBitmask;
	private TthcDoiTuongThucHien _escapedModel;
}