/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.common.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.common.model.TthcNoidungHoSo;
import vn.dtt.duongbo.dao.common.model.TthcNoidungHoSoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TthcNoidungHoSo service. Represents a row in the &quot;tthc_noidunghoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.common.model.TthcNoidungHoSoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TthcNoidungHoSoImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcNoidungHoSoImpl
 * @see vn.dtt.duongbo.dao.common.model.TthcNoidungHoSo
 * @see vn.dtt.duongbo.dao.common.model.TthcNoidungHoSoModel
 * @generated
 */
public class TthcNoidungHoSoModelImpl extends BaseModelImpl<TthcNoidungHoSo>
	implements TthcNoidungHoSoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tthc noidung ho so model instance should use the {@link vn.dtt.duongbo.dao.common.model.TthcNoidungHoSo} interface instead.
	 */
	public static final String TABLE_NAME = "tthc_noidunghoso";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "matusinh", Types.VARCHAR },
			{ "hosothutucid", Types.BIGINT },
			{ "thanhphanhosoid", Types.BIGINT },
			{ "tentailieu", Types.VARCHAR },
			{ "tailieudinhkem", Types.BIGINT },
			{ "noidungxml", Types.VARCHAR },
			{ "noiDungHtml", Types.VARCHAR },
			{ "bieumauhosoid", Types.BIGINT },
			{ "ngayguinhan", Types.TIMESTAMP },
			{ "loaitailieu", Types.BIGINT },
			{ "ngaytao", Types.TIMESTAMP },
			{ "nguoitao", Types.BIGINT },
			{ "trangthai", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table tthc_noidunghoso (id LONG not null primary key,matusinh VARCHAR(75) null,hosothutucid LONG,thanhphanhosoid LONG,tentailieu VARCHAR(75) null,tailieudinhkem LONG,noidungxml VARCHAR(75) null,noiDungHtml VARCHAR(75) null,bieumauhosoid LONG,ngayguinhan DATE null,loaitailieu LONG,ngaytao DATE null,nguoitao LONG,trangthai LONG)";
	public static final String TABLE_SQL_DROP = "drop table tthc_noidunghoso";
	public static final String ORDER_BY_JPQL = " ORDER BY tthcNoidungHoSo.id DESC";
	public static final String ORDER_BY_SQL = " ORDER BY tthc_noidunghoso.id DESC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.common.model.TthcNoidungHoSo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.common.model.TthcNoidungHoSo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.common.model.TthcNoidungHoSo"),
			true);
	public static long BIEUMAUHOSOID_COLUMN_BITMASK = 1L;
	public static long HOSOTHUTUCID_COLUMN_BITMASK = 2L;
	public static long MATUSINH_COLUMN_BITMASK = 4L;
	public static long TAILIEUDINHKEM_COLUMN_BITMASK = 8L;
	public static long THANHPHANHOSOID_COLUMN_BITMASK = 16L;
	public static long TRANGTHAI_COLUMN_BITMASK = 32L;
	public static long ID_COLUMN_BITMASK = 64L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.common.model.TthcNoidungHoSo"));

	public TthcNoidungHoSoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TthcNoidungHoSo.class;
	}

	@Override
	public String getModelClassName() {
		return TthcNoidungHoSo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maTuSinh", getMaTuSinh());
		attributes.put("hoSoThuTucId", getHoSoThuTucId());
		attributes.put("thanhPhanHoSoId", getThanhPhanHoSoId());
		attributes.put("tenTaiLieu", getTenTaiLieu());
		attributes.put("taiLieuDinhKem", getTaiLieuDinhKem());
		attributes.put("noiDungXml", getNoiDungXml());
		attributes.put("noiDungHtml", getNoiDungHtml());
		attributes.put("bieuMauHoSoId", getBieuMauHoSoId());
		attributes.put("ngayGuiNhan", getNgayGuiNhan());
		attributes.put("loaiTaiLieu", getLoaiTaiLieu());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("nguoiTao", getNguoiTao());
		attributes.put("trangThai", getTrangThai());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maTuSinh = (String)attributes.get("maTuSinh");

		if (maTuSinh != null) {
			setMaTuSinh(maTuSinh);
		}

		Long hoSoThuTucId = (Long)attributes.get("hoSoThuTucId");

		if (hoSoThuTucId != null) {
			setHoSoThuTucId(hoSoThuTucId);
		}

		Long thanhPhanHoSoId = (Long)attributes.get("thanhPhanHoSoId");

		if (thanhPhanHoSoId != null) {
			setThanhPhanHoSoId(thanhPhanHoSoId);
		}

		String tenTaiLieu = (String)attributes.get("tenTaiLieu");

		if (tenTaiLieu != null) {
			setTenTaiLieu(tenTaiLieu);
		}

		Long taiLieuDinhKem = (Long)attributes.get("taiLieuDinhKem");

		if (taiLieuDinhKem != null) {
			setTaiLieuDinhKem(taiLieuDinhKem);
		}

		String noiDungXml = (String)attributes.get("noiDungXml");

		if (noiDungXml != null) {
			setNoiDungXml(noiDungXml);
		}

		String noiDungHtml = (String)attributes.get("noiDungHtml");

		if (noiDungHtml != null) {
			setNoiDungHtml(noiDungHtml);
		}

		Long bieuMauHoSoId = (Long)attributes.get("bieuMauHoSoId");

		if (bieuMauHoSoId != null) {
			setBieuMauHoSoId(bieuMauHoSoId);
		}

		Date ngayGuiNhan = (Date)attributes.get("ngayGuiNhan");

		if (ngayGuiNhan != null) {
			setNgayGuiNhan(ngayGuiNhan);
		}

		Long loaiTaiLieu = (Long)attributes.get("loaiTaiLieu");

		if (loaiTaiLieu != null) {
			setLoaiTaiLieu(loaiTaiLieu);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Long nguoiTao = (Long)attributes.get("nguoiTao");

		if (nguoiTao != null) {
			setNguoiTao(nguoiTao);
		}

		Long trangThai = (Long)attributes.get("trangThai");

		if (trangThai != null) {
			setTrangThai(trangThai);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public String getMaTuSinh() {
		if (_maTuSinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTuSinh;
		}
	}

	@Override
	public void setMaTuSinh(String maTuSinh) {
		_columnBitmask |= MATUSINH_COLUMN_BITMASK;

		if (_originalMaTuSinh == null) {
			_originalMaTuSinh = _maTuSinh;
		}

		_maTuSinh = maTuSinh;
	}

	public String getOriginalMaTuSinh() {
		return GetterUtil.getString(_originalMaTuSinh);
	}

	@Override
	public long getHoSoThuTucId() {
		return _hoSoThuTucId;
	}

	@Override
	public void setHoSoThuTucId(long hoSoThuTucId) {
		_columnBitmask |= HOSOTHUTUCID_COLUMN_BITMASK;

		if (!_setOriginalHoSoThuTucId) {
			_setOriginalHoSoThuTucId = true;

			_originalHoSoThuTucId = _hoSoThuTucId;
		}

		_hoSoThuTucId = hoSoThuTucId;
	}

	public long getOriginalHoSoThuTucId() {
		return _originalHoSoThuTucId;
	}

	@Override
	public long getThanhPhanHoSoId() {
		return _thanhPhanHoSoId;
	}

	@Override
	public void setThanhPhanHoSoId(long thanhPhanHoSoId) {
		_columnBitmask |= THANHPHANHOSOID_COLUMN_BITMASK;

		if (!_setOriginalThanhPhanHoSoId) {
			_setOriginalThanhPhanHoSoId = true;

			_originalThanhPhanHoSoId = _thanhPhanHoSoId;
		}

		_thanhPhanHoSoId = thanhPhanHoSoId;
	}

	public long getOriginalThanhPhanHoSoId() {
		return _originalThanhPhanHoSoId;
	}

	@Override
	public String getTenTaiLieu() {
		if (_tenTaiLieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenTaiLieu;
		}
	}

	@Override
	public void setTenTaiLieu(String tenTaiLieu) {
		_tenTaiLieu = tenTaiLieu;
	}

	@Override
	public long getTaiLieuDinhKem() {
		return _taiLieuDinhKem;
	}

	@Override
	public void setTaiLieuDinhKem(long taiLieuDinhKem) {
		_columnBitmask |= TAILIEUDINHKEM_COLUMN_BITMASK;

		if (!_setOriginalTaiLieuDinhKem) {
			_setOriginalTaiLieuDinhKem = true;

			_originalTaiLieuDinhKem = _taiLieuDinhKem;
		}

		_taiLieuDinhKem = taiLieuDinhKem;
	}

	public long getOriginalTaiLieuDinhKem() {
		return _originalTaiLieuDinhKem;
	}

	@Override
	public String getNoiDungXml() {
		if (_noiDungXml == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiDungXml;
		}
	}

	@Override
	public void setNoiDungXml(String noiDungXml) {
		_noiDungXml = noiDungXml;
	}

	@Override
	public String getNoiDungHtml() {
		if (_noiDungHtml == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiDungHtml;
		}
	}

	@Override
	public void setNoiDungHtml(String noiDungHtml) {
		_noiDungHtml = noiDungHtml;
	}

	@Override
	public long getBieuMauHoSoId() {
		return _bieuMauHoSoId;
	}

	@Override
	public void setBieuMauHoSoId(long bieuMauHoSoId) {
		_columnBitmask |= BIEUMAUHOSOID_COLUMN_BITMASK;

		if (!_setOriginalBieuMauHoSoId) {
			_setOriginalBieuMauHoSoId = true;

			_originalBieuMauHoSoId = _bieuMauHoSoId;
		}

		_bieuMauHoSoId = bieuMauHoSoId;
	}

	public long getOriginalBieuMauHoSoId() {
		return _originalBieuMauHoSoId;
	}

	@Override
	public Date getNgayGuiNhan() {
		return _ngayGuiNhan;
	}

	@Override
	public void setNgayGuiNhan(Date ngayGuiNhan) {
		_ngayGuiNhan = ngayGuiNhan;
	}

	@Override
	public long getLoaiTaiLieu() {
		return _loaiTaiLieu;
	}

	@Override
	public void setLoaiTaiLieu(long loaiTaiLieu) {
		_loaiTaiLieu = loaiTaiLieu;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public long getNguoiTao() {
		return _nguoiTao;
	}

	@Override
	public void setNguoiTao(long nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	@Override
	public long getTrangThai() {
		return _trangThai;
	}

	@Override
	public void setTrangThai(long trangThai) {
		_columnBitmask |= TRANGTHAI_COLUMN_BITMASK;

		if (!_setOriginalTrangThai) {
			_setOriginalTrangThai = true;

			_originalTrangThai = _trangThai;
		}

		_trangThai = trangThai;
	}

	public long getOriginalTrangThai() {
		return _originalTrangThai;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TthcNoidungHoSo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TthcNoidungHoSo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TthcNoidungHoSo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TthcNoidungHoSoImpl tthcNoidungHoSoImpl = new TthcNoidungHoSoImpl();

		tthcNoidungHoSoImpl.setId(getId());
		tthcNoidungHoSoImpl.setMaTuSinh(getMaTuSinh());
		tthcNoidungHoSoImpl.setHoSoThuTucId(getHoSoThuTucId());
		tthcNoidungHoSoImpl.setThanhPhanHoSoId(getThanhPhanHoSoId());
		tthcNoidungHoSoImpl.setTenTaiLieu(getTenTaiLieu());
		tthcNoidungHoSoImpl.setTaiLieuDinhKem(getTaiLieuDinhKem());
		tthcNoidungHoSoImpl.setNoiDungXml(getNoiDungXml());
		tthcNoidungHoSoImpl.setNoiDungHtml(getNoiDungHtml());
		tthcNoidungHoSoImpl.setBieuMauHoSoId(getBieuMauHoSoId());
		tthcNoidungHoSoImpl.setNgayGuiNhan(getNgayGuiNhan());
		tthcNoidungHoSoImpl.setLoaiTaiLieu(getLoaiTaiLieu());
		tthcNoidungHoSoImpl.setNgayTao(getNgayTao());
		tthcNoidungHoSoImpl.setNguoiTao(getNguoiTao());
		tthcNoidungHoSoImpl.setTrangThai(getTrangThai());

		tthcNoidungHoSoImpl.resetOriginalValues();

		return tthcNoidungHoSoImpl;
	}

	@Override
	public int compareTo(TthcNoidungHoSo tthcNoidungHoSo) {
		int value = 0;

		if (getId() < tthcNoidungHoSo.getId()) {
			value = -1;
		}
		else if (getId() > tthcNoidungHoSo.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TthcNoidungHoSo)) {
			return false;
		}

		TthcNoidungHoSo tthcNoidungHoSo = (TthcNoidungHoSo)obj;

		long primaryKey = tthcNoidungHoSo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TthcNoidungHoSoModelImpl tthcNoidungHoSoModelImpl = this;

		tthcNoidungHoSoModelImpl._originalMaTuSinh = tthcNoidungHoSoModelImpl._maTuSinh;

		tthcNoidungHoSoModelImpl._originalHoSoThuTucId = tthcNoidungHoSoModelImpl._hoSoThuTucId;

		tthcNoidungHoSoModelImpl._setOriginalHoSoThuTucId = false;

		tthcNoidungHoSoModelImpl._originalThanhPhanHoSoId = tthcNoidungHoSoModelImpl._thanhPhanHoSoId;

		tthcNoidungHoSoModelImpl._setOriginalThanhPhanHoSoId = false;

		tthcNoidungHoSoModelImpl._originalTaiLieuDinhKem = tthcNoidungHoSoModelImpl._taiLieuDinhKem;

		tthcNoidungHoSoModelImpl._setOriginalTaiLieuDinhKem = false;

		tthcNoidungHoSoModelImpl._originalBieuMauHoSoId = tthcNoidungHoSoModelImpl._bieuMauHoSoId;

		tthcNoidungHoSoModelImpl._setOriginalBieuMauHoSoId = false;

		tthcNoidungHoSoModelImpl._originalTrangThai = tthcNoidungHoSoModelImpl._trangThai;

		tthcNoidungHoSoModelImpl._setOriginalTrangThai = false;

		tthcNoidungHoSoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TthcNoidungHoSo> toCacheModel() {
		TthcNoidungHoSoCacheModel tthcNoidungHoSoCacheModel = new TthcNoidungHoSoCacheModel();

		tthcNoidungHoSoCacheModel.id = getId();

		tthcNoidungHoSoCacheModel.maTuSinh = getMaTuSinh();

		String maTuSinh = tthcNoidungHoSoCacheModel.maTuSinh;

		if ((maTuSinh != null) && (maTuSinh.length() == 0)) {
			tthcNoidungHoSoCacheModel.maTuSinh = null;
		}

		tthcNoidungHoSoCacheModel.hoSoThuTucId = getHoSoThuTucId();

		tthcNoidungHoSoCacheModel.thanhPhanHoSoId = getThanhPhanHoSoId();

		tthcNoidungHoSoCacheModel.tenTaiLieu = getTenTaiLieu();

		String tenTaiLieu = tthcNoidungHoSoCacheModel.tenTaiLieu;

		if ((tenTaiLieu != null) && (tenTaiLieu.length() == 0)) {
			tthcNoidungHoSoCacheModel.tenTaiLieu = null;
		}

		tthcNoidungHoSoCacheModel.taiLieuDinhKem = getTaiLieuDinhKem();

		tthcNoidungHoSoCacheModel.noiDungXml = getNoiDungXml();

		String noiDungXml = tthcNoidungHoSoCacheModel.noiDungXml;

		if ((noiDungXml != null) && (noiDungXml.length() == 0)) {
			tthcNoidungHoSoCacheModel.noiDungXml = null;
		}

		tthcNoidungHoSoCacheModel.noiDungHtml = getNoiDungHtml();

		String noiDungHtml = tthcNoidungHoSoCacheModel.noiDungHtml;

		if ((noiDungHtml != null) && (noiDungHtml.length() == 0)) {
			tthcNoidungHoSoCacheModel.noiDungHtml = null;
		}

		tthcNoidungHoSoCacheModel.bieuMauHoSoId = getBieuMauHoSoId();

		Date ngayGuiNhan = getNgayGuiNhan();

		if (ngayGuiNhan != null) {
			tthcNoidungHoSoCacheModel.ngayGuiNhan = ngayGuiNhan.getTime();
		}
		else {
			tthcNoidungHoSoCacheModel.ngayGuiNhan = Long.MIN_VALUE;
		}

		tthcNoidungHoSoCacheModel.loaiTaiLieu = getLoaiTaiLieu();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			tthcNoidungHoSoCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			tthcNoidungHoSoCacheModel.ngayTao = Long.MIN_VALUE;
		}

		tthcNoidungHoSoCacheModel.nguoiTao = getNguoiTao();

		tthcNoidungHoSoCacheModel.trangThai = getTrangThai();

		return tthcNoidungHoSoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maTuSinh=");
		sb.append(getMaTuSinh());
		sb.append(", hoSoThuTucId=");
		sb.append(getHoSoThuTucId());
		sb.append(", thanhPhanHoSoId=");
		sb.append(getThanhPhanHoSoId());
		sb.append(", tenTaiLieu=");
		sb.append(getTenTaiLieu());
		sb.append(", taiLieuDinhKem=");
		sb.append(getTaiLieuDinhKem());
		sb.append(", noiDungXml=");
		sb.append(getNoiDungXml());
		sb.append(", noiDungHtml=");
		sb.append(getNoiDungHtml());
		sb.append(", bieuMauHoSoId=");
		sb.append(getBieuMauHoSoId());
		sb.append(", ngayGuiNhan=");
		sb.append(getNgayGuiNhan());
		sb.append(", loaiTaiLieu=");
		sb.append(getLoaiTaiLieu());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.common.model.TthcNoidungHoSo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTuSinh</column-name><column-value><![CDATA[");
		sb.append(getMaTuSinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoSoThuTucId</column-name><column-value><![CDATA[");
		sb.append(getHoSoThuTucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thanhPhanHoSoId</column-name><column-value><![CDATA[");
		sb.append(getThanhPhanHoSoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenTaiLieu</column-name><column-value><![CDATA[");
		sb.append(getTenTaiLieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiLieuDinhKem</column-name><column-value><![CDATA[");
		sb.append(getTaiLieuDinhKem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiDungXml</column-name><column-value><![CDATA[");
		sb.append(getNoiDungXml());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiDungHtml</column-name><column-value><![CDATA[");
		sb.append(getNoiDungHtml());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bieuMauHoSoId</column-name><column-value><![CDATA[");
		sb.append(getBieuMauHoSoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayGuiNhan</column-name><column-value><![CDATA[");
		sb.append(getNgayGuiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiTaiLieu</column-name><column-value><![CDATA[");
		sb.append(getLoaiTaiLieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TthcNoidungHoSo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TthcNoidungHoSo.class
		};
	private long _id;
	private String _maTuSinh;
	private String _originalMaTuSinh;
	private long _hoSoThuTucId;
	private long _originalHoSoThuTucId;
	private boolean _setOriginalHoSoThuTucId;
	private long _thanhPhanHoSoId;
	private long _originalThanhPhanHoSoId;
	private boolean _setOriginalThanhPhanHoSoId;
	private String _tenTaiLieu;
	private long _taiLieuDinhKem;
	private long _originalTaiLieuDinhKem;
	private boolean _setOriginalTaiLieuDinhKem;
	private String _noiDungXml;
	private String _noiDungHtml;
	private long _bieuMauHoSoId;
	private long _originalBieuMauHoSoId;
	private boolean _setOriginalBieuMauHoSoId;
	private Date _ngayGuiNhan;
	private long _loaiTaiLieu;
	private Date _ngayTao;
	private long _nguoiTao;
	private long _trangThai;
	private long _originalTrangThai;
	private boolean _setOriginalTrangThai;
	private long _columnBitmask;
	private TthcNoidungHoSo _escapedModel;
}