/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.thanhtoan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToan;
import vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToanModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TthcXacNhanThanhToan service. Represents a row in the &quot;tthc_xacnhanthanhtoan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TthcXacNhanThanhToanImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcXacNhanThanhToanImpl
 * @see vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToan
 * @see vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToanModel
 * @generated
 */
public class TthcXacNhanThanhToanModelImpl extends BaseModelImpl<TthcXacNhanThanhToan>
	implements TthcXacNhanThanhToanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tthc xac nhan thanh toan model instance should use the {@link vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToan} interface instead.
	 */
	public static final String TABLE_NAME = "tthc_xacnhanthanhtoan";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "matusinh", Types.VARCHAR },
			{ "sotien", Types.BIGINT },
			{ "hinhthucthanhtoan", Types.BIGINT },
			{ "thongtinxacnhan", Types.VARCHAR },
			{ "tailieudinhkem", Types.BIGINT },
			{ "ngaytao", Types.TIMESTAMP },
			{ "nguoitao", Types.BIGINT },
			{ "ngayxacnhan", Types.TIMESTAMP },
			{ "nguoixacnhan", Types.BIGINT },
			{ "tochucquanly", Types.BIGINT },
			{ "trangthai", Types.INTEGER },
			{ "YKIENXULY", Types.VARCHAR },
			{ "LOAIPHI", Types.VARCHAR },
			{ "tendoanhnghiep", Types.VARCHAR },
			{ "ghichu", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table tthc_xacnhanthanhtoan (id LONG not null primary key,matusinh VARCHAR(75) null,sotien LONG,hinhthucthanhtoan LONG,thongtinxacnhan VARCHAR(75) null,tailieudinhkem LONG,ngaytao DATE null,nguoitao LONG,ngayxacnhan DATE null,nguoixacnhan LONG,tochucquanly LONG,trangthai INTEGER,YKIENXULY VARCHAR(75) null,LOAIPHI VARCHAR(75) null,tendoanhnghiep VARCHAR(75) null,ghichu VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table tthc_xacnhanthanhtoan";
	public static final String ORDER_BY_JPQL = " ORDER BY tthcXacNhanThanhToan.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY tthc_xacnhanthanhtoan.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToan"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToan"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToan"),
			true);
	public static long MATUSINH_COLUMN_BITMASK = 1L;
	public static long TOCHUCQUANLY_COLUMN_BITMASK = 2L;
	public static long ID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToan"));

	public TthcXacNhanThanhToanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TthcXacNhanThanhToan.class;
	}

	@Override
	public String getModelClassName() {
		return TthcXacNhanThanhToan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("maTuSinh", getMaTuSinh());
		attributes.put("soTien", getSoTien());
		attributes.put("hinhThucThanhToan", getHinhThucThanhToan());
		attributes.put("thongTinXacNhan", getThongTinXacNhan());
		attributes.put("taiLieuDinhKem", getTaiLieuDinhKem());
		attributes.put("ngayTao", getNgayTao());
		attributes.put("nguoiTao", getNguoiTao());
		attributes.put("ngayXacNhan", getNgayXacNhan());
		attributes.put("nguoiXacNhan", getNguoiXacNhan());
		attributes.put("toChucQuanLy", getToChucQuanLy());
		attributes.put("trangThaiXacNhan", getTrangThaiXacNhan());
		attributes.put("yKienXuLy", getYKienXuLy());
		attributes.put("loaiPhi", getLoaiPhi());
		attributes.put("tenDoanhNghiep", getTenDoanhNghiep());
		attributes.put("ghiChu", getGhiChu());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String maTuSinh = (String)attributes.get("maTuSinh");

		if (maTuSinh != null) {
			setMaTuSinh(maTuSinh);
		}

		Long soTien = (Long)attributes.get("soTien");

		if (soTien != null) {
			setSoTien(soTien);
		}

		Long hinhThucThanhToan = (Long)attributes.get("hinhThucThanhToan");

		if (hinhThucThanhToan != null) {
			setHinhThucThanhToan(hinhThucThanhToan);
		}

		String thongTinXacNhan = (String)attributes.get("thongTinXacNhan");

		if (thongTinXacNhan != null) {
			setThongTinXacNhan(thongTinXacNhan);
		}

		Long taiLieuDinhKem = (Long)attributes.get("taiLieuDinhKem");

		if (taiLieuDinhKem != null) {
			setTaiLieuDinhKem(taiLieuDinhKem);
		}

		Date ngayTao = (Date)attributes.get("ngayTao");

		if (ngayTao != null) {
			setNgayTao(ngayTao);
		}

		Long nguoiTao = (Long)attributes.get("nguoiTao");

		if (nguoiTao != null) {
			setNguoiTao(nguoiTao);
		}

		Date ngayXacNhan = (Date)attributes.get("ngayXacNhan");

		if (ngayXacNhan != null) {
			setNgayXacNhan(ngayXacNhan);
		}

		Long nguoiXacNhan = (Long)attributes.get("nguoiXacNhan");

		if (nguoiXacNhan != null) {
			setNguoiXacNhan(nguoiXacNhan);
		}

		Long toChucQuanLy = (Long)attributes.get("toChucQuanLy");

		if (toChucQuanLy != null) {
			setToChucQuanLy(toChucQuanLy);
		}

		Integer trangThaiXacNhan = (Integer)attributes.get("trangThaiXacNhan");

		if (trangThaiXacNhan != null) {
			setTrangThaiXacNhan(trangThaiXacNhan);
		}

		String yKienXuLy = (String)attributes.get("yKienXuLy");

		if (yKienXuLy != null) {
			setYKienXuLy(yKienXuLy);
		}

		String loaiPhi = (String)attributes.get("loaiPhi");

		if (loaiPhi != null) {
			setLoaiPhi(loaiPhi);
		}

		String tenDoanhNghiep = (String)attributes.get("tenDoanhNghiep");

		if (tenDoanhNghiep != null) {
			setTenDoanhNghiep(tenDoanhNghiep);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public String getMaTuSinh() {
		if (_maTuSinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maTuSinh;
		}
	}

	@Override
	public void setMaTuSinh(String maTuSinh) {
		_columnBitmask |= MATUSINH_COLUMN_BITMASK;

		if (_originalMaTuSinh == null) {
			_originalMaTuSinh = _maTuSinh;
		}

		_maTuSinh = maTuSinh;
	}

	public String getOriginalMaTuSinh() {
		return GetterUtil.getString(_originalMaTuSinh);
	}

	@Override
	public long getSoTien() {
		return _soTien;
	}

	@Override
	public void setSoTien(long soTien) {
		_soTien = soTien;
	}

	@Override
	public long getHinhThucThanhToan() {
		return _hinhThucThanhToan;
	}

	@Override
	public void setHinhThucThanhToan(long hinhThucThanhToan) {
		_hinhThucThanhToan = hinhThucThanhToan;
	}

	@Override
	public String getThongTinXacNhan() {
		if (_thongTinXacNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _thongTinXacNhan;
		}
	}

	@Override
	public void setThongTinXacNhan(String thongTinXacNhan) {
		_thongTinXacNhan = thongTinXacNhan;
	}

	@Override
	public long getTaiLieuDinhKem() {
		return _taiLieuDinhKem;
	}

	@Override
	public void setTaiLieuDinhKem(long taiLieuDinhKem) {
		_taiLieuDinhKem = taiLieuDinhKem;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@Override
	public long getNguoiTao() {
		return _nguoiTao;
	}

	@Override
	public void setNguoiTao(long nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	@Override
	public Date getNgayXacNhan() {
		return _ngayXacNhan;
	}

	@Override
	public void setNgayXacNhan(Date ngayXacNhan) {
		_ngayXacNhan = ngayXacNhan;
	}

	@Override
	public long getNguoiXacNhan() {
		return _nguoiXacNhan;
	}

	@Override
	public void setNguoiXacNhan(long nguoiXacNhan) {
		_nguoiXacNhan = nguoiXacNhan;
	}

	@Override
	public long getToChucQuanLy() {
		return _toChucQuanLy;
	}

	@Override
	public void setToChucQuanLy(long toChucQuanLy) {
		_columnBitmask |= TOCHUCQUANLY_COLUMN_BITMASK;

		if (!_setOriginalToChucQuanLy) {
			_setOriginalToChucQuanLy = true;

			_originalToChucQuanLy = _toChucQuanLy;
		}

		_toChucQuanLy = toChucQuanLy;
	}

	public long getOriginalToChucQuanLy() {
		return _originalToChucQuanLy;
	}

	@Override
	public int getTrangThaiXacNhan() {
		return _trangThaiXacNhan;
	}

	@Override
	public void setTrangThaiXacNhan(int trangThaiXacNhan) {
		_trangThaiXacNhan = trangThaiXacNhan;
	}

	@Override
	public String getYKienXuLy() {
		if (_yKienXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _yKienXuLy;
		}
	}

	@Override
	public void setYKienXuLy(String yKienXuLy) {
		_yKienXuLy = yKienXuLy;
	}

	@Override
	public String getLoaiPhi() {
		if (_loaiPhi == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiPhi;
		}
	}

	@Override
	public void setLoaiPhi(String loaiPhi) {
		_loaiPhi = loaiPhi;
	}

	@Override
	public String getTenDoanhNghiep() {
		if (_tenDoanhNghiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDoanhNghiep;
		}
	}

	@Override
	public void setTenDoanhNghiep(String tenDoanhNghiep) {
		_tenDoanhNghiep = tenDoanhNghiep;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TthcXacNhanThanhToan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TthcXacNhanThanhToan toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TthcXacNhanThanhToan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TthcXacNhanThanhToanImpl tthcXacNhanThanhToanImpl = new TthcXacNhanThanhToanImpl();

		tthcXacNhanThanhToanImpl.setId(getId());
		tthcXacNhanThanhToanImpl.setMaTuSinh(getMaTuSinh());
		tthcXacNhanThanhToanImpl.setSoTien(getSoTien());
		tthcXacNhanThanhToanImpl.setHinhThucThanhToan(getHinhThucThanhToan());
		tthcXacNhanThanhToanImpl.setThongTinXacNhan(getThongTinXacNhan());
		tthcXacNhanThanhToanImpl.setTaiLieuDinhKem(getTaiLieuDinhKem());
		tthcXacNhanThanhToanImpl.setNgayTao(getNgayTao());
		tthcXacNhanThanhToanImpl.setNguoiTao(getNguoiTao());
		tthcXacNhanThanhToanImpl.setNgayXacNhan(getNgayXacNhan());
		tthcXacNhanThanhToanImpl.setNguoiXacNhan(getNguoiXacNhan());
		tthcXacNhanThanhToanImpl.setToChucQuanLy(getToChucQuanLy());
		tthcXacNhanThanhToanImpl.setTrangThaiXacNhan(getTrangThaiXacNhan());
		tthcXacNhanThanhToanImpl.setYKienXuLy(getYKienXuLy());
		tthcXacNhanThanhToanImpl.setLoaiPhi(getLoaiPhi());
		tthcXacNhanThanhToanImpl.setTenDoanhNghiep(getTenDoanhNghiep());
		tthcXacNhanThanhToanImpl.setGhiChu(getGhiChu());

		tthcXacNhanThanhToanImpl.resetOriginalValues();

		return tthcXacNhanThanhToanImpl;
	}

	@Override
	public int compareTo(TthcXacNhanThanhToan tthcXacNhanThanhToan) {
		int value = 0;

		if (getId() < tthcXacNhanThanhToan.getId()) {
			value = -1;
		}
		else if (getId() > tthcXacNhanThanhToan.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TthcXacNhanThanhToan)) {
			return false;
		}

		TthcXacNhanThanhToan tthcXacNhanThanhToan = (TthcXacNhanThanhToan)obj;

		long primaryKey = tthcXacNhanThanhToan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TthcXacNhanThanhToanModelImpl tthcXacNhanThanhToanModelImpl = this;

		tthcXacNhanThanhToanModelImpl._originalMaTuSinh = tthcXacNhanThanhToanModelImpl._maTuSinh;

		tthcXacNhanThanhToanModelImpl._originalToChucQuanLy = tthcXacNhanThanhToanModelImpl._toChucQuanLy;

		tthcXacNhanThanhToanModelImpl._setOriginalToChucQuanLy = false;

		tthcXacNhanThanhToanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TthcXacNhanThanhToan> toCacheModel() {
		TthcXacNhanThanhToanCacheModel tthcXacNhanThanhToanCacheModel = new TthcXacNhanThanhToanCacheModel();

		tthcXacNhanThanhToanCacheModel.id = getId();

		tthcXacNhanThanhToanCacheModel.maTuSinh = getMaTuSinh();

		String maTuSinh = tthcXacNhanThanhToanCacheModel.maTuSinh;

		if ((maTuSinh != null) && (maTuSinh.length() == 0)) {
			tthcXacNhanThanhToanCacheModel.maTuSinh = null;
		}

		tthcXacNhanThanhToanCacheModel.soTien = getSoTien();

		tthcXacNhanThanhToanCacheModel.hinhThucThanhToan = getHinhThucThanhToan();

		tthcXacNhanThanhToanCacheModel.thongTinXacNhan = getThongTinXacNhan();

		String thongTinXacNhan = tthcXacNhanThanhToanCacheModel.thongTinXacNhan;

		if ((thongTinXacNhan != null) && (thongTinXacNhan.length() == 0)) {
			tthcXacNhanThanhToanCacheModel.thongTinXacNhan = null;
		}

		tthcXacNhanThanhToanCacheModel.taiLieuDinhKem = getTaiLieuDinhKem();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			tthcXacNhanThanhToanCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			tthcXacNhanThanhToanCacheModel.ngayTao = Long.MIN_VALUE;
		}

		tthcXacNhanThanhToanCacheModel.nguoiTao = getNguoiTao();

		Date ngayXacNhan = getNgayXacNhan();

		if (ngayXacNhan != null) {
			tthcXacNhanThanhToanCacheModel.ngayXacNhan = ngayXacNhan.getTime();
		}
		else {
			tthcXacNhanThanhToanCacheModel.ngayXacNhan = Long.MIN_VALUE;
		}

		tthcXacNhanThanhToanCacheModel.nguoiXacNhan = getNguoiXacNhan();

		tthcXacNhanThanhToanCacheModel.toChucQuanLy = getToChucQuanLy();

		tthcXacNhanThanhToanCacheModel.trangThaiXacNhan = getTrangThaiXacNhan();

		tthcXacNhanThanhToanCacheModel.yKienXuLy = getYKienXuLy();

		String yKienXuLy = tthcXacNhanThanhToanCacheModel.yKienXuLy;

		if ((yKienXuLy != null) && (yKienXuLy.length() == 0)) {
			tthcXacNhanThanhToanCacheModel.yKienXuLy = null;
		}

		tthcXacNhanThanhToanCacheModel.loaiPhi = getLoaiPhi();

		String loaiPhi = tthcXacNhanThanhToanCacheModel.loaiPhi;

		if ((loaiPhi != null) && (loaiPhi.length() == 0)) {
			tthcXacNhanThanhToanCacheModel.loaiPhi = null;
		}

		tthcXacNhanThanhToanCacheModel.tenDoanhNghiep = getTenDoanhNghiep();

		String tenDoanhNghiep = tthcXacNhanThanhToanCacheModel.tenDoanhNghiep;

		if ((tenDoanhNghiep != null) && (tenDoanhNghiep.length() == 0)) {
			tthcXacNhanThanhToanCacheModel.tenDoanhNghiep = null;
		}

		tthcXacNhanThanhToanCacheModel.ghiChu = getGhiChu();

		String ghiChu = tthcXacNhanThanhToanCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			tthcXacNhanThanhToanCacheModel.ghiChu = null;
		}

		return tthcXacNhanThanhToanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maTuSinh=");
		sb.append(getMaTuSinh());
		sb.append(", soTien=");
		sb.append(getSoTien());
		sb.append(", hinhThucThanhToan=");
		sb.append(getHinhThucThanhToan());
		sb.append(", thongTinXacNhan=");
		sb.append(getThongTinXacNhan());
		sb.append(", taiLieuDinhKem=");
		sb.append(getTaiLieuDinhKem());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngayXacNhan=");
		sb.append(getNgayXacNhan());
		sb.append(", nguoiXacNhan=");
		sb.append(getNguoiXacNhan());
		sb.append(", toChucQuanLy=");
		sb.append(getToChucQuanLy());
		sb.append(", trangThaiXacNhan=");
		sb.append(getTrangThaiXacNhan());
		sb.append(", yKienXuLy=");
		sb.append(getYKienXuLy());
		sb.append(", loaiPhi=");
		sb.append(getLoaiPhi());
		sb.append(", tenDoanhNghiep=");
		sb.append(getTenDoanhNghiep());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.duongbo.dao.thanhtoan.model.TthcXacNhanThanhToan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTuSinh</column-name><column-value><![CDATA[");
		sb.append(getMaTuSinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soTien</column-name><column-value><![CDATA[");
		sb.append(getSoTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hinhThucThanhToan</column-name><column-value><![CDATA[");
		sb.append(getHinhThucThanhToan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thongTinXacNhan</column-name><column-value><![CDATA[");
		sb.append(getThongTinXacNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiLieuDinhKem</column-name><column-value><![CDATA[");
		sb.append(getTaiLieuDinhKem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayXacNhan</column-name><column-value><![CDATA[");
		sb.append(getNgayXacNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiXacNhan</column-name><column-value><![CDATA[");
		sb.append(getNguoiXacNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>toChucQuanLy</column-name><column-value><![CDATA[");
		sb.append(getToChucQuanLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiXacNhan</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiXacNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yKienXuLy</column-name><column-value><![CDATA[");
		sb.append(getYKienXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiPhi</column-name><column-value><![CDATA[");
		sb.append(getLoaiPhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDoanhNghiep</column-name><column-value><![CDATA[");
		sb.append(getTenDoanhNghiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TthcXacNhanThanhToan.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TthcXacNhanThanhToan.class
		};
	private long _id;
	private String _maTuSinh;
	private String _originalMaTuSinh;
	private long _soTien;
	private long _hinhThucThanhToan;
	private String _thongTinXacNhan;
	private long _taiLieuDinhKem;
	private Date _ngayTao;
	private long _nguoiTao;
	private Date _ngayXacNhan;
	private long _nguoiXacNhan;
	private long _toChucQuanLy;
	private long _originalToChucQuanLy;
	private boolean _setOriginalToChucQuanLy;
	private int _trangThaiXacNhan;
	private String _yKienXuLy;
	private String _loaiPhi;
	private String _tenDoanhNghiep;
	private String _ghiChu;
	private long _columnBitmask;
	private TthcXacNhanThanhToan _escapedModel;
}