/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.thanhtoan.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.dtt.duongbo.dao.thanhtoan.model.TthcYeuCauThanhToan;
import vn.dtt.duongbo.dao.thanhtoan.service.TthcYeuCauThanhToanLocalServiceUtil;

/**
 * The extended model base implementation for the TthcYeuCauThanhToan service. Represents a row in the &quot;tthc_yeucauthanhtoan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TthcYeuCauThanhToanImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcYeuCauThanhToanImpl
 * @see vn.dtt.duongbo.dao.thanhtoan.model.TthcYeuCauThanhToan
 * @generated
 */
public abstract class TthcYeuCauThanhToanBaseImpl
	extends TthcYeuCauThanhToanModelImpl implements TthcYeuCauThanhToan {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tthc yeu cau thanh toan model instance should use the {@link TthcYeuCauThanhToan} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TthcYeuCauThanhToanLocalServiceUtil.addTthcYeuCauThanhToan(this);
		}
		else {
			TthcYeuCauThanhToanLocalServiceUtil.updateTthcYeuCauThanhToan(this);
		}
	}
}