/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.quocte.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import vn.dtt.duongbo.dao.quocte.model.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai;
import vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService;
import vn.dtt.duongbo.dao.quocte.service.persistence.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence;
import vn.dtt.duongbo.dao.quocte.service.persistence.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence;
import vn.dtt.duongbo.dao.quocte.service.persistence.QlvtXuLyGpkdvtQuocTePersistence;
import vn.dtt.duongbo.dao.quocte.service.persistence.QlvtXuLyKTTQuocTeBieuDoXePersistence;
import vn.dtt.duongbo.dao.quocte.service.persistence.QlvtXuLyKTTQuocTeDiemDungNghiPersistence;
import vn.dtt.duongbo.dao.quocte.service.persistence.QlvtXuLyKTTQuocTePersistence;
import vn.dtt.duongbo.dao.quocte.service.persistence.QlvtXuLyKTTQuocTePhuongTienPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the qlvt xu ly gpkdvt quoc te loai hinh van tai remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dtt.duongbo.dao.quocte.service.impl.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiServiceImpl}.
 * </p>
 *
 * @author NoiPham
 * @see vn.dtt.duongbo.dao.quocte.service.impl.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiServiceImpl
 * @see vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiServiceUtil
 * @generated
 */
public abstract class QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiServiceBaseImpl
	extends BaseServiceImpl implements QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiServiceUtil} to access the qlvt xu ly gpkdvt quoc te loai hinh van tai remote service.
	 */

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te local service.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te local service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLocalService getQlvtXuLyGpkdvtQuocTeLocalService() {
		return qlvtXuLyGpkdvtQuocTeLocalService;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te local service.
	 *
	 * @param qlvtXuLyGpkdvtQuocTeLocalService the qlvt xu ly gpkdvt quoc te local service
	 */
	public void setQlvtXuLyGpkdvtQuocTeLocalService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLocalService qlvtXuLyGpkdvtQuocTeLocalService) {
		this.qlvtXuLyGpkdvtQuocTeLocalService = qlvtXuLyGpkdvtQuocTeLocalService;
	}

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te remote service.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te remote service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeService getQlvtXuLyGpkdvtQuocTeService() {
		return qlvtXuLyGpkdvtQuocTeService;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te remote service.
	 *
	 * @param qlvtXuLyGpkdvtQuocTeService the qlvt xu ly gpkdvt quoc te remote service
	 */
	public void setQlvtXuLyGpkdvtQuocTeService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeService qlvtXuLyGpkdvtQuocTeService) {
		this.qlvtXuLyGpkdvtQuocTeService = qlvtXuLyGpkdvtQuocTeService;
	}

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te persistence.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te persistence
	 */
	public QlvtXuLyGpkdvtQuocTePersistence getQlvtXuLyGpkdvtQuocTePersistence() {
		return qlvtXuLyGpkdvtQuocTePersistence;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te persistence.
	 *
	 * @param qlvtXuLyGpkdvtQuocTePersistence the qlvt xu ly gpkdvt quoc te persistence
	 */
	public void setQlvtXuLyGpkdvtQuocTePersistence(
		QlvtXuLyGpkdvtQuocTePersistence qlvtXuLyGpkdvtQuocTePersistence) {
		this.qlvtXuLyGpkdvtQuocTePersistence = qlvtXuLyGpkdvtQuocTePersistence;
	}

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te loai hinh van tai local service.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te loai hinh van tai local service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService getQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService() {
		return qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te loai hinh van tai local service.
	 *
	 * @param qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService the qlvt xu ly gpkdvt quoc te loai hinh van tai local service
	 */
	public void setQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService) {
		this.qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService;
	}

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te loai hinh van tai remote service.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te loai hinh van tai remote service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService getQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService() {
		return qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te loai hinh van tai remote service.
	 *
	 * @param qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService the qlvt xu ly gpkdvt quoc te loai hinh van tai remote service
	 */
	public void setQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService) {
		this.qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService;
	}

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te loai hinh van tai persistence.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te loai hinh van tai persistence
	 */
	public QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence getQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence() {
		return qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te loai hinh van tai persistence.
	 *
	 * @param qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence the qlvt xu ly gpkdvt quoc te loai hinh van tai persistence
	 */
	public void setQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence(
		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence) {
		this.qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence;
	}

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen local service.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen local service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService getQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService() {
		return qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen local service.
	 *
	 * @param qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen local service
	 */
	public void setQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService) {
		this.qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService;
	}

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen remote service.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen remote service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService getQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService() {
		return qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen remote service.
	 *
	 * @param qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen remote service
	 */
	public void setQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService) {
		this.qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService;
	}

	/**
	 * Returns the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen persistence.
	 *
	 * @return the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen persistence
	 */
	public QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence getQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence() {
		return qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence;
	}

	/**
	 * Sets the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen persistence.
	 *
	 * @param qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence the qlvt xu ly gpkdvt quoc te loai hinh van tai tuyen persistence
	 */
	public void setQlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence(
		QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence) {
		this.qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te local service.
	 *
	 * @return the qlvt xu ly k t t quoc te local service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeLocalService getQlvtXuLyKTTQuocTeLocalService() {
		return qlvtXuLyKTTQuocTeLocalService;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te local service.
	 *
	 * @param qlvtXuLyKTTQuocTeLocalService the qlvt xu ly k t t quoc te local service
	 */
	public void setQlvtXuLyKTTQuocTeLocalService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeLocalService qlvtXuLyKTTQuocTeLocalService) {
		this.qlvtXuLyKTTQuocTeLocalService = qlvtXuLyKTTQuocTeLocalService;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te remote service.
	 *
	 * @return the qlvt xu ly k t t quoc te remote service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeService getQlvtXuLyKTTQuocTeService() {
		return qlvtXuLyKTTQuocTeService;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te remote service.
	 *
	 * @param qlvtXuLyKTTQuocTeService the qlvt xu ly k t t quoc te remote service
	 */
	public void setQlvtXuLyKTTQuocTeService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeService qlvtXuLyKTTQuocTeService) {
		this.qlvtXuLyKTTQuocTeService = qlvtXuLyKTTQuocTeService;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te persistence.
	 *
	 * @return the qlvt xu ly k t t quoc te persistence
	 */
	public QlvtXuLyKTTQuocTePersistence getQlvtXuLyKTTQuocTePersistence() {
		return qlvtXuLyKTTQuocTePersistence;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te persistence.
	 *
	 * @param qlvtXuLyKTTQuocTePersistence the qlvt xu ly k t t quoc te persistence
	 */
	public void setQlvtXuLyKTTQuocTePersistence(
		QlvtXuLyKTTQuocTePersistence qlvtXuLyKTTQuocTePersistence) {
		this.qlvtXuLyKTTQuocTePersistence = qlvtXuLyKTTQuocTePersistence;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te bieu do xe local service.
	 *
	 * @return the qlvt xu ly k t t quoc te bieu do xe local service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeBieuDoXeLocalService getQlvtXuLyKTTQuocTeBieuDoXeLocalService() {
		return qlvtXuLyKTTQuocTeBieuDoXeLocalService;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te bieu do xe local service.
	 *
	 * @param qlvtXuLyKTTQuocTeBieuDoXeLocalService the qlvt xu ly k t t quoc te bieu do xe local service
	 */
	public void setQlvtXuLyKTTQuocTeBieuDoXeLocalService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeBieuDoXeLocalService qlvtXuLyKTTQuocTeBieuDoXeLocalService) {
		this.qlvtXuLyKTTQuocTeBieuDoXeLocalService = qlvtXuLyKTTQuocTeBieuDoXeLocalService;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te bieu do xe remote service.
	 *
	 * @return the qlvt xu ly k t t quoc te bieu do xe remote service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeBieuDoXeService getQlvtXuLyKTTQuocTeBieuDoXeService() {
		return qlvtXuLyKTTQuocTeBieuDoXeService;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te bieu do xe remote service.
	 *
	 * @param qlvtXuLyKTTQuocTeBieuDoXeService the qlvt xu ly k t t quoc te bieu do xe remote service
	 */
	public void setQlvtXuLyKTTQuocTeBieuDoXeService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeBieuDoXeService qlvtXuLyKTTQuocTeBieuDoXeService) {
		this.qlvtXuLyKTTQuocTeBieuDoXeService = qlvtXuLyKTTQuocTeBieuDoXeService;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te bieu do xe persistence.
	 *
	 * @return the qlvt xu ly k t t quoc te bieu do xe persistence
	 */
	public QlvtXuLyKTTQuocTeBieuDoXePersistence getQlvtXuLyKTTQuocTeBieuDoXePersistence() {
		return qlvtXuLyKTTQuocTeBieuDoXePersistence;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te bieu do xe persistence.
	 *
	 * @param qlvtXuLyKTTQuocTeBieuDoXePersistence the qlvt xu ly k t t quoc te bieu do xe persistence
	 */
	public void setQlvtXuLyKTTQuocTeBieuDoXePersistence(
		QlvtXuLyKTTQuocTeBieuDoXePersistence qlvtXuLyKTTQuocTeBieuDoXePersistence) {
		this.qlvtXuLyKTTQuocTeBieuDoXePersistence = qlvtXuLyKTTQuocTeBieuDoXePersistence;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te diem dung nghi local service.
	 *
	 * @return the qlvt xu ly k t t quoc te diem dung nghi local service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeDiemDungNghiLocalService getQlvtXuLyKTTQuocTeDiemDungNghiLocalService() {
		return qlvtXuLyKTTQuocTeDiemDungNghiLocalService;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te diem dung nghi local service.
	 *
	 * @param qlvtXuLyKTTQuocTeDiemDungNghiLocalService the qlvt xu ly k t t quoc te diem dung nghi local service
	 */
	public void setQlvtXuLyKTTQuocTeDiemDungNghiLocalService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeDiemDungNghiLocalService qlvtXuLyKTTQuocTeDiemDungNghiLocalService) {
		this.qlvtXuLyKTTQuocTeDiemDungNghiLocalService = qlvtXuLyKTTQuocTeDiemDungNghiLocalService;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te diem dung nghi remote service.
	 *
	 * @return the qlvt xu ly k t t quoc te diem dung nghi remote service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeDiemDungNghiService getQlvtXuLyKTTQuocTeDiemDungNghiService() {
		return qlvtXuLyKTTQuocTeDiemDungNghiService;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te diem dung nghi remote service.
	 *
	 * @param qlvtXuLyKTTQuocTeDiemDungNghiService the qlvt xu ly k t t quoc te diem dung nghi remote service
	 */
	public void setQlvtXuLyKTTQuocTeDiemDungNghiService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeDiemDungNghiService qlvtXuLyKTTQuocTeDiemDungNghiService) {
		this.qlvtXuLyKTTQuocTeDiemDungNghiService = qlvtXuLyKTTQuocTeDiemDungNghiService;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te diem dung nghi persistence.
	 *
	 * @return the qlvt xu ly k t t quoc te diem dung nghi persistence
	 */
	public QlvtXuLyKTTQuocTeDiemDungNghiPersistence getQlvtXuLyKTTQuocTeDiemDungNghiPersistence() {
		return qlvtXuLyKTTQuocTeDiemDungNghiPersistence;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te diem dung nghi persistence.
	 *
	 * @param qlvtXuLyKTTQuocTeDiemDungNghiPersistence the qlvt xu ly k t t quoc te diem dung nghi persistence
	 */
	public void setQlvtXuLyKTTQuocTeDiemDungNghiPersistence(
		QlvtXuLyKTTQuocTeDiemDungNghiPersistence qlvtXuLyKTTQuocTeDiemDungNghiPersistence) {
		this.qlvtXuLyKTTQuocTeDiemDungNghiPersistence = qlvtXuLyKTTQuocTeDiemDungNghiPersistence;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te phuong tien local service.
	 *
	 * @return the qlvt xu ly k t t quoc te phuong tien local service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTePhuongTienLocalService getQlvtXuLyKTTQuocTePhuongTienLocalService() {
		return qlvtXuLyKTTQuocTePhuongTienLocalService;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te phuong tien local service.
	 *
	 * @param qlvtXuLyKTTQuocTePhuongTienLocalService the qlvt xu ly k t t quoc te phuong tien local service
	 */
	public void setQlvtXuLyKTTQuocTePhuongTienLocalService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTePhuongTienLocalService qlvtXuLyKTTQuocTePhuongTienLocalService) {
		this.qlvtXuLyKTTQuocTePhuongTienLocalService = qlvtXuLyKTTQuocTePhuongTienLocalService;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te phuong tien remote service.
	 *
	 * @return the qlvt xu ly k t t quoc te phuong tien remote service
	 */
	public vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTePhuongTienService getQlvtXuLyKTTQuocTePhuongTienService() {
		return qlvtXuLyKTTQuocTePhuongTienService;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te phuong tien remote service.
	 *
	 * @param qlvtXuLyKTTQuocTePhuongTienService the qlvt xu ly k t t quoc te phuong tien remote service
	 */
	public void setQlvtXuLyKTTQuocTePhuongTienService(
		vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTePhuongTienService qlvtXuLyKTTQuocTePhuongTienService) {
		this.qlvtXuLyKTTQuocTePhuongTienService = qlvtXuLyKTTQuocTePhuongTienService;
	}

	/**
	 * Returns the qlvt xu ly k t t quoc te phuong tien persistence.
	 *
	 * @return the qlvt xu ly k t t quoc te phuong tien persistence
	 */
	public QlvtXuLyKTTQuocTePhuongTienPersistence getQlvtXuLyKTTQuocTePhuongTienPersistence() {
		return qlvtXuLyKTTQuocTePhuongTienPersistence;
	}

	/**
	 * Sets the qlvt xu ly k t t quoc te phuong tien persistence.
	 *
	 * @param qlvtXuLyKTTQuocTePhuongTienPersistence the qlvt xu ly k t t quoc te phuong tien persistence
	 */
	public void setQlvtXuLyKTTQuocTePhuongTienPersistence(
		QlvtXuLyKTTQuocTePhuongTienPersistence qlvtXuLyKTTQuocTePhuongTienPersistence) {
		this.qlvtXuLyKTTQuocTePhuongTienPersistence = qlvtXuLyKTTQuocTePhuongTienPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.class;
	}

	protected String getModelClassName() {
		return QlvtXuLyGpkdvtQuocTeLoaiHinhVanTai.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLocalService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLocalService qlvtXuLyGpkdvtQuocTeLocalService;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeService qlvtXuLyGpkdvtQuocTeService;
	@BeanReference(type = QlvtXuLyGpkdvtQuocTePersistence.class)
	protected QlvtXuLyGpkdvtQuocTePersistence qlvtXuLyGpkdvtQuocTePersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiLocalService;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiService;
	@BeanReference(type = QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence.class)
	protected QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenLocalService;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenService;
	@BeanReference(type = QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence.class)
	protected QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence qlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiTuyenPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeLocalService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeLocalService qlvtXuLyKTTQuocTeLocalService;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeService qlvtXuLyKTTQuocTeService;
	@BeanReference(type = QlvtXuLyKTTQuocTePersistence.class)
	protected QlvtXuLyKTTQuocTePersistence qlvtXuLyKTTQuocTePersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeBieuDoXeLocalService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeBieuDoXeLocalService qlvtXuLyKTTQuocTeBieuDoXeLocalService;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeBieuDoXeService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeBieuDoXeService qlvtXuLyKTTQuocTeBieuDoXeService;
	@BeanReference(type = QlvtXuLyKTTQuocTeBieuDoXePersistence.class)
	protected QlvtXuLyKTTQuocTeBieuDoXePersistence qlvtXuLyKTTQuocTeBieuDoXePersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeDiemDungNghiLocalService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeDiemDungNghiLocalService qlvtXuLyKTTQuocTeDiemDungNghiLocalService;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeDiemDungNghiService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTeDiemDungNghiService qlvtXuLyKTTQuocTeDiemDungNghiService;
	@BeanReference(type = QlvtXuLyKTTQuocTeDiemDungNghiPersistence.class)
	protected QlvtXuLyKTTQuocTeDiemDungNghiPersistence qlvtXuLyKTTQuocTeDiemDungNghiPersistence;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTePhuongTienLocalService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTePhuongTienLocalService qlvtXuLyKTTQuocTePhuongTienLocalService;
	@BeanReference(type = vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTePhuongTienService.class)
	protected vn.dtt.duongbo.dao.quocte.service.QlvtXuLyKTTQuocTePhuongTienService qlvtXuLyKTTQuocTePhuongTienService;
	@BeanReference(type = QlvtXuLyKTTQuocTePhuongTienPersistence.class)
	protected QlvtXuLyKTTQuocTePhuongTienPersistence qlvtXuLyKTTQuocTePhuongTienPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiServiceClpInvoker _clpInvoker = new QlvtXuLyGpkdvtQuocTeLoaiHinhVanTaiServiceClpInvoker();
}