/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QlvtNoiDungThamTra service. Represents a row in the &quot;nghiepvu_noidungthamtra&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtNoiDungThamTraModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtNoiDungThamTraImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtNoiDungThamTra
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtNoiDungThamTraImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtNoiDungThamTraModelImpl
 * @generated
 */
public interface QlvtNoiDungThamTraModel extends BaseModel<QlvtNoiDungThamTra> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt noi dung tham tra model instance should use the {@link QlvtNoiDungThamTra} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt noi dung tham tra.
	 *
	 * @return the primary key of this qlvt noi dung tham tra
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt noi dung tham tra.
	 *
	 * @param primaryKey the primary key of this qlvt noi dung tham tra
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt noi dung tham tra.
	 *
	 * @return the ID of this qlvt noi dung tham tra
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt noi dung tham tra.
	 *
	 * @param id the ID of this qlvt noi dung tham tra
	 */
	public void setId(long id);

	/**
	 * Returns the muc kiem tra of this qlvt noi dung tham tra.
	 *
	 * @return the muc kiem tra of this qlvt noi dung tham tra
	 */
	@AutoEscape
	public String getMucKiemTra();

	/**
	 * Sets the muc kiem tra of this qlvt noi dung tham tra.
	 *
	 * @param mucKiemTra the muc kiem tra of this qlvt noi dung tham tra
	 */
	public void setMucKiemTra(String mucKiemTra);

	/**
	 * Returns the cha ID of this qlvt noi dung tham tra.
	 *
	 * @return the cha ID of this qlvt noi dung tham tra
	 */
	public int getChaId();

	/**
	 * Sets the cha ID of this qlvt noi dung tham tra.
	 *
	 * @param chaId the cha ID of this qlvt noi dung tham tra
	 */
	public void setChaId(int chaId);

	/**
	 * Returns the co y kien of this qlvt noi dung tham tra.
	 *
	 * @return the co y kien of this qlvt noi dung tham tra
	 */
	public int getCoYKien();

	/**
	 * Sets the co y kien of this qlvt noi dung tham tra.
	 *
	 * @param coYKien the co y kien of this qlvt noi dung tham tra
	 */
	public void setCoYKien(int coYKien);

	/**
	 * Returns the buoc xu ly of this qlvt noi dung tham tra.
	 *
	 * @return the buoc xu ly of this qlvt noi dung tham tra
	 */
	public int getBuocXuLy();

	/**
	 * Sets the buoc xu ly of this qlvt noi dung tham tra.
	 *
	 * @param buocXuLy the buoc xu ly of this qlvt noi dung tham tra
	 */
	public void setBuocXuLy(int buocXuLy);

	/**
	 * Returns the thu tu hien thi of this qlvt noi dung tham tra.
	 *
	 * @return the thu tu hien thi of this qlvt noi dung tham tra
	 */
	public int getThuTuHienThi();

	/**
	 * Sets the thu tu hien thi of this qlvt noi dung tham tra.
	 *
	 * @param thuTuHienThi the thu tu hien thi of this qlvt noi dung tham tra
	 */
	public void setThuTuHienThi(int thuTuHienThi);

	/**
	 * Returns the tthc noi dung tham tra ID of this qlvt noi dung tham tra.
	 *
	 * @return the tthc noi dung tham tra ID of this qlvt noi dung tham tra
	 */
	public int getTthcNoiDungThamTraId();

	/**
	 * Sets the tthc noi dung tham tra ID of this qlvt noi dung tham tra.
	 *
	 * @param tthcNoiDungThamTraId the tthc noi dung tham tra ID of this qlvt noi dung tham tra
	 */
	public void setTthcNoiDungThamTraId(int tthcNoiDungThamTraId);

	/**
	 * Returns the tien to of this qlvt noi dung tham tra.
	 *
	 * @return the tien to of this qlvt noi dung tham tra
	 */
	@AutoEscape
	public String getTienTo();

	/**
	 * Sets the tien to of this qlvt noi dung tham tra.
	 *
	 * @param tienTo the tien to of this qlvt noi dung tham tra
	 */
	public void setTienTo(String tienTo);

	/**
	 * Returns the thanh phan ho so of this qlvt noi dung tham tra.
	 *
	 * @return the thanh phan ho so of this qlvt noi dung tham tra
	 */
	@AutoEscape
	public String getThanhPhanHoSo();

	/**
	 * Sets the thanh phan ho so of this qlvt noi dung tham tra.
	 *
	 * @param thanhPhanHoSo the thanh phan ho so of this qlvt noi dung tham tra
	 */
	public void setThanhPhanHoSo(String thanhPhanHoSo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtNoiDungThamTra qlvtNoiDungThamTra);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtNoiDungThamTra> toCacheModel();

	@Override
	public QlvtNoiDungThamTra toEscapedModel();

	@Override
	public QlvtNoiDungThamTra toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}