/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QlvtLoaiHinhHoatDongTths service. Represents a row in the &quot;QLVT_LOAIHINHHOATDONG_TTHS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtLoaiHinhHoatDongTthsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtLoaiHinhHoatDongTthsImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtLoaiHinhHoatDongTths
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtLoaiHinhHoatDongTthsImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtLoaiHinhHoatDongTthsModelImpl
 * @generated
 */
public interface QlvtLoaiHinhHoatDongTthsModel extends BaseModel<QlvtLoaiHinhHoatDongTths> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt loai hinh hoat dong tths model instance should use the {@link QlvtLoaiHinhHoatDongTths} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the primary key of this qlvt loai hinh hoat dong tths
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt loai hinh hoat dong tths.
	 *
	 * @param primaryKey the primary key of this qlvt loai hinh hoat dong tths
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the ID of this qlvt loai hinh hoat dong tths
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt loai hinh hoat dong tths.
	 *
	 * @param id the ID of this qlvt loai hinh hoat dong tths
	 */
	public void setId(long id);

	/**
	 * Returns the ma loai hinh hoat dong of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the ma loai hinh hoat dong of this qlvt loai hinh hoat dong tths
	 */
	@AutoEscape
	public String getMaLoaiHinhHoatDong();

	/**
	 * Sets the ma loai hinh hoat dong of this qlvt loai hinh hoat dong tths.
	 *
	 * @param maLoaiHinhHoatDong the ma loai hinh hoat dong of this qlvt loai hinh hoat dong tths
	 */
	public void setMaLoaiHinhHoatDong(String maLoaiHinhHoatDong);

	/**
	 * Returns the thong tin ho so ID of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the thong tin ho so ID of this qlvt loai hinh hoat dong tths
	 */
	public long getThongTinHoSoId();

	/**
	 * Sets the thong tin ho so ID of this qlvt loai hinh hoat dong tths.
	 *
	 * @param thongTinHoSoId the thong tin ho so ID of this qlvt loai hinh hoat dong tths
	 */
	public void setThongTinHoSoId(long thongTinHoSoId);

	/**
	 * Returns the so luong phuong tien of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the so luong phuong tien of this qlvt loai hinh hoat dong tths
	 */
	public int getSoLuongPhuongTien();

	/**
	 * Sets the so luong phuong tien of this qlvt loai hinh hoat dong tths.
	 *
	 * @param soLuongPhuongTien the so luong phuong tien of this qlvt loai hinh hoat dong tths
	 */
	public void setSoLuongPhuongTien(int soLuongPhuongTien);

	/**
	 * Returns the thiet bi giam sat hanh trinh of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the thiet bi giam sat hanh trinh of this qlvt loai hinh hoat dong tths
	 */
	public int getThietBiGiamSatHanhTrinh();

	/**
	 * Sets the thiet bi giam sat hanh trinh of this qlvt loai hinh hoat dong tths.
	 *
	 * @param thietBiGiamSatHanhTrinh the thiet bi giam sat hanh trinh of this qlvt loai hinh hoat dong tths
	 */
	public void setThietBiGiamSatHanhTrinh(int thietBiGiamSatHanhTrinh);

	/**
	 * Returns the tuyen tu of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the tuyen tu of this qlvt loai hinh hoat dong tths
	 */
	@AutoEscape
	public String getTuyenTu();

	/**
	 * Sets the tuyen tu of this qlvt loai hinh hoat dong tths.
	 *
	 * @param tuyenTu the tuyen tu of this qlvt loai hinh hoat dong tths
	 */
	public void setTuyenTu(String tuyenTu);

	/**
	 * Returns the tuyen den of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the tuyen den of this qlvt loai hinh hoat dong tths
	 */
	@AutoEscape
	public String getTuyenDen();

	/**
	 * Sets the tuyen den of this qlvt loai hinh hoat dong tths.
	 *
	 * @param tuyenDen the tuyen den of this qlvt loai hinh hoat dong tths
	 */
	public void setTuyenDen(String tuyenDen);

	/**
	 * Returns the so chuyen of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the so chuyen of this qlvt loai hinh hoat dong tths
	 */
	public long getSoChuyen();

	/**
	 * Sets the so chuyen of this qlvt loai hinh hoat dong tths.
	 *
	 * @param soChuyen the so chuyen of this qlvt loai hinh hoat dong tths
	 */
	public void setSoChuyen(long soChuyen);

	/**
	 * Returns the mau son of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the mau son of this qlvt loai hinh hoat dong tths
	 */
	@AutoEscape
	public String getMauSon();

	/**
	 * Sets the mau son of this qlvt loai hinh hoat dong tths.
	 *
	 * @param mauSon the mau son of this qlvt loai hinh hoat dong tths
	 */
	public void setMauSon(String mauSon);

	/**
	 * Returns the loai hinh kinh doanh cu the of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the loai hinh kinh doanh cu the of this qlvt loai hinh hoat dong tths
	 */
	@AutoEscape
	public String getLoaiHinhKinhDoanhCuThe();

	/**
	 * Sets the loai hinh kinh doanh cu the of this qlvt loai hinh hoat dong tths.
	 *
	 * @param loaiHinhKinhDoanhCuThe the loai hinh kinh doanh cu the of this qlvt loai hinh hoat dong tths
	 */
	public void setLoaiHinhKinhDoanhCuThe(String loaiHinhKinhDoanhCuThe);

	/**
	 * Returns the danh gia of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the danh gia of this qlvt loai hinh hoat dong tths
	 */
	public int getDanhGia();

	/**
	 * Sets the danh gia of this qlvt loai hinh hoat dong tths.
	 *
	 * @param danhGia the danh gia of this qlvt loai hinh hoat dong tths
	 */
	public void setDanhGia(int danhGia);

	/**
	 * Returns the ly do khong dat of this qlvt loai hinh hoat dong tths.
	 *
	 * @return the ly do khong dat of this qlvt loai hinh hoat dong tths
	 */
	@AutoEscape
	public String getLyDoKhongDat();

	/**
	 * Sets the ly do khong dat of this qlvt loai hinh hoat dong tths.
	 *
	 * @param lyDoKhongDat the ly do khong dat of this qlvt loai hinh hoat dong tths
	 */
	public void setLyDoKhongDat(String lyDoKhongDat);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtLoaiHinhHoatDongTths qlvtLoaiHinhHoatDongTths);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtLoaiHinhHoatDongTths> toCacheModel();

	@Override
	public QlvtLoaiHinhHoatDongTths toEscapedModel();

	@Override
	public QlvtLoaiHinhHoatDongTths toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}