/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QlvtThongTinHoSo service. Represents a row in the &quot;nghiepvu_thongtinhoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinHoSoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinHoSoImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtThongTinHoSo
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinHoSoImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinHoSoModelImpl
 * @generated
 */
public interface QlvtThongTinHoSoModel extends BaseModel<QlvtThongTinHoSo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt thong tin ho so model instance should use the {@link QlvtThongTinHoSo} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt thong tin ho so.
	 *
	 * @return the primary key of this qlvt thong tin ho so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt thong tin ho so.
	 *
	 * @param primaryKey the primary key of this qlvt thong tin ho so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt thong tin ho so.
	 *
	 * @return the ID of this qlvt thong tin ho so
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt thong tin ho so.
	 *
	 * @param id the ID of this qlvt thong tin ho so
	 */
	public void setId(long id);

	/**
	 * Returns the so cong van den of this qlvt thong tin ho so.
	 *
	 * @return the so cong van den of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getSoCongVanDen();

	/**
	 * Sets the so cong van den of this qlvt thong tin ho so.
	 *
	 * @param soCongVanDen the so cong van den of this qlvt thong tin ho so
	 */
	public void setSoCongVanDen(String soCongVanDen);

	/**
	 * Returns the ten dn of this qlvt thong tin ho so.
	 *
	 * @return the ten dn of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getTenDn();

	/**
	 * Sets the ten dn of this qlvt thong tin ho so.
	 *
	 * @param tenDn the ten dn of this qlvt thong tin ho so
	 */
	public void setTenDn(String tenDn);

	/**
	 * Returns the dia chi dn of this qlvt thong tin ho so.
	 *
	 * @return the dia chi dn of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getDiaChiDn();

	/**
	 * Sets the dia chi dn of this qlvt thong tin ho so.
	 *
	 * @param diaChiDn the dia chi dn of this qlvt thong tin ho so
	 */
	public void setDiaChiDn(String diaChiDn);

	/**
	 * Returns the dien thoai dn of this qlvt thong tin ho so.
	 *
	 * @return the dien thoai dn of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getDienThoaiDn();

	/**
	 * Sets the dien thoai dn of this qlvt thong tin ho so.
	 *
	 * @param dienThoaiDn the dien thoai dn of this qlvt thong tin ho so
	 */
	public void setDienThoaiDn(String dienThoaiDn);

	/**
	 * Returns the so fax dn of this qlvt thong tin ho so.
	 *
	 * @return the so fax dn of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getSoFaxDn();

	/**
	 * Sets the so fax dn of this qlvt thong tin ho so.
	 *
	 * @param soFaxDn the so fax dn of this qlvt thong tin ho so
	 */
	public void setSoFaxDn(String soFaxDn);

	/**
	 * Returns the email dn of this qlvt thong tin ho so.
	 *
	 * @return the email dn of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getEmailDn();

	/**
	 * Sets the email dn of this qlvt thong tin ho so.
	 *
	 * @param emailDn the email dn of this qlvt thong tin ho so
	 */
	public void setEmailDn(String emailDn);

	/**
	 * Returns the web site dn of this qlvt thong tin ho so.
	 *
	 * @return the web site dn of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getWebSiteDn();

	/**
	 * Sets the web site dn of this qlvt thong tin ho so.
	 *
	 * @param webSiteDn the web site dn of this qlvt thong tin ho so
	 */
	public void setWebSiteDn(String webSiteDn);

	/**
	 * Returns the so dkkd of this qlvt thong tin ho so.
	 *
	 * @return the so dkkd of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getSoDkkd();

	/**
	 * Sets the so dkkd of this qlvt thong tin ho so.
	 *
	 * @param soDkkd the so dkkd of this qlvt thong tin ho so
	 */
	public void setSoDkkd(String soDkkd);

	/**
	 * Returns the ngay cap dkkd of this qlvt thong tin ho so.
	 *
	 * @return the ngay cap dkkd of this qlvt thong tin ho so
	 */
	public Date getNgayCapDkkd();

	/**
	 * Sets the ngay cap dkkd of this qlvt thong tin ho so.
	 *
	 * @param ngayCapDkkd the ngay cap dkkd of this qlvt thong tin ho so
	 */
	public void setNgayCapDkkd(Date ngayCapDkkd);

	/**
	 * Returns the ngay het han dkkd of this qlvt thong tin ho so.
	 *
	 * @return the ngay het han dkkd of this qlvt thong tin ho so
	 */
	public Date getNgayHetHanDkkd();

	/**
	 * Sets the ngay het han dkkd of this qlvt thong tin ho so.
	 *
	 * @param ngayHetHanDkkd the ngay het han dkkd of this qlvt thong tin ho so
	 */
	public void setNgayHetHanDkkd(Date ngayHetHanDkkd);

	/**
	 * Returns the co quan cap dkkd of this qlvt thong tin ho so.
	 *
	 * @return the co quan cap dkkd of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getCoQuanCapDkkd();

	/**
	 * Sets the co quan cap dkkd of this qlvt thong tin ho so.
	 *
	 * @param coQuanCapDkkd the co quan cap dkkd of this qlvt thong tin ho so
	 */
	public void setCoQuanCapDkkd(String coQuanCapDkkd);

	/**
	 * Returns the dai dien dn of this qlvt thong tin ho so.
	 *
	 * @return the dai dien dn of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getDaiDienDn();

	/**
	 * Sets the dai dien dn of this qlvt thong tin ho so.
	 *
	 * @param daiDienDn the dai dien dn of this qlvt thong tin ho so
	 */
	public void setDaiDienDn(String daiDienDn);

	/**
	 * Returns the co quan giai quyet of this qlvt thong tin ho so.
	 *
	 * @return the co quan giai quyet of this qlvt thong tin ho so
	 */
	public long getCoQuanGiaiQuyet();

	/**
	 * Sets the co quan giai quyet of this qlvt thong tin ho so.
	 *
	 * @param coQuanGiaiQuyet the co quan giai quyet of this qlvt thong tin ho so
	 */
	public void setCoQuanGiaiQuyet(long coQuanGiaiQuyet);

	/**
	 * Returns the dia diem lam ho so of this qlvt thong tin ho so.
	 *
	 * @return the dia diem lam ho so of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getDiaDiemLamHoSo();

	/**
	 * Sets the dia diem lam ho so of this qlvt thong tin ho so.
	 *
	 * @param diaDiemLamHoSo the dia diem lam ho so of this qlvt thong tin ho so
	 */
	public void setDiaDiemLamHoSo(String diaDiemLamHoSo);

	/**
	 * Returns the phieu xu ly ID of this qlvt thong tin ho so.
	 *
	 * @return the phieu xu ly ID of this qlvt thong tin ho so
	 */
	public long getPhieuXuLyId();

	/**
	 * Sets the phieu xu ly ID of this qlvt thong tin ho so.
	 *
	 * @param phieuXuLyId the phieu xu ly ID of this qlvt thong tin ho so
	 */
	public void setPhieuXuLyId(long phieuXuLyId);

	/**
	 * Returns the ma so ho so of this qlvt thong tin ho so.
	 *
	 * @return the ma so ho so of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getMaSoHoSo();

	/**
	 * Sets the ma so ho so of this qlvt thong tin ho so.
	 *
	 * @param maSoHoSo the ma so ho so of this qlvt thong tin ho so
	 */
	public void setMaSoHoSo(String maSoHoSo);

	/**
	 * Returns the ly do cap lai of this qlvt thong tin ho so.
	 *
	 * @return the ly do cap lai of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getLyDoCapLai();

	/**
	 * Sets the ly do cap lai of this qlvt thong tin ho so.
	 *
	 * @param lyDoCapLai the ly do cap lai of this qlvt thong tin ho so
	 */
	public void setLyDoCapLai(String lyDoCapLai);

	/**
	 * Returns the lan cap giay dang ky kinh doanh of this qlvt thong tin ho so.
	 *
	 * @return the lan cap giay dang ky kinh doanh of this qlvt thong tin ho so
	 */
	public int getLanCapGiayDangKyKinhDoanh();

	/**
	 * Sets the lan cap giay dang ky kinh doanh of this qlvt thong tin ho so.
	 *
	 * @param lanCapGiayDangKyKinhDoanh the lan cap giay dang ky kinh doanh of this qlvt thong tin ho so
	 */
	public void setLanCapGiayDangKyKinhDoanh(int lanCapGiayDangKyKinhDoanh);

	/**
	 * Returns the so giay phep kinh doanh van tai noi dia of this qlvt thong tin ho so.
	 *
	 * @return the so giay phep kinh doanh van tai noi dia of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getSoGiayPhepKinhDoanhVanTaiNoiDia();

	/**
	 * Sets the so giay phep kinh doanh van tai noi dia of this qlvt thong tin ho so.
	 *
	 * @param soGiayPhepKinhDoanhVanTaiNoiDia the so giay phep kinh doanh van tai noi dia of this qlvt thong tin ho so
	 */
	public void setSoGiayPhepKinhDoanhVanTaiNoiDia(
		String soGiayPhepKinhDoanhVanTaiNoiDia);

	/**
	 * Returns the ngay cap g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @return the ngay cap g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public Date getNgayCapGPKDVTNoiDia();

	/**
	 * Sets the ngay cap g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @param ngayCapGPKDVTNoiDia the ngay cap g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public void setNgayCapGPKDVTNoiDia(Date ngayCapGPKDVTNoiDia);

	/**
	 * Returns the ngay gia han g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @return the ngay gia han g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public Date getNgayGiaHanGPKDVTNoiDia();

	/**
	 * Sets the ngay gia han g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @param NgayGiaHanGPKDVTNoiDia the ngay gia han g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public void setNgayGiaHanGPKDVTNoiDia(Date NgayGiaHanGPKDVTNoiDia);

	/**
	 * Returns the ngay het han g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @return the ngay het han g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public Date getNgayHetHanGPKDVTNoiDia();

	/**
	 * Sets the ngay het han g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @param NgayHetHanGPKDVTNoiDia the ngay het han g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public void setNgayHetHanGPKDVTNoiDia(Date NgayHetHanGPKDVTNoiDia);

	/**
	 * Returns the lan cap g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @return the lan cap g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public int getLanCapGPKDVTNoiDia();

	/**
	 * Sets the lan cap g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @param lanCapGPKDVTNoiDia the lan cap g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public void setLanCapGPKDVTNoiDia(int lanCapGPKDVTNoiDia);

	/**
	 * Returns the ngay gia han giay dang ky kinh doanh of this qlvt thong tin ho so.
	 *
	 * @return the ngay gia han giay dang ky kinh doanh of this qlvt thong tin ho so
	 */
	public Date getNgayGiaHanGiayDangKyKinhDoanh();

	/**
	 * Sets the ngay gia han giay dang ky kinh doanh of this qlvt thong tin ho so.
	 *
	 * @param ngayGiaHanGiayDangKyKinhDoanh the ngay gia han giay dang ky kinh doanh of this qlvt thong tin ho so
	 */
	public void setNgayGiaHanGiayDangKyKinhDoanh(
		Date ngayGiaHanGiayDangKyKinhDoanh);

	/**
	 * Returns the so giay phep kinh doanh van tai quoc te of this qlvt thong tin ho so.
	 *
	 * @return the so giay phep kinh doanh van tai quoc te of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getSoGiayPhepKinhDoanhVanTaiQuocTe();

	/**
	 * Sets the so giay phep kinh doanh van tai quoc te of this qlvt thong tin ho so.
	 *
	 * @param soGiayPhepKinhDoanhVanTaiQuocTe the so giay phep kinh doanh van tai quoc te of this qlvt thong tin ho so
	 */
	public void setSoGiayPhepKinhDoanhVanTaiQuocTe(
		String soGiayPhepKinhDoanhVanTaiQuocTe);

	/**
	 * Returns the lan cap g p k d v t quoc te of this qlvt thong tin ho so.
	 *
	 * @return the lan cap g p k d v t quoc te of this qlvt thong tin ho so
	 */
	public int getLanCapGPKDVTQuocTe();

	/**
	 * Sets the lan cap g p k d v t quoc te of this qlvt thong tin ho so.
	 *
	 * @param lanCapGPKDVTQuocTe the lan cap g p k d v t quoc te of this qlvt thong tin ho so
	 */
	public void setLanCapGPKDVTQuocTe(int lanCapGPKDVTQuocTe);

	/**
	 * Returns the ngay cap g p k d v t quoc te of this qlvt thong tin ho so.
	 *
	 * @return the ngay cap g p k d v t quoc te of this qlvt thong tin ho so
	 */
	public Date getNgayCapGPKDVTQuocTe();

	/**
	 * Sets the ngay cap g p k d v t quoc te of this qlvt thong tin ho so.
	 *
	 * @param ngayCapGPKDVTQuocTe the ngay cap g p k d v t quoc te of this qlvt thong tin ho so
	 */
	public void setNgayCapGPKDVTQuocTe(Date ngayCapGPKDVTQuocTe);

	/**
	 * Returns the ngay gia han g p k d v t quoc te of this qlvt thong tin ho so.
	 *
	 * @return the ngay gia han g p k d v t quoc te of this qlvt thong tin ho so
	 */
	public Date getNgayGiaHanGPKDVTQuocTe();

	/**
	 * Sets the ngay gia han g p k d v t quoc te of this qlvt thong tin ho so.
	 *
	 * @param ngayGiaHanGPKDVTQuocTe the ngay gia han g p k d v t quoc te of this qlvt thong tin ho so
	 */
	public void setNgayGiaHanGPKDVTQuocTe(Date ngayGiaHanGPKDVTQuocTe);

	/**
	 * Returns the ngay het han g p k d v t quoc te of this qlvt thong tin ho so.
	 *
	 * @return the ngay het han g p k d v t quoc te of this qlvt thong tin ho so
	 */
	public Date getNgayHetHanGPKDVTQuocTe();

	/**
	 * Sets the ngay het han g p k d v t quoc te of this qlvt thong tin ho so.
	 *
	 * @param ngayHetHanGPKDVTQuocTe the ngay het han g p k d v t quoc te of this qlvt thong tin ho so
	 */
	public void setNgayHetHanGPKDVTQuocTe(Date ngayHetHanGPKDVTQuocTe);

	/**
	 * Returns the nguoi lien he tra ket qua of this qlvt thong tin ho so.
	 *
	 * @return the nguoi lien he tra ket qua of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getNguoiLienHeTraKetQua();

	/**
	 * Sets the nguoi lien he tra ket qua of this qlvt thong tin ho so.
	 *
	 * @param nguoiLienHeTraKetQua the nguoi lien he tra ket qua of this qlvt thong tin ho so
	 */
	public void setNguoiLienHeTraKetQua(String nguoiLienHeTraKetQua);

	/**
	 * Returns the so dien thoai nguoi lien he of this qlvt thong tin ho so.
	 *
	 * @return the so dien thoai nguoi lien he of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getSoDienThoaiNguoiLienHe();

	/**
	 * Sets the so dien thoai nguoi lien he of this qlvt thong tin ho so.
	 *
	 * @param soDienThoaiNguoiLienHe the so dien thoai nguoi lien he of this qlvt thong tin ho so
	 */
	public void setSoDienThoaiNguoiLienHe(String soDienThoaiNguoiLienHe);

	/**
	 * Returns the co quan cap g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @return the co quan cap g p k d v t noi dia of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getCoQuanCapGPKDVTNoiDia();

	/**
	 * Sets the co quan cap g p k d v t noi dia of this qlvt thong tin ho so.
	 *
	 * @param coQuanCapGPKDVTNoiDia the co quan cap g p k d v t noi dia of this qlvt thong tin ho so
	 */
	public void setCoQuanCapGPKDVTNoiDia(String coQuanCapGPKDVTNoiDia);

	/**
	 * Returns the nguoi nhan ket qua of this qlvt thong tin ho so.
	 *
	 * @return the nguoi nhan ket qua of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getNguoiNhanKetQua();

	/**
	 * Sets the nguoi nhan ket qua of this qlvt thong tin ho so.
	 *
	 * @param nguoiNhanKetQua the nguoi nhan ket qua of this qlvt thong tin ho so
	 */
	public void setNguoiNhanKetQua(String nguoiNhanKetQua);

	/**
	 * Returns the thong tin tra ket qua of this qlvt thong tin ho so.
	 *
	 * @return the thong tin tra ket qua of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getThongTinTraKetQua();

	/**
	 * Sets the thong tin tra ket qua of this qlvt thong tin ho so.
	 *
	 * @param thongTinTraKetQua the thong tin tra ket qua of this qlvt thong tin ho so
	 */
	public void setThongTinTraKetQua(String thongTinTraKetQua);

	/**
	 * Returns the ngay tra ket qua of this qlvt thong tin ho so.
	 *
	 * @return the ngay tra ket qua of this qlvt thong tin ho so
	 */
	public Date getNgayTraKetQua();

	/**
	 * Sets the ngay tra ket qua of this qlvt thong tin ho so.
	 *
	 * @param ngayTraKetQua the ngay tra ket qua of this qlvt thong tin ho so
	 */
	public void setNgayTraKetQua(Date ngayTraKetQua);

	/**
	 * Returns the dia chi nguoi lien he tra ket qua of this qlvt thong tin ho so.
	 *
	 * @return the dia chi nguoi lien he tra ket qua of this qlvt thong tin ho so
	 */
	@AutoEscape
	public String getDiaChiNguoiLienHeTraKetQua();

	/**
	 * Sets the dia chi nguoi lien he tra ket qua of this qlvt thong tin ho so.
	 *
	 * @param diaChiNguoiLienHeTraKetQua the dia chi nguoi lien he tra ket qua of this qlvt thong tin ho so
	 */
	public void setDiaChiNguoiLienHeTraKetQua(String diaChiNguoiLienHeTraKetQua);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtThongTinHoSo qlvtThongTinHoSo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtThongTinHoSo> toCacheModel();

	@Override
	public QlvtThongTinHoSo toEscapedModel();

	@Override
	public QlvtThongTinHoSo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}