/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QlvtTTHCNoiDungThamTra service. Represents a row in the &quot;nghiepvu_tthc_noidungthamtra&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtTTHCNoiDungThamTraModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtTTHCNoiDungThamTraImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtTTHCNoiDungThamTra
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtTTHCNoiDungThamTraImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtTTHCNoiDungThamTraModelImpl
 * @generated
 */
public interface QlvtTTHCNoiDungThamTraModel extends BaseModel<QlvtTTHCNoiDungThamTra> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt t t h c noi dung tham tra model instance should use the {@link QlvtTTHCNoiDungThamTra} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt t t h c noi dung tham tra.
	 *
	 * @return the primary key of this qlvt t t h c noi dung tham tra
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt t t h c noi dung tham tra.
	 *
	 * @param primaryKey the primary key of this qlvt t t h c noi dung tham tra
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt t t h c noi dung tham tra.
	 *
	 * @return the ID of this qlvt t t h c noi dung tham tra
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt t t h c noi dung tham tra.
	 *
	 * @param id the ID of this qlvt t t h c noi dung tham tra
	 */
	public void setId(long id);

	/**
	 * Returns the ma t t h c of this qlvt t t h c noi dung tham tra.
	 *
	 * @return the ma t t h c of this qlvt t t h c noi dung tham tra
	 */
	@AutoEscape
	public String getMaTTHC();

	/**
	 * Sets the ma t t h c of this qlvt t t h c noi dung tham tra.
	 *
	 * @param maTTHC the ma t t h c of this qlvt t t h c noi dung tham tra
	 */
	public void setMaTTHC(String maTTHC);

	/**
	 * Returns the to chuc xu ly of this qlvt t t h c noi dung tham tra.
	 *
	 * @return the to chuc xu ly of this qlvt t t h c noi dung tham tra
	 */
	public int getToChucXuLy();

	/**
	 * Sets the to chuc xu ly of this qlvt t t h c noi dung tham tra.
	 *
	 * @param toChucXuLy the to chuc xu ly of this qlvt t t h c noi dung tham tra
	 */
	public void setToChucXuLy(int toChucXuLy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtTTHCNoiDungThamTra qlvtTTHCNoiDungThamTra);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtTTHCNoiDungThamTra> toCacheModel();

	@Override
	public QlvtTTHCNoiDungThamTra toEscapedModel();

	@Override
	public QlvtTTHCNoiDungThamTra toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}