/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QlvtThongTinXuLy service. Represents a row in the &quot;nghiepvu_thongtinxulyso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinXuLyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinXuLyImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtThongTinXuLy
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinXuLyImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinXuLyModelImpl
 * @generated
 */
public interface QlvtThongTinXuLyModel extends BaseModel<QlvtThongTinXuLy> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt thong tin xu ly model instance should use the {@link QlvtThongTinXuLy} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt thong tin xu ly.
	 *
	 * @return the primary key of this qlvt thong tin xu ly
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt thong tin xu ly.
	 *
	 * @param primaryKey the primary key of this qlvt thong tin xu ly
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt thong tin xu ly.
	 *
	 * @return the ID of this qlvt thong tin xu ly
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt thong tin xu ly.
	 *
	 * @param id the ID of this qlvt thong tin xu ly
	 */
	public void setId(long id);

	/**
	 * Returns the ket qua xu ly of this qlvt thong tin xu ly.
	 *
	 * @return the ket qua xu ly of this qlvt thong tin xu ly
	 */
	@AutoEscape
	public String getKetQuaXuLy();

	/**
	 * Sets the ket qua xu ly of this qlvt thong tin xu ly.
	 *
	 * @param ketQuaXuLy the ket qua xu ly of this qlvt thong tin xu ly
	 */
	public void setKetQuaXuLy(String ketQuaXuLy);

	/**
	 * Returns the thong tin ho so ID of this qlvt thong tin xu ly.
	 *
	 * @return the thong tin ho so ID of this qlvt thong tin xu ly
	 */
	public long getThongTinHoSoId();

	/**
	 * Sets the thong tin ho so ID of this qlvt thong tin xu ly.
	 *
	 * @param thongTinHoSoId the thong tin ho so ID of this qlvt thong tin xu ly
	 */
	public void setThongTinHoSoId(long thongTinHoSoId);

	/**
	 * Returns the ma so ho so of this qlvt thong tin xu ly.
	 *
	 * @return the ma so ho so of this qlvt thong tin xu ly
	 */
	@AutoEscape
	public String getMaSoHoSo();

	/**
	 * Sets the ma so ho so of this qlvt thong tin xu ly.
	 *
	 * @param maSoHoSo the ma so ho so of this qlvt thong tin xu ly
	 */
	public void setMaSoHoSo(String maSoHoSo);

	/**
	 * Returns the can bo xu ly of this qlvt thong tin xu ly.
	 *
	 * @return the can bo xu ly of this qlvt thong tin xu ly
	 */
	public int getCanBoXuLy();

	/**
	 * Sets the can bo xu ly of this qlvt thong tin xu ly.
	 *
	 * @param canBoXuLy the can bo xu ly of this qlvt thong tin xu ly
	 */
	public void setCanBoXuLy(int canBoXuLy);

	/**
	 * Returns the thoi gian xu ly of this qlvt thong tin xu ly.
	 *
	 * @return the thoi gian xu ly of this qlvt thong tin xu ly
	 */
	public Date getThoiGianXuLy();

	/**
	 * Sets the thoi gian xu ly of this qlvt thong tin xu ly.
	 *
	 * @param thoiGianXuLy the thoi gian xu ly of this qlvt thong tin xu ly
	 */
	public void setThoiGianXuLy(Date thoiGianXuLy);

	/**
	 * Returns the y kien can bo xu ly of this qlvt thong tin xu ly.
	 *
	 * @return the y kien can bo xu ly of this qlvt thong tin xu ly
	 */
	@AutoEscape
	public String getYKienCanBoXuLy();

	/**
	 * Sets the y kien can bo xu ly of this qlvt thong tin xu ly.
	 *
	 * @param yKienCanBoXuLy the y kien can bo xu ly of this qlvt thong tin xu ly
	 */
	public void setYKienCanBoXuLy(String yKienCanBoXuLy);

	/**
	 * Returns the lanh dao duyet of this qlvt thong tin xu ly.
	 *
	 * @return the lanh dao duyet of this qlvt thong tin xu ly
	 */
	public int getLanhDaoDuyet();

	/**
	 * Sets the lanh dao duyet of this qlvt thong tin xu ly.
	 *
	 * @param lanhDaoDuyet the lanh dao duyet of this qlvt thong tin xu ly
	 */
	public void setLanhDaoDuyet(int lanhDaoDuyet);

	/**
	 * Returns the y kien lanh dao duyet of this qlvt thong tin xu ly.
	 *
	 * @return the y kien lanh dao duyet of this qlvt thong tin xu ly
	 */
	@AutoEscape
	public String getYKienLanhDaoDuyet();

	/**
	 * Sets the y kien lanh dao duyet of this qlvt thong tin xu ly.
	 *
	 * @param yKienLanhDaoDuyet the y kien lanh dao duyet of this qlvt thong tin xu ly
	 */
	public void setYKienLanhDaoDuyet(String yKienLanhDaoDuyet);

	/**
	 * Returns the thoi gian duyet of this qlvt thong tin xu ly.
	 *
	 * @return the thoi gian duyet of this qlvt thong tin xu ly
	 */
	public Date getThoiGianDuyet();

	/**
	 * Sets the thoi gian duyet of this qlvt thong tin xu ly.
	 *
	 * @param thoiGianDuyet the thoi gian duyet of this qlvt thong tin xu ly
	 */
	public void setThoiGianDuyet(Date thoiGianDuyet);

	/**
	 * Returns the ket qua duyet of this qlvt thong tin xu ly.
	 *
	 * @return the ket qua duyet of this qlvt thong tin xu ly
	 */
	public int getKetQuaDuyet();

	/**
	 * Sets the ket qua duyet of this qlvt thong tin xu ly.
	 *
	 * @param ketQuaDuyet the ket qua duyet of this qlvt thong tin xu ly
	 */
	public void setKetQuaDuyet(int ketQuaDuyet);

	/**
	 * Returns the lanh dao phe duyet of this qlvt thong tin xu ly.
	 *
	 * @return the lanh dao phe duyet of this qlvt thong tin xu ly
	 */
	public int getLanhDaoPheDuyet();

	/**
	 * Sets the lanh dao phe duyet of this qlvt thong tin xu ly.
	 *
	 * @param lanhDaoPheDuyet the lanh dao phe duyet of this qlvt thong tin xu ly
	 */
	public void setLanhDaoPheDuyet(int lanhDaoPheDuyet);

	/**
	 * Returns the thoi gian phe duyet of this qlvt thong tin xu ly.
	 *
	 * @return the thoi gian phe duyet of this qlvt thong tin xu ly
	 */
	public Date getThoiGianPheDuyet();

	/**
	 * Sets the thoi gian phe duyet of this qlvt thong tin xu ly.
	 *
	 * @param thoiGianPheDuyet the thoi gian phe duyet of this qlvt thong tin xu ly
	 */
	public void setThoiGianPheDuyet(Date thoiGianPheDuyet);

	/**
	 * Returns the ket qua phe duyet of this qlvt thong tin xu ly.
	 *
	 * @return the ket qua phe duyet of this qlvt thong tin xu ly
	 */
	public int getKetQuaPheDuyet();

	/**
	 * Sets the ket qua phe duyet of this qlvt thong tin xu ly.
	 *
	 * @param ketQuaPheDuyet the ket qua phe duyet of this qlvt thong tin xu ly
	 */
	public void setKetQuaPheDuyet(int ketQuaPheDuyet);

	/**
	 * Returns the y kien lanh dao phe duyet of this qlvt thong tin xu ly.
	 *
	 * @return the y kien lanh dao phe duyet of this qlvt thong tin xu ly
	 */
	@AutoEscape
	public String getYKienLanhDaoPheDuyet();

	/**
	 * Sets the y kien lanh dao phe duyet of this qlvt thong tin xu ly.
	 *
	 * @param yKienLanhDaoPheDuyet the y kien lanh dao phe duyet of this qlvt thong tin xu ly
	 */
	public void setYKienLanhDaoPheDuyet(String yKienLanhDaoPheDuyet);

	/**
	 * Returns the nguoi tra ket qua of this qlvt thong tin xu ly.
	 *
	 * @return the nguoi tra ket qua of this qlvt thong tin xu ly
	 */
	public int getNguoiTraKetQua();

	/**
	 * Sets the nguoi tra ket qua of this qlvt thong tin xu ly.
	 *
	 * @param nguoiTraKetQua the nguoi tra ket qua of this qlvt thong tin xu ly
	 */
	public void setNguoiTraKetQua(int nguoiTraKetQua);

	/**
	 * Returns the thoi gian tra ket qua of this qlvt thong tin xu ly.
	 *
	 * @return the thoi gian tra ket qua of this qlvt thong tin xu ly
	 */
	public Date getThoiGianTraKetQua();

	/**
	 * Sets the thoi gian tra ket qua of this qlvt thong tin xu ly.
	 *
	 * @param thoiGianTraKetQua the thoi gian tra ket qua of this qlvt thong tin xu ly
	 */
	public void setThoiGianTraKetQua(Date thoiGianTraKetQua);

	/**
	 * Returns the thoi gian cap phep of this qlvt thong tin xu ly.
	 *
	 * @return the thoi gian cap phep of this qlvt thong tin xu ly
	 */
	public Date getThoiGianCapPhep();

	/**
	 * Sets the thoi gian cap phep of this qlvt thong tin xu ly.
	 *
	 * @param thoiGianCapPhep the thoi gian cap phep of this qlvt thong tin xu ly
	 */
	public void setThoiGianCapPhep(Date thoiGianCapPhep);

	/**
	 * Returns the ket qua tham dinh x m l of this qlvt thong tin xu ly.
	 *
	 * @return the ket qua tham dinh x m l of this qlvt thong tin xu ly
	 */
	@AutoEscape
	public String getKetQuaThamDinhXML();

	/**
	 * Sets the ket qua tham dinh x m l of this qlvt thong tin xu ly.
	 *
	 * @param ketQuaThamDinhXML the ket qua tham dinh x m l of this qlvt thong tin xu ly
	 */
	public void setKetQuaThamDinhXML(String ketQuaThamDinhXML);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtThongTinXuLy qlvtThongTinXuLy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtThongTinXuLy> toCacheModel();

	@Override
	public QlvtThongTinXuLy toEscapedModel();

	@Override
	public QlvtThongTinXuLy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}