/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QlvtThongTinHoSoNoiDia service. Represents a row in the &quot;nghiepvu_thongtinhoso_qlvt_capphep_gpkdvt_bangoto_noidia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinHoSoNoiDiaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinHoSoNoiDiaImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtThongTinHoSoNoiDia
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinHoSoNoiDiaImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtThongTinHoSoNoiDiaModelImpl
 * @generated
 */
public interface QlvtThongTinHoSoNoiDiaModel extends BaseModel<QlvtThongTinHoSoNoiDia> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt thong tin ho so noi dia model instance should use the {@link QlvtThongTinHoSoNoiDia} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt thong tin ho so noi dia.
	 *
	 * @return the primary key of this qlvt thong tin ho so noi dia
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt thong tin ho so noi dia.
	 *
	 * @param primaryKey the primary key of this qlvt thong tin ho so noi dia
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt thong tin ho so noi dia.
	 *
	 * @return the ID of this qlvt thong tin ho so noi dia
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt thong tin ho so noi dia.
	 *
	 * @param id the ID of this qlvt thong tin ho so noi dia
	 */
	public void setId(long id);

	/**
	 * Returns the thongtin ho so ID of this qlvt thong tin ho so noi dia.
	 *
	 * @return the thongtin ho so ID of this qlvt thong tin ho so noi dia
	 */
	public long getThongtinHoSoId();

	/**
	 * Sets the thongtin ho so ID of this qlvt thong tin ho so noi dia.
	 *
	 * @param thongtinHoSoId the thongtin ho so ID of this qlvt thong tin ho so noi dia
	 */
	public void setThongtinHoSoId(long thongtinHoSoId);

	/**
	 * Returns the noi dia ID of this qlvt thong tin ho so noi dia.
	 *
	 * @return the noi dia ID of this qlvt thong tin ho so noi dia
	 */
	public long getNoiDiaId();

	/**
	 * Sets the noi dia ID of this qlvt thong tin ho so noi dia.
	 *
	 * @param noiDiaId the noi dia ID of this qlvt thong tin ho so noi dia
	 */
	public void setNoiDiaId(long noiDiaId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtThongTinHoSoNoiDia qlvtThongTinHoSoNoiDia);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtThongTinHoSoNoiDia> toCacheModel();

	@Override
	public QlvtThongTinHoSoNoiDia toEscapedModel();

	@Override
	public QlvtThongTinHoSoNoiDia toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}