/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.duongbo.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QlvtQuanLyFile service. Represents a row in the &quot;nghiepvu_quanlyfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtQuanLyFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtQuanLyFileImpl}.
 * </p>
 *
 * @author NhanNc
 * @see QlvtQuanLyFile
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtQuanLyFileImpl
 * @see vn.dtt.duongbo.dao.nghiepvu.model.impl.QlvtQuanLyFileModelImpl
 * @generated
 */
public interface QlvtQuanLyFileModel extends BaseModel<QlvtQuanLyFile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qlvt quan ly file model instance should use the {@link QlvtQuanLyFile} interface instead.
	 */

	/**
	 * Returns the primary key of this qlvt quan ly file.
	 *
	 * @return the primary key of this qlvt quan ly file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qlvt quan ly file.
	 *
	 * @param primaryKey the primary key of this qlvt quan ly file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qlvt quan ly file.
	 *
	 * @return the ID of this qlvt quan ly file
	 */
	public long getId();

	/**
	 * Sets the ID of this qlvt quan ly file.
	 *
	 * @param id the ID of this qlvt quan ly file
	 */
	public void setId(long id);

	/**
	 * Returns the ten file of this qlvt quan ly file.
	 *
	 * @return the ten file of this qlvt quan ly file
	 */
	@AutoEscape
	public String getTenFile();

	/**
	 * Sets the ten file of this qlvt quan ly file.
	 *
	 * @param tenFile the ten file of this qlvt quan ly file
	 */
	public void setTenFile(String tenFile);

	/**
	 * Returns the loai file of this qlvt quan ly file.
	 *
	 * @return the loai file of this qlvt quan ly file
	 */
	public long getLoaiFile();

	/**
	 * Sets the loai file of this qlvt quan ly file.
	 *
	 * @param loaiFile the loai file of this qlvt quan ly file
	 */
	public void setLoaiFile(long loaiFile);

	/**
	 * Returns the thong tin file of this qlvt quan ly file.
	 *
	 * @return the thong tin file of this qlvt quan ly file
	 */
	@AutoEscape
	public String getThongTinFile();

	/**
	 * Sets the thong tin file of this qlvt quan ly file.
	 *
	 * @param thongTinFile the thong tin file of this qlvt quan ly file
	 */
	public void setThongTinFile(String thongTinFile);

	/**
	 * Returns the ngay tai of this qlvt quan ly file.
	 *
	 * @return the ngay tai of this qlvt quan ly file
	 */
	public Date getNgayTai();

	/**
	 * Sets the ngay tai of this qlvt quan ly file.
	 *
	 * @param ngayTai the ngay tai of this qlvt quan ly file
	 */
	public void setNgayTai(Date ngayTai);

	/**
	 * Returns the ngay cap of this qlvt quan ly file.
	 *
	 * @return the ngay cap of this qlvt quan ly file
	 */
	public Date getNgayCap();

	/**
	 * Sets the ngay cap of this qlvt quan ly file.
	 *
	 * @param ngayCap the ngay cap of this qlvt quan ly file
	 */
	public void setNgayCap(Date ngayCap);

	/**
	 * Returns the ngay het han of this qlvt quan ly file.
	 *
	 * @return the ngay het han of this qlvt quan ly file
	 */
	public Date getNgayHetHan();

	/**
	 * Sets the ngay het han of this qlvt quan ly file.
	 *
	 * @param ngayHetHan the ngay het han of this qlvt quan ly file
	 */
	public void setNgayHetHan(Date ngayHetHan);

	/**
	 * Returns the id file of this qlvt quan ly file.
	 *
	 * @return the id file of this qlvt quan ly file
	 */
	public long getIdFile();

	/**
	 * Sets the id file of this qlvt quan ly file.
	 *
	 * @param idFile the id file of this qlvt quan ly file
	 */
	public void setIdFile(long idFile);

	/**
	 * Returns the trang thai of this qlvt quan ly file.
	 *
	 * @return the trang thai of this qlvt quan ly file
	 */
	@AutoEscape
	public String getTrangThai();

	/**
	 * Sets the trang thai of this qlvt quan ly file.
	 *
	 * @param trangThai the trang thai of this qlvt quan ly file
	 */
	public void setTrangThai(String trangThai);

	/**
	 * Returns the doanh nghiep ID of this qlvt quan ly file.
	 *
	 * @return the doanh nghiep ID of this qlvt quan ly file
	 */
	public long getDoanhNghiepId();

	/**
	 * Sets the doanh nghiep ID of this qlvt quan ly file.
	 *
	 * @param doanhNghiepId the doanh nghiep ID of this qlvt quan ly file
	 */
	public void setDoanhNghiepId(long doanhNghiepId);

	/**
	 * Returns the tai khoan of this qlvt quan ly file.
	 *
	 * @return the tai khoan of this qlvt quan ly file
	 */
	public long getTaiKhoan();

	/**
	 * Sets the tai khoan of this qlvt quan ly file.
	 *
	 * @param taiKhoan the tai khoan of this qlvt quan ly file
	 */
	public void setTaiKhoan(long taiKhoan);

	/**
	 * Returns the mieu ta of this qlvt quan ly file.
	 *
	 * @return the mieu ta of this qlvt quan ly file
	 */
	@AutoEscape
	public String getMieuTa();

	/**
	 * Sets the mieu ta of this qlvt quan ly file.
	 *
	 * @param mieuTa the mieu ta of this qlvt quan ly file
	 */
	public void setMieuTa(String mieuTa);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QlvtQuanLyFile qlvtQuanLyFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QlvtQuanLyFile> toCacheModel();

	@Override
	public QlvtQuanLyFile toEscapedModel();

	@Override
	public QlvtQuanLyFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}